<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';helper(['general','date_time','plugin','currency']);require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
$db=require dirname(__DIR__).'/Increment02/isolated_database.php';$settings=[];foreach($db->table('settings')->get()->getResult()as$s)$settings[$s->setting_name]=$s->setting_value;config('Rise')->app_settings_array=$settings+['timezone'=>'UTC'];session();
$pass=0;$fail=0;$assert=static function(bool$ok,string$msg)use(&$pass,&$fail){echo($ok?'[PASS] ':'[FAIL] ').$msg.PHP_EOL;$ok?$pass++:$fail++;};
$assert($db->tableExists('fiscal_series'),'fiscal_series exists in the isolated clone.');foreach(['trade_name','expedition_postal_code','email','phone']as$f)$assert($db->fieldExists($f,'fiscal_profiles'),"fiscal_profiles.$f exists.");
$regime=$db->table('sat_tax_regimes')->where('is_active',1)->get(1)->getRow();$company=$db->table('company')->where('deleted',0)->get(1)->getRow();$now=date('Y-m-d H:i:s');$profiles=new App\Models\Fiscal\Fiscal_profiles_model();
$base=['profile_type'=>'issuer','client_id'=>null,'company_id'=>$company->id??null,'rfc'=>'XAXX010101000','legal_name'=>'EMISOR AISLADO','tax_regime_id'=>$regime->id,'fiscal_postal_code'=>'06000','expedition_postal_code'=>'06000','fiscal_country_code'=>'MEX','status'=>'incomplete','is_default'=>0,'created_at'=>$now,'updated_at'=>$now];
$incomplete=$base;$incomplete['rfc']='';$incompleteId=(int)$profiles->ci_save($incomplete);$r=(new App\Services\Fiscal\IssuerFiscalReadinessService())->evaluate($incompleteId,$company?(int)$company->id:null);$assert(!$r['is_ready']&&in_array('rfc',$r['missing_fields'],true),'Incomplete issuer reports missing RFC.');
$first=$base+['fiscal_street'=>'Uno','fiscal_neighborhood'=>'Centro','fiscal_municipality'=>'Cuauhtémoc','fiscal_state'=>'CDMX'];$firstId=(int)$profiles->ci_save($first);$second=$base;$second['legal_name']='EMISOR DOS';$second['fiscal_street']='Dos';$secondId=(int)$profiles->ci_save($second);$r=(new App\Services\Fiscal\IssuerFiscalReadinessService())->evaluate($firstId,$company?(int)$company->id:null);$assert($r['is_ready']&&$r['status']==='ready','Issuer with fiscal minimums is ready.');$assert($profiles->get_one($firstId)->fiscal_street!==$profiles->get_one($secondId)->fiscal_street,'Two issuers keep independent addresses.');$profiles->setIssuerDefault($company?(int)$company->id:null,$firstId);$profiles->setIssuerDefault($company?(int)$company->id:null,$secondId);$assert($db->table('fiscal_profiles')->where(['profile_type'=>'issuer','company_id'=>$company->id??null,'is_default'=>1])->countAllResults()===1,'Only one issuer is default for the company.');$db->table('company')->where('id',$company->id)->update(['name'=>$company->name]);$assert($db->table('company')->where('id',$company->id)->get()->getRow()->name===$company->name,'Issuer operations do not modify commercial company data.');
$seriesModel=new App\Models\Fiscal\Fiscal_series_model();$seriesData=['issuer_profile_id'=>$firstId,'document_type'=>'ingreso','series'=>'A','initial_folio'=>10,'current_folio'=>9,'is_default'=>1,'is_active'=>1,'deleted'=>0,'created_at'=>$now,'updated_at'=>$now];$seriesId=(int)$seriesModel->ci_save($seriesData);$folio=new App\Services\Fiscal\FiscalFolioService($db);$before=(int)$seriesModel->get_one($seriesId)->current_folio;$p1=$folio->previewNextFolio($seriesId);$p2=$folio->previewNextFolio($seriesId);$assert($p1['folio']===10&&$p2['folio']===10&&(int)$seriesModel->get_one($seriesId)->current_folio===$before,'Repeated preview does not consume a folio.');$a=$folio->reserveNextFolio($seriesId);$b=$folio->reserveNextFolio($seriesId);$assert($a['folio']===10&&$b['folio']===11,'Sequential transactional reservations are unique.');$beforeRollback=(int)$seriesModel->get_one($seriesId)->current_folio;try{$folio->reserveNextFolio($seriesId,static function(){throw new RuntimeException('forced rollback');});}catch(RuntimeException$e){}$assert((int)$seriesModel->get_one($seriesId)->current_folio===$beforeRollback,'Reservation rollback restores current_folio.');
$otherType=$seriesData;$otherType['document_type']='egreso';$otherType['current_folio']=9;$egresoId=(int)$seriesModel->ci_save($otherType);$otherIssuer=$seriesData;$otherIssuer['issuer_profile_id']=$secondId;$otherIssuerId=(int)$seriesModel->ci_save($otherIssuer);$assert($egresoId>0&&$otherIssuerId>0,'Different types and issuers may reuse series A.');$inactiveData=['is_active'=>0];$seriesModel->ci_save($inactiveData,$egresoId);try{$folio->reserveNextFolio($egresoId);$inactiveBlocked=false;}catch(RuntimeException$e){$inactiveBlocked=true;}$assert($inactiveBlocked,'Inactive series cannot reserve.');
$role=$db->table('roles')->where('deleted',0)->get(1)->getRow();if($role){$p=@unserialize((string)$role->permissions)?:[];$assert(!array_key_exists('fiscal_issuers_view',$p)&&!array_key_exists('fiscal_series_view',$p)&&!array_key_exists('fiscal_sales_review',$p),'Existing role receives no Increment 04 permission automatically.');}
$documentCountBefore=$db->tableExists('fiscal_documents')?$db->table('fiscal_documents')->countAllResults():0;$invoice=$db->table('invoices')->where('deleted',0)->get(1)->getRow();if($invoice){$beforeFolio=(int)$seriesModel->get_one($seriesId)->current_folio;try{$review=(new App\Services\Fiscal\SaleFiscalReadinessService())->review((int)$invoice->id,$firstId,$seriesId,null);$assert(isset($review['issuer'],$review['receiver'],$review['series'],$review['items'],$review['sale']),'Sale review returns all readiness groups.');}catch(Throwable$e){$assert(false,'Sale review executes on an administrative invoice: '.$e->getMessage());}$assert((int)$seriesModel->get_one($seriesId)->current_folio===$beforeFolio,'Sale review does not consume a folio.');}
$assert(!$db->tableExists('fiscal_documents')||$db->table('fiscal_documents')->countAllResults()===$documentCountBefore,'Increment 04 review persists no fiscal document.');
echo "\n$pass passed, $fail failed.\n";exit($fail?1:0);
