<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
$root=dirname(__DIR__,2);$pass=0;$fail=0;$assert=static function(bool$ok,string$msg)use(&$pass,&$fail){echo($ok?'[PASS] ':'[FAIL] ').$msg.PHP_EOL;$ok?$pass++:$fail++;};
$migrations=glob($root.'/app/Database/Migrations/2026-07-24-*.php')?:[];$assert(count($migrations)===2,'Increment 04 defines two ordered migrations.');$migrationText=implode("\n",array_map('file_get_contents',$migrations));$assert(!preg_match("/'type'\s*=>\s*'(?:FLOAT|DOUBLE)'/i",$migrationText),'No new fiscal field uses FLOAT or DOUBLE.');$assert(!preg_match('/alterColumn\([\'\"](?:invoices|items|taxes)/',$migrationText),'Increment 04 does not alter invoices, items, or taxes.');
$folio=file_get_contents($root.'/app/Services/Fiscal/FiscalFolioService.php');$assert(str_contains($folio,'FOR UPDATE')&&!preg_match('/SELECT\s+MAX\s*\(/i',$folio),'Folio reservation uses a row lock and never SQL MAX + 1.');$assert(str_contains($folio,'previewNextFolio')&&str_contains($folio,'reserveNextFolio'),'Preview and reservation are separate operations.');
$review=file_get_contents($root.'/app/Services/Fiscal/SaleFiscalReadinessService.php');$assert(str_contains($review,'IssuerFiscalReadinessService')&&str_contains($review,'FiscalReadinessService')&&str_contains($review,'ItemFiscalReadinessService'),'Sale review composes issuer, receiver, and item readiness.');$assert(str_contains($review,'previewNextFolio')&&!str_contains($review,'reserveNextFolio'),'Sale review previews but never consumes a folio.');$assert(!preg_match('/fiscal_documents|PacClient|stampDocument|createXml/i',$review),'Sale review creates no document and has no PAC/XML/stamping integration.');
$roles=file_get_contents($root.'/app/Controllers/Roles.php');foreach(['fiscal_issuers_view','fiscal_issuers_manage','fiscal_series_view','fiscal_series_manage','fiscal_sales_review']as$p)$assert(str_contains($roles,$p),"Role persistence supports $p.");
$routes=file_get_contents($root.'/app/Config/FiscalRoutes.php');foreach(['fiscal/issuers','fiscal/series','fiscal/invoices/review']as$r)$assert(str_contains($routes,$r),"Explicit fiscal route exists: $r.");
$invoiceAction=file_get_contents($root.'/app/Views/invoices/invoice_actions.php');$assert(str_contains($invoiceAction,'fiscal_sales_review')&&!str_contains($invoiceAction,'>Timbrar<'),'Invoice action requires review permission and exposes no stamp button.');
$assert(!str_contains($migrationText,'fiscal_documents')&&!file_exists($root.'/app/Database/Migrations/2026-07-24-040200_CreateFiscalDocuments.php'),'Increment 04 itself introduced no fiscal_documents persistence.');
echo "\n$pass passed, $fail failed.\n";exit($fail?1:0);
