<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
use App\Services\Fiscal\FiscalOnboardingReadinessService;
use App\Services\Fiscal\FiscalPreviewModeGuard;
use App\Services\Baseline\IkontrolBaselineCheckService;
use App\Services\Upgrade\Legacy\SmartfreePrefiscalBridgeService;
use Config\Database;
$database=$argv[1]??null;if(!$database)throw new RuntimeException('Provide the isolated local bridge database.');
$base=config('Database')->default;$cfg=is_array($base)?$base:get_object_vars($base);$db=Database::connect(array_replace($cfg,['database'=>$database,'DBPrefix'=>'sf_']),false);
$f=(new ReflectionClass(Config\Fiscal::class))->newInstanceWithoutConstructor();$f->enabled=true;$f->stampingEnabled=false;$f->allowRealPac=false;$f->runtimeMode='integration';$f->environment='development';$f->pacAdapter='timbradorxpress';
$p=(new ReflectionClass(Config\TimbradorXpress::class))->newInstanceWithoutConstructor();$p->environment='sandbox';$p->apiKey='';$p->baseUrl=Config\TimbradorXpress::SANDBOX_URL;$p->productionEnabled=false;
$checks=0;$ok=static function(bool$c,string$m)use(&$checks){if(!$c)throw new RuntimeException('[FAIL] '.$m);$checks++;echo'[PASS] '.$m.PHP_EOL;};
$status=(new FiscalOnboardingReadinessService($db,$f,$p))->inspect();
$ok($status['state']==='ONBOARDING'&&!$status['ready'],'fiscal onboarding is visible but incomplete');
$routes=file_get_contents(APPPATH.'Config/FiscalRoutes.php');$menu=file_get_contents(APPPATH.'Views/settings/tabs.php');$controller=file_get_contents(APPPATH.'Controllers/Fiscal/Onboarding.php');$ok(str_contains($routes,"get('fiscal/onboarding'")&&str_contains($menu,'fiscal_pac_status_view')&&str_contains($controller,'fiscal_pac_status_view'),'onboarding route, menu and controller share the existing diagnostic permission');
$ok($status['details']['stamping']['status']==='BLOCKED','stamping remains blocked');
$blocked=false;try{(new FiscalOnboardingReadinessService($db,$f,$p))->assertReadyForStamping();}catch(RuntimeException $e){$blocked=str_starts_with($e->getMessage(),'FISCAL_ONBOARDING_INCOMPLETE:');}$ok($blocked,'readiness guard rejects stamping before any PAC operation');
$cancellationBlocked=false;try{(new FiscalPreviewModeGuard($db))->assertCancellationAllowed();}catch(RuntimeException){$cancellationBlocked=true;}$ok($cancellationBlocked,'real cancellation remains blocked during onboarding');
$ok($status['details']['pac']['status']==='MISSING','PAC remains unconfigured and no transport is invoked');
$ok($status['details']['catalogs']['product-service']['status']==='EMPTY','missing verified SAT catalog is reported');
$ok($status['details']['products']['total']>0&&$status['details']['clients']['total']>0&&(int)$db->table('items')->countAllResults()===273&&(int)$db->table('clients')->countAllResults()===315,'legacy products and clients remain visible and total rows are preserved');
$ok((int)$db->table('invoices')->countAllResults()===1301&&(int)$db->table('invoice_payments')->countAllResults()===1418,'legacy sales and payments remain unchanged');
$ok((int)$db->table('payment_methods')->where(['deleted'=>0,'available_on_invoice'=>1])->countAllResults()===4,'four used legacy methods are available for SAT mapping');
$ok((int)$db->table('fiscal_payment_method_mappings')->countAllResults()===0,'SAT payment mappings are not invented');
$bridge=(new SmartfreePrefiscalBridgeService($database,'ikontrol20_clean'))->dryRun();$ok(!empty($bridge['already_completed']),'bridge remains idempotent');
$baseline=(new IkontrolBaselineCheckService($db))->run();$ok(($baseline['summary']['fail']??-1)===1&&($baseline['summary']['warn']??-1)===1,'baseline has only the expected empty SAT failure and bridge migration-history warning');
$fiscalStructure=array_values(array_filter($baseline['checks'],static fn(array $check):bool=>($check['key']??'')==='fiscal_structure'));$ok(($fiscalStructure[0]['status']??'')==='PASS','fiscal canonical structure is installed for onboarding');
$source=file_get_contents(APPPATH.'Services/Fiscal/FiscalOnboardingReadinessService.php');$ok(str_contains($source,"\$blockers === [] ? 'READY' : 'ONBOARDING'"),'onboarding can become READY after configuration without reinstalling');
echo "passed={$checks}\n";
