<?php
declare(strict_types=1);
ob_start();$root=dirname(__DIR__,2);require $root.'/tests/bootstrap.php';helper(['general','date_time','currency','form']);$db=require $root.'/tests/Increment02/isolated_database.php';
use App\Services\SupplierComparisonService;
$p=$f=0;$ok=function(bool$v,string$m)use(&$p,&$f){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$p++:$f++;};
$baseSupplier=$db->table('suppliers')->get(1)->getRowArray();$supplierIds=[];foreach([['Comparador A','active'],['Comparador B','active'],['Comparador C','inactive']]as$i=>$definition){$row=$baseSupplier;unset($row['id']);$row['name']=$definition[0].' 20260829';$row['normalized_name']='COMPARADOR'.chr(65+$i).'20260829';$row['rfc']=null;$row['status']=$definition[1];$row['deleted']=0;$db->table('suppliers')->insert($row);$supplierIds[]=(int)$db->insertID();}
$product=$db->table('items')->where('deleted',0)->get(1)->getRowArray();unset($product['id']);$product['title']='Producto comparación DOLD';$product['deleted']=0;$db->table('items')->insert($product);$productId=(int)$db->insertID();$proposal=$db->table('proposals')->where('deleted',0)->get(1)->getRow();$proposalItem=$db->table('proposal_items')->where('deleted',0)->get(1)->getRow();
$data=[[$supplierIds[0],'780.000000','1100.000000','2026-08-01 10:00:00'],[$supplierIds[0],'820.000000','1250.000000','2026-08-15 10:00:00'],[$supplierIds[1],'810.000000','1180.000000','2026-08-02 10:00:00'],[$supplierIds[1],'790.000000','1170.000000','2026-08-10 10:00:00'],[$supplierIds[2],'835.000000','1220.000000','2026-08-05 10:00:00']];foreach($data as$i=>$x){$db->table('product_supplier_cost_history')->insert(['product_id'=>$productId,'supplier_id'=>$x[0],'proposal_id'=>$proposal->id,'proposal_item_id'=>$proposalItem->id,'client_id'=>$proposal->client_id,'unit_cost'=>$x[1],'sale_unit_price'=>$x[2],'quantity'=>'1.000000','currency'=>'MXN','quoted_at'=>$x[3],'recorded_by'=>null,'created_at'=>$x[3],'source_status'=>'sent','snapshot_version'=>$i+1,'economic_hash'=>hash('sha256','compare-'.$i)]);}
$service=new SupplierComparisonService($db);$comparison=$service->compare($productId);$ok(count($comparison['suppliers'])===3,'producto con tres proveedores devuelve tres filas');$byId=[];foreach($comparison['suppliers']as$row)$byId[$row['supplier_id']]=$row;$a=$byId[$supplierIds[0]];$b=$byId[$supplierIds[1]];$c=$byId[$supplierIds[2]];$ok($a['last_cost']==='820.000000'&&$a['last_date']==='2026-08-15 10:00:00','último costo usa quoted_at DESC');$ok($a['best_cost']==='780.000000','mejor costo usa MIN histórico');$ok($a['quote_count']===2&&$b['quote_count']===2&&$c['quote_count']===1,'veces cotizado cuenta snapshots idempotentes');$ok($a['last_sale_unit_price']==='1250.000000','último precio de venta corresponde al snapshot más reciente');$ok(!$c['active'],'proveedor inactivo permanece como referencia no seleccionable');$ok($comparison['indicators']['last_supplier_id']===$supplierIds[0]&&$comparison['indicators']['best_cost']==='780.000000'&&$comparison['indicators']['supplier_count']===3,'indicadores generales son correctos');
$variation=$service->variation('820.000000','845.000000');$ok($variation['difference']==='25.000000'&&str_starts_with((string)$variation['percent'],'3.048780'),'variación usa decimal exacto sin float');$before=$db->table('product_supplier_cost_history')->where('product_id',$productId)->countAllResults();$service->compare($productId);$ok($db->table('product_supplier_cost_history')->where('product_id',$productId)->countAllResults()===$before,'comparar no crea snapshots ni modifica historia');$empty=$service->compare($productId+999999);$ok($empty['suppliers']===[]&&$empty['indicators']['supplier_count']===0,'producto sin historia devuelve estado vacío');
$modal=file_get_contents($root.'/app/Views/proposals/item_modal_form.php');$view=file_get_contents($root.'/app/Views/proposals/supplier_comparison.php');$controller=file_get_contents($root.'/app/Controllers/Proposals.php');$public=file_get_contents($root.'/app/Views/proposals/proposal_parts/proposal_items_table.php');$ok(str_contains($modal,'Comparar proveedores')&&str_contains($modal,'function selectSupplierInParent(data)'),'seleccionar proveedor actualiza Select2');$ok(str_contains($modal,'use-last-supplier-cost')&&str_contains($modal,"$('#proposal_item_cost').val(cost)"),'último costo se copia sólo por acción explícita');$ok(str_contains($modal,'BigInt')&&!str_contains($modal,'parseFloat'),'variación del comparador no usa float');$ok(str_contains($view,'Reactivar para seleccionar')&&str_contains($view,'Ver historial'),'modal distingue inactivos y expone detalle');$ok(str_contains($controller,'supplier_costs_view')&&str_contains($controller,'supplier_costs_edit'),'endpoints reutilizan permisos de costos');$ok(!str_contains($public,'supplier-comparison')&&!str_contains($public,'best_cost'),'comparación no se expone a propuesta pública');
echo"TOTAL PASS=$p FAIL=$f".PHP_EOL;$out=ob_get_clean();echo$out;exit($f?1:0);
