<?php
namespace App\Services;
use RuntimeException;
final class FinancialAccountMovementService
{
    public function __construct(private $db) {}
    public function sync(string $type, int $referenceId, ?int $accountId, string $direction, $amount, string $date, ?int $actor, ?string $description = null): void
    {
        if(!$accountId)throw new RuntimeException('La cuenta financiera es obligatoria.');if(!in_array($direction,['in','out'],true))throw new RuntimeException('La dirección financiera no es válida.');$amount=FinancialMoney::positive($amount);
        $account=$this->db->table('financial_accounts')->where(['id'=>$accountId,'deleted'=>0,'is_active'=>1,'currency'=>'MXN'])->get(1)->getRow();if(!$account)throw new RuntimeException('La cuenta financiera MXN no existe o está inactiva.');
        $existing=$this->db->table('financial_account_movements')->where(['reference_type'=>$type,'reference_id'=>$referenceId,'movement_role'=>'original'])->get(1)->getRow();$data=['financial_account_id'=>$accountId,'direction'=>$direction,'amount'=>$amount,'movement_date'=>$date,'reference_type'=>$type,'reference_id'=>$referenceId,'movement_role'=>'original','description'=>$description,'is_active'=>1,'updated_at'=>get_current_utc_time()];
        if($existing){if((int)$existing->reversed_movement_id)throw new RuntimeException('Un movimiento reversado no puede modificarse.');$this->db->table('financial_account_movements')->where('id',$existing->id)->update($data);}else{$data['created_by']=$actor;$data['created_at']=get_current_utc_time();if(!$this->db->table('financial_account_movements')->insert($data))throw new RuntimeException('No fue posible crear el movimiento financiero.');}
    }
    public function reverseSource(string$type,int$referenceId,int$actor,string$reason):array{$rows=$this->db->table('financial_account_movements')->where(['reference_type'=>$type,'reference_id'=>$referenceId,'movement_role'=>'original','is_active'=>1])->get()->getResult();if(!$rows)throw new RuntimeException('No existe movimiento original para reversar.');$ids=[];foreach($rows as$row)$ids[]=$this->reverse((int)$row->id,$actor,$reason);return$ids;}
    public function reverse(int$id,int$actor,string$reason):int{$reason=trim($reason);if($reason==='')throw new RuntimeException('El motivo de reversa es obligatorio.');$o=$this->db->query('SELECT * FROM '.$this->db->prefixTable('financial_account_movements').' WHERE id=? FOR UPDATE',[$id])->getRow();if(!$o||$o->movement_role!=='original'||!(int)$o->is_active)throw new RuntimeException('El movimiento original no está disponible.');if((int)$o->reversed_movement_id)return(int)$o->reversed_movement_id;$data=['financial_account_id'=>(int)$o->financial_account_id,'direction'=>$o->direction==='in'?'out':'in','amount'=>(string)$o->amount,'movement_date'=>gmdate('Y-m-d'),'reference_type'=>'movement_reversal','reference_id'=>$id,'movement_role'=>'reversal','reversal_of_movement_id'=>$id,'reversal_reason'=>$reason,'description'=>'Reversa: '.$reason,'is_active'=>1,'created_by'=>$actor,'created_at'=>get_current_utc_time(),'updated_at'=>get_current_utc_time()];if(!$this->db->table('financial_account_movements')->insert($data))throw new RuntimeException('No fue posible crear la reversa.');$rid=(int)$this->db->insertID();$this->db->table('financial_account_movements')->where('id',$id)->update(['reversed_movement_id'=>$rid,'updated_at'=>get_current_utc_time()]);return$rid;}
    /** @deprecated */ public function deactivate(string$type,int$id):void{throw new RuntimeException('Los movimientos financieros deben reversarse.');}
}
