<?php
declare(strict_types=1);
namespace App\Services;
use App\Services\Fiscal\FiscalDecimal;
use App\Services\Fiscal\FiscalIssueDatePolicy;
final class PaymentComplementReadinessService
{
 public function __construct(private$db){}
 public function check(int$id):array{$checks=[];$blockers=[];$warnings=[];$add=function(string$section,string$label,bool$ok,string$detail,string$resolution='',bool$warning=false)use(&$checks,&$blockers,&$warnings){$severity=$ok?'correct':($warning?'warning':'error');$row=['section'=>$section,'label'=>$label,'severity'=>$severity,'detail'=>$detail,'resolution'=>$resolution];$checks[]=$row;if(!$ok){if($warning)$warnings[]=$detail;else$blockers[]=$detail;}};$c=$this->db->table('payment_complements c')->select('c.*,cl.company_name,cl.vat_number')->join('clients cl','cl.id=c.client_id','left')->where(['c.id'=>$id,'c.deleted'=>0])->get(1)->getRow();$add('general','Cliente / receptor',(bool)($c&&$c->client_id&&!empty($c->company_name)),$c?'Cliente: '.($c->company_name?:'#'.$c->client_id):'Borrador inexistente.','Seleccione un cliente válido.');$add('general','RFC receptor',(bool)($c&&trim((string)$c->vat_number)!==''),$c&&$c->vat_number?'RFC: '.$c->vat_number:'El cliente no tiene RFC.','Complete el RFC en la ficha fiscal del cliente.',true);$validDate=false;if($c)try{(new FiscalIssueDatePolicy())->validate((string)$c->issue_date);$validDate=true;}catch(\Throwable$e){$dateError=$e->getMessage();}$add('general','Fecha del complemento',$validDate,$validDate?'Fecha fiscal dentro de la ventana permitida.':($dateError??'Fecha fiscal inválida.'),'Ajuste la Fecha del complemento en el generador.');
  $p=$this->db->table('payment_complement_payments p')->select('p.*,ip.status source_status,ip.deleted source_deleted,ip.payment_method_id,fm.sat_payment_form_code mapped_payment_form,sf.name payment_form_name')->join('invoice_payments ip','ip.id=p.source_invoice_payment_id','left')->join('fiscal_payment_method_mappings fm','fm.payment_method_id=ip.payment_method_id AND fm.is_active=1','left')->join('sat_payment_forms sf','sf.code=fm.sat_payment_form_code AND sf.is_active=1','left')->where(['p.payment_complement_id'=>$id,'p.deleted'=>0])->get(1)->getRow();$form=$p?($p->payment_form_code?:$p->mapped_payment_form):null;$catalog=$form?$this->db->table('sat_payment_forms')->where(['code'=>$form,'is_active'=>1])->get(1)->getRow():null;$add('general','Pago administrativo',(bool)($p&&$p->source_invoice_payment_id&&$p->source_status==='active'&&!(int)$p->source_deleted),$p?'Pago #'.$p->source_invoice_payment_id:'No existe pago origen.','Seleccione un pago administrativo activo.');$add('general','FormaDePagoP',(bool)$catalog,$catalog?$form.' '.$catalog->name:($form?'La Forma de pago SAT guardada no está activa o no existe.':'No se ha seleccionado Forma de pago SAT.'),'Seleccione una clave activa del catálogo SAT en el generador.');
  $banking=in_array((string)$form,['02','03','04','05','06','28','29'],true);if($banking){$hasBeneficiary=trim((string)($p->beneficiary_bank_rfc??''))!==''||trim((string)($p->beneficiary_account??''))!=='';$hasOrdering=trim((string)($p->ordering_bank_rfc??''))!==''||trim((string)($p->ordering_account??''))!==''||trim((string)($p->ordering_bank_name??''))!=='';$add('banking','Información bancaria',true,($hasBeneficiary||$hasOrdering)?'Datos bancarios opcionales informados; se incluirán cuando sean válidos.':'Opcional / No informada. No aplica como requisito bloqueante para esta operación.');}else$add('banking','Información bancaria',true,'No aplica para la FormaDePagoP seleccionada.');$chain=(string)($p->payment_chain_type??'');$chainOk=$chain===''||(trim((string)$p->payment_certificate)!==''&&trim((string)$p->payment_chain)!==''&&trim((string)$p->payment_signature)!=='');$add('banking','Cadena de pago',$chainOk,$chainOk?($chain?'Cadena de pago completa.':'No aplica.'):'TipoCadPago requiere CertPago, CadPago y SelloPago.','Complete los cuatro datos de cadena de pago o elimine TipoCadPago.');
  $docs=$p?$this->db->table('payment_complement_documents d')->select('d.*,fd.status source_status,fd.payment_method_code,fd.deleted source_deleted,fd.cancelled_at,s.uuid current_uuid')->join('fiscal_documents fd','fd.id=d.fiscal_document_id','left')->join('fiscal_document_stamps s','s.fiscal_document_id=fd.id','left')->where(['d.payment_complement_payment_id'=>$p->id,'d.deleted'=>0])->get()->getResult():[];$add('documents','Documentos relacionados',(bool)$docs,$docs?count($docs).' CFDI relacionado(s).':'No hay facturas agregadas.','Agregue al menos una factura PPD.');$total='0.000000';$resolver=new FiscalDocumentHistoricalTaxResolver($this->db);foreach($docs as$d){$valid=$d->source_status==='stamped'&&$d->payment_method_code==='PPD'&&!(int)$d->source_deleted&&!$d->cancelled_at&&trim((string)$d->current_uuid)!==''&&$d->current_uuid===$d->document_uuid;$add('documents','CFDI '.$d->document_uuid,$valid,$valid?'Timbrado, vigente y MetodoPago PPD.':'El CFDI ya no está timbrado, vigente o PPD.','Revise el CFDI de origen.');$numbers=FiscalDecimal::micros((string)$d->installment_number)>0&&FiscalDecimal::micros((string)$d->previous_balance)>0&&FiscalDecimal::micros((string)$d->amount_paid)>0&&FiscalDecimal::micros((string)$d->remaining_balance)>=0&&FiscalDecimal::subtract((string)$d->previous_balance,(string)$d->amount_paid)===$this->decimal($d->remaining_balance);$add('documents','Parcialidad '.$d->installment_number,$numbers,$numbers?'ImpSaldoAnt, ImpPagado e ImpSaldoInsoluto son consistentes.':'Parcialidad o saldos inconsistentes.','Retire y vuelva a agregar la factura para recalcular.');try{$h=$resolver->resolve((int)$d->fiscal_document_id);$tax=$resolver->prorate($h,(string)$d->amount_paid,(string)$d->previous_balance);$add('taxes','ObjetoImpDR '.$d->document_uuid,in_array($h['tax_object_code'],['01','02'],true),'ObjetoImpDR '.$h['tax_object_code'].' derivado del CFDI histórico.','Revise los conceptos fiscales originales.');$add('taxes','Impuestos DR '.$d->document_uuid,$h['tax_object_code']==='01'||(bool)$tax,$h['tax_object_code']==='01'?'El documento no es objeto de impuesto.':count($tax).' grupo(s) de impuestos prorrateados.','Reconcilie los impuestos históricos del CFDI.');}catch(\Throwable$e){$add('taxes','Impuestos históricos '.$d->document_uuid,false,$e->getMessage(),'Reconcilie fiscal_document_items y fiscal_document_item_taxes del CFDI original.');}$total=FiscalDecimal::add($total,(string)$d->amount_paid);}if($p)$add('totals','MontoTotalPagos',$this->decimal($p->amount)===$total,'Monto incluido: '.$total,'Revise los documentos relacionados.');return['ready'=>!$blockers,'status'=>!$blockers?'complete_draft':'draft','checks'=>$checks,'blockers'=>$blockers,'warnings'=>$warnings,'total'=>$total];}
 private function decimal($v):string{return FiscalDecimal::format(FiscalDecimal::micros((string)$v));}
}
