<?php
declare(strict_types=1);
namespace App\Services;
use App\Models\Suppliers_model;use CodeIgniter\Database\BaseConnection;use InvalidArgumentException;use RuntimeException;
final class SupplierService{
 private BaseConnection$db;private Suppliers_model$model;
 public function __construct(?BaseConnection$db=null){$this->db=$db??db_connect();$this->model=new Suppliers_model($this->db);}
 public function save(array$input,int$actorId):array{$id=(int)($input['id']??0);$name=trim((string)($input['name']??''));if($name==='')throw new InvalidArgumentException('Capture el nombre comercial del proveedor.');$normalized=self::normalizeName($name);$rfc=self::normalizeRfc((string)($input['rfc']??''));if($rfc!==null&&!preg_match('/^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$/u',$rfc))throw new InvalidArgumentException('El RFC del proveedor no tiene un formato válido.');
  if($rfc!==null){$same=$this->db->table('suppliers')->where(['rfc'=>$rfc,'deleted'=>0])->where('id !=',$id)->get(1)->getRow();if($same)return$this->duplicate('rfc','Ya existe un proveedor con este RFC.',$same);}
  $similar=$this->db->table('suppliers')->where(['normalized_name'=>$normalized,'deleted'=>0])->where('id !=',$id)->get(1)->getRow();if($similar&&empty($input['allow_similar_name']))return$this->duplicate('name_warning','Ya existe un proveedor con un nombre equivalente.',$similar,true);
  $now=get_current_utc_time();$data=['name'=>$name,'normalized_name'=>$normalized,'rfc'=>$rfc,'contact_name'=>self::optional($input['contact_name']??null),'phone'=>self::optional($input['phone']??null),'email'=>self::optional($input['email']??null),'notes'=>self::optional($input['notes']??null),'status'=>($input['status']??'')==='inactive'?'inactive':'active','updated_at'=>$now];if(!$id)$data+=['created_by'=>$actorId,'created_at'=>$now,'deleted'=>0];
  $this->db->transBegin();try{if($id>0){$ok=$this->db->table('suppliers')->where(['id'=>$id,'deleted'=>0])->update($data);$saved=$ok?$id:0;}else{$ok=$this->db->table('suppliers')->insert($data);$saved=$ok?(int)$this->db->insertID():0;}if($saved<1||!$this->db->transStatus())throw new RuntimeException('No fue posible guardar el proveedor.');$this->db->transCommit();$row=$this->model->get_one($saved);return['success'=>true,'id'=>$saved,'text'=>$row->name,'supplier_id'=>$saved,'supplier_name'=>$row->name,'supplier_rfc'=>(string)($row->rfc??''),'message'=>'Proveedor guardado correctamente.'];}catch(\Throwable$e){$this->db->transRollback();if($rfc!==null&&$this->db->table('suppliers')->where(['rfc'=>$rfc,'deleted'=>0])->countAllResults()){$row=$this->db->table('suppliers')->where(['rfc'=>$rfc,'deleted'=>0])->get(1)->getRow();return$this->duplicate('rfc','Ya existe un proveedor con este RFC.',$row);}throw$e;}}
 public static function normalizeName(string$name):string{$ascii=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',trim($name));return preg_replace('/[^A-Z0-9]+/','',strtoupper($ascii===false?$name:$ascii))??'';}
 public static function normalizeRfc(string$rfc):?string{$value=strtoupper(preg_replace('/\s+/','',trim($rfc))??'');return$value===''?null:$value;}
 private function duplicate(string$type,string$message,object$row,bool$allow=false):array{return['success'=>false,'duplicate_supplier'=>true,'duplicate_type'=>$type,'allow_create'=>$allow,'message'=>$message,'existing'=>['id'=>(int)$row->id,'name'=>(string)$row->name,'rfc'=>(string)($row->rfc??''),'phone'=>(string)($row->phone??''),'email'=>(string)($row->email??'')]];}
 private static function optional(mixed$value):?string{$value=trim((string)$value);return$value===''?null:$value;}
}
