<?php
declare(strict_types=1);
namespace App\Services;
use App\Services\Fiscal\FiscalDecimal;use CodeIgniter\Database\BaseConnection;use RuntimeException;
final class SupplierCostHistoryService
{
 public function __construct(private ?BaseConnection$db=null){$this->db??=db_connect();}
 public function snapshotProposal(int$id,string$status,int$user):int{return$this->snapshotDocument('proposal',$id,$status,$user);}
 public function snapshotEstimate(int$id,string$status,int$user):int{return$this->snapshotDocument('estimate',$id,$status,$user);}
 public function snapshotInvoice(int$id,string$status,int$user):int{return$this->snapshotDocument('invoice',$id,$status,$user);}
 public function snapshotDocument(string$type,int$id,string$status,int$user):int{
  $map=['proposal'=>['proposals','proposal_items','proposal_id',['sent','accepted','declined'],'public_key'],'estimate'=>['estimates','estimate_items','estimate_id',['sent','accepted','declined'],'id'],'invoice'=>['invoices','invoice_items','invoice_id',['not_paid','partially_paid','paid','open','closed'],'id']];if(!isset($map[$type])||!in_array($status,$map[$type][3],true))return 0;[$parentTable,$itemTable,$fk,,$folioField]=$map[$type];$parent=$this->db->table($parentTable)->where(['id'=>$id,'deleted'=>0])->get(1)->getRow();if(!$parent)throw new RuntimeException('El documento comercial no existe.');$rows=$this->db->table($itemTable)->where([$fk=>$id,'deleted'=>0])->where('item_id >',0)->where('supplier_id IS NOT NULL',null,false)->where('cost IS NOT NULL',null,false)->where('cost >',0)->get()->getResult();$count=0;$now=get_current_utc_time();foreach($rows as$r){if(!$this->db->table('suppliers')->where(['id'=>$r->supplier_id,'deleted'=>0])->countAllResults())continue;$economic=hash('sha256',implode('|',[(int)$r->item_id,(int)$r->supplier_id,self::d($r->cost),self::d($r->rate),self::d($r->quantity),'MXN']));if($this->db->table('product_supplier_cost_history')->where(['source_type'=>$type,'source_item_id'=>$r->id,'economic_hash'=>$economic])->countAllResults())continue;$version=(int)($this->db->table('product_supplier_cost_history')->selectMax('snapshot_version','v')->where(['source_type'=>$type,'source_item_id'=>$r->id])->get()->getRow()->v??0)+1;$row=['source_type'=>$type,'source_id'=>$id,'source_item_id'=>(int)$r->id,'source_folio'=>(string)($parent->$folioField??$id),'proposal_id'=>$type==='proposal'?$id:null,'proposal_item_id'=>$type==='proposal'?(int)$r->id:null,'product_id'=>(int)$r->item_id,'supplier_id'=>(int)$r->supplier_id,'client_id'=>(int)$parent->client_id,'unit_cost'=>self::d($r->cost),'sale_unit_price'=>self::d($r->rate),'quantity'=>self::d($r->quantity),'currency'=>'MXN','quoted_at'=>$now,'recorded_by'=>$user?:null,'created_at'=>$now,'source_status'=>$status,'snapshot_version'=>$version,'economic_hash'=>$economic];$this->db->table('product_supplier_cost_history')->insert($row);$count++;}return$count;
 }
 public function productSummary(int$id):array{return$this->db->query('SELECT h.supplier_id,s.name supplier_name,COUNT(*) quote_count,MIN(h.unit_cost) best_cost,MAX(h.quoted_at) last_date,SUBSTRING_INDEX(GROUP_CONCAT(h.unit_cost ORDER BY h.quoted_at DESC,h.id DESC),\',\',1) last_cost FROM '.$this->db->prefixTable('product_supplier_cost_history').' h JOIN '.$this->db->prefixTable('suppliers').' s ON s.id=h.supplier_id WHERE h.product_id=? GROUP BY h.supplier_id,s.name ORDER BY last_date DESC',[$id])->getResult();}
 public function productIndicators(int$id):array{$row=$this->db->query('SELECT COUNT(DISTINCT supplier_id) supplier_count,MIN(unit_cost) best_cost,MAX(quoted_at) last_date FROM '.$this->db->prefixTable('product_supplier_cost_history').' WHERE product_id=?',[$id])->getRow();$last=$this->db->table('product_supplier_cost_history h')->select('h.unit_cost,h.quoted_at,s.name supplier_name')->join('suppliers s','s.id=h.supplier_id')->where('h.product_id',$id)->orderBy('h.quoted_at','DESC')->orderBy('h.id','DESC')->get(1)->getRow();return['supplier_count'=>(int)($row->supplier_count??0),'best_cost'=>$row->best_cost??null,'last_cost'=>$last->unit_cost??null,'last_supplier'=>$last->supplier_name??null,'last_date'=>$last->quoted_at??null];}
 public function productHistory(int$id):array{return$this->historyBuilder()->where('h.product_id',$id)->orderBy('h.quoted_at','DESC')->orderBy('h.id','DESC')->get()->getResult();}
 public function supplierProducts(int$id):array{return$this->db->query('SELECT h.product_id,i.title,COUNT(*) quote_count,MAX(h.quoted_at) last_date,SUBSTRING_INDEX(GROUP_CONCAT(h.unit_cost ORDER BY h.quoted_at DESC,h.id DESC),\',\',1) last_cost FROM '.$this->db->prefixTable('product_supplier_cost_history').' h JOIN '.$this->db->prefixTable('items').' i ON i.id=h.product_id WHERE h.supplier_id=? GROUP BY h.product_id,i.title ORDER BY last_date DESC',[$id])->getResult();}
 public function supplierHistory(int$id):array{return$this->historyBuilder()->where('h.supplier_id',$id)->orderBy('h.quoted_at','DESC')->orderBy('h.id','DESC')->get()->getResult();}
 private function historyBuilder(){return$this->db->table('product_supplier_cost_history h')->select("h.*,i.title product_name,s.name supplier_name,c.company_name,COALESCE(h.source_folio,p.public_key,CONCAT('#',h.source_id)) document_folio",false)->join('items i','i.id=h.product_id')->join('suppliers s','s.id=h.supplier_id')->join('clients c','c.id=h.client_id')->join('proposals p',"p.id=h.proposal_id AND h.source_type='proposal'",'left');}
 private static function d(mixed$v):string{return FiscalDecimal::format(FiscalDecimal::micros((string)$v));}
}
