<?php
declare(strict_types=1);
namespace App\Services;
use CodeIgniter\Database\BaseConnection;
final class WarehouseStockService {
 public function __construct(private ?BaseConnection $db=null){$this->db??=db_connect('default');}
 private function t(string $n,string $a=''):string{return $this->db->prefixTable($n).($a?' '.$a:'');}
 public function getStock(int $p,int $w):string{$r=$this->db->table($this->t('warehouse_movement_lines','l'))->select('COALESCE(SUM(l.quantity_delta),0) stock',false)->join($this->t('warehouse_movements','m'),'m.id=l.warehouse_movement_id')->where(['l.warehouse_product_id'=>$p,'m.warehouse_id'=>$w,'m.status'=>'confirmed'])->get()->getRow();return bcadd((string)($r->stock??'0'),'0',6);}
 public function getProductStocks(int $p):array{return $this->db->table($this->t('warehouses','w'))->select('w.id warehouse_id,w.name,w.code,COALESCE(SUM(CASE WHEN m.status="confirmed" THEN l.quantity_delta ELSE 0 END),0) stock',false)->join($this->t('warehouse_movements','m'),'m.warehouse_id=w.id','left')->join($this->t('warehouse_movement_lines','l'),'l.warehouse_movement_id=m.id AND l.warehouse_product_id='.$p,'left',false)->where('w.deleted',0)->groupBy('w.id')->orderBy('w.name')->get()->getResultArray();}
 public function getWarehouseStocks(int $w):array{return $this->db->table($this->t('warehouse_products','p'))->select('p.id product_id,p.name,p.internal_code,p.barcode,p.category,COALESCE(SUM(CASE WHEN m.status="confirmed" THEN l.quantity_delta ELSE 0 END),0) stock',false)->join($this->t('warehouse_movement_lines','l'),'l.warehouse_product_id=p.id','left')->join($this->t('warehouse_movements','m'),'m.id=l.warehouse_movement_id AND m.warehouse_id='.$w,'left',false)->where('p.deleted',0)->groupBy('p.id')->having('stock !=',0)->orderBy('p.name')->get()->getResultArray();}
 public function getTotalControlled(int $p):string{$r=$this->db->table($this->t('warehouse_movement_lines','l'))->select('COALESCE(SUM(l.quantity_delta),0) stock',false)->join($this->t('warehouse_movements','m'),'m.id=l.warehouse_movement_id')->where(['l.warehouse_product_id'=>$p,'m.status'=>'confirmed'])->get()->getRow();return bcadd((string)($r->stock??'0'),'0',6);}
 public function totalAll():string{$r=$this->db->table($this->t('warehouse_movement_lines','l'))->select('COALESCE(SUM(l.quantity_delta),0) stock',false)->join($this->t('warehouse_movements','m'),'m.id=l.warehouse_movement_id')->where('m.status','confirmed')->get()->getRow();return bcadd((string)($r->stock??'0'),'0',6);}
 public function kardex(int $p,?int $w=null):array{$b=$this->db->table($this->t('warehouse_movement_lines','l'))->select('l.quantity_delta,l.quantity,m.id,m.folio,m.movement_type,m.movement_date,m.reference_type,m.reference_id,m.reference_text,m.warehouse_id,w.name warehouse_name,u.first_name,u.last_name')->join($this->t('warehouse_movements','m'),'m.id=l.warehouse_movement_id')->join($this->t('warehouses','w'),'w.id=m.warehouse_id')->join($this->t('users','u'),'u.id=m.confirmed_by','left')->where(['l.warehouse_product_id'=>$p,'m.status'=>'confirmed']);if($w)$b->where('m.warehouse_id',$w);$rows=$b->orderBy('m.movement_date','ASC')->orderBy('m.id','ASC')->orderBy('l.id','ASC')->get()->getResultArray();$balance='0.000000';foreach($rows as &$r){$balance=bcadd($balance,(string)$r['quantity_delta'],6);$r['balance']=$balance;}unset($r);return $rows;}
}
