<?php
namespace App\Controllers\Fiscal;
use App\Controllers\Security_Controller;
use App\Models\Company_model;
use App\Models\Fiscal\Fiscal_profiles_model;
use App\Models\Fiscal\Sat_tax_regimes_model;
use App\Services\Fiscal\IssuerFiscalReadinessService;
class Issuers extends Security_Controller{
 private Fiscal_profiles_model$profiles;
 public function __construct(){parent::__construct();$this->profiles=new Fiscal_profiles_model();}
 private function allowed(bool$manage=false):bool{if($this->login_user->is_admin)return true;$p=$this->login_user->permissions;if(!is_array($p))$p=@unserialize((string)$p)?:[];return(bool)get_array_value($p,$manage?'fiscal_issuers_manage':'fiscal_issuers_view');}
 private function guard(bool$manage=false):void{if(!$this->allowed($manage))app_redirect('forbidden');}
 public function index(){$this->guard();return$this->template->rander('fiscal/issuers/index',['can_manage'=>$this->allowed(true)]);}
 public function list_data():void{$this->guard();$rows=[];foreach($this->profiles->issuers()->getResult()as$p){$r=(new IssuerFiscalReadinessService())->evaluate((int)$p->id);$actions=anchor(get_uri('fiscal/issuers/'.$p->id.'/certificates'),'<i data-feather="key" class="icon-16"></i>',['title'=>app_lang('digital_seal_certificates')]);if($this->allowed(true))$actions.=modal_anchor(get_uri('fiscal/issuers/form'),'<i data-feather="edit" class="icon-16"></i>',['data-post-id'=>$p->id,'title'=>app_lang('edit')]);$rows[]=[$p->legal_name?:'-',$p->rfc?:'-',$p->expedition_postal_code?:'-',$p->is_default?app_lang('yes'):app_lang('no'),app_lang('issuer_status_'.$r['status']),$actions];}echo json_encode(['data'=>$rows]);}
 public function form(){$this->guard(true);$id=(int)$this->request->getPost('id');$companies=[''=>'-'];foreach((new Company_model())->get_all_where(['deleted'=>0])->getResult()as$c)$companies[$c->id]=$c->name;return$this->template->view('fiscal/issuers/modal_form',['model_info'=>$this->profiles->get_one($id),'companies'=>$companies,'regimes'=>[''=>'-']+(new Sat_tax_regimes_model())->getActiveDropdown(['code','description'])]);}
 public function save():void{$this->guard(true);$id=(int)$this->request->getPost('id');$country=strtoupper(trim((string)$this->request->getPost('fiscal_country_code')));if($country!==''&&!preg_match('/^[A-Z]{3}$/',$country)){echo json_encode(['success'=>false,'message'=>app_lang('fiscal_country_code_invalid')]);return;}$mode=(string)$this->request->getPost('tax_pricing_mode');if(!in_array($mode,['tax_inclusive','tax_exclusive','preserve_total'],true))$mode='tax_inclusive';$company=$this->request->getPost('company_id')?:null;$data=['profile_type'=>'issuer','client_id'=>null,'company_id'=>$company,'rfc'=>strtoupper(trim((string)$this->request->getPost('rfc'))),'legal_name'=>trim((string)$this->request->getPost('legal_name')),'trade_name'=>$this->nullable('trade_name'),'tax_regime_id'=>$this->request->getPost('tax_regime_id')?:null,'fiscal_postal_code'=>trim((string)$this->request->getPost('fiscal_postal_code')),'expedition_postal_code'=>trim((string)$this->request->getPost('expedition_postal_code')),'fiscal_country_code'=>$country?:null,'fiscal_street'=>$this->nullable('fiscal_street'),'fiscal_external_number'=>$this->nullable('fiscal_external_number'),'fiscal_internal_number'=>$this->nullable('fiscal_internal_number'),'fiscal_neighborhood'=>$this->nullable('fiscal_neighborhood'),'fiscal_locality'=>$this->nullable('fiscal_locality'),'fiscal_municipality'=>$this->nullable('fiscal_municipality'),'fiscal_state'=>$this->nullable('fiscal_state'),'fiscal_address_reference'=>$this->nullable('fiscal_address_reference'),'email'=>$this->nullable('email'),'phone'=>$this->nullable('phone'),'tax_pricing_mode'=>$mode,'allow_sale_tax_pricing_override'=>$this->request->getPost('allow_sale_tax_pricing_override')?1:0,'is_default'=>$this->request->getPost('is_default')?1:0,'status'=>'incomplete','updated_at'=>get_current_utc_time()];if($id){$old=$this->profiles->get_one($id);if(!$old->id||$old->profile_type!=='issuer'){echo json_encode(['success'=>false,'message'=>app_lang('error_occurred')]);return;}}else{$data['created_by']=$this->login_user->id;$data['created_at']=get_current_utc_time();}$saved=$this->profiles->ci_save($data,$id);$profileId=$id?:($saved?(int)$saved:0);if($profileId){$ready=(new IssuerFiscalReadinessService())->evaluate($profileId,$company?(int)$company:null);$statusData=['status'=>$ready['is_ready']?'ready':'incomplete'];$this->profiles->ci_save($statusData,$profileId);if($data['is_default']&&$ready['is_ready'])$this->profiles->setIssuerDefault($company?(int)$company:null,$profileId);}echo json_encode(['success'=>(bool)$profileId,'id'=>$profileId,'message'=>$profileId?app_lang('record_saved'):app_lang('error_occurred')]);}
 public function set_default():void{$this->guard(true);$p=$this->profiles->get_one((int)$this->request->getPost('id'));$ok=$p->id&&$p->profile_type==='issuer'&&$p->status==='ready'?$this->profiles->setIssuerDefault($p->company_id?(int)$p->company_id:null,(int)$p->id):false;echo json_encode(['success'=>$ok]);}
 public function deactivate():void{$this->guard(true);$p=$this->profiles->get_one((int)$this->request->getPost('id'));$data=['status'=>'inactive','is_default'=>0,'updated_at'=>get_current_utc_time()];echo json_encode(['success'=>(bool)($p->id&&$p->profile_type==='issuer'?$this->profiles->ci_save($data,(int)$p->id):false)]);}
 private function nullable(string$n):?string{$v=trim((string)$this->request->getPost($n));return$v===''?null:$v;}
}
