<?php
declare(strict_types=1);

foreach (['fiscal.enabled'=>'false','fiscal.stampingEnabled'=>'false','fiscal.allowRealPac'=>'false','fiscal.runtimeMode'=>'automated_test','fiscal.pacAdapter'=>'fake'] as $key=>$value) {
    putenv($key.'='.$value); $_ENV[$key]=$_SERVER[$key]=$value;
}
require dirname(__DIR__).'/bootstrap.php';
if (!function_exists('get_current_utc_time')) { function get_current_utc_time():string{return gmdate('Y-m-d H:i:s');} }

use App\Contracts\Fiscal\Pdf\PacPdfGenerationAdapterInterface;
use App\Domain\Fiscal\Cfdi40\{CfdiConcept,CfdiConceptTax,CfdiDocument,CfdiParty,CfdiTaxSummary};
use App\Domain\Fiscal\Pdf\{PacPdfGenerationRequest,PacPdfGenerationResult};
use App\FiscalServices\PaymentComplementPrintDataBuilder;
use App\Services\Fiscal\Cfdi40\CfdiXmlBuilder;
use App\Services\Fiscal\CreditNoteService;
use App\Services\Fiscal\FiscalFolioService;
use App\Services\Fiscal\Pac\FakePacPdfFixture;
use App\Services\Fiscal\Pdf\{FiscalIssuerBrandingService,FiscalPacPdfGenerationService,FiscalPdfPrintMetadataBuilder};
use App\Services\PaymentComplementCfdiMaterializer;
use Config\Database;
use Config\FiscalPdfProvider;

final class P12CapturingPdfAdapter implements PacPdfGenerationAdapterInterface
{
    public int $calls=0; public array $requests=[];
    public function generate(PacPdfGenerationRequest $request):PacPdfGenerationResult
    {
        $this->calls++; $this->requests[]=$request;
        return new PacPdfGenerationResult(true,'fake','210','PDF fixture.',base64_encode(FakePacPdfFixture::bytes()),'application/pdf',$request->templateCode,true,false,'success');
    }
}

$server=null;$db=null;$owned=null;$root=null;$passed=0;$failed=0;
$assert=static function(bool$ok,string$label)use(&$passed,&$failed):void{echo($ok?'[PASS] ':'[FAIL] ').$label.PHP_EOL;$ok?$passed++:$failed++;};
$reject=static function(callable$action,string$label)use($assert):void{try{$action();$assert(false,$label);}catch(Throwable){$assert(true,$label);}};
$stampXml=static function(string$xml,string$uuid):string{$dom=new DOMDocument();if(!$dom->loadXML($xml,LIBXML_NONET|LIBXML_NOBLANKS))throw new RuntimeException('Invalid fixture XML');$root=$dom->documentElement;$complement=null;foreach($root->childNodes as$child)if($child instanceof DOMElement&&$child->localName==='Complemento'){$complement=$child;break;}if(!$complement){$complement=$dom->createElementNS('http://www.sat.gob.mx/cfd/4','cfdi:Complemento');$root->appendChild($complement);}$tfd=$dom->createElementNS('http://www.sat.gob.mx/TimbreFiscalDigital','tfd:TimbreFiscalDigital');foreach(['Version'=>'1.1','UUID'=>$uuid,'FechaTimbrado'=>'2026-09-30T12:01:00','RfcProvCertif'=>'AAA010101AAA','SelloCFD'=>'SELLOCFD','NoCertificadoSAT'=>'00001000000500000000','SelloSAT'=>'SELLOSAT']as$k=>$v)$tfd->setAttribute($k,$v);$complement->appendChild($tfd);return(string)$dom->saveXML();};
$removeTree=static function(string$path):void{if(!is_dir($path))return;foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST)as$item){$item->isDir()?rmdir($item->getPathname()):unlink($item->getPathname());}rmdir($path);};

try{
    $local=config(Database::class)->default;if(!in_array($local['hostname'],['localhost','127.0.0.1','::1'],true))throw new RuntimeException('P12 requires local MySQL fixtures.');
    mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$server=new mysqli($local['hostname'],$local['username'],$local['password'],'',(int)$local['port']);$owned='ikontrol_test_p12_'.bin2hex(random_bytes(6));$server->query('CREATE DATABASE `'.$owned.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci');
    $db=Database::connect(array_replace($local,['DSN'=>'','database'=>$owned,'DBDriver'=>'MySQLi','DBPrefix'=>'p12_','pConnect'=>false,'DBDebug'=>true,'failover'=>[]]),false);$forge=Database::forge($db);$root=WRITEPATH.'tests/p12_'.bin2hex(random_bytes(6));mkdir($root,0700,true);
    $assert($db->query('SELECT DATABASE() n')->getRow()->n===$owned,'1. Owned isolated MySQL schema verified.');
    $make=static function(string$table,array$fields,array$unique=[])use($forge):void{$forge->addField($fields);$forge->addKey('id',true);foreach($unique as$cols=>$name)$forge->addUniqueKey(explode(',',$cols),$name);$forge->createTable($table);};
    $id=['type'=>'INT','unsigned'=>true,'auto_increment'=>true];$int=['type'=>'INT','unsigned'=>true];$nint=['type'=>'INT','unsigned'=>true,'null'=>true];$dt=['type'=>'DATETIME','null'=>true];$money=['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0.000000'];
    $make('fiscal_series',['id'=>$id,'issuer_profile_id'=>$int,'document_type'=>['type'=>'VARCHAR','constraint'=>20],'series'=>['type'=>'VARCHAR','constraint'=>25,'default'=>''],'initial_folio'=>$int,'current_folio'=>$int,'is_default'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'is_active'=>['type'=>'TINYINT','constraint'=>1,'default'=>1],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'updated_at'=>$dt]);
    $make('invoices',['id'=>$id,'client_id'=>$int]);
    $make('fiscal_documents',['id'=>$id,'invoice_id'=>$nint,'issuer_profile_id'=>$int,'document_type'=>['type'=>'VARCHAR','constraint'=>20],'status'=>['type'=>'VARCHAR','constraint'=>40],'series'=>['type'=>'VARCHAR','constraint'=>25],'folio'=>['type'=>'VARCHAR','constraint'=>40],'expedition_postal_code'=>['type'=>'VARCHAR','constraint'=>12,'default'=>'06000'],'currency_code'=>['type'=>'CHAR','constraint'=>3,'default'=>'MXN'],'exchange_rate'=>['type'=>'DECIMAL','constraint'=>'18,6','null'=>true],'payment_form_code'=>['type'=>'CHAR','constraint'=>3,'default'=>'01'],'payment_method_code'=>['type'=>'CHAR','constraint'=>3,'default'=>'PUE'],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'updated_at'=>$dt]);
    $make('fiscal_document_issuers',['id'=>$id,'fiscal_document_id'=>$int,'rfc'=>['type'=>'VARCHAR','constraint'=>13],'legal_name'=>['type'=>'VARCHAR','constraint'=>255],'tax_regime_code'=>['type'=>'VARCHAR','constraint'=>3]]);
    $make('fiscal_document_receivers',['id'=>$id,'fiscal_document_id'=>$int,'rfc'=>['type'=>'VARCHAR','constraint'=>13],'legal_name'=>['type'=>'VARCHAR','constraint'=>255],'tax_regime_code'=>['type'=>'VARCHAR','constraint'=>3],'fiscal_postal_code'=>['type'=>'VARCHAR','constraint'=>12],'cfdi_use_code'=>['type'=>'VARCHAR','constraint'=>3]]);
    $make('fiscal_document_stamps',['id'=>$id,'fiscal_document_id'=>$int,'stamp_attempt_id'=>$int,'uuid'=>['type'=>'CHAR','constraint'=>36],'stamped_xml_artifact_id'=>$nint,'pac_pdf_artifact_id'=>$nint,'pdf_status'=>['type'=>'VARCHAR','constraint'=>30,'default'=>'pending'],'pdf_template'=>['type'=>'VARCHAR','constraint'=>40,'null'=>true],'provider'=>['type'=>'VARCHAR','constraint'=>30,'default'=>'fake']]);
    $make('fiscal_document_artifacts',['id'=>$id,'fiscal_document_id'=>$int,'artifact_type'=>['type'=>'VARCHAR','constraint'=>40],'storage_path'=>['type'=>'VARCHAR','constraint'=>255],'sha256'=>['type'=>'CHAR','constraint'=>64],'superseded_at'=>$dt]);
    $make('fiscal_issuer_pdf_templates',['id'=>$id,'issuer_id'=>$int,'provider'=>['type'=>'VARCHAR','constraint'=>30],'document_type'=>['type'=>'CHAR','constraint'=>1],'template_code'=>['type'=>'VARCHAR','constraint'=>40],'is_active'=>['type'=>'TINYINT','constraint'=>1,'default'=>1]]);
    $make('fiscal_pdf_generation_attempts',['id'=>$id,'document_id'=>$int,'stamp_id'=>$int,'stamp_attempt_id'=>$int,'uuid'=>['type'=>'CHAR','constraint'=>36],'provider'=>['type'=>'VARCHAR','constraint'=>30],'environment'=>['type'=>'VARCHAR','constraint'=>30],'template_code'=>['type'=>'VARCHAR','constraint'=>40],'status'=>['type'=>'VARCHAR','constraint'=>40],'request_sent'=>['type'=>'TINYINT','constraint'=>1,'null'=>true],'retryable'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'requires_reconciliation'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'idempotency_key'=>['type'=>'CHAR','constraint'=>64],'provider_code'=>['type'=>'VARCHAR','constraint'=>30,'null'=>true],'provider_message'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'started_at'=>$dt,'completed_at'=>$dt,'created_by'=>$nint,'created_at'=>$dt,'updated_at'=>$dt],['idempotency_key'=>'uq_pdf_key']);
    $make('fiscal_document_binary_artifacts',['id'=>$id,'fiscal_document_id'=>$int,'stamp_attempt_id'=>$int,'artifact_type'=>['type'=>'VARCHAR','constraint'=>40],'content_encoding'=>['type'=>'VARCHAR','constraint'=>20],'content_base64'=>['type'=>'LONGTEXT'],'decoded_mime_type'=>['type'=>'VARCHAR','constraint'=>80],'decoded_size_bytes'=>$int,'decoded_sha256'=>['type'=>'CHAR','constraint'=>64],'provider'=>['type'=>'VARCHAR','constraint'=>30],'template'=>['type'=>'VARCHAR','constraint'=>40,'null'=>true],'template_code'=>['type'=>'VARCHAR','constraint'=>40,'null'=>true],'uuid'=>['type'=>'CHAR','constraint'=>36],'validation_status'=>['type'=>'VARCHAR','constraint'=>30],'pdf_generation_attempt_id'=>$nint,'artifact_status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'active'],'superseded_at'=>$dt,'created_by'=>$nint,'created_at'=>$dt]);
    $make('fiscal_document_audit',['id'=>$id,'fiscal_document_id'=>$int,'invoice_id'=>$nint,'user_id'=>$nint,'action'=>['type'=>'VARCHAR','constraint'=>50],'reason'=>['type'=>'TEXT','null'=>true],'created_at'=>$dt]);
    $make('fiscal_credit_notes',['id'=>$id,'source_fiscal_document_id'=>$int,'source_invoice_id'=>$int,'fiscal_document_id'=>$nint,'issuer_profile_id'=>$int,'receiver_profile_id'=>$int,'issue_date'=>$dt,'relation_type_code'=>['type'=>'CHAR','constraint'=>2],'currency_code'=>['type'=>'CHAR','constraint'=>3],'payment_form_code'=>['type'=>'CHAR','constraint'=>3],'payment_method_code'=>['type'=>'CHAR','constraint'=>3],'cfdi_use_code'=>['type'=>'CHAR','constraint'=>3],'status'=>['type'=>'VARCHAR','constraint'=>20],'subtotal'=>$money,'discount'=>$money,'transferred_tax_total'=>$money,'withheld_tax_total'=>$money,'total'=>$money,'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);
    $make('fiscal_document_items',['id'=>$id,'fiscal_document_id'=>$int,'invoice_item_id'=>$nint,'item_id'=>$nint,'line_number'=>$int,'product_service_code'=>['type'=>'VARCHAR','constraint'=>10],'identification_number'=>['type'=>'VARCHAR','constraint'=>50,'null'=>true],'quantity'=>$money,'unit_code'=>['type'=>'VARCHAR','constraint'=>10],'unit_name'=>['type'=>'VARCHAR','constraint'=>50],'description'=>['type'=>'VARCHAR','constraint'=>255],'unit_value'=>$money,'gross_amount'=>$money,'discount'=>$money,'tax_object_code'=>['type'=>'CHAR','constraint'=>2]]);
    $make('fiscal_document_item_taxes',['id'=>$id,'fiscal_document_item_id'=>$int,'administrative_tax_id'=>$nint,'tax_code'=>['type'=>'CHAR','constraint'=>3],'tax_type'=>['type'=>'VARCHAR','constraint'=>20],'factor_type'=>['type'=>'VARCHAR','constraint'=>10],'rate_or_quota'=>['type'=>'DECIMAL','constraint'=>'18,6','null'=>true],'taxable_base'=>$money,'amount'=>$money,'sort_order'=>$int]);
    $make('fiscal_credit_note_items',['id'=>$id,'fiscal_credit_note_id'=>$int,'source_fiscal_document_item_id'=>$int,'quantity'=>$money,'unit_value'=>$money,'subtotal'=>$money,'discount'=>$money,'transferred_tax_total'=>$money,'withheld_tax_total'=>$money,'total'=>$money,'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);

    foreach([['ingreso','FI',10],['pago','FP',20],['egreso','NE',30]]as$i=>$series)$db->table('fiscal_series')->insert(['id'=>$i+1,'issuer_profile_id'=>1,'document_type'=>$series[0],'series'=>$series[1],'initial_folio'=>$series[2],'current_folio'=>$series[2]-1,'is_default'=>1,'is_active'=>1,'deleted'=>0]);
    $folios=new FiscalFolioService($db);$preview=$folios->previewNextFolio(1);$assert($preview['series']==='FI'&&$preview['folio']===10,'2. Income series previews its next persisted folio without consuming it.');
    $a=$folios->reserveNextFolio(1);$b=$folios->reserveNextFolio(1);$assert($a['folio']===10&&$b['folio']===11,'3. Sequential reservations are unique.');
    $before=(int)$db->table('fiscal_series')->where('id',1)->get()->getRow()->current_folio;try{$folios->reserveNextFolio(1,static fn()=>throw new RuntimeException('rollback'));}catch(RuntimeException){}$assert((int)$db->table('fiscal_series')->where('id',1)->get()->getRow()->current_folio===$before,'4. Failed reservation rolls back current_folio.');
    $assert($folios->previewNextFolio(2)['series']==='FP'&&$folios->previewNextFolio(3)['series']==='NE','5. Income payment and expense retain independent series.');

    $issuer=['rfc'=>'AAA010101AAA','legal_name'=>'Compañía Ñandú','tax_regime_code'=>'601','expedition_postal_code'=>'06000'];$receiver=['rfc'=>'XAXX010101000','legal_name'=>'Cliente Único','tax_regime_code'=>'616','fiscal_postal_code'=>'06000','cfdi_use_code'=>'S01'];
    $income=(new CfdiXmlBuilder())->build(new CfdiDocument(['series'=>'FI','folio'=>'10','issue_date'=>'2026-09-30 12:00:00','payment_form_code'=>'01','subtotal'=>'100','discount'=>'0','currency_code'=>'MXN','total'=>'116','export_code'=>'01','payment_method_code'=>'PUE','expedition_postal_code'=>'06000','withheld_tax_total'=>'0','transferred_tax_total'=>'16'],new CfdiParty($issuer),new CfdiParty($receiver),[new CfdiConcept(['product_service_code'=>'01010101','quantity'=>'1','unit_code'=>'H87','unit_name'=>'Pieza','description'=>'Servicio Ñ','unit_value'=>'100','gross_amount'=>'100','discount'=>'0','tax_object_code'=>'02'],[new CfdiConceptTax('002','transferred','Tasa','0.160000','100','16')])],[new CfdiTaxSummary('002','transferred','Tasa','0.160000','100','16')]));
    $assert(str_contains($income,'Serie="FI"')&&str_contains($income,'Folio="10"')&&str_contains($income,'Compañía Ñandú'),'6. Income XML uses frozen identity and UTF-8 snapshot data.');

    $basePayment=['series'=>'FP','folio'=>20,'issue_date'=>'2026-09-30T12:00:00','issuer'=>$issuer,'receiver'=>$receiver,'sat_totals'=>['MontoTotalPagos'=>'100.00'],'totals'=>['MontoTotalPagos'=>'100.000000','TrasladosP'=>[],'RetencionesP'=>[]],'payments'=>[['FechaPago'=>'2026-09-30T11:00:00','FormaDePagoP'=>'03','MonedaP'=>'MXN','TipoCambioP'=>'1','Monto'=>'100','DoctoRelacionado'=>[]]]];
    $internal=['source_type'=>'internal','source_id'=>1,'invoice_id'=>1,'fiscal_document_id'=>100,'IdDocumento'=>'11111111-1111-4111-8111-111111111111','Serie'=>'A','Folio'=>'1','MonedaDR'=>'MXN','EquivalenciaDR'=>'1','MetodoDePagoDR'=>'PPD','ObjetoImpDR'=>'02','NumParcialidad'=>1,'ImpSaldoAnt'=>'116','ImpPagado'=>'100','ImpSaldoInsoluto'=>'16','ImpuestosDR'=>['TrasladosDR'=>[['BaseDR'=>'86.21','ImpuestoDR'=>'002','TipoFactorDR'=>'Tasa','TasaOCuotaDR'=>'0.160000','ImporteDR'=>'13.79']],'RetencionesDR'=>[]]];
    $external=array_replace($internal,['source_type'=>'external','source_id'=>2,'invoice_id'=>null,'fiscal_document_id'=>null,'IdDocumento'=>'22222222-2222-4222-8222-222222222222','Serie'=>'EXT','Folio'=>'2']);
    $paymentXml=[];foreach(['internal'=>[$internal],'external'=>[$external],'mixed'=>[$internal,$external]]as$kind=>$documents){$payload=$basePayment;$payload['folio']=['internal'=>20,'external'=>21,'mixed'=>22][$kind];$payload['payments'][0]['DoctoRelacionado']=$documents;$paymentXml[$kind]=(new PaymentComplementCfdiMaterializer())->materialize($payload);}
    $assert(str_contains($paymentXml['internal'],'Serie="FP"')&&str_contains($paymentXml['internal'],'Folio="20"'),'7. Payment XML materializes the fiscal document series and folio.');
    $prints=[];foreach($paymentXml as$kind=>$xml)$prints[$kind]=(new PaymentComplementPrintDataBuilder())->build($xml);
    $assert(count($prints['internal']['payments'][0]['documents'])===1&&$prints['internal']['document']['folio']==='20','8. Internal payment PDF data comes from persisted XML.');
    $assert(count($prints['external']['payments'][0]['documents'])===1&&$prints['external']['payments'][0]['documents'][0]['attributes']['Serie']==='EXT','9. External payment PDF data comes from persisted XML.');
    $assert(count($prints['mixed']['payments'][0]['documents'])===2,'10. Mixed payment PDF data preserves both normalized origins.');

    $db->table('invoices')->insert(['id'=>100,'client_id'=>1]);$db->table('fiscal_documents')->insert(['id'=>100,'invoice_id'=>100,'issuer_profile_id'=>1,'document_type'=>'income','status'=>'stamped','series'=>'SRC','folio'=>'9','expedition_postal_code'=>'06000','currency_code'=>'MXN','payment_form_code'=>'01','payment_method_code'=>'PUE','deleted'=>0]);
    $db->table('fiscal_document_stamps')->insert(['id'=>100,'fiscal_document_id'=>100,'stamp_attempt_id'=>100,'uuid'=>'99999999-9999-4999-8999-999999999999','provider'=>'fake']);
    $db->table('fiscal_document_issuers')->insert(['fiscal_document_id'=>100,'rfc'=>$issuer['rfc'],'legal_name'=>$issuer['legal_name'],'tax_regime_code'=>'601']);$db->table('fiscal_document_receivers')->insert(['fiscal_document_id'=>100,'rfc'=>$receiver['rfc'],'legal_name'=>$receiver['legal_name'],'tax_regime_code'=>'616','fiscal_postal_code'=>'06000','cfdi_use_code'=>'S01']);
    $db->table('fiscal_document_items')->insert(['id'=>100,'fiscal_document_id'=>100,'invoice_item_id'=>1,'item_id'=>1,'line_number'=>1,'product_service_code'=>'01010101','quantity'=>'1','unit_code'=>'H87','unit_name'=>'Pieza','description'=>'Devolución Ñ','unit_value'=>'100','gross_amount'=>'100','discount'=>'0','tax_object_code'=>'02']);
    $db->table('fiscal_document_item_taxes')->insert(['fiscal_document_item_id'=>100,'administrative_tax_id'=>null,'tax_code'=>'002','tax_type'=>'transferred','factor_type'=>'Tasa','rate_or_quota'=>'0.160000','taxable_base'=>'100','amount'=>'16','sort_order'=>1]);
    $db->table('fiscal_credit_notes')->insert(['id'=>1,'source_fiscal_document_id'=>100,'source_invoice_id'=>100,'fiscal_document_id'=>null,'issuer_profile_id'=>1,'receiver_profile_id'=>1,'issue_date'=>'2026-09-30 12:00:00','relation_type_code'=>'01','currency_code'=>'MXN','payment_form_code'=>'01','payment_method_code'=>'PUE','cfdi_use_code'=>'G02','status'=>'draft','subtotal'=>'100','discount'=>'0','transferred_tax_total'=>'16','withheld_tax_total'=>'0','total'=>'116','deleted'=>0]);
    $db->table('fiscal_credit_note_items')->insert(['fiscal_credit_note_id'=>1,'source_fiscal_document_item_id'=>100,'quantity'=>'1','unit_value'=>'100','subtotal'=>'100','discount'=>'0','transferred_tax_total'=>'16','withheld_tax_total'=>'0','total'=>'116','deleted'=>0]);
    $expense=(new CreditNoteService($db))->buildXml(1,'NE',30);$assert(str_contains($expense,'TipoDeComprobante="E"')&&str_contains($expense,'Serie="NE"')&&str_contains($expense,'Folio="30"'),'11. Expense XML uses its independent frozen series and folio.');
    $assert(str_contains($expense,'UUID="99999999-9999-4999-8999-999999999999"')&&str_contains($expense,'TasaOCuota="0.160000"'),'12. Expense XML preserves related UUID and persisted taxes.');

    $uuids=['aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2','cccccccc-cccc-4ccc-8ccc-ccccccccccc3','dddddddd-dddd-4ddd-8ddd-ddddddddddd4','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee5'];$xmls=[$stampXml($income,$uuids[0]),$stampXml($expense,$uuids[1]),$stampXml($paymentXml['internal'],$uuids[2]),$stampXml($paymentXml['external'],$uuids[3]),$stampXml($paymentXml['mixed'],$uuids[4])];$identities=[['income','FI','10'],['expense','NE','30'],['payment','FP','20'],['payment','FP','21'],['payment','FP','22']];
    foreach(['I','E','P']as$type)$db->table('fiscal_issuer_pdf_templates')->insert(['issuer_id'=>1,'provider'=>'fake','document_type'=>$type,'template_code'=>'TPL-'.$type,'is_active'=>1]);
    foreach($identities as$i=>$identity){$docId=$i+1;$db->table('fiscal_documents')->insert(['id'=>$docId,'invoice_id'=>$identity[0]==='payment'?null:100,'issuer_profile_id'=>1,'document_type'=>$identity[0],'status'=>'stamped','series'=>$identity[1],'folio'=>$identity[2],'expedition_postal_code'=>'06000','currency_code'=>$identity[0]==='payment'?'XXX':'MXN','deleted'=>0]);$db->table('fiscal_document_issuers')->insert(['fiscal_document_id'=>$docId,'rfc'=>$issuer['rfc'],'legal_name'=>$issuer['legal_name'],'tax_regime_code'=>'601']);$db->table('fiscal_document_receivers')->insert(['fiscal_document_id'=>$docId,'rfc'=>$receiver['rfc'],'legal_name'=>$receiver['legal_name'],'tax_regime_code'=>'616','fiscal_postal_code'=>'06000','cfdi_use_code'=>$identity[0]==='payment'?'CP01':'S01']);$name=str_pad(dechex($docId),48,'0',STR_PAD_LEFT).'.xml';file_put_contents($root.DIRECTORY_SEPARATOR.$name,$xmls[$i]);$db->table('fiscal_document_artifacts')->insert(['id'=>$docId,'fiscal_document_id'=>$docId,'artifact_type'=>'stamped_xml','storage_path'=>'fiscal/artifacts/'.$name,'sha256'=>hash('sha256',$xmls[$i]),'superseded_at'=>null]);$db->table('fiscal_document_stamps')->insert(['id'=>$docId,'fiscal_document_id'=>$docId,'stamp_attempt_id'=>$docId,'uuid'=>strtoupper($uuids[$i]),'stamped_xml_artifact_id'=>$docId,'pac_pdf_artifact_id'=>null,'pdf_status'=>'pending','provider'=>'fake']);}
    $meta=new FiscalPdfPrintMetadataBuilder();foreach($identities as$i=>$identity){$m=$meta->build($xmls[$i],(object)['document_type'=>$identity[0],'series'=>$identity[1],'folio'=>$identity[2]],(object)$issuer,(object)$receiver);$assert($m['serie']===$identity[1]&&$m['folio']===(string)$identity[2]&&$m['emisor_razon_social']==='Compañía Ñandú','13.'.($i+1).' PDF metadata '.$identity[0].' is derived from stamped XML identity.');}
    $reject(fn()=>$meta->build($xmls[0],(object)['document_type'=>'income','series'=>'CHANGED','folio'=>'999'],(object)$issuer,(object)$receiver),'14. PDF rejects disagreement between stamped XML and persisted document.');
    $oldHash=hash('sha256',$xmls[0]);$db->table('fiscal_series')->where('id',1)->update(['series'=>'NEW','current_folio'=>999]);$assert(hash('sha256',$xmls[0])===$oldHash&&$meta->build($xmls[0],(object)['document_type'=>'income','series'=>'FI','folio'=>'10'],(object)$issuer,(object)$receiver)['folio']==='10','15. Current series changes do not alter historical XML/PDF identity.');

    $logo=$root.DIRECTORY_SEPARATOR.'logo.png';file_put_contents($logo,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));$adapter=new P12CapturingPdfAdapter();$config=new FiscalPdfProvider();$config->provider='fake';$config->enabled=true;$branding=new FiscalIssuerBrandingService(static fn(int$issuerId):string=>$logo);$pdf=new FiscalPacPdfGenerationService($db,$adapter,$config,$root,$branding);
    foreach($identities as$i=>$identity){$result=$pdf->generate($i+1,7);$assert($result->pdfAvailable&&$result->status==='stamped','16.'.($i+1).' Final fake PDF generated for '.$identity[0].' fixture.');}
    $assert($adapter->calls===5&&$adapter->requests[0]->printMetadata['serie']==='FI'&&$adapter->requests[1]->printMetadata['serie']==='NE'&&$adapter->requests[4]->printMetadata['folio']==='22','17. PDF adapter receives persisted identity for income expense and mixed payment.');
    $assert($adapter->requests[0]->uuid===strtoupper($uuids[0])&&$adapter->requests[0]->stampedXml===$xmls[0],'18. PDF uses persisted stamped XML and UUID evidence.');
    $assert($adapter->requests[0]->logoBase64!==null&&hash('sha256',$adapter->requests[0]->stampedXml)===$oldHash,'19. Configurable current logo changes presentation only, never XML.');
    $again=$pdf->generate(1,7);$assert($again->status==='existing'&&$adapter->calls===5,'20. Repeated PDF request is idempotent and does not call provider twice.');
    $assert($db->table('fiscal_document_binary_artifacts')->countAllResults()===5,'21. One validated immutable PDF artifact is active per document.');

    $incomeSource=file_get_contents(APPPATH.'Services/Fiscal/FiscalDocumentFromDraftSnapshotService.php');$paymentSource=file_get_contents(APPPATH.'FiscalServices/PaymentComplementFiscalDocumentService.php');$expenseSource=file_get_contents(APPPATH.'Services/Fiscal/CreditNoteService.php');
    $assert(str_contains($incomeSource,'fiscal_document_id FROM')&&str_contains($paymentSource,"'action'=>'existing'")&&str_contains($expenseSource,"fiscal_credit_notes').' WHERE id=? AND deleted=0 FOR UPDATE"),'22. All three materializers guard repeated requests with persisted document identity.');
    $assert(substr_count($incomeSource,'FOR UPDATE')>=2&&str_contains($paymentSource,"document_type='pago'")&&str_contains($paymentSource,'FOR UPDATE')&&str_contains($expenseSource,"document_type=? AND is_active=1 AND deleted=0 ORDER BY is_default DESC,id FOR UPDATE"),'23. Income payment and expense allocate folios under row locks.');
    $assert(str_contains($paymentSource,'$finalSnapshot')&&str_contains($paymentSource,'$finalXml'),'24. Payment pre-XML is rebuilt once from frozen snapshot plus persisted series/folio.');
    echo "{$passed} passed, {$failed} failed. No source database or PAC accessed.\n";
}catch(Throwable$e){fwrite(STDERR,'[FAIL] '.get_class($e).': '.$e->getMessage().PHP_EOL.$e->getTraceAsString().PHP_EOL);$failed++;}
finally{if($db)$db->close();if($server&&$owned){if(!preg_match('/^ikontrol_test_p12_[a-f0-9]{12}$/D',$owned))throw new RuntimeException('Unsafe database cleanup target.');$server->query('DROP DATABASE `'.$owned.'`');$server->close();echo "Owned synthetic MySQL schema removed.\n";}if($root){$real=realpath($root);$base=realpath(WRITEPATH.'tests');if($real&&$base&&str_starts_with($real,$base.DIRECTORY_SEPARATOR.'p12_'))$removeTree($real);}}
exit($failed?1:0);
