<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
helper(['general','date_time','currency','form']);
$db=require dirname(__DIR__).'/Increment02/isolated_database.php';
$pass=$fail=0;$ok=static function(bool$v,string$m)use(&$pass,&$fail):void{echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$pass++:$fail++;};
try{
 $row=$db->table('payment_complements c')->select('c.id,c.fiscal_document_id,p.source_invoice_payment_id,d.payment_allocation_id,d.fiscal_document_id source_fiscal_document_id')->join('payment_complement_payments p','p.payment_complement_id=c.id AND p.deleted=0')->join('payment_complement_documents d','d.payment_complement_payment_id=p.id AND d.deleted=0')->join('fiscal_document_stamps s','s.fiscal_document_id=c.fiscal_document_id')->where(['c.status'=>'stamped','c.deleted'=>0])->orderBy('c.id','DESC')->get(1)->getRow();
 if(!$row)throw new RuntimeException('La copia aislada no contiene un Complemento timbrado para probar cancelación.');
 $user=(int)$db->table('users')->where(['is_admin'=>1,'deleted'=>0])->get(1)->getRow()->id;
 $paymentBefore=(array)$db->table('invoice_payments')->where('id',$row->source_invoice_payment_id)->get(1)->getRow();$allocationBefore=(array)$db->table('payment_allocations')->where('id',$row->payment_allocation_id)->get(1)->getRow();$movementsBefore=$db->table('financial_account_movements')->countAllResults();
 $invalid=false;try{(new App\FiscalServices\PaymentComplementCancellationService($db,new App\Services\Fiscal\Cancellation\FiscalCancellationService($db,new App\Services\Fiscal\Cancellation\FakeFiscalCancellationAdapter('accepted'))))->request((int)$row->id,'01',null,$user);}catch(Throwable){$invalid=true;}$ok($invalid,'Motivo 01 exige UUID sustituto válido antes del PAC.');
 $fake=new App\Services\Fiscal\Cancellation\FakeFiscalCancellationAdapter('accepted');$service=new App\FiscalServices\PaymentComplementCancellationService($db,new App\Services\Fiscal\Cancellation\FiscalCancellationService($db,$fake));$result=$service->request((int)$row->id,'02',null,$user);$again=$service->request((int)$row->id,'02',null,$user);
 $request=$db->table('fiscal_cancellation_requests')->where('fiscal_document_id',$row->fiscal_document_id)->orderBy('id','DESC')->get(1)->getRow();$document=$db->table('fiscal_documents')->where('id',$row->fiscal_document_id)->get(1)->getRow();
 $ok($result['status']==='accepted'&&$document->status==='cancelled','Cancelación confirmada cambia sólo el estado fiscal definitivo.');$ok($fake->calls===1&&$again['status']==='accepted','Solicitud repetida es idempotente y no llama dos veces al PAC.');$ok($request&&$request->cancellation_reason==='02'&&$request->user_id==$user,'Solicitud conserva motivo, usuario y fechas durables.');$ok($db->table('fiscal_cancellation_artifacts')->where(['fiscal_cancellation_request_id'=>$request->id,'artifact_type'=>'cancellation_ack'])->countAllResults()===1,'Acuse XML queda persistido como artifact fiscal.');
 $paymentAfter=(array)$db->table('invoice_payments')->where('id',$row->source_invoice_payment_id)->get(1)->getRow();$allocationAfter=(array)$db->table('payment_allocations')->where('id',$row->payment_allocation_id)->get(1)->getRow();$ok($paymentBefore['status']===$paymentAfter['status']&&$paymentBefore['deleted']===$paymentAfter['deleted'],'Pago administrativo permanece intacto.');$ok($allocationBefore['status']===$allocationAfter['status']&&$allocationBefore['deleted']===$allocationAfter['deleted']&&$allocationBefore['amount_applied']===$allocationAfter['amount_applied'],'payment_allocation permanece activa e intacta.');$ok($movementsBefore===$db->table('financial_account_movements')->countAllResults(),'Cancelar Complemento genera cero movimientos financieros.');
 $drafts=new App\Services\PaymentComplementDraftService($db);$installments=new ReflectionMethod($drafts,'stampedInstallments');$paid=new ReflectionMethod($drafts,'stampedAmount');$ok($installments->invoke($drafts,(int)$row->source_fiscal_document_id)===0&&$paid->invoke($drafts,(int)$row->source_fiscal_document_id)==='0.000000','Historia fiscal futura ignora el Complemento cancelado sin renumerar documentos existentes.');$eligible=array_filter($drafts->candidatePayments((int)$paymentAfter['client_id']),fn($p)=>(int)$p->id===(int)$row->source_invoice_payment_id);$ok((bool)$eligible,'Pago vuelve a ser elegible fiscalmente después de cancelación definitiva.');
 $routes=file_get_contents(APPPATH.'Config/Routes.php');$controller=file_get_contents(APPPATH.'Controllers/Payment_complements.php');$view=file_get_contents(APPPATH.'Views/payment_complements/edit.php');$ok(str_contains($routes,'cancel/request')&&str_contains($routes,'cancel/check'),'Rutas explícitas de solicitud y consulta existen.');$ok(str_contains($controller,'fiscal_invoices_cancel')&&str_contains($controller,'Verificar cancelación')&&str_contains($view,'Descargar acuse'),'Listado y detalle reutilizan permisos y acciones fiscales existentes.');$adapter=file_get_contents(APPPATH.'Services/Fiscal/Cancellation/TimbradorXpressCancellationAdapter.php');$ok(str_contains($adapter,'FiscalCancellationStatusMapper')&&str_contains($adapter,'cancelarPEM')&&str_contains($adapter,'consultarEstadoSAT'),'Complementos reutilizan mapper, cancelarPEM y consulta SAT de Facturas.');
 $modalController=file_get_contents(APPPATH.'Controllers/Payment_complement_cancellations.php');$modalView=file_get_contents(APPPATH.'Views/payment_complements/cancel_form.php');
 $ok(str_contains($routes,"post('payment_complements/cancel/form'")&&str_contains($routes,"post('payment_complements/(:num)/cancel/request'")&&str_contains($routes,"['filter' => 'csrf']"),'Modal usa POST compatible con ajax-modal y la solicitud mutante conserva POST + CSRF.');
 $ok(str_contains($controller,'payment_complements/cancel/form')&&str_contains($controller,'data-post-complement_id')&&str_contains($view,'payment_complements/cancel/form')&&str_contains($view,'data-post-complement_id'),'Listado y detalle envían complement_id con el patrón modal de Facturas.');
 $ok(str_contains($modalController,'function form()')&&str_contains($modalController,"getPost('complement_id')")&&str_contains($modalController,'PageNotFoundException')&&str_contains($modalView,'payment-complement-cancel-form')&&str_contains($modalView,'cancellation_reason'),'Controlador carga el formulario, rechaza IDs/estados no cancelables y usa la vista modal esperada.');
}catch(Throwable$e){echo'[FAIL] '.get_class($e).': '.$e->getMessage().' at '.$e->getFile().':'.$e->getLine().PHP_EOL;$fail++;}
echo"TOTAL PASS=$pass FAIL=$fail".PHP_EOL;exit($fail?1:0);
