<?php
declare(strict_types=1);
namespace App\Services\Fiscal\Cfdi40;
use App\Models\Fiscal\Fiscal_document_artifacts_model;
use RuntimeException;use Throwable;
final class CfdiPreXmlArtifactService{
 private $db;private string$dir;public function __construct($db=null,?string$dir=null){$this->db=$db?:db_connect();$this->dir=$dir?:WRITEPATH.'fiscal/prexml';}
 public function generate(int$documentId,int$userId,bool$authorized):array{if(!$authorized)throw new RuntimeException('No tiene permiso para generar Pre-XML.');$model=(new CfdiDraftMapper())->map($documentId);$xml=(new CfdiXmlBuilder())->build($model);$semantic=(new CfdiSemanticValidator())->validate($model);if(!$semantic['is_valid']){$artifact=$this->storeDiagnosticXml($documentId,$userId,$xml,$semantic);$failure=new CfdiSemanticValidationException($semantic);$this->recordSemanticFailure($documentId,$userId,$failure->diagnostic()+['pre_xml_artifact_id'=>(int)$artifact->id]);throw $failure;}$hash=hash('sha256',$xml);$artifacts=new Fiscal_document_artifacts_model();$existing=$this->db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','builder_version'=>CfdiXmlBuilder::VERSION,'sha256'=>$hash,'superseded_at'=>null])->get(1)->getRow();if($existing)return['artifact'=>$existing,'xml'=>$xml,'semantic'=>$semantic,'xsd'=>json_decode((string)$existing->validation_payload,true)['xsd']??null,'action'=>'existing'];$xsd=(new CfdiXsdValidator())->validate($xml);$validation=['semantic'=>$semantic,'xsd'=>$xsd,'full_cfdi_validation'=>['is_valid'=>false,'reason'=>'Pendiente de certificado y sello.']];$this->ensurePrivateDir();$name=bin2hex(random_bytes(24)).'.xml';$relative='fiscal/prexml/'.$name;$target=$this->dir.DIRECTORY_SEPARATOR.$name;$tmp=$target.'.tmp.'.bin2hex(random_bytes(6));if(file_put_contents($tmp,$xml,LOCK_EX)===false||!rename($tmp,$target)){@unlink($tmp);throw new RuntimeException('No fue posible almacenar el Pre-XML de forma atómica.');}$this->db->transBegin();try{$now=get_current_utc_time();$this->db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','superseded_at'=>null])->update(['superseded_at'=>$now]);$data=['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','storage_path'=>$relative,'sha256'=>$hash,'byte_size'=>strlen($xml),'builder_version'=>CfdiXmlBuilder::VERSION,'schema_version'=>CfdiXmlBuilder::SCHEMA_VERSION,'schema_sha256'=>$xsd['schema_sha256'],'validation_status'=>$xsd['status'],'validation_payload'=>json_encode($validation,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'created_by'=>$userId,'created_at'=>$now];$id=$artifacts->ci_save($data);$this->audit($documentId,$userId,'pre_xml_generated',$hash,CfdiXmlBuilder::VERSION,$xsd['status'],(int)$id);$this->db->transCommit();$data['id']=$id;return['artifact'=>(object)$data,'xml'=>$xml,'semantic'=>$semantic,'xsd'=>$xsd,'action'=>'created'];}catch(Throwable$e){$this->db->transRollback();@unlink($target);throw$e;}}
 public function read(int$artifactId,bool$authorized):array{if(!$authorized)throw new RuntimeException('No tiene permiso para ver Pre-XML.');$a=$this->db->table('fiscal_document_artifacts')->where(['id'=>$artifactId,'artifact_type'=>'pre_xml'])->get(1)->getRow();if(!$a)throw new RuntimeException('El artefacto no existe.');$path=$this->safePath($a->storage_path);$xml=file_get_contents($path);if($xml===false||!hash_equals($a->sha256,hash('sha256',$xml)))throw new RuntimeException('El artefacto no supera la verificación de integridad.');return['artifact'=>$a,'xml'=>$xml,'validation'=>json_decode((string)$a->validation_payload,true)];}
 private function storeDiagnosticXml(int$documentId,int$userId,string$xml,array$semantic):object
 {
  $hash=hash('sha256',$xml);$existing=$this->db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','builder_version'=>CfdiXmlBuilder::VERSION,'sha256'=>$hash,'superseded_at'=>null])->get(1)->getRow();if($existing)return$existing;
  $this->ensurePrivateDir();$name=bin2hex(random_bytes(24)).'.xml';$relative='fiscal/prexml/'.$name;$target=$this->dir.DIRECTORY_SEPARATOR.$name;$tmp=$target.'.tmp.'.bin2hex(random_bytes(6));if(file_put_contents($tmp,$xml,LOCK_EX)===false||!rename($tmp,$target)){@unlink($tmp);throw new RuntimeException('No fue posible almacenar el XML diagnóstico.');}
  $now=get_current_utc_time();$this->db->transBegin();try{$this->db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','superseded_at'=>null])->update(['superseded_at'=>$now]);$data=['fiscal_document_id'=>$documentId,'artifact_type'=>'pre_xml','storage_path'=>$relative,'sha256'=>$hash,'byte_size'=>strlen($xml),'builder_version'=>CfdiXmlBuilder::VERSION,'schema_version'=>CfdiXmlBuilder::SCHEMA_VERSION,'schema_sha256'=>null,'validation_status'=>'semantic_error','validation_payload'=>json_encode(['semantic'=>$semantic,'diagnostic_only'=>true],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'created_by'=>$userId,'created_at'=>$now];$id=(new Fiscal_document_artifacts_model())->ci_save($data);$this->audit($documentId,$userId,'pre_xml_diagnostic_stored',$hash,CfdiXmlBuilder::VERSION,'semantic_error',(int)$id);$this->db->transCommit();$data['id']=$id;return(object)$data;}catch(Throwable$e){$this->db->transRollback();@unlink($target);throw$e;}
 } private function ensurePrivateDir():void{if(!is_dir($this->dir)&&!mkdir($this->dir,0770,true)&&!is_dir($this->dir))throw new RuntimeException('No fue posible crear el almacenamiento privado.');}
 private function safePath(string$relative):string{if(!preg_match('#^fiscal/prexml/([a-f0-9]{48}\.xml)$#',$relative,$match))throw new RuntimeException('Ruta de artefacto inválida.');$base=realpath($this->dir);$path=realpath($this->dir.DIRECTORY_SEPARATOR.$match[1]);if(!$base||!$path||!str_starts_with($path,$base.DIRECTORY_SEPARATOR))throw new RuntimeException('Acceso de almacenamiento denegado.');return$path;}
 private function recordSemanticFailure(int$documentId,int$userId,array$diagnostic):void
 {
  try{
   $doc=$this->db->table('fiscal_documents')->select('invoice_id,source_draft_id')->where('id',$documentId)->get(1)->getRow();
   $draftId=(int)($doc->source_draft_id??0);
   $saleIds=array_map('intval',array_column($this->db->table('fiscal_document_sales')->select('sale_id')->where('fiscal_document_id',$documentId)->get()->getResultArray(),'sale_id'));
   if(!$saleIds&&$draftId)$saleIds=array_map('intval',array_column($this->db->table('fiscal_draft_sales')->select('sale_id')->where('fiscal_draft_id',$draftId)->get()->getResultArray(),'sale_id'));
   if(!$saleIds&&!empty($doc->invoice_id))$saleIds=[(int)$doc->invoice_id];
   $detail=['draft_id'=>$draftId?:null,'fiscal_document_id'=>$documentId,'sale_id'=>$saleIds[0]??null,'sale_ids'=>$saleIds]+$diagnostic;
   log_message('error','CFDI_SEMANTIC_VALIDATION_FAILURE {detail}',['detail'=>json_encode($detail,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);
   $this->audit($documentId,$userId,'pre_xml_error',null,CfdiXmlBuilder::VERSION,'semantic_error',null,$detail);
   if($draftId)$this->db->table('fiscal_draft_audit')->insert(['fiscal_draft_id'=>$draftId,'sale_id'=>$saleIds[0]??null,'user_id'=>$userId,'event'=>'semantic_validation_failed','summary_json'=>json_encode($detail,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'created_at'=>get_current_utc_time()]);
  }catch(Throwable$e){
   log_message('error','CFDI semantic validation diagnostic persistence failed for document {document}: {type}',['document'=>$documentId,'type'=>get_class($e)]);
  }
 }
 private function audit(int$documentId,int$userId,string$action,?string$hash,string$version,string$status,?int$artifactId=null,array$detail=[]):void{$doc=$this->db->table('fiscal_documents')->where('id',$documentId)->get(1)->getRow();$reason=['artifact_id'=>$artifactId,'sha256'=>$hash,'builder_version'=>$version,'status'=>$status]+$detail;$this->db->table('fiscal_document_audit')->insert(['fiscal_document_id'=>$documentId,'invoice_id'=>$doc->invoice_id??null,'user_id'=>$userId,'action'=>$action,'reason'=>json_encode($reason,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'new_hash'=>$hash,'created_at'=>get_current_utc_time()]);}
}
