<?php
declare(strict_types=1);
namespace App\Services\Fiscal\Cfdi40;
use App\Domain\Fiscal\Cfdi40\{CfdiDocument,CfdiConceptTax,CfdiTaxSummary};
use App\Services\Fiscal\{FiscalDecimalCalculator,FiscalIssueDateService};
use DOMDocument;use DOMElement;use RuntimeException;
final class CfdiXmlBuilder{
 public const VERSION='1.0.0';public const SCHEMA_VERSION='CFDI 4.0';
 private const CFDI='http://www.sat.gob.mx/cfd/4';private const XSI='http://www.w3.org/2001/XMLSchema-instance';
 private FiscalDecimalCalculator$d;public function __construct(){$this->d=new FiscalDecimalCalculator();}
 public function build(CfdiDocument$c):string{$dom=new DOMDocument('1.0','UTF-8');$dom->formatOutput=true;$dom->preserveWhiteSpace=false;$root=$dom->createElementNS(self::CFDI,'cfdi:Comprobante');$dom->appendChild($root);$root->setAttributeNS('http://www.w3.org/2000/xmlns/','xmlns:xsi',self::XSI);$root->setAttributeNS(self::XSI,'xsi:schemaLocation',self::CFDI.' http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd');
  $this->attrs($root,['Version'=>'4.0','Serie'=>$c->get('series'),'Folio'=>$c->get('folio'),'Fecha'=>$this->date((string)$c->get('issue_date')),'FormaPago'=>$c->get('payment_form_code'),'SubTotal'=>$this->money((string)$c->get('subtotal')),'Descuento'=>$this->positive((string)$c->get('discount'))?$this->money((string)$c->get('discount')):null,'Moneda'=>$c->get('currency_code'),'TipoCambio'=>$c->get('currency_code')!=='MXN'?$this->decimal((string)$c->get('exchange_rate'),6):null,'Total'=>$this->money((string)$c->get('total')),'TipoDeComprobante'=>'I','Exportacion'=>$c->get('export_code'),'MetodoPago'=>$c->get('payment_method_code'),'LugarExpedicion'=>$c->get('expedition_postal_code')]);
  $issuer=$dom->createElementNS(self::CFDI,'cfdi:Emisor');$this->attrs($issuer,['Rfc'=>$c->issuer->get('rfc'),'Nombre'=>$c->issuer->get('legal_name'),'RegimenFiscal'=>$c->issuer->get('tax_regime_code')]);$root->appendChild($issuer);
  $receiver=$dom->createElementNS(self::CFDI,'cfdi:Receptor');$foreign=$c->receiver->get('fiscal_residence_country_code');$this->attrs($receiver,['Rfc'=>$c->receiver->get('rfc'),'Nombre'=>$c->receiver->get('legal_name'),'DomicilioFiscalReceptor'=>$c->receiver->get('fiscal_postal_code'),'ResidenciaFiscal'=>$foreign&&$foreign!=='MEX'?$foreign:null,'NumRegIdTrib'=>$foreign&&$foreign!=='MEX'?$c->receiver->get('foreign_tax_registration'):null,'RegimenFiscalReceptor'=>$c->receiver->get('tax_regime_code'),'UsoCFDI'=>$c->receiver->get('cfdi_use_code')]);$root->appendChild($receiver);
  $concepts=$dom->createElementNS(self::CFDI,'cfdi:Conceptos');foreach($c->concepts as$item){$node=$dom->createElementNS(self::CFDI,'cfdi:Concepto');$this->attrs($node,['ClaveProdServ'=>$item->get('product_service_code'),'NoIdentificacion'=>$item->get('identification_number'),'Cantidad'=>$this->decimal((string)$item->get('quantity'),6),'ClaveUnidad'=>$item->get('unit_code'),'Unidad'=>$item->get('unit_name'),'Descripcion'=>$item->get('description'),'ValorUnitario'=>$this->decimal((string)$item->get('unit_value'),6),'Importe'=>$this->money((string)$item->get('gross_amount')),'Descuento'=>$this->positive((string)$item->get('discount'))?$this->money((string)$item->get('discount')):null,'ObjetoImp'=>$item->get('tax_object_code')]);
   if($item->get('tax_object_code')!=='01'&&$item->taxes){$taxNode=$dom->createElementNS(self::CFDI,'cfdi:Impuestos');$ret=array_values(array_filter($item->taxes,fn($t)=>$t->taxType==='withheld'));$tra=array_values(array_filter($item->taxes,fn($t)=>$t->taxType==='transferred'));if($tra){$group=$dom->createElementNS(self::CFDI,'cfdi:Traslados');foreach($tra as$t)$group->appendChild($this->conceptTax($dom,'Traslado',$t));$taxNode->appendChild($group);}if($ret){$group=$dom->createElementNS(self::CFDI,'cfdi:Retenciones');foreach($ret as$t)$group->appendChild($this->conceptTax($dom,'Retencion',$t));$taxNode->appendChild($group);}$node->appendChild($taxNode);}$concepts->appendChild($node);}$root->appendChild($concepts);
  if($c->taxTotals){$global=$dom->createElementNS(self::CFDI,'cfdi:Impuestos');$ret=array_values(array_filter($c->taxTotals,fn($t)=>$t->taxType==='withheld'));$tra=array_values(array_filter($c->taxTotals,fn($t)=>$t->taxType==='transferred'));$this->attrs($global,['TotalImpuestosRetenidos'=>$ret?$this->money((string)$c->get('withheld_tax_total')):null,'TotalImpuestosTrasladados'=>$tra?$this->money((string)$c->get('transferred_tax_total')):null]);if($ret){$group=$dom->createElementNS(self::CFDI,'cfdi:Retenciones');foreach($ret as$t){$n=$dom->createElementNS(self::CFDI,'cfdi:Retencion');$this->attrs($n,['Impuesto'=>$t->taxCode,'Importe'=>$this->money($t->amount)]);$group->appendChild($n);}$global->appendChild($group);}if($tra){$group=$dom->createElementNS(self::CFDI,'cfdi:Traslados');foreach($tra as$t)$group->appendChild($this->summaryTax($dom,$t));$global->appendChild($group);}$root->appendChild($global);}
  $xml=$dom->saveXML();if($xml===false)throw new RuntimeException('No fue posible serializar el Pre-XML.');return$xml;
 }
 private function conceptTax(DOMDocument$d,string$name,CfdiConceptTax$t):DOMElement{$n=$d->createElementNS(self::CFDI,'cfdi:'.$name);$attrs=['Base'=>$this->money($t->base),'Impuesto'=>$t->taxCode,'TipoFactor'=>$t->factorType];if($t->factorType!=='Exento'){$attrs['TasaOCuota']=$this->decimal((string)$t->rateOrQuota,6);$attrs['Importe']=$this->money($t->amount);}$this->attrs($n,$attrs);return$n;}
 private function summaryTax(DOMDocument$d,CfdiTaxSummary$t):DOMElement{$n=$d->createElementNS(self::CFDI,'cfdi:Traslado');$attrs=['Base'=>$this->money($t->base),'Impuesto'=>$t->taxCode,'TipoFactor'=>$t->factorType];if($t->factorType!=='Exento'){$attrs['TasaOCuota']=$this->decimal((string)$t->rateOrQuota,6);$attrs['Importe']=$this->money($t->amount);}$this->attrs($n,$attrs);return$n;}
 private function attrs(DOMElement$e,array$a):void{foreach($a as$k=>$v)if($v!==null&&$v!==''){$v=(string)$v;if(preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F]/',$v))throw new RuntimeException("El atributo $k contiene caracteres de control no permitidos.");$e->setAttribute($k,$v);}}
 private function date(string$v):string{return(new FiscalIssueDateService())->formatForXml($v);}
 private function money(string$v):string{return$this->d->money($v);}
 private function decimal(string$v,int$scale):string{return$this->d->normalize($v,$scale);}
 private function positive(string$v):bool{return$this->d->compare($v,'0')>0;}
}
