<?php
declare(strict_types=1);
namespace App\Services\Fiscal\Cfdi40;
use DOMDocument;use RuntimeException;
final class CfdiXsdValidator{
 private string$root;public function __construct(?string$root=null){$this->root=$root?:ROOTPATH.'resources/fiscal/sat/cfdi40';}
 public function schemaHash():string{$path=$this->path('cfdv40.xsd');return hash_file('sha256',$path)?:'';}
 public function validate(string$xml):array{$schema=$this->path('cfdv40.xsd');$catalog=$this->path('catCFDI.xsd');$types=$this->path('tdCFDI.xsd');$payments=ROOTPATH.'resources/fiscal/sat/pagos20/Pagos20.xsd';$paymentCatalog=ROOTPATH.'resources/fiscal/sat/pagos20/catPagos.xsd';$composite=ROOTPATH.'resources/fiscal/sat/pagos20/cfdi40-pagos20.xsd';if(!is_file($payments)||!is_file($paymentCatalog)||!is_file($composite))throw new RuntimeException('Los XSD locales de Pagos 2.0 no están disponibles.');$validationSchema=str_contains($xml,'http://www.sat.gob.mx/Pagos20')?$composite:$schema;$map=['http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd'=>$schema,'http://www.sat.gob.mx/sitio_internet/cfd/catalogos/catCFDI.xsd'=>$catalog,'http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI/tdCFDI.xsd'=>$types,'http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos20.xsd'=>$payments,'http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos/catPagos.xsd'=>$paymentCatalog];$allowed=[$schema,$catalog,$types,$payments,$paymentCatalog,$composite];$previous=libxml_use_internal_errors(true);libxml_clear_errors();$oldLoader=libxml_set_external_entity_loader(static function($public,$system,$context)use($map,$allowed){if(isset($map[$system]))return fopen($map[$system],'rb');$candidate=str_starts_with((string)$system,'file://')?urldecode(substr((string)$system,7)):(string)$system;foreach($allowed as$path)if(str_replace('\\','/',$candidate)===str_replace('\\','/',$path))return fopen($path,'rb');return null;});try{$dom=new DOMDocument();$loaded=$dom->loadXML($xml,LIBXML_NONET|LIBXML_NOBLANKS);$valid=$loaded&&@$dom->schemaValidate($validationSchema);$errors=[];foreach(libxml_get_errors()as$e)$errors[]=['level'=>$e->level,'code'=>$e->code,'line'=>$e->line,'column'=>$e->column,'message'=>trim($e->message)];$pending=!$valid&&$errors!==[];foreach($errors as$e)if(!preg_match('/(Sello|NoCertificado|Certificado).*required/i',$e['message'])){$pending=false;break;}return['is_valid'=>$valid,'status'=>$valid?'valid':($pending?'schema_pending_signature':'invalid'),'errors'=>$errors,'schema_version'=>'CFDI 4.0','schema_sha256'=>$this->schemaHash()];}finally{libxml_set_external_entity_loader(is_callable($oldLoader)?$oldLoader:null);libxml_clear_errors();libxml_use_internal_errors($previous);}}
 private function path(string$file):string{if(!in_array($file,['cfdv40.xsd','catCFDI.xsd','tdCFDI.xsd'],true))throw new RuntimeException('Recurso XSD no permitido.');$path=$this->root.DIRECTORY_SEPARATOR.$file;if(!is_file($path))throw new RuntimeException('El recurso XSD local no está disponible.');return$path;}
}
