<?php
echo view('items/_fiscal_item_fields',get_defined_vars());return;
$fc=$fiscal_configuration??[];$setting=$fc['setting']??[];$override=in_array(($fc['source']??''),['invoice_item_override','item_override'],true);
$value=static fn($key)=>(string)($override?($fc[$key]??''):($setting[$key]??''));$taxes=(array)($fc['taxes']??[]);
?>
<hr><h4>Datos fiscales</h4><div id="invoice-fiscal-summary" class="alert <?php echo !empty($fc['ready'])?'alert-success':'alert-warning';?>"><?php echo !empty($fc['ready'])?'Configuración fiscal completa.':'Falta configuración fiscal para esta partida.';?></div>
<div class="form-check mb15"><input type="checkbox" class="form-check-input" id="fiscal_override_enabled" name="fiscal_override_enabled" value="1" <?php echo$override?'checked':'';?>><label for="fiscal_override_enabled">Usar configuración específica para esta venta</label><div><small>No modifica el producto maestro.</small></div></div>
<div id="invoice-fiscal-override-fields" class="<?php echo$override?'':'d-none';?>">
 <div class="row g-2"><div class="col-md-6"><label>ClaveProdServ SAT</label><input class="form-control" name="product_service_code" value="<?php echo esc($value('product_service_code'));?>"></div><div class="col-md-6"><label>ClaveUnidad SAT</label><input class="form-control" name="unit_code" value="<?php echo esc($value('unit_code'));?>"></div><div class="col-md-6"><label>Unidad</label><input class="form-control" name="fiscal_commercial_unit" value="<?php echo esc($value('commercial_unit'));?>"></div><div class="col-md-6"><label>Objeto de impuesto</label><input class="form-control" name="tax_object_code" value="<?php echo esc($value('tax_object_code'));?>"></div><div class="col-md-12"><label>Descripción fiscal</label><input class="form-control" name="fiscal_description" value="<?php echo esc($value('fiscal_description'));?>"></div></div>
 <h5 class="mt15">Impuestos</h5><?php foreach($taxes as$i=>$tax){?><div class="row g-2 mb5"><div class="col-md-3"><input class="form-control" name="fiscal_taxes[<?php echo$i;?>][tax_code]" value="<?php echo esc($tax['tax_code']??'');?>" placeholder="Código SAT"></div><div class="col-md-3"><select class="form-control" name="fiscal_taxes[<?php echo$i;?>][tax_type]"><option value="transfer" <?php echo($tax['tax_type']??'')==='transfer'?'selected':'';?>>Traslado</option><option value="withholding" <?php echo($tax['tax_type']??'')==='withholding'?'selected':'';?>>Retención</option></select></div><div class="col-md-3"><input class="form-control" name="fiscal_taxes[<?php echo$i;?>][factor_type]" value="<?php echo esc($tax['factor_type']??'');?>" placeholder="Factor"></div><div class="col-md-3"><input class="form-control" name="fiscal_taxes[<?php echo$i;?>][rate_or_quota]" value="<?php echo esc($tax['rate_or_quota']??'');?>" placeholder="Tasa/cuota"></div></div><?php }?>
<style>#invoice-fiscal-override-fields>.row.g-2.mb5{display:none}</style>
<div class="mt10"><label>Objeto de impuesto SAT</label><select class="form-control" id="invoice-tax-object-select" name="tax_object_code"><?php foreach(($sat_tax_objects??[])as$obj){?><option value="<?php echo esc($obj->code);?>" <?php echo$value('tax_object_code')===$obj->code?'selected':'';?>><?php echo esc($obj->code.' · '.$obj->description);?></option><?php }?></select></div>
<div id="invoice-tax-editor" class="mt15"></div><button type="button" id="invoice-add-tax" class="btn btn-default btn-sm mt5">+ Agregar impuesto</button>
<?php if(!empty($can_update_master_fiscal)){?><div class="form-check mt15"><input class="form-check-input" type="checkbox" name="update_master_fiscal" value="1" id="update-master-fiscal"><label for="update-master-fiscal">Guardar también como configuración predeterminada del producto</label><div><small class="text-warning">Esta configuración se utilizará en futuras ventas.</small></div></div><?php }?>
</div>
<script>$(function(){var codes=<?php echo json_encode(array_map(fn($x)=>['code'=>$x->code,'label'=>$x->code.' · '.$x->description],$sat_tax_codes??[]),JSON_UNESCAPED_UNICODE);?>,factors=['Tasa','Cuota','Exento'],initial=<?php echo json_encode(array_values($taxes),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);?>,editor=$('#invoice-tax-editor'),index=0;$('#invoice-fiscal-override-fields input[name=tax_object_code]').removeAttr('name').hide();$('#invoice-fiscal-override-fields>.row.g-2.mb5').find(':input').removeAttr('name');function options(rows,value){return rows.map(function(r){var v=r.code||r;return '<option value="'+v+'" '+(v===value?'selected':'')+'>'+String(r.label||r)+'</option>';}).join('');}function add(t){t=t||{};var i=index++,row=$('<div class="invoice-tax-row border rounded p-2 mb10"><div class="row g-2"><div class="col-md-3"><label>Tipo</label><select class="form-control" name="fiscal_taxes['+i+'][tax_type]"><option value="transfer">Traslado</option><option value="withholding">Retención</option></select></div><div class="col-md-3"><label>Impuesto SAT</label><select class="form-control" name="fiscal_taxes['+i+'][tax_code]">'+options(codes,t.tax_code||'')+'</select></div><div class="col-md-2"><label>Factor</label><select class="form-control tax-factor" name="fiscal_taxes['+i+'][factor_type]">'+options(factors,t.factor_type||'Tasa')+'</select></div><div class="col-md-3"><label>Tasa/cuota</label><input class="form-control tax-rate" name="fiscal_taxes['+i+'][rate_or_quota]" value="'+String(t.rate_or_quota||'')+'" inputmode="decimal"></div><div class="col-md-1"><button type="button" class="btn btn-danger btn-sm remove-tax mt25">Eliminar</button></div></div></div>');row.find('[name$="[tax_type]"]').val(t.tax_type||'transfer');row.on('change','.tax-factor',function(){row.find('.tax-rate').prop('disabled',this.value==='Exento').val(this.value==='Exento'?'':row.find('.tax-rate').val());});row.on('click','.remove-tax',function(){row.remove();activate();});editor.append(row);}function activate(){$('#fiscal_override_enabled').prop('checked',true);$('#invoice-fiscal-override-fields').removeClass('d-none');}window.invoiceRenderFiscalTaxes=function(rows){editor.empty();index=0;(rows||[]).forEach(add);};window.invoiceRenderFiscalTaxes(initial);$('#invoice-add-tax').on('click',function(){add({});activate();});$('#invoice-fiscal-override-fields').on('change input','input,select',activate);$('#fiscal_override_enabled').on('change',function(){$('#invoice-fiscal-override-fields').toggleClass('d-none',!this.checked);});$('#invoice-tax-object-select').on('change',function(){if(this.value==='01')editor.empty();activate();});});</script>
