<?php echo form_open(get_uri('invoice_payments/save_payment'),['id'=>'invoice-payment-form','class'=>'general-form']); ?>
<div class="modal-body clearfix"><div class="container-fluid"><input type="hidden" name="id" value="<?php echo (int)$model_info->id; ?>">
<div class="alert alert-info">El pago se registra una sola vez. Aplicarlo a ventas no genera movimientos financieros adicionales.</div>
<div class="form-group"><div class="row"><label class="col-md-3">Cliente</label><div class="col-md-9"><?php echo form_dropdown('client_id',$clients_dropdown,$client_id,"id='payment-client-id' class='select2 validate-hidden form-control' required data-rule-required='true'"); ?></div></div></div>
<?php if($invoice_id): ?><input type="hidden" name="invoice_id" value="<?php echo (int)$invoice_id; ?>"><div class="form-group"><div class="row"><label class="col-md-3">Venta</label><div class="col-md-9"><input class="form-control" value="Venta #<?php echo (int)$invoice_id; ?>" readonly><small>Al crear el pago se aplicará automáticamente hasta cubrir el saldo pendiente de esta venta.</small></div></div></div><?php else: ?><div class="form-group"><div class="row"><label class="col-md-3">Venta (opcional)</label><div class="col-md-9"><?php echo form_dropdown('invoice_id',$invoices_dropdown,'',"id='invoice_id' class='select2 form-control'"); ?><small>Puede dejarla vacía y aplicar el pago posteriormente.</small></div></div></div><?php endif; ?>
<div class="form-group"><div class="row"><label class="col-md-3">Forma de pago</label><div class="col-md-9"><input id="invoice_payment_method_id" name="invoice_payment_method_id" value="<?php echo (int)($model_info->payment_method_id?:0); ?>" class="form-control selected_payment_method" required></div></div></div>
<div class="form-group"><div class="row"><label class="col-md-3">Cuenta de destino</label><div class="col-md-9"><select name="destination_financial_account_id" class="form-control select2 validate-hidden" required><option value="">Seleccione cuenta MXN</option><?php foreach($financial_accounts as$a): ?><option value="<?php echo(int)$a->id; ?>" <?php echo((int)$model_info->destination_financial_account_id===(int)$a->id?'selected':''); ?>><?php echo esc($a->name); ?></option><?php endforeach; ?></select></div></div></div>
<div class="form-group"><div class="row"><label class="col-md-3">Fecha</label><div class="col-md-9"><input id="invoice_payment_date" name="invoice_payment_date" value="<?php echo esc($model_info->payment_date?:get_my_local_time('Y-m-d')); ?>" class="form-control" required></div></div></div>
<div class="form-group"><div class="row"><label class="col-md-3">Monto recibido</label><div class="col-md-9"><input name="invoice_payment_amount" value="<?php echo esc($amount); ?>" class="form-control" inputmode="decimal" required></div></div></div>
<div class="form-group"><div class="row"><label class="col-md-3">Referencia</label><div class="col-md-9"><input name="invoice_payment_reference" value="<?php echo esc($model_info->reference??''); ?>" class="form-control" placeholder="Folio bancario, operación, depósito..."></div></div></div>
<div class="form-group"><div class="row"><label class="col-md-3">Notas</label><div class="col-md-9"><textarea name="invoice_payment_note" class="form-control"><?php echo esc($model_info->note??''); ?></textarea></div></div></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cerrar</button><button class="btn btn-primary">Guardar pago</button></div><?php echo form_close(); ?>
<script>$(function(){$('#invoice-payment-form').appForm({onSuccess:function(r){if(r.id)window.location='<?php echo get_uri('invoice_payments/view'); ?>/'+r.id;else location.reload();}});$('#payment-client-id,#invoice_id').select2();$('#payment-client-id').on('change',function(){var clientId=$(this).val(),$invoice=$('#invoice_id');if(!$invoice.length)return;$invoice.empty().append(new Option('Sin venta de origen','',true,true)).trigger('change');if(!clientId)return;appAjaxRequest({url:'<?php echo get_uri('invoice_payments/client_invoices'); ?>',type:'POST',dataType:'json',data:{client_id:clientId},success:function(r){if(r.success){$.each(r.results,function(_,item){$invoice.append(new Option(item.text,item.id,false,false));});$invoice.trigger('change');}else appAlert.error(r.message||'No fue posible cargar las ventas.');}});});$('#invoice-payment-form #invoice_payment_method_id').select2({data:<?php echo $payment_methods_dropdown; ?>});setDatePicker('#invoice_payment_date');});</script>
