<?php
declare(strict_types=1);
define('ROOTPATH',dirname(__DIR__,2).DIRECTORY_SEPARATOR);define('FCPATH',ROOTPATH);require ROOTPATH.'app/Config/Paths.php';$p=new Config\Paths();define('APPPATH',realpath($p->appDirectory).DIRECTORY_SEPARATOR);define('SYSTEMPATH',realpath($p->systemDirectory).DIRECTORY_SEPARATOR);define('WRITEPATH',realpath($p->writableDirectory).DIRECTORY_SEPARATOR);define('ENVIRONMENT','development');require$p->systemDirectory.'/Boot.php';CodeIgniter\Boot::bootTest($p);helper(['plugin','general','date_time']);
use App\Services\Fiscal\CommercialTaxBreakdownService;use App\Services\Fiscal\FiscalDecimal;use App\Services\Fiscal\FiscalDraftTaxSnapshotService;use App\Services\Fiscal\InvoiceItemTaxResolver;
$pass=$fail=0;$ok=function(bool$v,string$m)use(&$pass,&$fail){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$pass++:$fail++;};
try{$db=db_connect();$attempts=$db->table('fiscal_stamp_attempts')->countAllResults();$moves=$db->table('fiscal_stamp_movements')->countAllResults();$issuer=$db->table('fiscal_profiles')->where('id',2)->get(1)->getRow();
$ok($issuer&&$issuer->tax_pricing_mode==='tax_inclusive','Setting real tax_pricing_mode encontrada.');
$resolver=new InvoiceItemTaxResolver($db);$source=file_get_contents(APPPATH.'Services/Fiscal/InvoiceItemTaxResolver.php');$ok(!str_contains($source,"taxable')")&&!str_contains($source,'invoice_items.taxable'),'Setting no decide código y taxable no es fuente.');
$bad=$resolver->resolve(20,2);$ok(($bad['ready']&&$bad['tax_object_code']==='01')||(!$bad['ready']&&!empty($bad['missing'])),'Producto/override decide impuestos sin taxable administrativo.');
$original=$db->table('invoice_items')->select('fiscal_override_json')->where('id',20)->get(1)->getRow()->fiscal_override_json;$valid=['ready'=>true,'product_service_code'=>'53111600','unit_code'=>'PR','commercial_unit'=>'PRS','tax_object_code'=>'02','fiscal_description'=>'ZAPATOS','taxes'=>[['tax_code'=>'002','tax_type'=>'transfer','factor_type'=>'Tasa','rate_or_quota'=>'0.160000']],'product_id'=>2];$db->transBegin();$db->table('invoice_items')->where('id',20)->update(['fiscal_override_json'=>json_encode($valid)]);$effective=$resolver->resolve(20,2);$ok($effective['ready']&&$effective['source']==='invoice_item_override','Override válido tiene prioridad.');$ok($effective['taxes'][0]['tax_code']==='002','IVA usa código 002.');
$calc=(new FiscalDraftTaxSnapshotService($db))->calculate(['sale_item_id'=>20,'product_id'=>2,'quantity'=>'10','subtotal'=>'2000','discount'=>'0','total'=>'2000','snapshot'=>['tax_object_code'=>'02','taxes'=>$effective['taxes']]],'tax_inclusive');$ok(FiscalDecimal::micros($calc['total'])===FiscalDecimal::micros('2000'),'200x10 IVA incluido conserva total 2000.');$ok(abs((float)$calc['base']-1724.137931)<0.00001,'Subtotal incluido es 1724.137931.');$ok(abs((float)$calc['transferred']-275.862069)<0.00001,'IVA incluido es 275.862069.');
$breakdown=(new CommercialTaxBreakdownService($db))->forSale(11,2);$ok($breakdown['ready'],'Venta obtiene desglose canónico.');$ok(abs((float)$breakdown['subtotal']-1724.137931)<0.00001&&abs((float)$breakdown['transferred']-275.862069)<0.00001&&(float)$breakdown['total']===2000.0,'Venta muestra subtotal, IVA y total canónicos.');
$reviewSource=file_get_contents(APPPATH.'Services/Fiscal/FiscalReviewPreparation.php');$snapshotSource=file_get_contents(APPPATH.'Services/Fiscal/FiscalDraftTaxSnapshotService.php');$ok(str_contains($snapshotSource,'InvoiceItemTaxResolver'),'Snapshot usa resolver canónico.');$ok(str_contains($reviewSource,'CommercialItemTaxResolver'),'Review mantiene prioridad override/product compartida.');$ok(abs((float)$calc['base']-(float)$breakdown['subtotal'])<0.00001&&abs((float)$calc['transferred']-(float)$breakdown['transferred'])<0.00001,'Review/snapshot y venta comparten números.');
$noTax=(new FiscalDraftTaxSnapshotService($db))->calculate(['sale_item_id'=>20,'product_id'=>0,'quantity'=>'10','subtotal'=>'2000','discount'=>'0','total'=>'2000','snapshot'=>['tax_object_code'=>'01','taxes'=>[]]],'tax_inclusive');$ok((float)$noTax['base']===2000.0&&(float)$noTax['transferred']===0.0&&(float)$noTax['total']===2000.0,'ObjetoImp 01 no inventa impuesto.');
$discounted=(new FiscalDraftTaxSnapshotService($db))->calculate(['sale_item_id'=>20,'product_id'=>2,'quantity'=>'10','subtotal'=>'2000','discount'=>'200','total'=>'1800','snapshot'=>['tax_object_code'=>'02','taxes'=>$effective['taxes']]],'tax_inclusive');$ok(abs((float)$discounted['base']-1551.724138)<0.00001&&abs((float)$discounted['transferred']-248.275862)<0.00001&&(float)$discounted['total']===1800.0,'Descuento 10% se aplica una vez sobre precio incluido.');
$ok(str_contains($source,'resolveProduct'),'Proposal/Estimate pueden resolver producto con el mismo servicio.');$manual=(new InvoiceItemTaxResolver($db))->resolveProduct(0,1,2);$ok($manual['source']==='manual_line','Línea libre queda explícita y requiere configuración.');$ok(!$manual['ready']&&!empty($manual['missing']),'Producto incompleto genera blocker.');$ok(str_contains(file_get_contents(APPPATH.'Views/invoices/item_modal_form.php'),'taxable')===false,'UI normal de partida no muestra taxable.');$ok(str_contains($source,"code==='001'")&&str_contains($source,"withholding"),'ISR 001 se restringe a retención.');$ok($db->table('sat_tax_codes')->where(['code'=>'003','is_active'=>1])->countAllResults()===1,'IEPS 003 disponible sin inferencia.');$db->transRollback();$db->resetTransStatus();
$ok($db->table('invoice_items')->where('id',20)->get(1)->getRow()->fiscal_override_json===$original,'Fixture no modifica venta real.');$ok($db->table('fiscal_stamp_attempts')->countAllResults()===$attempts,'PAC calls=0.');$ok($db->table('fiscal_stamp_movements')->countAllResults()===$moves,'Stamps=0.');
}catch(Throwable$e){echo'[FAIL] '.$e->getMessage().PHP_EOL;$fail++;}echo"\n$pass passed, $fail failed.\n";exit($fail?1:0);
