<?php
declare(strict_types=1);
define('ROOTPATH',dirname(__DIR__,2).DIRECTORY_SEPARATOR);define('FCPATH',ROOTPATH);require ROOTPATH.'app/Config/Paths.php';$paths=new Config\Paths();define('APPPATH',realpath($paths->appDirectory).DIRECTORY_SEPARATOR);define('SYSTEMPATH',realpath($paths->systemDirectory).DIRECTORY_SEPARATOR);define('WRITEPATH',realpath($paths->writableDirectory).DIRECTORY_SEPARATOR);define('ENVIRONMENT','development');require $paths->systemDirectory.'/Boot.php';CodeIgniter\Boot::bootTest($paths);
use App\Services\Fiscal\FiscalIssueDateNormalizer;use App\Services\Fiscal\FiscalIssueDatePolicy;
$passed=$failed=0;$assert=static function(bool$ok,string$message)use(&$passed,&$failed):void{echo($ok?'[PASS] ':'[FAIL] ').$message.PHP_EOL;$ok?$passed++:$failed++;};$normalizer=new FiscalIssueDateNormalizer();
$assert($normalizer->normalizeTransport('2026-08-25T12:40')==='2026-08-25 12:40:00','Minutos se normalizan con segundos 00.');$assert($normalizer->normalizeTransport('2026-08-25T12:40:35')==='2026-08-25 12:40:35','Segundos de transporte se conservan.');$assert($normalizer->formatForInput('2026-08-25 12:40:00')==='2026-08-25T12:40','Persistencia vuelve al contrato datetime-local.');
$now=new DateTimeImmutable('2026-08-25 12:41:00',$normalizer->timezone());(new FiscalIssueDatePolicy())->validate('2026-08-25 12:40:00',$now);$assert(true,'El dominio acepta la fecha canónica del round trip.');
foreach(['','2026-02-30T12:40','08/25/2026 12:40 PM','arbitrario','2026-08-25T25:00']as$value){try{$normalizer->normalizeTransport($value);$rejected=false;}catch(Throwable){$rejected=true;}$assert($rejected,'Rechaza entrada inválida: '.($value===''?'vacía':$value));}
$review=(string)file_get_contents(APPPATH.'Views/fiscal/drafts/review.php');$assert(substr_count($review,'name="issue_date"')===1,'La revisión contiene un solo campo issue_date.');$assert(str_contains($review,'type="datetime-local" name="issue_date"'),'El input datetime-local tiene el name canónico.');echo "Resultado: {$passed} aprobadas, {$failed} fallidas".PHP_EOL;exit($failed===0?0:1);
