<?php
declare(strict_types=1);define('ROOTPATH',dirname(__DIR__,2).DIRECTORY_SEPARATOR);define('FCPATH',ROOTPATH);require ROOTPATH.'app/Config/Paths.php';$p=new Config\Paths();define('APPPATH',realpath($p->appDirectory).DIRECTORY_SEPARATOR);define('SYSTEMPATH',realpath($p->systemDirectory).DIRECTORY_SEPARATOR);define('WRITEPATH',realpath($p->writableDirectory).DIRECTORY_SEPARATOR);define('ENVIRONMENT','development');require$p->systemDirectory.'/Boot.php';CodeIgniter\Boot::bootTest($p);helper(['plugin','general','date_time']);
use App\Services\Fiscal\FiscalDecimal;
$pass=$fail=0;$ok=function($v,$m)use(&$pass,&$fail){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$pass++:$fail++;};$read=fn($f)=>(string)file_get_contents(ROOTPATH.$f);
try{$db=db_connect();$flow=$read('app/Services/Fiscal/FiscalInvoiceFlowService.php');$drafts=$read('app/Controllers/Fiscal/Drafts.php');$review=$read('app/Views/fiscal/drafts/review.php');$details=$read('app/Views/invoices/details.php');$info=$read('app/Views/invoices/invoice_info.php');$controller=$read('app/Controllers/Invoices.php');$lifecycle=$read('app/Services/Sales/SaleLifecycleService.php');$materializer=$read('app/Services/Fiscal/FiscalDocumentFromDraftSnapshotService.php');$attempts=$db->table('fiscal_stamp_attempts')->countAllResults();$moves=$db->table('fiscal_stamp_movements')->countAllResults();
$ok(str_contains($flow,'executeSale')&&str_contains($flow,"['draft','open','closed']"),'Open sale puede iniciar facturación.');
$ok(str_contains($flow,'SaleLifecycleService')&&str_contains($flow,'Cierre automático al confirmar facturación'),'Facturar auto-cierra por lifecycle.');
$ok(str_contains($flow,"['draft','open','closed']"),'Closed sigue facturable.');
$ok(str_contains($details,'$can_edit_invoices && $is_invoice_editable'),'Closed no muestra agregar partida.');
$ok(str_contains($controller,'$is_ediable ? modal_anchor'),'Closed no muestra editar partida.');
$ok(str_contains($controller,"data-action-url")&&str_contains($controller,": ''"),'Closed no muestra eliminar partida.');
$ok(str_contains($controller,'is_invoice_editable($invoice_id)')&&str_contains($lifecycle,'canEdit'),'Backend closed sigue bloqueando.');
$create=substr($drafts,strpos($drafts,'public function create'),strpos($drafts,'public function store')-strpos($drafts,'public function create'));$ok(!str_contains($create,'->save(')&&str_contains($create,'FiscalReviewPreparation'),'Abrir review no crea draft.');
$ok(!str_contains($create,'->save('),'Repetir review no crea drafts.');
$ok(str_contains($review,'Guardar borrador')&&str_contains($drafts,'$workflow->save'),'Guardar borrador sí persiste explícitamente.');
$ok(str_contains($flow,'if(!$draftId){$saved=$this->workflow->save'),'Facturar sin draft lo crea internamente.');
$ok(str_contains($flow,"input['save_as_draft']")&&str_contains($read('app/Services/Fiscal/FiscalDraftWorkflowService.php'),"'snapshot_version'=>2"),'Snapshot v2 y ready internos.');
$ok(str_contains($flow,'$this->execute($draftId')&&str_contains($flow,'$this->workflow->markReady'),'Ready interno antes del PAC.');
$ok(str_contains($flow,"provider_rejected")&&str_contains($lifecycle,"'closed'"),'Rechazo mantiene sale closed.');
$ok(str_contains($flow,'PREPARED_DOCUMENT_REBUILD_REQUIRED')&&str_contains($flow,'hasRejectedAttempt'),'Documento preparado rechazado no se reenvia sin regeneracion.');
$ok(str_contains($flow,'sanitizeProviderMessage')&&str_contains($review,'escapeUx(r.message)'),'Provider message llega sanitizado al modal.');
$ok(str_contains($flow,'[PROTEGIDO]')&&!str_contains($review,'provider_message'),'Mensaje técnico no se expone directamente.');
$ok(str_contains($flow,"category'=>'transport_unknown'")&&str_contains($flow,"retry_allowed'=>false"),'Unknown no permite retry.');
$ok(str_contains($flow,'pero el PDF no pudo generarse')&&str_contains($flow,'pdfAvailable'),'PDF error no retimbra.');
$ok(str_contains($flow,"redirect_url")&&str_contains($review,'window.location=r.redirect_url'),'Éxito redirige.');
$attempt=$db->table('fiscal_stamp_attempts')->where('id',21)->get(1)->getRow();$ok($attempt&&$attempt->status==='rejected'&&$attempt->provider_code==='CFDI40167'&&(int)$attempt->requires_reconciliation===0,'Intento 21 es rechazo seguro.');
$ok(FiscalDecimal::divide('100.000000','2.000000')==='50.000000'&&str_contains($materializer,'FiscalDecimal::divide'),'ValorUnitario fiscal deriva de Importe/Cantidad.');
$ok($db->table('fiscal_stamp_attempts')->countAllResults()===$attempts&&$db->table('fiscal_stamp_movements')->countAllResults()===$moves,'Cero PAC y cero movimientos durante pruebas.');
}catch(Throwable$e){echo'[FAIL] '.$e->getMessage().PHP_EOL;$fail++;}echo"\n{$pass} passed, {$fail} failed.\n";exit($fail?1:0);
