<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';helper(['general','date_time','plugin','currency']);require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
$db=require dirname(__DIR__).'/Increment02/isolated_database.php';service('migrations')->setNamespace('App')->latest();$settings=[];foreach($db->table('settings')->get()->getResult()as$s)$settings[$s->setting_name]=$s->setting_value;$settings['timezone']=$settings['timezone']?:'UTC';config('Rise')->app_settings_array=$settings;session();
$pass=0;$fail=0;$a=function(bool$o,string$m)use(&$pass,&$fail){echo($o?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$o?$pass++:$fail++;};
$reference=$db->table('fiscal_documents')->where('id',12)->get(1)->getRow();$user=(int)$db->table('users')->where(['is_admin'=>1,'deleted'=>0])->get(1)->getRow()->id;$now=get_current_utc_time();$counter=0;
(new App\Services\Fiscal\Stamps\FiscalStampAccountService($db))->allocate((int)$reference->issuer_profile_id,10,'Fixture commercial stamps',null,'increment-c1:allocation');
$fixture=function(bool$pdf=true)use($db,$reference,$user,$now,&$counter){$counter++;$doc=(array)$reference;unset($doc['id']);$doc['status']=$pdf?'stamped':'stamped_pdf_pending';$doc['folio']=90000+$counter;$doc['version']=100+$counter;$doc['source_snapshot_hash']=hash('sha256','c1-'.$counter);$doc['created_at']=$now;$doc['updated_at']=$now;$db->table('fiscal_documents')->insert($doc);$id=(int)$db->insertID();foreach(['fiscal_document_issuers','fiscal_document_receivers']as$t){$r=(array)$db->table($t)->where('fiscal_document_id',12)->get(1)->getRow();unset($r['id']);$r['fiscal_document_id']=$id;$db->table($t)->insert($r);}
 $sourceArtifact=(array)$db->table('fiscal_document_artifacts')->where('fiscal_document_id',12)->get(1)->getRow();unset($sourceArtifact['id']);$sourceArtifact['fiscal_document_id']=$id;$sourceArtifact['artifact_type']='stamped_xml';$sourceArtifact['sha256']=hash('sha256','xml-'.$id);$sourceArtifact['created_at']=$now;$db->table('fiscal_document_artifacts')->insert($sourceArtifact);$artifactId=(int)$db->insertID();
 $uuid=sprintf('123E4567-E89B-42D3-A456-%012d',$counter);$db->table('fiscal_stamp_attempts')->insert(['fiscal_document_id'=>$id,'signed_xml_artifact_id'=>$artifactId,'pac_configuration_id'=>0,'provider'=>'fake','environment'=>'local','operation'=>'timbrar3','request_hash'=>str_repeat('a',64),'idempotency_key'=>hash('sha256','attempt-'.$id),'attempt_number'=>1,'status'=>'success','started_at'=>$now,'responded_at'=>$now,'provider_code'=>'200','provider_message'=>'ok','uuid'=>$uuid,'created_by'=>$user,'created_at'=>$now,'updated_at'=>$now]);$attempt=(int)$db->insertID();
 $db->table('fiscal_document_stamps')->insert(['fiscal_document_id'=>$id,'stamp_attempt_id'=>$attempt,'stamped_xml_artifact_id'=>$artifactId,'uuid'=>$uuid,'stamp_date'=>$now,'pac_rfc'=>'AAA010101AAA','sat_certificate_number'=>'30001000000500000001','cfd_seal'=>'fake','sat_seal'=>'fake','tfd_version'=>'1.1','provider'=>'fake','environment'=>'local','stamped_xml_sha256'=>$sourceArtifact['sha256'],'created_at'=>$now,'pdf_status'=>$pdf?'valid':'pending','pdf_template'=>'Principal']);$stamp=(int)$db->insertID();
 if($pdf){$p=(new App\Services\Fiscal\Pac\PacPdfArtifactService($db))->store($id,$attempt,$uuid,App\Services\Fiscal\Pac\FakePacAdapter::fixturePdf(),'Principal',$user);$db->table('fiscal_document_stamps')->where('id',$stamp)->update(['pac_pdf_artifact_id'=>$p->id]);}
 return[$id,$uuid,$attempt];};
try{
 foreach(['fiscal_cancellation_requests','fiscal_cancellation_attempts','fiscal_cancellation_artifacts']as$t)$a($db->tableExists($t),"$t exists.");
 $validator=new App\Services\Fiscal\Pac\PacPdfValidator();$fixturePdf=$validator->validate(App\Services\Fiscal\Pac\FakePacAdapter::fixturePdf());
 $a($fixturePdf['page_count']===1,'Fake PAC fixture is parsed as a one-page PDF.');
 $a($fixturePdf['bytes']===App\Services\Fiscal\Pac\FakePacPdfFixture::bytes(),'Fake PAC PDF fixture is deterministic.');
 $a(str_contains($fixturePdf['bytes'],'FACTURA DE PRUEBA')&&str_contains($fixturePdf['bytes'],'FAKE PAC - SIN VALIDEZ FISCAL'),'Fake PAC PDF contains visible test-only identification.');
 $oldPdf="%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n2 0 obj\n<< /Length 28 >>\nstream\nBT (FAKE CFDI) Tj ET\nendstream\nendobj\nxref\n0 3\n0000000000 65535 f \ntrailer\n<< /Root 1 0 R /Size 3 >>\nstartxref\n100\n%%EOF\n";
 $a(strlen($oldPdf)===198,'Historical invalid fake PDF fixture is characterized at 198 bytes.');
 foreach([
  base64_encode($oldPdf)=>'Historical fake PDF without Pages is rejected.',
  base64_encode("%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF\n")=>'Header/EOF without a Pages tree is rejected.',
  base64_encode(substr($fixturePdf['bytes'],0,-40))=>'Truncated PDF is rejected.',
  '%%%not-base64%%%'=>'Invalid Base64 PDF is rejected.',
  ''=>'Empty PDF is rejected.',
 ]as$candidate=>$message){try{$validator->validate($candidate);$invalid=false;}catch(Throwable){$invalid=true;}$a($invalid,$message);}
 [$id,$uuid]=$fixture(true);$pdf=(new App\Services\Fiscal\Pac\PacPdfArtifactService($db))->read($id);$a(str_starts_with($pdf['bytes'],'%PDF-'),'Valid Base64 PDF is persisted and decoded in memory.');$a(hash_equals($pdf['artifact']->decoded_sha256,hash('sha256',$pdf['bytes'])),'PDF SHA-256 is preserved.');
 $projection=(new App\Services\Fiscal\Pac\FiscalDocumentStatusPresenter($db))->forDocument($id);$a($projection->visibleStatus==='stamped'&&$projection->pdfAvailable,'XML/UUID/PDF projects as stamped.');
 [$pendingId]=$fixture(false);$pending=(new App\Services\Fiscal\Pac\FiscalDocumentStatusPresenter($db))->forDocument($pendingId);$a($pending->visibleStatus==='stamped_pdf_pending'&&!$pending->canStamp,'Missing PDF projects pending and cannot restamp.');
 $fake=new App\Services\Fiscal\Cancellation\FakeFiscalCancellationAdapter('accepted');$service=new App\Services\Fiscal\Cancellation\FiscalCancellationService($db,$fake);$beforePdf=$db->table('fiscal_document_binary_artifacts')->where('fiscal_document_id',$id)->countAllResults();$cancel=$service->cancel($id,'02',null,$user,true);
 $a($db->table('fiscal_stamp_movements')->where('fiscal_cancellation_request_id',$cancel['request_id'])->countAllResults()===0,'Cancellation does not create commercial stamp movements.');
 $a($cancel['status']==='accepted'&&$fake->calls===1,'Fake accepted cancellation completes once.');$a($db->table('fiscal_cancellation_attempts')->where('fiscal_cancellation_request_id',$cancel['request_id'])->countAllResults()===1,'Durable cancellation attempt is stored.');$a($db->table('fiscal_cancellation_artifacts')->where('fiscal_cancellation_request_id',$cancel['request_id'])->countAllResults()===1,'Cancellation acknowledgement is persisted.');$a($db->table('fiscal_documents')->where('id',$id)->get()->getRow()->status==='cancelled','Only accepted cancellation marks the fiscal document cancelled.');$again=$service->cancel($id,'02',null,$user,true);$a($fake->calls===1,'A cancelled invoice cannot invoke the adapter twice.');$a($db->table('fiscal_document_binary_artifacts')->where('fiscal_document_id',$id)->countAllResults()===$beforePdf,'Cancellation preserves the original PDF.');$a($db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$id,'artifact_type'=>'stamped_xml'])->countAllResults()===1,'Cancellation preserves the original XML.');
 foreach(['pending'=>'cancellation_pending','rejected'=>'cancellation_rejected','timeout_unknown'=>'cancellation_pending']as$scenario=>$expected){[$caseId]=$fixture(true);$adapter=new App\Services\Fiscal\Cancellation\FakeFiscalCancellationAdapter($scenario);$r=(new App\Services\Fiscal\Cancellation\FiscalCancellationService($db,$adapter))->cancel($caseId,'02',null,$user,true);$a($db->table('fiscal_documents')->where('id',$caseId)->get()->getRow()->status===$expected,"$scenario maps to $expected.");if($scenario==='timeout_unknown')$a(($r['requires_reconciliation']??false)&&$adapter->calls===1,'Unknown cancellation requires reconciliation and is not treated as accepted.');}
 $source=file_get_contents(APPPATH.'Services/Fiscal/FiscalInvoiceCenterQueryService.php');$a(!str_contains($source,'content_base64'),'Invoice center query never selects PDF Base64.');
 $listed=(new App\Services\Fiscal\FiscalInvoiceCenterQueryService($db))->search(['search'=>$uuid]);$a(count($listed)===1&&(int)$listed[0]->id===$id,'Invoice center filters by UUID without loading binary content.');
 [$repairId,$repairUuid,$repairAttempt]=$fixture(true);$repairArtifact=$db->table('fiscal_document_binary_artifacts')->where(['fiscal_document_id'=>$repairId,'artifact_type'=>'pac_pdf'])->get(1)->getRow();$db->table('fiscal_document_binary_artifacts')->where('id',$repairArtifact->id)->update(['content_base64'=>base64_encode($oldPdf),'decoded_size_bytes'=>strlen($oldPdf),'decoded_sha256'=>hash('sha256',$oldPdf)]);config('Fiscal')->pacAdapter='fake';config('Fiscal')->allowRealPac=false;
 $repairService=new App\Services\Fiscal\Pac\FakePacPdfFixtureRepairService($db);$repairBefore=$repairService->inspect($repairId);$repair=$repairService->repair($repairId,$user);$repairAfter=$repairService->inspect($repairId);
 $a($repair['changed']&&$repairBefore['pdf_valid']===false&&$repairAfter['pdf_valid']===true,'Local repair replaces an invalid fake fixture with a valid PDF.');
 $a($repairBefore['uuid']===$repairAfter['uuid']&&$repairAfter['uuid']===$repairUuid,'Fake PDF repair preserves UUID.');
 $a($repairBefore['xml_sha256']===$repairAfter['xml_sha256'],'Fake PDF repair preserves stamped XML hash.');
 $a($repairBefore['attempt_id']===$repairAfter['attempt_id']&&$repairAfter['attempt_id']===$repairAttempt&&$repairBefore['attempt_count']===$repairAfter['attempt_count'],'Fake PDF repair creates no stamp attempt.');
 $a($db->table('fiscal_document_binary_artifacts')->where(['id'=>$repairBefore['pdf_artifact_id'],'artifact_type'=>'pac_pdf_replaced','validation_status'=>'invalid_structure'])->countAllResults()===1,'Invalid binary artifact is retained as superseded evidence.');
 $a($db->table('fiscal_document_audit')->where(['fiscal_document_id'=>$repairId,'action'=>'fake_pdf_fixture_replaced'])->countAllResults()===1,'Fake PDF repair is audited.');
 session()->set('user_id',$user);
 $makeController=static function(){$request=Config\Services::incomingrequest(null,false);$request->setMethod('GET');$response=Config\Services::response(null,false);$controller=new App\Controllers\Fiscal\Stamping();$controller->initController($request,$response,service('logger'));return$controller;};
 $preview=$makeController()->viewPdf($repairId);$download=$makeController()->downloadPdf($repairId);$expected=(new App\Services\Fiscal\Pac\PacPdfArtifactService($db))->read($repairId)['bytes'];
 $a($preview->getBody()===$expected&&$download->getBody()===$expected,'Preview and download return bytes identical to the stored PDF.');
 $a(str_starts_with($preview->getBody(),'%PDF-')&&str_starts_with($download->getBody(),'%PDF-'),'HTTP PDF bodies start at byte zero with the PDF header.');
 $a($preview->getHeaderLine('Content-Type')==='application/pdf'&&str_contains($preview->getHeaderLine('Content-Disposition'),'inline'),'Preview returns inline application/pdf.');
 $a($download->getHeaderLine('Content-Type')==='application/pdf'&&str_contains($download->getHeaderLine('Content-Disposition'),'attachment'),'Download returns attachment application/pdf.');
 $a((int)$preview->getHeaderLine('Content-Length')===strlen($expected)&&(int)$download->getHeaderLine('Content-Length')===strlen($expected),'HTTP Content-Length equals decoded PDF size.');
 $routes=file_get_contents(APPPATH.'Config/FiscalRoutes.php');$a(str_contains($routes,"fiscal/invoices/cancel', 'Fiscal\\Invoices::cancel', ['filter' => 'csrf']"),'Cancellation is POST-only and explicitly CSRF protected.');
 $a(config('Fiscal')->allowRealPac===false,'Real PAC calls remain disabled.');
}catch(Throwable$e){echo'[FAIL] '.get_class($e).': '.$e->getMessage().' at '.$e->getFile().':'.$e->getLine().PHP_EOL;$fail++;}
echo"\n$pass passed, $fail failed.\n";exit($fail?1:0);
