<?php
declare(strict_types=1);
namespace App\Services\Fiscal\Stamps;
use RuntimeException;use Throwable;
final class FiscalStampAccountService{
 private const TYPES=['allocation','adjustment_credit','adjustment_debit','document_reservation','document_consumption','document_release','reconciliation_consumption','reconciliation_release','cancellation_request','cancellation_status_query'];
 public function __construct(private$db=null){$this->db??=db_connect();}
 public function getOrCreateAccountForIssuer(int$i,string$environment='development'):object{$this->assertEnvironment($environment);$this->assertIssuer($i);$this->db->transBegin();try{$a=$this->lock($i,$environment);if(!$a){$n=get_current_utc_time();$row=['issuer_profile_id'=>$i,'available_balance'=>0,'reserved_balance'=>0,'status'=>'active','created_at'=>$n,'updated_at'=>$n];if($this->environmentAware())$row['environment']=$environment;try{$this->db->table('fiscal_stamp_accounts')->insert($row);}catch(Throwable){}$a=$this->lock($i,$environment);}if(!$a)throw new RuntimeException('Unable to create fiscal stamp account.');$this->commit();return$a;}catch(Throwable$e){$this->db->transRollback();throw$e;}}
 public function getBalance(int$i,string$environment='development'):array{$this->assertEnvironment($environment);$builder=$this->db->table('fiscal_stamp_accounts')->where('issuer_profile_id',$i);if($this->environmentAware())$builder->where('environment',$environment);$a=$builder->get(1)->getRow();return['issuer_profile_id'=>$i,'environment'=>$environment,'available'=>(int)($a->available_balance??0),'reserved'=>(int)($a->reserved_balance??0),'status'=>(string)($a->status??'missing')];}
 public function allocate(int$i,int$q,string$r,?int$actor,string$key,?string$ref=null):object{if($q<=0)throw new FiscalStampBalanceException('Allocation quantity must be positive.');return$this->move($i,'allocation',$q,$q,0,$key,$r,$actor,['reference'=>$ref]);}
 public function adjust(int$i,int$q,string$r,?int$actor,string$key,?string$ref=null,string$environment='development'):object{if($q===0)throw new FiscalStampBalanceException('Adjustment quantity cannot be zero.');return$this->move($i,$q>0?'adjustment_credit':'adjustment_debit',$q,$q,0,$key,$r,$actor,['reference'=>$ref,'environment'=>$environment]);}
 public function reverseInvalidPacSync(int$movementId,?int$actor):object{$m=$this->db->table('fiscal_stamp_movements m')->select('m.*,a.issuer_profile_id')->join($this->db->prefixTable('fiscal_stamp_accounts').' a','a.id=m.stamp_account_id')->where('m.id',$movementId)->get(1)->getRow();if(!$m||$m->reason!=='pac_development_sync'||(int)$m->quantity<=0)throw new FiscalStampBalanceException('INVALID_PAC_SYNC_MOVEMENT_NOT_FOUND');return$this->move((int)$m->issuer_profile_id,'adjustment_debit',-(int)$m->quantity,-(int)$m->quantity,0,'reverse-invalid-pac-sync:'.$movementId,'reverse_invalid_pac_sync',$actor,['reference'=>'movement:'.$movementId,'environment'=>(string)$m->environment]);}
 public function synchronizeDevelopment(int$i,int$pacCredits,int$consultationId,?int$actor):object{throw new FiscalStampBalanceException('PAC_PROVIDER_CREDITS_MUST_NOT_MUTATE_CLIENT_WALLET');}
 public function reserveForAttempt(int$id,?int$a=null):object{$x=$this->attempt($id);return$this->move((int)$x->issuer_profile_id,'document_reservation',1,-1,1,"stamp-reservation:{$id}",'Reserve one commercial stamp before PAC transport.',$a,['document'=>$x->fiscal_document_id,'attempt'=>$id,'environment'=>$x->fiscal_environment]);}
 public function consumeReservation(int$id,int$stamp,?int$a=null):object{$x=$this->attempt($id);return$this->move((int)$x->issuer_profile_id,'document_consumption',1,0,-1,"stamp-consumption:{$stamp}",'Consume successful CFDI stamp.',$a,['document'=>$x->fiscal_document_id,'attempt'=>$id,'stamp'=>$stamp,'consumption'=>"stamp:{$stamp}",'environment'=>$x->fiscal_environment]);}
 public function releaseReservation(int$id,string$r='Release unused document stamp reservation.',?int$a=null):object{$x=$this->attempt($id);return$this->move((int)$x->issuer_profile_id,'document_release',1,1,-1,"stamp-release:{$id}",$r,$a,['document'=>$x->fiscal_document_id,'attempt'=>$id,'environment'=>$x->fiscal_environment],true);}
 public function consumeFromReconciliation(int$id,int$stamp,?int$a=null):object{$x=$this->attempt($id);return$this->move((int)$x->issuer_profile_id,'reconciliation_consumption',1,0,-1,"stamp-reconciliation-consumption:{$stamp}",'Consume reservation after successful reconciliation.',$a,['document'=>$x->fiscal_document_id,'attempt'=>$id,'stamp'=>$stamp,'consumption'=>"stamp:{$stamp}",'environment'=>$x->fiscal_environment]);}
 public function releaseFromReconciliation(int$id,?int$a=null):object{$x=$this->attempt($id);return$this->move((int)$x->issuer_profile_id,'reconciliation_release',1,1,-1,"stamp-reconciliation-release:{$id}",'Release reservation after definitive rejected reconciliation.',$a,['document'=>$x->fiscal_document_id,'attempt'=>$id,'environment'=>$x->fiscal_environment],true);}
 public function consumeCancellationRequest(int$id,?int$actor=null):object{$x=$this->cancel($id);return$this->move((int)$x->issuer_profile_id,'cancellation_request',1,-1,0,"cancellation-request:{$id}",'Commercial charge for cancellation request sent to provider.',$actor,['document'=>$x->fiscal_document_id,'cancellation'=>$id,'consumption'=>"cancellation-request:{$id}",'environment'=>$x->fiscal_environment]);}
 public function consumeCancellationStatusQuery(int$id,string$queryKey,?int$actor=null):object{if(!preg_match('/^[A-Za-z0-9_-]{16,80}$/',$queryKey))throw new FiscalStampBalanceException('Invalid cancellation status query key.');$x=$this->cancel($id);return$this->move((int)$x->issuer_profile_id,'cancellation_status_query',1,-1,0,"cancellation-status-query:{$id}:{$queryKey}",'Commercial charge for cancellation status query sent to provider.',$actor,['document'=>$x->fiscal_document_id,'cancellation'=>$id,'consumption'=>"cancellation-status-query:{$id}:{$queryKey}",'environment'=>$x->fiscal_environment]);}
 public function recentForIssuer(int$i,int$l=20):array{$a=$this->db->table('fiscal_stamp_accounts')->where('issuer_profile_id',$i)->get(1)->getRow();return$a?$this->db->table('fiscal_stamp_movements')->where('stamp_account_id',$a->id)->orderBy('id','DESC')->limit(max(1,min(20,$l)))->get()->getResultArray():[];}
 private function move(int$i,string$type,int$q,int$da,int$dr,string$key,string$reason,?int$actor,array$link=[],bool$missing=false):object{$environment=$link['environment']??'development';$this->assertEnvironment($environment);if(!in_array($type,self::TYPES,true)||trim($reason)===''||trim($key)===''||$q===0)throw new FiscalStampBalanceException('Invalid stamp movement.');$e=$this->db->table('fiscal_stamp_movements')->where('idempotency_key',$key)->get(1)->getRow();if($e)return$e;$this->assertIssuer($i);$this->db->transBegin();try{$a=$this->lock($i,$environment);if(!$a){$n=get_current_utc_time();$account=['issuer_profile_id'=>$i,'available_balance'=>0,'reserved_balance'=>0,'status'=>'active','created_at'=>$n,'updated_at'=>$n];if($this->environmentAware())$account['environment']=$environment;$this->db->table('fiscal_stamp_accounts')->insert($account);$a=$this->lock($i,$environment);}if(!$a||$a->status!=='active')throw new FiscalStampBalanceException('Fiscal stamp account is not active.');$e=$this->db->table('fiscal_stamp_movements')->where('idempotency_key',$key)->get(1)->getRow();if($e){$this->commit();return$e;}$ba=(int)$a->available_balance;$br=(int)$a->reserved_balance;$aa=$ba+$da;$ar=$br+$dr;if($aa<0)throw new FiscalStampBalanceException('Insufficient fiscal stamp balance.');if($ar<0)throw new FiscalStampBalanceException($missing?'STAMP_RESERVATION_MISSING':'Reserved fiscal stamp balance cannot be negative.');$n=get_current_utc_time();$row=['stamp_account_id'=>(int)$a->id,'movement_type'=>$type,'quantity'=>$q,'available_before'=>$ba,'available_after'=>$aa,'reserved_before'=>$br,'reserved_after'=>$ar,'fiscal_document_id'=>$link['document']??null,'pac_attempt_id'=>$link['attempt']??null,'fiscal_document_stamp_id'=>$link['stamp']??null,'fiscal_cancellation_request_id'=>$link['cancellation']??null,'idempotency_key'=>$key,'consumption_key'=>$link['consumption']??null,'reason'=>$reason,'reference'=>$link['reference']??null,'created_by'=>$actor,'created_at'=>$n];if($this->db->fieldExists('environment','fiscal_stamp_movements'))$row['environment']=$environment;if(!$this->db->table('fiscal_stamp_movements')->insert($row))throw new RuntimeException('Unable to persist fiscal stamp movement.');$mid=(int)$this->db->insertID();$this->db->table('fiscal_stamp_accounts')->where('id',$a->id)->update(['available_balance'=>$aa,'reserved_balance'=>$ar,'updated_at'=>$n]);$this->commit();return$this->db->table('fiscal_stamp_movements')->where('id',$mid)->get(1)->getRow();}catch(Throwable$e){$this->db->transRollback();throw$e;}}
 private function lock(int$i,string$environment='development'):?object{$t=$this->db->protectIdentifiers($this->db->prefixTable('fiscal_stamp_accounts'));return$this->environmentAware()?$this->db->query("SELECT * FROM {$t} WHERE issuer_profile_id=? AND environment=? FOR UPDATE",[$i,$environment])->getRow():$this->db->query("SELECT * FROM {$t} WHERE issuer_profile_id=? FOR UPDATE",[$i])->getRow();}
 private function environmentAware():bool{return$this->db->fieldExists('environment','fiscal_stamp_accounts');}
 private function assertIssuer(int$i):void{if(!$this->db->table('fiscal_profiles')->where(['id'=>$i,'profile_type'=>'issuer'])->countAllResults())throw new FiscalStampBalanceException('Issuer fiscal profile not found.');}
 private function assertEnvironment(string$environment):void{if(!in_array($environment,['development','production'],true))throw new FiscalStampBalanceException('Invalid fiscal stamp environment.');}
 private function attempt(int$i):object{$r=$this->db->table('fiscal_stamp_attempts a')->select("a.id,a.fiscal_document_id,d.issuer_profile_id,CASE WHEN d.environment='production' THEN 'production' ELSE 'development' END fiscal_environment",false)->join('fiscal_documents d','d.id=a.fiscal_document_id')->where('a.id',$i)->get(1)->getRow();if(!$r)throw new FiscalStampBalanceException('PAC attempt not found.');return$r;}
 private function cancel(int$i):object{$r=$this->db->table('fiscal_cancellation_requests c')->select("c.id,c.fiscal_document_id,d.issuer_profile_id,CASE WHEN d.environment='production' THEN 'production' ELSE 'development' END fiscal_environment",false)->join('fiscal_documents d','d.id=c.fiscal_document_id')->where('c.id',$i)->get(1)->getRow();if(!$r)throw new FiscalStampBalanceException('Cancellation request not found.');return$r;}
 private function commit():void{if(!$this->db->transStatus())throw new RuntimeException('Fiscal stamp transaction failed.');$this->db->transCommit();}
}
