<?php
declare(strict_types=1);ob_start();$root=dirname(__DIR__,2);require$root.'/tests/bootstrap.php';helper(['general','date_time','currency']);$db=require$root.'/tests/Increment02/isolated_database.php';use App\Services\WarehouseLabelService;$p=$f=0;$ok=function($v,$m)use(&$p,&$f){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$p++:$f++;};$now=get_current_utc_time();$actor=(int)$db->table('users')->where('deleted',0)->get(1)->getRow()->id;$make=function($name,$barcode)use($db,$actor,$now){$db->table('warehouse_products')->insert(['name'=>$name,'internal_code'=>'LBL-'.strtoupper(bin2hex(random_bytes(4))),'barcode'=>$barcode,'control_unit'=>'PIEZA','model'=>'M750','variant'=>'NEGRO','size'=>'28','color'=>'Negro','status'=>'active','created_by'=>$actor,'created_at'=>$now,'updated_at'=>$now,'deleted'=>0]);return(int)$db->insertID();};$ean=$make('Producto EAN','4006381333931');$code=$make('Producto Code128','DOLD-ABC-28');$none=$make('Producto sin barcode',null);$svc=new WarehouseLabelService($db);
$ok($svc->barcodeType('4006381333931')==='EAN13'&&$svc->validEan13('4006381333931'),'EAN-13 de 13 dígitos valida checksum y usa EAN13');$ok($svc->barcodeType('DOLD-ABC-28')==='C128'&&$svc->barcodeType('1234567890123')==='C128','alfanumérico o EAN inválido usa Code128');$ok($svc->barcodeType(null)===null,'producto sin barcode no inventa código');
foreach(['50x30'=>[50,30],'60x40'=>[60,40],'100x50'=>[100,50]]as$preset=>$dims){$o=$svc->options(['size_preset'=>$preset,'quantity'=>1]);$ok($o['width_mm']==$dims[0]&&$o['height_mm']==$dims[1],$preset.' conserva dimensiones físicas');}$custom=$svc->options(['size_preset'=>'custom','width_mm'=>'72.5','height_mm'=>'35','quantity'=>1]);$ok($custom['width_mm']===72.5&&$custom['height_mm']===35.0,'tamaño personalizado usa milímetros');
$layout50=$svc->prepare($ean,['size_preset'=>'50x30','quantity'=>1]);$roles50=array_map(static fn($block)=>$block['type']==='text'?$block['role']:$block['type'],$layout50['blocks']);$expected50=['name','detail','detail','barcode','barcode_text','internal_code'];
$ok($roles50===$expected50&&count(array_filter($layout50['blocks'],static fn($block)=>$block['align']!=='center'))===0,'50x30 usa orden canónico y todos los bloques centrados');
$preview50=$svc->renderPreview($ean,['size_preset'=>'50x30','quantity'=>1]);$ok(str_contains($preview50,'data-layout="physical-mm"')&&str_contains($preview50,'wl-barcode-block')&&!str_contains($preview50,'wl-spacer'),'preview 50x30 recorre layout canónico sin spacer independiente');
$geometryComplete=count(array_filter($layout50['blocks'],static fn($block)=>isset($block['x_mm'],$block['y_mm'],$block['width_mm'],$block['height_mm'],$block['alignment'],$block['visible'])))===count($layout50['blocks']);$barcode50=$layout50['blocks'][3];$ok($geometryComplete&&abs($barcode50['x_mm']-(50-$barcode50['width_mm'])/2)<0.000001,'layout canónico define rectángulos mm y centra el barcode');
$layout100=$svc->prepare($ean,['size_preset'=>'100x50','quantity'=>1]);$used100=array_sum(array_column($layout100['blocks'],'height'))+(count($layout100['blocks'])-1)*$layout100['profile']['gap'];$available100=$layout100['options']['height_mm']-2*$layout100['profile']['margin'];$ok($used100<=$available100+0.000001&&$layout100['blocks'][3]['width_ratio']===0.88,'100x50 conserva proporciones, cabe en página y centra barcode al 88%');
$hidden=$svc->prepare($ean,['size_preset'=>'50x30','quantity'=>1,'fields'=>['name'=>1,'barcode'=>1]]);$hiddenRoles=array_map(static fn($block)=>$block['type']==='text'?$block['role']:$block['type'],$hidden['blocks']);$ok($hiddenRoles===['name','barcode'],'checks ocultos eliminan bloques sin alterar orden ni alineación');

$html=$svc->renderPreview($ean,['size_preset'=>'50x30','quantity'=>5]);$ok(str_contains($html,'Producto EAN')&&str_contains($html,'<svg')&&str_contains($html,'4006381333931'),'preview usa datos y barcode reales del servicio canónico');$htmlNone=$svc->renderPreview($none,['size_preset'=>'50x30','quantity'=>1]);$ok(str_contains($htmlNone,'wl-warning')&&!str_contains($htmlNone,'<svg'),'sin barcode muestra aviso y etiqueta sigue funcionando');
foreach([1,10,100]as$q){$pdf=$svc->pdf($code,['size_preset'=>'50x30','quantity'=>$q]);$pages=preg_match_all('/\/Type\s*\/Page\b/',$pdf);$ok(str_starts_with($pdf,'%PDF')&&$pages===$q,'PDF genera exactamente '.$q.' página(s)/etiqueta(s)');}$pdf100=$svc->pdf($ean,['size_preset'=>'100x50','quantity'=>1]);$ok((bool)preg_match('/\/MediaBox\s*\[0\.000000 0\.000000 283\.464567 141\.732283\]/',$pdf100),'PDF 100x50 conserva tamaño físico de página');
$invalidQty=false;try{$svc->options(['size_preset'=>'50x30','quantity'=>1001]);}catch(InvalidArgumentException$e){$invalidQty=str_contains($e->getMessage(),'1000');}$ok($invalidQty,'cantidad máxima es 1000');$invalidSize=false;try{$svc->options(['size_preset'=>'custom','width_mm'=>10,'height_mm'=>10,'quantity'=>1]);}catch(InvalidArgumentException$e){$invalidSize=true;}$ok($invalidSize,'dimensiones personalizadas fuera de rango se rechazan');
$dir=$svc->logoDirectory();if(!is_dir($dir))mkdir($dir,0755,true);$logoA='product_'.$ean.'_test.png';file_put_contents($dir.$logoA,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));$db->table('warehouse_products')->where('id',$ean)->update(['label_logo'=>$logoA]);$a=$svc->prepare($ean,['size_preset'=>'60x40','quantity'=>1]);$b=$svc->prepare($code,['size_preset'=>'60x40','quantity'=>1]);$ok($a['logo_path']!==null&&$b['logo_path']===null,'logo pertenece sólo al producto asignado y no usa logo empresarial');$pngPreview=$svc->renderPreview($ean,['size_preset'=>'60x40','quantity'=>1]);
$ok(str_contains($pngPreview,'data:image/png;base64,'),'producto con logo PNG válido genera preview');
$logoJpeg='product_'.$ean.'_test.jpg';$image=imagecreatetruecolor(2,2);imagejpeg($image,$dir.$logoJpeg);imagedestroy($image);$db->table('warehouse_products')->where('id',$ean)->update(['label_logo'=>$logoJpeg]);
$jpegPreview=$svc->renderPreview($ean,['size_preset'=>'60x40','quantity'=>1]);
$ok(str_contains($jpegPreview,'data:image/jpeg;base64,'),'producto con logo JPG/JPEG válido genera preview');
$invalidLogo='product_'.$ean.'_invalid.png';file_put_contents($dir.$invalidLogo,'not-an-image');$db->table('warehouse_products')->where('id',$ean)->update(['label_logo'=>$invalidLogo]);$invalidControlled=false;try{$svc->renderPreview($ean,['size_preset'=>'60x40','quantity'=>1]);}catch(RuntimeException$e){$invalidControlled=$e->getMessage()==='No fue posible validar la imagen del logo.';}$ok($invalidControlled,'logo inválido produce error controlado sin exponer excepción PHP');
$ok(extension_loaded('fileinfo')&&class_exists('\finfo')&&!str_contains(file_get_contents($root.'/app/Services/WarehouseLabelService.php'),'new\finfo('),'Fileinfo disponible y clase resuelta explícitamente como global');
$db->table('warehouse_products')->where('id',$ean)->update(['label_logo'=>$logoA]);@unlink($dir.$logoJpeg);@unlink($dir.$invalidLogo);

$logoPdf=$svc->pdf($ean,['size_preset'=>'60x40','quantity'=>1]);$ok(str_starts_with($logoPdf,'%PDF'),'producto con logo genera PDF válido');@unlink($dir.$logoA);
$before=['movements'=>$db->table('warehouse_movements')->countAllResults(),'transfers'=>$db->table('warehouse_transfers')->countAllResults(),'items'=>$db->table('items')->countAllResults(),'proposals'=>$db->table('proposals')->countAllResults()];$svc->pdf($ean,['size_preset'=>'50x30','quantity'=>1]);$after=['movements'=>$db->table('warehouse_movements')->countAllResults(),'transfers'=>$db->table('warehouse_transfers')->countAllResults(),'items'=>$db->table('items')->countAllResults(),'proposals'=>$db->table('proposals')->countAllResults()];$ok($before===$after,'generar etiquetas no crea movimientos, traspasos ni documentos comerciales');$controller=file_get_contents($root.'/app/Controllers/Warehouse_labels.php');$ok(str_contains($controller,'FILEINFO_MIME_TYPE')&&str_contains($controller,'MAX_LOGO_BYTES')&&str_contains($controller,"'image/png'"),'upload valida MIME real, imagen y límite de 2 MB');
$accent=$make('Información Código Ubicación En tránsito','DOLD-ACENTO-01');
$accentHtml=$svc->renderPreview($accent,['size_preset'=>'50x30','quantity'=>1]);
$ok(str_contains($accentHtml,'Información Código Ubicación En tránsito')&&!preg_match('/Ã|Â|â€/u',$accentHtml),'preview conserva texto UTF-8 con acentos y no contiene mojibake');
$accentPdf=$svc->pdf($accent,['size_preset'=>'50x30','quantity'=>1]);
$ok(str_starts_with($accentPdf,'%PDF')&&str_contains(file_get_contents($root.'/app/Services/WarehouseLabelService.php'),"SetFont('dejavusans'"),'PDF Unicode se genera con DejaVu Sans');
$fixture=$db->table('warehouse_products')->where('internal_code','0111212')->get()->getRow();
if(!$fixture){$fixtureId=$make('Zapato Xelx','0121616819165');$db->table('warehouse_products')->where('id',$fixtureId)->update(['internal_code'=>'0111212','model'=>'Tal','variant'=>'Blanco','color'=>'Blanco','size'=>'32']);}else{$fixtureId=(int)$fixture->id;$db->table('warehouse_products')->where('id',$fixtureId)->update(['name'=>'Zapato Xelx','barcode'=>'0121616819165','model'=>'Tal','variant'=>'Blanco','color'=>'Blanco','size'=>'32']);}
$fixtureLayout=$svc->prepare($fixtureId,['size_preset'=>'50x30','quantity'=>1]);$fixtureTextBlocks=array_values(array_filter($fixtureLayout['blocks'],static fn($block)=>$block['type']==='text'));
$textBlocksValid=count($fixtureTextBlocks)===5&&count(array_filter($fixtureTextBlocks,static fn($block)=>$block['visible']===true&&trim((string)$block['value'])!==''&&$block['x_mm']>=0&&$block['y_mm']>=0&&$block['width_mm']>0&&$block['height_mm']>0&&$block['font_size_pt']>0))===5;
$ok($textBlocksValid,'fixture PDF lleva name, variant, color_size, barcode_text e internal_code visibles');
$fixturePdf=$svc->pdf($fixtureId,['size_preset'=>'50x30','quantity'=>1]);preg_match_all('/stream\r?\n(.*?)\r?\nendstream/s',$fixturePdf,$streams);$decoded='';foreach($streams[1]as$stream){$inflated=@gzuncompress($stream);if($inflated!==false)$decoded.=$inflated;}
$containsPdfText=static fn(string$value):bool=>str_contains($decoded,mb_convert_encoding($value,'UTF-16BE','UTF-8'));
$ok(str_starts_with($fixturePdf,'%PDF-')&&$containsPdfText('Zapato Xelx')&&$containsPdfText('0121616819165')&&$containsPdfText('0111212'),'PDF embebe todos los textos del fixture exacto');
$rendererSource=file_get_contents($root.'/app/Services/WarehouseLabelService.php');$ok(str_contains($rendererSource,"SetAlpha(1)")&&str_contains($rendererSource,"SetTextColor(0, 0, 0)")&&str_contains($rendererSource,"->Cell(\$width, \$height, \$text"),'renderer TCPDF usa Cell con alpha, negro y fuente explícitos');
$warehouseFiles=array_merge(glob($root.'/app/Views/warehouses/*.php'),[$root.'/app/Controllers/Warehouse_labels.php',$root.'/app/Services/WarehouseLabelService.php']);
$cleanSources=true;foreach($warehouseFiles as$warehouseFile){$source=file_get_contents($warehouseFile);if(str_starts_with($source,"\xEF\xBB\xBF")||preg_match('/Ã|Â|â€/u',$source)){$cleanSources=false;break;}}
$ok($cleanSources,'vistas, controlador y servicio de Almacenes están en UTF-8 sin BOM ni mojibake');
$labelView=file_get_contents($root.'/app/Views/warehouses/label_form.php');
$ok(str_contains($labelView,"dataType: 'json'")&&str_contains($labelView,'response.success !== true'),'preview valida respuesta AJAX y muestra errores controlados');
$ok(str_contains($labelView,"signature !== '%PDF-'")&&str_contains($labelView,"contentType.indexOf('application/pdf')")&&!str_contains($labelView,'target="_blank"'),'descarga rechaza HTML/redirecciones y sólo abre un PDF binario válido');
$ok(str_contains($controller,"setHeader('Content-Type','application/pdf')")&&str_contains($controller,"str_starts_with(\$bytes,'%PDF-')")&&str_contains($controller,"X-Content-Type-Options','nosniff"),'controlador entrega PDF con firma y headers binarios explícitos');
$routes=file_get_contents($root.'/app/Config/Routes.php');
$ok(str_contains($routes,"warehouses/products/(:num)/labels/preview")&&str_contains($routes,"warehouses/products/(:num)/labels/pdf"),'rutas protegidas de preview y PDF permanecen registradas');

echo'TOTAL PASS='.$p.' FAIL='.$f.PHP_EOL;$out=ob_get_clean();echo$out;exit($f?1:0);


