<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';helper(['general','date_time','plugin','currency']);require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
final class Increment09FakePacAdapter implements App\Contracts\Fiscal\Pac\PacAdapterInterface{public int$calls=0;public function __construct(private string$xml,private string$mode='success',private ?string$pdf=null){}public function stamp(App\Domain\Fiscal\Pac\StampRequest$r):App\Domain\Fiscal\Pac\PacResponse{$this->calls++;if($this->mode==='timeout')return new App\Domain\Fiscal\Pac\PacResponse(null,'timeout',null,0,[],true,true);if($this->mode==='reject')return new App\Domain\Fiscal\Pac\PacResponse('999','rejected',null,200);return new App\Domain\Fiscal\Pac\PacResponse('200','ok',json_encode(['XML'=>$this->xml,'UUID'=>'123E4567-E89B-42D3-A456-426614174000','FechaTimbrado'=>'2026-07-23T10:00:01','NoCertificado'=>'30001000000500003416','NoCertificadoSAT'=>'30001000000500000001','CadenaOriginal'=>'ORIGINAL','CadenaOriginalSAT'=>'SAT-ORIGINAL','Sello'=>'SELL-CFD','SelloSAT'=>'SELL-SAT','CodigoQR'=>'id=123E4567-E89B-42D3-A456-426614174000','PDF'=>$this->pdf]),200);}public function getStampStatus(array$q):App\Domain\Fiscal\Pac\PacResponse{return new App\Domain\Fiscal\Pac\PacResponse('200','ok',null,200);}}
putenv('TIMBRADORXPRESS_ENVIRONMENT=sandbox');putenv('TIMBRADORXPRESS_APIKEY_SANDBOX=test-only-key-32-characters-0000');putenv('TIMBRADORXPRESS_PRODUCTION_ENABLED=false');
 $db=require dirname(__DIR__).'/Increment02/isolated_database.php';service('migrations')->setNamespace('App')->latest();$config=(new ReflectionClass(Config\TimbradorXpress::class))->newInstanceWithoutConstructor();$config->apiKey='test-only-key-32-characters-0000';$config->environment='sandbox';$config->baseUrl=Config\TimbradorXpress::SANDBOX_URL;$config->productionEnabled=false;$config->connectTimeout=10;$config->requestTimeout=60;$config->maxSignedXmlBytes=2097152;$config->maxResponseBytes=8388608;$config->maxPdfBytes=10485760;$config->pdfTemplate='Principal';CodeIgniter\Config\Factories::injectMock('config','TimbradorXpress',$config);$fiscal=(new ReflectionClass(Config\Fiscal::class))->newInstanceWithoutConstructor();$fiscal->enabled=true;$fiscal->environment='local';$fiscal->allowRealPac=false;$fiscal->pacAdapter='fake';$fiscal->pacEncryptionKey=str_repeat('T',40);$fiscal->stampingSendingStaleMinutes=5;
$pass=0;$fail=0;$a=function(bool$o,string$m)use(&$pass,&$fail){echo($o?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$o?$pass++:$fail++;};
$temp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'ikontrol_increment09_'.bin2hex(random_bytes(5));mkdir($temp,0700,true);
$clean=function($p)use(&$clean){if(!is_dir($p))return;foreach(scandir($p)?:[]as$e){if($e==='.'||$e==='..')continue;$t=$p.DIRECTORY_SEPARATOR.$e;is_dir($t)?$clean($t):@unlink($t);}@rmdir($p);};register_shutdown_function(fn()=>$clean($temp));
try{
  foreach(['fiscal_pac_configurations','fiscal_stamp_attempts','fiscal_document_stamps','fiscal_document_binary_artifacts']as$t)$a($db->tableExists($t),"$t exists.");
 $vault=new App\Services\Fiscal\Pac\PacSecretVault(str_repeat('T',40));
 $signed='<?xml version="1.0" encoding="UTF-8"?><cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/4" Version="4.0" Serie="T" Folio="9001" Fecha="2026-07-23T10:00:00" Sello="SELL-CFD" NoCertificado="30001000000500003416" Certificado="CERT" SubTotal="100.00" Moneda="MXN" Total="116.00" TipoDeComprobante="I" Exportacion="01" MetodoPago="PUE" FormaPago="01" LugarExpedicion="06000"><cfdi:Emisor Rfc="AAA010101AAA" Nombre="EMISOR TEST" RegimenFiscal="601"/><cfdi:Receptor Rfc="XAXX010101000" Nombre="PUBLICO GENERAL" DomicilioFiscalReceptor="06000" RegimenFiscalReceptor="616" UsoCFDI="S01"/><cfdi:Conceptos><cfdi:Concepto ClaveProdServ="01010101" Cantidad="1" ClaveUnidad="H87" Descripcion="TEST" ValorUnitario="100.00" Importe="100.00" ObjetoImp="01"/></cfdi:Conceptos></cfdi:Comprobante>';
 $dom=new DOMDocument();$dom->loadXML($signed);$comp=$dom->createElementNS('http://www.sat.gob.mx/cfd/4','cfdi:Complemento');$tfd=$dom->createElementNS('http://www.sat.gob.mx/TimbreFiscalDigital','tfd:TimbreFiscalDigital');foreach(['Version'=>'1.1','UUID'=>'123E4567-E89B-42D3-A456-426614174000','FechaTimbrado'=>'2026-07-23T10:00:01','RfcProvCertif'=>'AAA010101AAA','SelloCFD'=>'SELL-CFD','NoCertificadoSAT'=>'30001000000500000001','SelloSAT'=>'SELL-SAT']as$k=>$v)$tfd->setAttribute($k,$v);$comp->appendChild($tfd);$dom->documentElement->appendChild($comp);$stamped=$dom->saveXML();
 $v=(new App\Services\Fiscal\Pac\StampedXmlValidator())->validate($stamped,$signed);$a($v['uuid']==='123E4567-E89B-42D3-A456-426614174000','Stamped validator extracts UUID and validates official TFD XSD.');
 $tampered=str_replace('Total="116.00"','Total="117.00"',$stamped);try{(new App\Services\Fiscal\Pac\StampedXmlValidator())->validate($tampered,$signed);$blocked=false;}catch(Throwable){$blocked=true;}$a($blocked,'Stamped validator rejects a changed total.');
 $payload=json_encode(['XML'=>$stamped,'UUID'=>'123E4567-E89B-42D3-A456-426614174000']);$parser=new App\Services\Fiscal\Pac\TimbradorXpressResponseParser();$p=$parser->parse(json_encode(['code'=>'200','message'=>'ok','data'=>$payload]),200);$a($p->code==='200'&&$p->data===$payload,'PAC parser accepts only code/message/data contract.');
 foreach([json_encode(['message'=>'x','data'=>'x']),'<html>proxy</html>','']as$bad){try{$parser->parse($bad,200);$blocked=false;}catch(Throwable){$blocked=true;}$a($blocked,'Invalid PAC response is rejected.');}
 $request=new App\Domain\Fiscal\Pac\StampRequest(1,$signed,hash('sha256',$signed),'timbradorxpress','sandbox',str_repeat('a',64));$a(!property_exists($request,'privateKey')&&!property_exists($request,'password'),'StampRequest contains no CSD password or private key.');
 $http=new class($stamped){public array$calls=[];public function __construct(private string$xml){}public function post($url,$options){$this->calls[]=[$url,$options];return new class(json_encode(['code'=>'200','message'=>'ok','data'=>$this->xml])){public function __construct(private string$b){}public function getBody(){return$this->b;}public function getStatusCode(){return 200;}};}};
 $adapted=(new App\Services\Fiscal\Pac\TimbradorXpressRestAdapter($config,$http))->stamp($request);
 $call=$http->calls[0];$a($call[0]==='https://dev.timbradorxpress.mx/api/rest/servicio/timbrar3','Mock HTTP contract uses the sandbox REST timbrar3 endpoint.');
 $a(array_keys($call[1]['form_params'])===['apikey','xmlCFDI']&&$call[1]['form_params']['xmlCFDI']===$signed,'Mock HTTP contract sends exactly apikey and raw signed xmlCFDI.');
 $a($call[1]['verify']===true&&$call[1]['connect_timeout']===10&&$call[1]['timeout']===60,'Mock HTTP contract enforces TLS and configured timeouts.');
 $a($adapted->code==='200','Mock adapter normalizes the documented response.');
 $blockedConfig=clone$config;$blockedConfig->environment='production';$blockedConfig->baseUrl=Config\TimbradorXpress::PRODUCTION_URL;$blockedConfig->productionEnabled=true;try{(new App\Services\Fiscal\Pac\TimbradorXpressRestAdapter($blockedConfig,$http))->stamp(new App\Domain\Fiscal\Pac\StampRequest(1,$signed,hash('sha256',$signed),'timbradorxpress','production',str_repeat('b',64)));$blocked=false;}catch(Throwable){$blocked=true;}$a($blocked&&count($http->calls)===1,'Production is blocked before any HTTP call.');
 $badHost=clone$config;$badHost->baseUrl='https://example.invalid/';try{(new App\Services\Fiscal\Pac\TimbradorXpressRestAdapter($badHost,$http))->stamp($request);$blocked=false;}catch(Throwable){$blocked=true;}$a($blocked&&count($http->calls)===1,'An arbitrary endpoint is blocked before any HTTP call.');
 $key1=hash('sha256',implode('|',[1,hash('sha256',$signed),'timbradorxpress','sandbox','timbrar3']));$key2=hash('sha256',implode('|',[1,hash('sha256',$signed),'timbradorxpress','sandbox','timbrar3']));$a(hash_equals($key1,$key2),'Idempotency key inputs are deterministic.');
 $invoice=$db->table('invoices')->where('deleted',0)->get(1)->getRow();$user=$db->table('users')->where('deleted',0)->get(1)->getRow();$now=get_current_utc_time();$invoiceTotal=(string)$invoice->invoice_total;
 $doc=['invoice_id'=>$invoice->id,'issuer_profile_id'=>90009,'receiver_profile_id'=>90010,'fiscal_series_id'=>1,'document_type'=>'income','status'=>'ready_to_stamp','version'=>1,'series'=>'T','folio'=>9001,'issue_date'=>'2026-07-23 10:00:00','expedition_postal_code'=>'06000','currency_code'=>'MXN','payment_form_code'=>'01','payment_method_code'=>'PUE','cfdi_use_code'=>'S01','export_code'=>'01','subtotal'=>'100.00','discount'=>'0.00','transferred_tax_total'=>'16.00','withheld_tax_total'=>'0.00','total'=>'116.00','administrative_total_reference'=>$invoiceTotal,'pricing_mode'=>'tax_exclusive','source_snapshot_hash'=>str_repeat('9',64),'created_by'=>$user->id,'created_at'=>$now,'updated_at'=>$now,'locked_at'=>$now,'deleted'=>0];$db->table('fiscal_documents')->insert($doc);$docId=(int)$db->insertID();
 $db->table('fiscal_document_issuers')->insert(['fiscal_document_id'=>$docId,'rfc'=>'AAA010101AAA','legal_name'=>'EMISOR TEST','tax_regime_code'=>'601','fiscal_postal_code'=>'06000','expedition_postal_code'=>'06000','country_code'=>'MEX','created_at'=>$now]);
 $db->table('fiscal_document_receivers')->insert(['fiscal_document_id'=>$docId,'rfc'=>'XAXX010101000','legal_name'=>'PUBLICO GENERAL','tax_regime_code'=>'616','fiscal_postal_code'=>'06000','cfdi_use_code'=>'S01','created_at'=>$now]);
 $db->table('fiscal_document_items')->insert(['fiscal_document_id'=>$docId,'line_number'=>1,'product_service_code'=>'01010101','quantity'=>'1.000000','unit_code'=>'H87','unit_name'=>'Pieza','description'=>'TEST','unit_value'=>'100.000000','gross_amount'=>'100.00','discount'=>'0.00','tax_object_code'=>'01','taxable_base'=>'100.00','transferred_tax_total'=>'0.00','withheld_tax_total'=>'0.00','line_total'=>'100.00','created_at'=>$now]);
 $db->table('fiscal_issuer_certificates')->insert(['issuer_profile_id'=>90009,'certificate_number'=>'30001000000500003416','certificate_subject'=>'TEST','certificate_rfc'=>'AAA010101AAA','valid_from'=>gmdate('Y-m-d H:i:s',time()-3600),'valid_to'=>gmdate('Y-m-d H:i:s',time()+3600),'certificate_sha256'=>str_repeat('a',64),'public_certificate_path'=>'fiscal/certificates/90009/'.str_repeat('a',48).'.cer','encrypted_private_key_path'=>'fiscal/certificates/90009/'.str_repeat('b',48).'.key','private_key_sha256'=>str_repeat('b',64),'encryption_key_version'=>'password-v1','status'=>'valid','is_default'=>1,'created_by'=>$user->id,'created_at'=>$now,'updated_at'=>$now,'deleted'=>0]);$certId=(int)$db->insertID();
 $artifactRoot=$temp.DIRECTORY_SEPARATOR.'artifacts';$artifact=(new App\Services\Fiscal\FiscalArtifactStorageService($db,$artifactRoot))->store($docId,'signed_xml',$signed,'test-sign','CFDI 4.0','schema','valid',['signature_verified'=>true],(int)$user->id);
 $db->table('fiscal_document_signatures')->insert(['fiscal_document_id'=>$docId,'pre_xml_artifact_id'=>$artifact->id,'certificate_id'=>$certId,'original_chain_artifact_id'=>$artifact->id,'signed_xml_artifact_id'=>$artifact->id,'pre_xml_sha256'=>$artifact->sha256,'original_chain_sha256'=>str_repeat('c',64),'signed_xml_sha256'=>$artifact->sha256,'signature_verified'=>1,'xsd_status'=>'valid','created_by'=>$user->id,'created_at'=>$now]);
  $pdfBytes=App\Services\Fiscal\Pac\FakePacPdfFixture::bytes();$pdfBase64=base64_encode($pdfBytes);$verified=fn(string$xml,string$rfc,string$hash)=>new App\Domain\Fiscal\Signing\SignedXmlVerificationResult(true,true,true,true,true,true,true,true,[],[],hash('sha256',$xml),'30001000000500003416',$rfc);
  $projectCount=$db->table('projects')->countAllResults();$fake=new App\Services\Fiscal\Pac\FakePacAdapter('success',$stamped,$pdfBase64);$factory=new App\Services\Fiscal\Pac\FiscalPacAdapterFactory($fiscal,$config,$fake);$service=new App\Services\Fiscal\Pac\FiscalStampingService($db,$factory,$config,$vault,$artifactRoot,$temp.DIRECTORY_SEPARATOR.'contingency',$verified);$result=$service->stamp($docId,(int)$user->id,true);
 $a($result->status==='stamped'&&$fake->stampCalls===1,'Stamping service sends exactly once and reports stamped.');
 $a($db->table('fiscal_document_stamps')->where('fiscal_document_id',$docId)->countAllResults()===1,'Exactly one immutable document stamp is stored.');
 $a($db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$docId,'artifact_type'=>'stamped_xml'])->countAllResults()===1,'Stamped XML is stored as a private artifact.');
  $pdf=(new App\Services\Fiscal\Pac\PacPdfArtifactService($db))->read($docId);$a($pdf['bytes']===$pdfBytes&&$result->pdfAvailable,'PAC Base64 PDF is validated, stored in database, and decoded with integrity.');
  $a($db->table('fiscal_document_artifacts')->where(['fiscal_document_id'=>$docId,'artifact_type'=>'pdf'])->countAllResults()===0,'No permanent filesystem PDF artifact is generated.');
  try{(new App\Services\Fiscal\Pac\PacPdfValidator())->validate(base64_encode('not a pdf'));$invalid=false;}catch(Throwable){$invalid=true;}$a($invalid,'Base64 content that is not a PDF is rejected.');
  foreach([
    ['%%%not-base64%%%',10485760,'Malformed Base64 is rejected.'],
    ['data:application/pdf;base64,'.$pdfBase64,10485760,'A data URI is rejected; only clean Base64 is accepted.'],
    [base64_encode('<html>proxy error</html>'),10485760,'HTML disguised as Base64 is rejected.'],
    [$pdfBase64,8,'A PDF exceeding the configured decoded limit is rejected.'],
  ]as[$candidate,$limit,$message]){try{(new App\Services\Fiscal\Pac\PacPdfValidator($limit))->validate($candidate);$invalid=false;}catch(Throwable){$invalid=true;}$a($invalid,$message);}
 $a($db->table('fiscal_documents')->where('id',$docId)->get()->getRow()->status==='stamped','Document transitions to stamped.');
 $again=$service->stamp($docId,(int)$user->id,true);$a($again->status==='existing'&&$fake->stampCalls===1,'Repeated stamping returns the durable attempt without a second PAC call.');
 $a((string)$db->table('invoices')->where('id',$invoice->id)->get()->getRow()->invoice_total===$invoiceTotal,'Stamping does not modify the administrative sale.');
 $a($db->table('projects')->countAllResults()===$projectCount,'Stamping does not create projects.');
  $makeDoc=function(int$folio)use($db,$doc,$signed,$artifactRoot,$user,$certId,$now){$row=$doc;$row['folio']=$folio;$row['status']='ready_to_stamp';$row['source_snapshot_hash']=hash('sha256',(string)$folio);$db->table('fiscal_documents')->insert($row);$id=(int)$db->insertID();$db->table('fiscal_document_issuers')->insert(['fiscal_document_id'=>$id,'rfc'=>'AAA010101AAA','legal_name'=>'EMISOR TEST','tax_regime_code'=>'601','fiscal_postal_code'=>'06000','expedition_postal_code'=>'06000','country_code'=>'MEX','created_at'=>$now]);$db->table('fiscal_document_receivers')->insert(['fiscal_document_id'=>$id,'rfc'=>'XAXX010101000','legal_name'=>'PUBLICO GENERAL','tax_regime_code'=>'616','fiscal_postal_code'=>'06000','cfdi_use_code'=>'S01','created_at'=>$now]);$art=(new App\Services\Fiscal\FiscalArtifactStorageService($db,$artifactRoot))->store($id,'signed_xml',$signed,'test-sign','CFDI 4.0','schema','valid',['signature_verified'=>true],(int)$user->id);$db->table('fiscal_document_signatures')->insert(['fiscal_document_id'=>$id,'pre_xml_artifact_id'=>$art->id,'certificate_id'=>$certId,'original_chain_artifact_id'=>$art->id,'signed_xml_artifact_id'=>$art->id,'pre_xml_sha256'=>$art->sha256,'original_chain_sha256'=>str_repeat('c',64),'signed_xml_sha256'=>$art->sha256,'signature_verified'=>1,'xsd_status'=>'valid','created_by'=>$user->id,'created_at'=>$now]);return$id;};
  $withoutPdfId=$makeDoc(9006);$withoutPdfStamped=str_replace('123E4567-E89B-42D3-A456-426614174000','223E4567-E89B-42D3-A456-426614174001',$stamped);$withoutPdfAdapter=new App\Services\Fiscal\Pac\FakePacAdapter('success_pdf_missing',$withoutPdfStamped);$withoutPdfFactory=new App\Services\Fiscal\Pac\FiscalPacAdapterFactory($fiscal,$config,$withoutPdfAdapter);$withoutPdf=(new App\Services\Fiscal\Pac\FiscalStampingService($db,$withoutPdfFactory,$config,$vault,$artifactRoot,$temp.DIRECTORY_SEPARATOR.'contingency',$verified))->stamp($withoutPdfId,(int)$user->id,true);
 $a($withoutPdf->status==='stamped_pdf_pending'&&!$withoutPdf->pdfAvailable&&$withoutPdf->requiresPdfRecovery&&$db->table('fiscal_document_stamps')->where('fiscal_document_id',$withoutPdfId)->countAllResults()===1,'A valid XML/UUID without PDF is pending recovery and cannot be restamped.');
 $a($db->table('fiscal_document_binary_artifacts')->where('fiscal_document_id',$withoutPdfId)->countAllResults()===0,'A successful fake stamp without PDF creates no binary artifact.');
  $invalidPdfId=$makeDoc(9007);$invalidPdfStamped=str_replace('123E4567-E89B-42D3-A456-426614174000','323E4567-E89B-42D3-A456-426614174002',$stamped);$structurallyInvalidPdf=base64_encode("%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\nstartxref\n9\n%%EOF\n");$invalidPdfAdapter=new App\Services\Fiscal\Pac\FakePacAdapter('success',$invalidPdfStamped,$structurallyInvalidPdf);$invalidPdfFactory=new App\Services\Fiscal\Pac\FiscalPacAdapterFactory($fiscal,$config,$invalidPdfAdapter);$invalidPdfResult=(new App\Services\Fiscal\Pac\FiscalStampingService($db,$invalidPdfFactory,$config,$vault,$artifactRoot,$temp.DIRECTORY_SEPARATOR.'contingency',$verified))->stamp($invalidPdfId,(int)$user->id,true);
 $a($invalidPdfResult->status==='stamped_pdf_error'&&!$invalidPdfResult->pdfAvailable&&$db->table('fiscal_document_stamps')->where('fiscal_document_id',$invalidPdfId)->countAllResults()===1,'Structurally invalid PAC PDF preserves the XML stamp and projects stamped_pdf_error.');
 $a($db->table('fiscal_document_binary_artifacts')->where(['fiscal_document_id'=>$invalidPdfId,'artifact_type'=>'pac_pdf'])->countAllResults()===0&&$invalidPdfAdapter->stampCalls===1,'Structurally invalid PAC PDF is not activated and is never requested twice.');
  $rejectId=$makeDoc(9002);$rejectAdapter=new App\Services\Fiscal\Pac\FakePacAdapter('rejected');$rejectFactory=new App\Services\Fiscal\Pac\FiscalPacAdapterFactory($fiscal,$config,$rejectAdapter);$reject=(new App\Services\Fiscal\Pac\FiscalStampingService($db,$rejectFactory,$config,$vault,$artifactRoot,$temp.DIRECTORY_SEPARATOR.'contingency',$verified))->stamp($rejectId,(int)$user->id,true);
 $a($reject->status==='rejected'&&$db->table('fiscal_documents')->where('id',$rejectId)->get()->getRow()->status==='stamping_error','Known PAC rejection is persisted without creating a stamp.');
 $a($db->table('fiscal_document_stamps')->where('fiscal_document_id',$rejectId)->countAllResults()===0,'Rejected response creates no stamped XML record.');
  $timeoutId=$makeDoc(9003);$timeoutAdapter=new App\Services\Fiscal\Pac\FakePacAdapter('timeout_unknown');$timeoutFactory=new App\Services\Fiscal\Pac\FiscalPacAdapterFactory($fiscal,$config,$timeoutAdapter);$unknown=(new App\Services\Fiscal\Pac\FiscalStampingService($db,$timeoutFactory,$config,$vault,$artifactRoot,$temp.DIRECTORY_SEPARATOR.'contingency',$verified))->stamp($timeoutId,(int)$user->id,true);
 $a($unknown->status==='unknown'&&$db->table('fiscal_documents')->where('id',$timeoutId)->get()->getRow()->status==='stamp_status_unknown','Timeout is classified as unknown, not as a fiscal rejection.');
  $existingUnknown=(new App\Services\Fiscal\Pac\FiscalStampingService($db,$timeoutFactory,$config,$vault,$artifactRoot,$temp.DIRECTORY_SEPARATOR.'contingency',$verified))->stamp($timeoutId,(int)$user->id,true);$a($existingUnknown->status==='existing'&&$timeoutAdapter->stampCalls===1,'Unknown state cannot be resent automatically.');
  $orderedId=$makeDoc(9004);$orderedAdapter=new class($db,$orderedId)implements App\Contracts\Fiscal\Pac\PacAdapterInterface{public int$calls=0;public bool$durableBeforeCall=false;public function __construct(private$db,private int$id){}public function stamp(App\Domain\Fiscal\Pac\StampRequest$r):App\Domain\Fiscal\Pac\PacResponse{$this->calls++;$attempt=$this->db->table('fiscal_stamp_attempts')->where('fiscal_document_id',$this->id)->get(1)->getRow();$this->durableBeforeCall=$attempt&&$attempt->status==='sending'&&(int)$attempt->id>0;return new App\Domain\Fiscal\Pac\PacResponse(null,'not sent',null,0,['request_sent'=>false],true,false);}public function getStampStatus(array$q):App\Domain\Fiscal\Pac\PacResponse{return new App\Domain\Fiscal\Pac\PacResponse(null,'disabled',null,0,['request_sent'=>false],true,false);}};
  $orderedFactory=new App\Services\Fiscal\Pac\FiscalPacAdapterFactory($fiscal,$config,$orderedAdapter);$notSent=(new App\Services\Fiscal\Pac\FiscalStampingService($db,$orderedFactory,$config,$vault,$artifactRoot,$temp.DIRECTORY_SEPARATOR.'contingency',$verified))->stamp($orderedId,(int)$user->id,true);
  $a($orderedAdapter->durableBeforeCall&&$notSent->status==='transport_not_sent','A durable attempt with a real ID exists before the adapter is invoked.');
  $persistenceId=$makeDoc(9005);$persistenceAdapter=new App\Services\Fiscal\Pac\FakePacAdapter('persistence_error',$stamped);$persistenceFactory=new App\Services\Fiscal\Pac\FiscalPacAdapterFactory($fiscal,$config,$persistenceAdapter);$persistenceService=new App\Services\Fiscal\Pac\FiscalStampingService($db,$persistenceFactory,$config,$vault,$artifactRoot,$temp.DIRECTORY_SEPARATOR.'contingency',$verified);
  try{$persistenceService->stamp($persistenceId,(int)$user->id,true);$failed=false;}catch(Throwable){$failed=true;}$persistAttempt=$db->table('fiscal_stamp_attempts')->where('fiscal_document_id',$persistenceId)->get(1)->getRow();
  $a($failed&&$persistAttempt->status==='reconciliation_required'&&(int)$persistAttempt->requires_reconciliation===1,'Post-response persistence failure requires reconciliation.');
  $existingPersistence=$persistenceService->stamp($persistenceId,(int)$user->id,true);$a($existingPersistence->status==='existing'&&$persistenceAdapter->stampCalls===1,'Persistence failure is never resent automatically.');
}catch(Throwable$e){echo'[FAIL] '.get_class($e).': '.$e->getMessage().PHP_EOL;$fail++;}
echo"\n$pass passed, $fail failed.\n";exit($fail?1:0);
