<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);$pass=0;$fail=0;
$check=function(bool$ok,string$m)use(&$pass,&$fail){echo($ok?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$ok?$pass++:$fail++;};
$read=fn(string$p)=>(string)file_get_contents($root.'/'.$p);
$migrations=glob($root.'/app/Database/Migrations/2026-07-29-09*.php');sort($migrations);
$check(count($migrations)===9,'Increment 09 defines nine ordered migrations including Base64 PDF storage and permission migration.');
$all=implode("\n",array_map('file_get_contents',$migrations));
$check(!preg_match('/\b(FLOAT|DOUBLE)\b/i',$all),'Increment 09 introduces no FLOAT or DOUBLE fields.');
$check(str_contains($all,"'encrypted_api_key'=>''")&&str_contains($all,"'pac_configuration_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true]"),'Corrective migration scrubs legacy credentials and removes the runtime dependency.');
$adapter=$read('app/Services/Fiscal/Pac/TimbradorXpressRestAdapter.php');
$check(str_contains($adapter,".'timbrarConSello'")&&str_contains($adapter,"'form_params'"),'REST adapter posts form data to timbrarConSello.');
$check(str_contains($adapter,"'apikey'=>\$config->apiKey")&&str_contains($adapter,"'xmlCFDI'=>\$request->signedXml")&&str_contains($adapter,"'keyPEM'=>\$request->keyPem"),'REST adapter sends the confirmed timbrarConSello fields.');
$check(!preg_match('/cerPEM|timbrarJSON|timbrarTXT|withoutVerifying/i',$adapter),'Adapter contains no certificate, JSON/TXT or insecure TLS operation.');
$check(str_contains($adapter,"'verify'=>true"),'TLS verification remains enabled.');
$config=$read('app/Config/TimbradorXpress.php');
$check(str_contains($config,'SANDBOX_URL')&&str_contains($config,'PRODUCTION_URL')&&str_contains($config,'assertSandbox'),'Environment and endpoints are server-controlled and allowlisted.');
$service=$read('app/Services/Fiscal/Pac/FiscalStampingService.php');
$check(!str_contains($service,'fiscal_pac_configurations')&&!str_contains($service,'encrypted_api_key'),'Stamping service does not read PAC credentials from the database.');
$check(str_contains($service,'FOR UPDATE')&&str_contains($service,"'timbrarConSello'")&&preg_match("/'status'\\s*=>\\s*'pending'/",$service),'Attempt is durably prepared under lock for timbrarConSello.');
$check(str_contains($service,'stamp_status_unknown')&&!str_contains($service,'sleep('),'Unknown results are not blindly retried.');
$check(str_contains($service,'TimbradorXpressStampDataParser')&&str_contains($service,'StampedXmlValidator'),'Auxiliary JSON is parsed and XML remains authoritative.');
$routes=$read('app/Config/FiscalRoutes.php');
$check(!str_contains($routes,'fiscal/pac/save')&&!str_contains($routes,'fiscal/pac/form'),'Editable PAC routes were removed.');
foreach(['fiscal/pac/status','fiscal/stamping/stamp','fiscal/stamping/xml/download/(:num)','fiscal/documents/(:num)/pdf/download']as$r)$check(str_contains($routes,$r),"Explicit protected route exists: $r.");
$roles=$read('app/Controllers/Roles.php');
$check(!str_contains($roles,'fiscal_pac_manage')&&!str_contains($roles,'fiscal_pac_view')&&!str_contains($roles,'fiscal_stamp_production'),'Credential and production permissions are absent.');
foreach(['fiscal_pac_status_view','fiscal_stamp_sandbox','fiscal_stamped_xml_view','fiscal_pdf_view','fiscal_pdf_download']as$p)$check(str_contains($roles,$p),"Role persistence supports $p.");
$pdf=$read('app/Services/Fiscal/Pac/PacPdfValidator.php');$binary=$read('app/Services/Fiscal/Pac/PacPdfArtifactService.php');
$check(str_contains($pdf,"base64_decode(\$clean,true)")&&str_contains($pdf,"'%PDF-'")&&str_contains($binary,'fiscal_document_binary_artifacts'),'PAC PDF is strictly validated and stored as clean Base64 in the database.');
$check(!is_file($root.'/app/Services/Fiscal/Pdf/FiscalInvoicePdfService.php')&&!preg_match('/write2DBarcode|new\\s+TCPDF/i',$service),'No fiscal PDF or QR is generated locally.');
echo"\n$pass passed, $fail failed.\n";exit($fail?1:0);
