<?php
declare(strict_types=1);
namespace App\Commands;
use CodeIgniter\CLI\BaseCommand;use CodeIgniter\CLI\CLI;use Config\Database;use RuntimeException;
final class FiscalPlatformIdentity extends BaseCommand{
 protected$group='Security';protected$name='platform:identity';protected$description='Administra fuera de la UI la identidad persistente de plataforma.';protected$usage='platform:identity <grant|revoke> <email|id> --confirm [--actor=<email|id>] [--reason="..."]';
 public function run(array$p):void{$action=(string)($p[0]??'');$target=(string)($p[1]??'');if(!in_array($action,['grant','revoke'],true)||$target===''||CLI::getOption('confirm')===null)throw new RuntimeException('Uso inválido o falta --confirm.');$db=Database::connect('default',false);$user=$this->user($db,$target);$count=$db->table('users')->where(['is_platform_superadmin'=>1,'deleted'=>0])->countAllResults();$actorId=null;$actor=(string)CLI::getOption('actor');if($count>0){$a=$this->user($db,$actor);if((int)$a->is_platform_superadmin!==1)throw new RuntimeException('El actor no es identidad de plataforma.');$actorId=(int)$a->id;}elseif($action!=='grant')throw new RuntimeException('Sólo se permite bootstrap inicial para grant.');$permissions=@unserialize((string)$user->permissions);if(!is_array($permissions))$permissions=[];$permissions['platform.fiscal_stamps.manage']=$action==='grant'?1:0;$now=get_current_utc_time();$db->transStart();$db->table('users')->where('id',$user->id)->update(['is_platform_superadmin'=>$action==='grant'?1:0,'permissions'=>serialize($permissions)]);$db->table('platform_identity_audit')->insert(['user_id'=>$user->id,'action'=>$action,'performed_by'=>$actorId,'reason'=>trim((string)CLI::getOption('reason'))?:'Cambio controlado por CLI','created_at'=>$now]);$db->transComplete();if(!$db->transStatus())throw new RuntimeException('No fue posible actualizar la identidad.');CLI::write('Identidad de plataforma actualizada para usuario ID '.(int)$user->id.'.','green');}
 private function user($db,string$id):object{if($id==='')throw new RuntimeException('Falta usuario.');$b=$db->table('users')->where('deleted',0);ctype_digit($id)?$b->where('id',(int)$id):$b->where('email',$id);$u=$b->get(1)->getRow();if(!$u)throw new RuntimeException('Usuario inexistente.');return$u;}
}
