<?php
namespace App\Commands;
use CodeIgniter\CLI\{BaseCommand,CLI};
final class IkontrolSettingsBaseline extends BaseCommand {
 protected $group='iKontrol'; protected $name='ikontrol:settings-baseline';
 private const BASELINE=array (
  'timezone' => 'America/Mexico_City',
  'language' => 'spanish',
  'date_format' => 'Y-m-d',
  'time_format' => 'small',
  'first_day_of_week' => '0',
  'weekends' => '',
  'default_currency' => 'MXN',
  'currency_symbol' => '$',
  'currency_position' => 'left',
  'decimal_separator' => '.',
  'no_of_decimals' => '2',
  'accepted_file_formats' => 'jpg,jpeg,png,doc,xlsx,txt,pdf,zip,webm',
  'module_announcement' => '1',
  'module_attendance' => '1',
  'module_chat' => '1',
  'module_contract' => '',
  'module_estimate' => '1',
  'module_estimate_request' => '',
  'module_event' => '1',
  'module_expense' => '1',
  'module_file_manager' => '1',
  'module_gantt' => '1',
  'module_help' => '1',
  'module_invoice' => '1',
  'module_knowledge_base' => '1',
  'module_lead' => '1',
  'module_leave' => '1',
  'module_message' => '1',
  'module_note' => '1',
  'module_order' => '',
  'module_project_timesheet' => '1',
  'module_proposal' => '1',
  'module_reminder' => '1',
  'module_subscription' => '',
  'module_ticket' => '',
  'module_timeline' => '1',
  'module_todo' => '1',
  'add_signature_option_on_accepting_estimate' => '1',
  'add_signature_option_on_accepting_proposal' => '1',
  'allowed_ip_addresses' => '',
  'contract_color' => '#000000',
  'conversion_rate' => 'a:0:{}',
  'create_new_invoices_automatically_when_estimates_gets_accepted' => '1',
  'default_contract_template' => '1',
  'default_due_date_after_billing_date' => '14',
  'default_permissions_for_non_primary_contact' => 'projects',
  'default_proposal_template' => '3',
  'disable_proposal_pdf_for_clients' => '',
  'email_protocol' => 'mail',
  'enable_audio_recording' => '1',
  'enable_background_image_for_invoice_pdf' => '',
  'enable_comments_on_estimates' => '',
  'enable_comments_on_proposals' => '',
  'enable_estimate_lock_state' => '1',
  'enable_invoice_id_editing' => '',
  'enable_proposal_lock_state' => '1',
  'initial_number_of_the_estimate' => '1',
  'initial_number_of_the_invoice' => '1',
  'initial_number_of_the_proposal' => '1',
  'invoice_item_list_background' => '#f4f4f4',
  'invoice_number_format' => '{SERIAL}',
  'invoice_style' => 'style_1',
  'reset_invoice_number_every_year' => '',
  'set_invoice_pdf_background_only_on_first_page' => '',
  'show_background_image_in_signin_page' => '',
  'show_logo_in_signin_page' => 'yes',
  'show_most_recent_estimate_comments_at_the_top' => '',
  'show_most_recent_proposal_comments_at_the_top' => '',
  'show_the_status_checkbox_in_tasks_list' => '1',
  'show_theme_color_changer' => 'yes',
  'smtp_authorized' => '0',
  'task_point_range' => '5',
  'year_based_on' => 'bill_date',
  'app_title' => 'iKontrol',
  'default_theme_color' => '2e86c1',
  'landing_page' => '',
  'site_logo' => '',
  'favicon' => '',
  'signin_page_background' => '',
  'invoice_logo' => '',
  'invoice_prefix' => '',
  'invoice_footer' => '',
  'invoice_color' => '#000000',
  'estimate_prefix' => '',
  'estimate_footer' => '',
  'estimate_color' => '#000000',
  'proposal_prefix' => '',
  'proposal_color' => '#000000',
  'order_color' => '#000000',
  'email_sent_from_address' => '',
  'email_sent_from_name' => '',
  'email_smtp_host' => '',
  'email_smtp_port' => '',
  'email_smtp_security_type' => 'none',
  'email_smtp_user' => '',
  'item_purchase_code' => 'CLEAN-LOCAL-NOT-LICENSED',
);
         public function run(array$p){
          if($p)throw new \RuntimeException('Este comando no acepta argumentos.');
          try{$db=\Config\Database::connect();if(!$db->tableExists('settings')){$this->emit(['status'=>'FAILED','reason'=>'SETTING_TABLE_MISSING']);return;}$table=$db->table('settings');$created=[];$corrected=[];$preserved=[];
           foreach(self::BASELINE as$name=>$default){$default=$this->normalize($default);$query=$table->select('setting_name,setting_value,type,deleted')->where('setting_name',$name)->get();if($query===false){$this->emit(['status'=>'FAILED','reason'=>'SQL_QUERY_FAILED','operation'=>'read','setting'=>$name]);return;}$row=$query->getRowArray();
            if(!$row){$insert=$table->insert(['setting_name'=>$name,'setting_value'=>$default,'type'=>'app','deleted'=>0]);if($insert===false){$this->emit(['status'=>'FAILED','reason'=>'SQL_WRITE_FAILED','operation'=>'insert','setting'=>$name]);return;}$created[]=$name;continue;}
            $value=$this->normalize($row['setting_value']??'');$replacement=null;if(in_array($name,['site_logo','favicon'],true)&&in_array(trim($value),['b:0;','N;'],true))$replacement='';if($name==='item_purchase_code'&&trim($value)==='')$replacement=$default;if($name==='timezone'&&trim($value)==='')$replacement=$default;if($replacement!==null||$value!==($row['setting_value']??'' )||((int)($row['deleted']??0)!==0)){$update=$table->where('setting_name',$name)->update(['setting_value'=>$replacement??$value,'type'=>$row['type']??'app','deleted'=>0]);if($update===false){$this->emit(['status'=>'FAILED','reason'=>'SQL_WRITE_FAILED','operation'=>'update','setting'=>$name]);return;}$corrected[]=$name;}else{$preserved[]=$name;}
           }$check=$this->check($db);$this->emit(['status'=>$check['status'],'reason'=>$check['reason'],'created'=>$created,'corrected'=>$corrected,'preserved'=>$preserved,'checks'=>$check['checks']]);
          }catch(\Throwable$e){$this->emit(['status'=>'FAILED','reason'=>'SQL_QUERY_FAILED','error'=>get_class($e),'message'=>$e->getMessage()]);}
         }
         private function normalize($value){if($value===null)return '';if(is_bool($value))return $value?'1':'0';if(is_int($value)||is_float($value))return (string)$value;if(is_string($value))return $value;throw new \RuntimeException('El setting contiene un valor no escalar.');}
         private function check($db){$query=$db->table('settings')->select('setting_name,setting_value')->where('deleted',0)->whereIn('setting_name',array_keys(self::BASELINE))->get();if($query===false) return ['status'=>'FAILED','reason'=>'SQL_QUERY_FAILED','checks'=>[]];$values=[];foreach($query->getResultArray() as$r)$values[$r['setting_name']]=$this->normalize($r['setting_value']??'');$checks=[];$reason=null;foreach(self::BASELINE as$name=>$default){$exists=array_key_exists($name,$values);$valid=$exists;if(in_array($name,['site_logo','favicon'],true))$valid=$exists&&!in_array(trim($values[$name]??''),['b:0;','N;'],true);if(in_array($name,['timezone','item_purchase_code'],true))$valid=$exists&&trim($values[$name]??'')!=='';$checks[$name]=['present'=>$exists,'valid'=>$valid,'non_null'=>$exists&&$values[$name]!==null];if(!$valid&&$reason===null)$reason=!$exists?'SETTING_MISSING':($name==='site_logo'?'SITE_LOGO_INVALID':($name==='favicon'?'FAVICON_INVALID':($name==='item_purchase_code'?'ITEM_PURCHASE_CODE_MISSING':'SETTING_INVALID')));}$status=$reason===null?'READY':'FAILED';return compact('status','reason','checks');}
 private function emit(array$d){CLI::write("IKONTROL_JSON_BEGIN\n".json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\nIKONTROL_JSON_END");}
}