<?php
declare(strict_types=1);
namespace App\Commands;
use App\Services\Legacy\Fc2\{Fc2ClientSource,Fc2ConnectionGuard,Fc2IssuerSource,Fc2MasterDataAuditService,Fc2ProductSource,Fc2SeriesSource};use CodeIgniter\CLI\BaseCommand;use CodeIgniter\CLI\CLI;use RuntimeException;
final class LegacyFc2Audit extends BaseCommand {
 protected$group='Legacy';protected$name='legacy:fc2-audit';protected$description='Audita datos maestros FC2 en modo estricto de sólo lectura.';protected$usage='legacy:fc2-audit <RFC> --owner-id=15 --only=clients --format=json --output=reports/fc2.json';protected$options=['--owner-id'=>'FC2 users.id esperado','--only'=>'issuer|clients|products|series (repetible)','--format'=>'console|json','--output'=>'Ruta relativa dentro de writable','--sample-errors'=>'Máximo detalle mostrado'];
 public function run(array$params):void{$rfc=trim((string)($params[0]??''));$owner=filter_var($this->option($params,'owner-id',15),FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($rfc===''||!$owner)throw new RuntimeException('RFC y --owner-id válido son obligatorios.');$this->assertConfig();$only=$this->option($params,'only');$only=$only?[$only]:[];foreach($only as$v)if(!in_array($v,['issuer','clients','products','series'],true))throw new RuntimeException('Valor --only no permitido.');$format=(string)$this->option($params,'format','console');if(!in_array($format,['console','json'],true))throw new RuntimeException('Formato no permitido.');$db=db_connect('fc2_legacy');$report=(new Fc2MasterDataAuditService(new Fc2ConnectionGuard($db,db_connect('default')),new Fc2IssuerSource($db),new Fc2ClientSource($db),new Fc2ProductSource($db),new Fc2SeriesSource($db)))->audit($rfc,(int)$owner,$only);$json=json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$output=$this->option($params,'output');if($output)$this->writeReport((string)$output,$json);if($format==='json')CLI::write($json);else{$this->console($report,(int)$this->option($params,'sample-errors',10));}foreach($report['findings']as$f)if($f['severity']==='error')throw new RuntimeException('El dry-run terminó con errores de integridad; revise el reporte.');}
 private function option(array$params,string$name,mixed$default=null):mixed{$value=CLI::getOption($name);if($value!==null)return$value;foreach($params as$key=>$unused)if(is_string($key)&&str_starts_with($key,$name.'='))return substr($key,strlen($name)+1);return$default;}
 private function assertConfig():void{$c=config('Database')->fc2_legacy;foreach(['hostname','database','username']as$k)if(trim((string)$c[$k])==='')throw new RuntimeException('La conexión FC2 no está configurada completamente mediante variables de entorno.');}
 private function writeReport(string$relative,string$json):void{$relative=str_replace('\\','/',$relative);if($relative===''||str_starts_with($relative,'/')||str_contains($relative,'..'))throw new RuntimeException('La ruta de salida debe ser relativa y permanecer dentro de writable.');$path=WRITEPATH.$relative;$dir=dirname($path);if(!is_dir($dir)&&!mkdir($dir,0700,true)&&!is_dir($dir))throw new RuntimeException('No fue posible crear el directorio del reporte.');if(file_put_contents($path,$json,LOCK_EX)===false)throw new RuntimeException('No fue posible escribir el reporte.');@chmod($path,0600);}
 private function console(array$r,int$sample):void{CLI::write('FC2 dry-run '.($r['source_owner_key']??''),'yellow');foreach(['issuer_summary','client_summary','product_summary','series_summary']as$k)if(isset($r[$k]))CLI::write($k.': '.json_encode($r[$k],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$shown=0;foreach($r['findings']as$f){if($shown++>=$sample)break;CLI::write($f['severity'].' '.$f['code'].' '.$f['entity'].'#'.$f['source_id']);}}
}
