<?php
declare(strict_types=1);
ob_start();$root=dirname(__DIR__,2);require $root.'/tests/bootstrap.php';helper(['general','date_time','currency','form']);$db=require $root.'/tests/Increment02/isolated_database.php';
use App\Services\SupplierService;use App\Services\SupplierCostHistoryService;
$p=$f=0;$ok=function(bool$v,string$m)use(&$p,&$f){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$p++:$f++;};$actor=(int)$db->table('users')->select('id')->where('deleted',0)->get(1)->getRow()->id;$service=new SupplierService($db);
$first=$service->save(['name'=>'Calzado del Bajío','rfc'=>' dold 860620 ew7','status'=>'active'],$actor);$ok($first['success']&&$first['supplier_id']===$first['id']&&$first['supplier_name']===$first['text'],'quick-create devuelve id y nombre');$row=$db->table('suppliers')->where('id',$first['id'])->get(1)->getRow();$ok($row->rfc==='DOLD860620EW7'&&$row->normalized_name==='CALZADODELBAJIO','identidad se normaliza');
$dup=$service->save(['name'=>'Otro','rfc'=>'dold860620ew7'],$actor);$similar=$service->save(['name'=>'CALZADO DEL BAJIO'],$actor);$ok(!$dup['success']&&$dup['duplicate_type']==='rfc','RFC duplicado se bloquea');$ok(!$similar['success']&&$similar['duplicate_type']==='name_warning','nombre equivalente advierte');
$form=file_get_contents($root.'/app/Views/suppliers/form_fields.php');$quick=file_get_contents($root.'/app/Views/proposals/item_modal_form.php');$routes=file_get_contents($root.'/app/Config/Routes.php');$controller=file_get_contents($root.'/app/Controllers/Suppliers.php');$ok(str_contains($form,'csrf_field()'),'formulario incluye CSRF');$ok(str_contains($quick,"view('suppliers/form_fields'")&&str_contains($quick,"get_uri('suppliers/save')"),'alta rápida comparte endpoint');$ok(str_contains($quick,"supplier.val(id).trigger('change')")&&str_contains($quick,"function selectSupplierInParent(data)")&&str_contains($quick,"isModal: false"),'selector padre se añade, selecciona y notifica');$ok(str_contains($routes,"suppliers/save', 'Suppliers::save', ['filter'=>'csrf']")&&str_contains($controller,"guard('suppliers_manage')"),'ruta conserva CSRF y ACL');
$proposal=$db->table('proposals')->where('deleted',0)->get(1)->getRowArray();$item=$db->table('proposal_items')->where(['proposal_id'=>$proposal['id'],'deleted'=>0])->where('item_id >',0)->get(1)->getRowArray();unset($proposal['id']);$proposal['status']='draft';$proposal['public_key']='accepted-'.bin2hex(random_bytes(5));$proposal['converted_sale_id']=null;$proposal['accepted_at']=null;$proposal['converted_at']=null;$db->table('proposals')->insert($proposal);$proposalId=(int)$db->insertID();unset($item['id']);$item['proposal_id']=$proposalId;$item['supplier_id']=$first['id'];$item['cost']='100.000000';$db->table('proposal_items')->insert($item);$itemId=(int)$db->insertID();$history=new SupplierCostHistoryService($db);
$ok($history->snapshotProposal($proposalId,'accepted',$actor)===1,'accepted crea snapshot');$snapshot=$db->table('product_supplier_cost_history')->where('proposal_item_id',$itemId)->get(1)->getRow();$ok((int)$snapshot->product_id===(int)$item['item_id']&&(int)$snapshot->supplier_id===(int)$first['id']&&(string)$snapshot->unit_cost==='100.000000'&&$snapshot->source_status==='accepted','snapshot conserva producto, proveedor, partida y costo');$ok($history->snapshotProposal($proposalId,'accepted',$actor)===0&&$db->table('product_supplier_cost_history')->where('proposal_item_id',$itemId)->countAllResults()===1,'snapshot accepted es idempotente');$ok(count($history->supplierProducts((int)$first['id']))>0&&count($history->productSummary((int)$item['item_id']))>0,'snapshot alimenta proveedor y producto');
$offer=file_get_contents($root.'/app/Controllers/Offer.php');$acceptance=file_get_contents($root.'/app/Services/ProposalAcceptanceService.php');$ok(substr_count($offer,'acceptAndConvert')>=2&&str_contains($acceptance,'snapshotProposal'),'ambos flujos públicos generan snapshot');$public=file_get_contents($root.'/app/Views/proposals/proposal_parts/proposal_items_table.php');$ok(!str_contains($public,'supplier_id')&&!str_contains($public,'unit_cost'),'salida cliente mantiene privacidad');echo"TOTAL PASS=$p FAIL=$f".PHP_EOL;$out=ob_get_clean();echo$out;exit($f?1:0);
