<div class="modal-body">
<div class="alert alert-warning"><?php echo app_lang('prexml_no_fiscal_validity'); ?></div>
<h4><?php echo app_lang('prexml_cfdi40'); ?></h4>
<div class="row"><div class="col-md-6"><strong>SHA-256:</strong><br><code><?php echo htmlspecialchars($artifact->sha256); ?></code></div><div class="col-md-3"><strong><?php echo app_lang('status'); ?>:</strong><br><?php echo app_lang('prexml_status_'.$artifact->validation_status); ?></div><div class="col-md-3"><strong><?php echo app_lang('version'); ?>:</strong><br><?php echo htmlspecialchars($artifact->builder_version); ?></div></div>
<hr><h5><?php echo app_lang('semantic_validation'); ?></h5><div class="alert <?php echo !empty($validation['semantic']['is_valid'])?'alert-success':'alert-danger'; ?>"><?php echo !empty($validation['semantic']['is_valid'])?app_lang('semantic_validation_correct'):app_lang('semantic_validation_errors'); ?></div>
<h5><?php echo app_lang('structural_validation'); ?></h5><div class="alert alert-info"><?php echo app_lang('prexml_status_'.($validation['xsd']['status']??'not_generated')); ?></div>
<?php foreach(($validation['xsd']['errors']??[])as$error){?><div class="text-danger"><?php echo htmlspecialchars('Línea '.$error['line'].', columna '.$error['column'].': '.$error['message']); ?></div><?php } ?>
<hr><pre style="max-height:500px;overflow:auto;white-space:pre-wrap"><?php echo htmlspecialchars($xml,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); ?></pre>
</div><div class="modal-footer"><?php if($can_download){?><a class="btn btn-default" href="<?php echo get_uri('fiscal/invoices/prexml/download/'.$artifact->id); ?>"><?php echo app_lang('download_prexml'); ?></a><?php }if($can_validate){echo form_open(get_uri('fiscal/invoices/prexml/validate'),['id'=>'validate-prexml-view','class'=>'general-form d-inline']);?><input type="hidden" name="artifact_id" value="<?php echo$artifact->id; ?>"><button class="btn btn-primary"><?php echo app_lang('validate_prexml'); ?></button><?php echo form_close();}?><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang('close'); ?></button></div>
<script>$(document).ready(function(){$('#validate-prexml-view').appForm({onSuccess:function(){location.reload();}});});</script>
