<div class="modal-body">
<?php echo form_open(get_uri('fiscal/invoices/review/'.$review['invoice_id']),['id'=>'fiscal-sale-review-form','class'=>'general-form']); ?>
<div class="alert alert-info"><?php echo app_lang('fiscal_review_preparation_help'); ?></div><h4><?php echo app_lang('fiscal_review_status_'.$review['status']); ?></h4>
<div class="row"><div class="col-md-4"><?php echo form_dropdown('issuer_profile_id',[''=>'-']+$issuers,$review['issuer']['issuer_profile_id'],"class='select2 form-control'"); ?><small><?php echo app_lang('fiscal_issuer'); ?></small></div><div class="col-md-4"><?php echo form_dropdown('series_id',[''=>'-']+$series_options,$review['series']['series_id'],"class='select2 form-control'"); ?><small><?php echo app_lang('fiscal_series_single'); ?></small></div><div class="col-md-4"><?php echo form_dropdown('receiver_profile_id',[''=>'-']+$receivers,$review['receiver']['profile_id'],"class='select2 form-control'"); ?><small><?php echo app_lang('receiver_fiscal_profile'); ?></small></div></div>
<?php if($can_override){ ?><details class="mt15"><summary><?php echo app_lang('advanced_options'); ?></summary><div class="form-group mt10"><label><?php echo app_lang('tax_pricing_override'); ?></label><?php echo form_dropdown('pricing_mode_override',[''=>app_lang('use_issuer_policy'),'tax_inclusive'=>app_lang('tax_pricing_mode_tax_inclusive'),'tax_exclusive'=>app_lang('tax_pricing_mode_tax_exclusive'),'preserve_total'=>app_lang('tax_pricing_mode_preserve_total')],$simulation['pricing_mode']??'',"class='select2 form-control'"); ?><small class="text-warning"><?php echo app_lang('tax_pricing_override_warning'); ?></small></div></details><?php } ?>
<div class="mt15"><button type="submit" class="btn btn-primary"><?php echo app_lang('refresh_review'); ?></button></div><?php echo form_close(); ?><hr>
<?php $groups=['issuer'=>app_lang('fiscal_issuer'),'receiver'=>app_lang('client'),'items'=>app_lang('items'),'series'=>app_lang('fiscal_series_single'),'sale'=>app_lang('sale')];foreach($groups as$key=>$title){?><h5><?php echo$title; ?></h5><?php foreach($review['errors'][$key]as$error){?><div class="alert alert-danger py-2"><?php echo htmlspecialchars($error); ?></div><?php }foreach($review['warnings'][$key]as$warning){?><div class="alert alert-warning py-2"><?php echo htmlspecialchars($warning); ?></div><?php }} ?>
<?php if($simulation_error){?><div class="alert alert-danger"><?php echo htmlspecialchars($simulation_error); ?></div><?php } ?>
<hr><h5><?php echo app_lang('fiscal_generation_environment'); ?></h5>
<div class="row">
    <div class="col-md-6"><strong><?php echo app_lang('digital_seal_certificate'); ?>:</strong>
        <span class="badge <?php echo $csd_summary['ready']?'bg-success':'bg-warning'; ?>"><?php echo htmlspecialchars($csd_summary['label']); ?></span>
    </div>
    <div class="col-md-6"><strong><?php echo app_lang('provider'); ?>:</strong>
        <?php echo $pac_status->provider==='fake'?app_lang('fake_pac'):htmlspecialchars($pac_status->provider); ?>
        <span class="badge bg-info"><?php echo htmlspecialchars($pac_status->environment); ?></span>
    </div>
</div>
<?php if($simulation){ ?>
<hr><h5><?php echo app_lang('price_treatment'); ?></h5><p><strong><?php echo app_lang('tax_pricing_mode_'.$simulation['pricing_mode']); ?></strong><br><?php echo app_lang('tax_pricing_mode_'.$simulation['pricing_mode'].'_help'); ?></p>
<h5><?php echo app_lang('administrative_fiscal_comparison'); ?></h5><div class="table-responsive"><table class="table table-bordered"><thead><tr><th><?php echo app_lang('concept'); ?></th><th><?php echo app_lang('current_sale'); ?></th><th><?php echo app_lang('fiscal_preparation'); ?></th></tr></thead><tbody><?php foreach([['subtotal','administrative_subtotal','estimated_fiscal_base'],['discount','administrative_discount','estimated_fiscal_discount'],['taxes','administrative_tax_total','estimated_fiscal_tax_total'],['total','administrative_total','estimated_fiscal_total'],['paid','payment_total_snapshot','payment_total_snapshot'],['balance','previous_balance','estimated_balance']]as$row){?><tr><td><?php echo app_lang($row[0]); ?></td><td><?php echo to_currency($simulation[$row[1]]); ?></td><td><?php echo to_currency($simulation[$row[2]]); ?></td></tr><?php } ?></tbody></table></div>
<div class="alert <?php echo $simulation['requires_confirmation']?'alert-warning':'alert-success'; ?>"><strong><?php echo app_lang('economic_difference'); ?>:</strong> <?php echo to_currency($simulation['difference_amount']); ?><?php if($simulation['requires_confirmation']){?><br><?php echo app_lang('sale_tax_adjustment_warning'); ?><?php } ?></div>
<?php foreach($simulation['errors']as$error){?><div class="alert alert-danger"><?php echo htmlspecialchars($error); ?></div><?php }foreach($simulation['warnings']as$warning){?><div class="alert alert-warning"><?php echo htmlspecialchars($warning); ?></div><?php } ?>
<?php if($simulation['requires_confirmation']&&$can_apply){echo form_open(get_uri('fiscal/invoices/pricing/apply'),['id'=>'apply-pricing-form','class'=>'general-form']);?><input type="hidden" name="invoice_id" value="<?php echo$review['invoice_id']; ?>"><input type="hidden" name="preparation_id" value="<?php echo$simulation['id']; ?>"><div class="form-check mb10"><?php echo form_checkbox('confirm_adjustment','1',false,"id='confirm-adjustment' class='form-check-input'"); ?><label for="confirm-adjustment"><?php echo app_lang('confirm_sale_tax_adjustment'); ?></label></div><button type="submit" class="btn btn-warning"><?php echo app_lang('apply_taxes_to_sale'); ?></button><?php echo form_close(); }} ?>
<?php if($review['series']['preview']){?><div class="alert alert-light mt15"><strong><?php echo app_lang('next_folio'); ?>:</strong> <?php echo htmlspecialchars($review['series']['preview']['series'].' '.$review['series']['preview']['folio']); ?><br><small><?php echo app_lang('preview_does_not_consume_folio'); ?></small></div><?php } ?>
<?php if($simulation&&$review['is_ready']&&empty($simulation['errors'])&&($can_generate||$can_create_draft)){echo form_open(get_uri('fiscal/invoices/'.$review['invoice_id'].'/generate'),['id'=>'generate-fiscal-invoice-form','class'=>'general-form']);echo csrf_field();?>
<hr><h5><?php echo app_lang('generate_invoice'); ?></h5>
<input type="hidden" name="invoice_id" value="<?php echo$review['invoice_id']; ?>"><input type="hidden" name="issuer_profile_id" value="<?php echo$review['issuer']['issuer_profile_id']; ?>"><input type="hidden" name="receiver_profile_id" value="<?php echo$review['receiver']['profile_id']; ?>"><input type="hidden" name="series_id" value="<?php echo$review['series']['series_id']; ?>"><input type="hidden" name="preparation_id" value="<?php echo$simulation['id']; ?>">
<?php if(!empty($payment_suggestion['warning'])){?><div class="alert alert-warning"><?php echo htmlspecialchars($payment_suggestion['warning']); ?></div><?php } ?><div class="alert alert-info"><?php echo app_lang('payment_sat_suggestion_help'); ?></div>
<div class="row"><div class="col-md-4"><label><?php echo app_lang('sat_payment_form'); ?></label><?php echo form_dropdown('payment_form_code',[''=>'-']+$payment_forms,$payment_suggestion['payment_form_code']??'',"class='select2 form-control' required"); ?></div><div class="col-md-4"><label><?php echo app_lang('sat_payment_method'); ?></label><?php echo form_dropdown('payment_method_code',[''=>'-']+$payment_methods,$payment_suggestion['payment_method_code']??'',"class='select2 form-control' required"); ?></div><div class="col-md-4"><label><?php echo app_lang('currency'); ?></label><?php echo form_dropdown('currency_code',[''=>'-']+$currencies,$review['sale']['currency']?:'MXN',"class='select2 form-control' required"); ?></div></div>
<div class="form-group mt10"><label><?php echo app_lang('exchange_rate'); ?></label><input type="text" class="form-control" name="exchange_rate" inputmode="decimal"><small><?php echo app_lang('exchange_rate_help'); ?></small></div>
<div class="form-check mb10"><?php echo form_checkbox('confirm_new_version','1',false,"id='confirm-new-version' class='form-check-input'"); ?><label for="confirm-new-version"><?php echo app_lang('confirm_new_fiscal_version'); ?></label></div>
<?php if($can_generate){?><button type="submit" class="btn btn-success" <?php echo(!$csd_summary['ready']||!$pac_status->configured||$simulation['requires_confirmation'])?'disabled':''; ?>><?php echo app_lang('generate_invoice'); ?></button><?php } ?>
<?php if($can_create_draft){?><button type="button" id="save-fiscal-draft" class="btn btn-default"><?php echo app_lang('save_draft'); ?></button><?php } ?>
<span id="fiscal-generation-progress" class="ms-2 text-info"></span>
<?php echo form_close();} ?>
<?php if($can_advanced&&$can_view_drafts&&$drafts){?><details class="mt20"><summary><?php echo app_lang('advanced_fiscal_tools'); ?></summary><h5 class="mt15"><?php echo app_lang('fiscal_preparations'); ?></h5><div class="table-responsive"><table class="table table-bordered"><thead><tr><th><?php echo app_lang('series'); ?></th><th><?php echo app_lang('folio'); ?></th><th><?php echo app_lang('date'); ?></th><th><?php echo app_lang('total'); ?></th><th><?php echo app_lang('status'); ?></th><th></th></tr></thead><tbody><?php foreach($drafts as$d){?><tr><td><?php echo htmlspecialchars($d->series); ?></td><td><?php echo$d->folio; ?></td><td><?php echo format_to_datetime($d->issue_date); ?></td><td><?php echo to_currency($d->total); ?></td><td><?php echo app_lang('fiscal_draft_status_'.$d->status); ?></td><td><?php echo js_anchor(app_lang('view'),['class'=>'btn btn-default btn-sm fiscal-draft-view','data-action-url'=>url_to('fiscal_invoice_draft_view',$d->id),'data-fiscal-document-id'=>(int)$d->id,'title'=>app_lang('view_fiscal_draft')]); ?></td></tr><?php } ?></tbody></table></div></details><?php } ?>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang('cancel'); ?></button></div>
<script>$(document).ready(function(){var container=$('#ajaxModalContent'),form=$('#generate-fiscal-invoice-form'),progress=$('#fiscal-generation-progress'),loadView=function(url){$.ajax({url:url,type:'GET',data:{ajaxModal:1},success:function(html){container.html(html);},error:function(){appAlert.error('<?php echo addslashes(app_lang('something_went_wrong')); ?>');}});};$('#fiscal-sale-review-form .select2,#generate-fiscal-invoice-form .select2').select2();$('#fiscal-sale-review-form').on('submit',function(e){e.preventDefault();$.post($(this).attr('action'),$(this).serialize(),function(html){container.html(html);});});$('.fiscal-draft-view').on('click',function(e){e.preventDefault();loadView($(this).data('action-url'));return false;});$('#apply-pricing-form').appForm({onSuccess:function(){location.reload();}});form.appForm({closeModalOnSuccess:false,onSubmit:function(){progress.text('<?php echo addslashes(app_lang('processing_invoice')); ?>');form.find('button').prop('disabled',true);},onAjaxSuccess:function(result){if(result.csrf)form.find('input[name="'+result.csrf.name+'"]').val(result.csrf.hash);if(!result.success&&result.status!=='unknown')form.find('button').prop('disabled',false);progress.text(result.message||'');},onSuccess:function(result){appAlert.success(result.message);if(result.view_url)loadView(result.view_url);}});$('#save-fiscal-draft').on('click',function(){var data=form.serializeArray();data.push({name:'confirm_supersede',value:form.find('[name=\"confirm_new_version\"]').is(':checked')?'1':'0'});$.post('<?php echo get_uri('fiscal/invoices/drafts/create'); ?>',data,function(result){if(result.success){appAlert.success(result.message);location.reload();}else appAlert.error(result.message);},'json');});});</script>
