<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require $root.'/tests/bootstrap.php';helper(['general','date_time']);
use App\Services\Fiscal\FiscalStampAdminService;
$pass=$fail=0;$ok=static function(bool $v,string $m)use(&$pass,&$fail){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$pass++:$fail++;};
try{
 $db=require dirname(__DIR__).'/Increment02/isolated_database.php';$issuer=$db->table('fiscal_profiles')->where('profile_type','issuer')->get(1)->getRow();if(!$issuer)throw new RuntimeException('No issuer fixture.');$profileEnv=(string)($issuer->environment??'development');$env=in_array($profileEnv,['development','production'],true)?$profileEnv:'development';$svc=new FiscalStampAdminService($db);
 $before=$db->table('fiscal_stamp_accounts')->where('issuer_profile_id',$issuer->id);if($db->fieldExists('environment','fiscal_stamp_accounts'))$before->where('environment',$env);$account=$before->get(1)->getRow();$balance=(int)($account->available_balance??0);
 $credit=$svc->credit((int)$issuer->id,$env,100,'External admin test','REF-100',bin2hex(random_bytes(16)));$ok($credit->movement_type==='adjustment_credit'&&(int)$credit->available_after===$balance+100,'Agregar 100 crea adjustment_credit y suma saldo.');
 $debit=$svc->debit((int)$issuer->id,$env,10,'External admin test debit','REF-10',bin2hex(random_bytes(16)));$ok($debit->movement_type==='adjustment_debit'&&(int)$debit->available_after===$balance+90,'Quitar 10 crea adjustment_debit y resta saldo.');
 $blocked=false;try{$svc->debit((int)$issuer->id,$env,$balance+91,'Must fail',null,bin2hex(random_bytes(16)));}catch(Throwable){$blocked=true;}$row=$db->table('fiscal_stamp_accounts')->where('id',$debit->stamp_account_id)->get(1)->getRow();$ok($blocked&&(int)$row->available_balance===$balance+90,'Débito superior al saldo se bloquea sin mutación.');
 $movementTable=$db->protectIdentifiers($db->prefixTable('fiscal_stamp_movements'));$db->query("CREATE TRIGGER stamp_admin_test_reject BEFORE INSERT ON {$movementTable} FOR EACH ROW BEGIN IF NEW.reason='FORCE_MOVEMENT_FAILURE' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced movement failure'; END IF; END");$rolledBack=false;try{$svc->credit((int)$issuer->id,$env,7,'FORCE_MOVEMENT_FAILURE',null,bin2hex(random_bytes(16)));}catch(Throwable){$rolledBack=true;}finally{$db->query('DROP TRIGGER IF EXISTS stamp_admin_test_reject');$db->resetTransStatus();}$afterFailure=$db->table('fiscal_stamp_accounts')->where('id',$debit->stamp_account_id)->get(1)->getRow();$ok($rolledBack&&(int)$afterFailure->available_balance===$balance+90,'Si falla el movimiento, la transacción conserva el saldo anterior.');
 $sameId=bin2hex(random_bytes(16));$one=$svc->credit((int)$issuer->id,$env,1,'Idempotent',null,$sameId);$two=$svc->credit((int)$issuer->id,$env,1,'Idempotent',null,$sameId);$ok((int)$one->id===(int)$two->id,'Una misma solicitud no duplica el movimiento.');
 $history=$svc->getHistory((int)$issuer->id);$types=array_column($history,'movement_type');$ok(in_array('adjustment_credit',$types,true)&&in_array('adjustment_debit',$types,true),'Historial expone créditos y débitos.');$ok(!$db->fieldExists('environment','fiscal_stamp_movements')||$credit->environment===$env,'El ajuste se registra en el ambiente fiscal seleccionado.');
 $routes=(string)file_get_contents(APPPATH.'Config/Routes.php');$controller=(string)file_get_contents(APPPATH.'Controllers/Admin/FiscalStampAdmin.php');$view=(string)file_get_contents(APPPATH.'Views/external/fiscal_stamp_admin/index.php');$ok(str_contains($routes,"manage-7f9c2a4d91/adjust")&&str_contains($routes,"['filter' => 'csrf']"),'POST de ajuste tiene filtro CSRF.');$ok(str_contains($controller,"TIMBRES_ADMIN_SECRET")&&str_contains($controller,'hash_equals')&&str_contains($controller,'setStatusCode(404)'),'Secreto ausente/incorrecto se oculta con 404 y comparación constante.');$ok(str_contains($view,'csrf_field()')&&!str_contains($controller,'Security_Controller'),'Vista externa incluye token y no depende del login normal.');$ok(str_contains($controller,"helper(['general', 'date_time'])"),'Controlador externo carga la dependencia temporal del ledger.');$ok(str_contains($view,'position:static')&&!str_contains($view,'overflow:hidden'),'Formulario expande la fila y no queda recortado por overflow.');
}catch(Throwable $e){echo'[FAIL] '.$e->getMessage().PHP_EOL;$fail++;}
echo"\n{$pass} passed, {$fail} failed.\n";exit($fail?1:0);
