<?php echo form_open(get_uri('payment_complements/'.$complement->id.'/cancel/request'),['id'=>'payment-complement-cancel-form','class'=>'general-form']);echo csrf_field(); ?>
<div class="modal-body">
 <dl><dt>UUID</dt><dd><?php echo esc($complement->uuid); ?></dd><dt>Cliente / receptor</dt><dd><?php echo esc($complement->company_name); ?></dd><dt>Fecha de timbrado</dt><dd><?php echo esc($complement->stamp_date?:'-'); ?></dd><dt>Monto del pago</dt><dd><?php echo to_currency($payment->received_amount??$payment->amount??0); ?></dd><dt>Estado fiscal</dt><dd>Timbrado / Vigente</dd></dl>
 <?php if($warning): ?><div class="alert alert-warning"><?php echo esc($warning); ?></div><?php endif; ?>
 <div class="form-group"><label>Motivo de cancelación SAT</label><?php echo form_dropdown('cancellation_reason',$reasons,'',"id='pc-cancellation-reason' class='form-control' required"); ?></div>
 <div class="form-group d-none" id="pc-replacement-group"><label>Folio de sustitución</label><p class="text-muted">El motivo 01 exige el UUID válido del CFDI sustituto.</p><input type="text" class="form-control" name="replacement_uuid" id="pc-replacement-uuid" maxlength="36" pattern="[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}"></div>
 <div class="alert alert-info">La cancelación conserva pago, aplicación administrativa, movimiento financiero, XML, PDF, UUID e historial. Sólo libera el consumo fiscal después de confirmación definitiva.</div>
 <?php if((int)$balance['available']<1): ?><div class="alert alert-danger">No cuenta con timbres suficientes para solicitar la cancelación.</div><?php endif; ?>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cerrar</button><button class="btn btn-danger" <?php echo(int)$balance['available']<1?'disabled':''; ?>>Solicitar cancelación</button></div><?php echo form_close(); ?>
<script>$(function(){var reason=$('#pc-cancellation-reason'),group=$('#pc-replacement-group'),uuid=$('#pc-replacement-uuid');function sync(){var needed=reason.val()==='01';group.toggleClass('d-none',!needed);uuid.prop('required',needed);if(!needed)uuid.val('');}reason.on('change',sync);sync();$('#payment-complement-cancel-form').appForm({closeModalOnSuccess:true,onSuccess:function(r){appAlert.success(r.message);var table=$('#payment-complements-table');if(table.length)table.appTable({reload:true});else location.reload();}});});</script>
