<?php
$isStamped=$complement->status==='stamped';
$cancelRow=$cancellation['complement']??null;
$isFiscalCancelled=$isStamped&&($cancelRow->fiscal_document_status??'')==='cancelled';
$statusLabel=$isFiscalCancelled?'Cancelado fiscalmente':($isStamped?'Timbrado':($complement->status==='complete_draft'?'Borrador completo':'Borrador incompleto'));
$statusColor=$isFiscalCancelled?'secondary':($isStamped?'primary':($complement->status==='complete_draft'?'success':'warning'));
$bankForms=['02','03','04','05','06','28','29'];
$banking=in_array((string)$payment->effective_payment_form,$bankForms,true);
?>
<?php if(!$isStamped && !$candidates && !empty($candidate_empty_reason)): ?>
<div class="alert alert-info mb15"><b>Facturas elegibles:</b> <?php echo esc($candidate_empty_reason); ?></div>
<?php endif; ?>
<div class="page-content invoice-details-view clearfix"><div class="container-fluid">
<div class="page-title clearfix"><h1 class="pull-left"><i data-feather="file-text" class="icon-18"></i> Complemento de Pago #<?php echo (int)$complement->id; ?></h1><div class="title-button-group"><a class="btn btn-default" href="<?php echo site_url('payment_complements'); ?>">Volver al listado</a></div></div>
<div class="details-view-wrapper d-flex"><div class="w-100 pr15">
<div class="card mb15"><div class="card-body"><div class="row">
<div class="col-md-4"><small class="text-muted">Cliente / receptor</small><h4 class="mb5"><?php echo esc($complement->company_name); ?></h4><b>RFC:</b> <?php echo esc($complement->vat_number?:'No registrado'); ?></div>
<div class="col-md-4"><small class="text-muted">Pago administrativo #<?php echo (int)$payment->source_invoice_payment_id; ?></small><div><b>Fecha del pago:</b> <?php echo esc(format_to_date($payment->payment_date,false)); ?></div><div><b>Forma:</b> <?php echo esc($payment->payment_method?:'Sin forma'); ?></div><div><b>Cuenta destino:</b> <?php echo esc($payment->account_name?:'Sin cuenta'); ?></div><div><b>Referencia:</b> <?php echo esc($payment->payment_reference?:'-'); ?></div><div><b>Monto:</b> <?php echo to_currency($summary['received']); ?></div></div>
<div class="col-md-4"><small class="text-muted">Complemento</small><div><span class="badge bg-<?php echo $statusColor; ?>"><?php echo $statusLabel; ?></span></div><div class="mt10"><b>Fecha:</b> <?php echo esc(format_to_datetime($complement->issue_date)); ?></div><?php if($stamp): ?><div><b>UUID:</b> <code><?php echo esc($stamp->uuid); ?></code></div><div><b>Fecha timbrado:</b> <?php echo esc(format_to_datetime($stamp->stamp_date)); ?></div><?php endif; ?><div><b>Monto incluido:</b> <?php echo to_currency($summary['included']); ?></div><div><b>Saldo disponible:</b> <?php echo to_currency($summary['remaining']); ?></div></div>
</div></div></div>

<?php if($isStamped): ?><div class="card mb15"><div class="card-header fw-bold">Cancelación fiscal</div><div class="card-body"><dl class="row mb0"><dt class="col-md-3">Estado</dt><dd class="col-md-9"><?php echo esc(match($cancelRow->cancellation_status??''){'sending','pending','unknown'=>'En proceso','accepted'=>'Cancelado','rejected','transport_not_sent'=>'Solicitud rechazada',default=>'No solicitada'}); ?></dd><?php if($cancelRow&&$cancelRow->cancellation_request_id): ?><dt class="col-md-3">Motivo SAT</dt><dd class="col-md-9"><?php echo esc($cancelRow->cancellation_reason?:'-'); ?></dd><dt class="col-md-3">UUID sustitución</dt><dd class="col-md-9"><?php echo esc($cancelRow->replacement_uuid?:'-'); ?></dd><dt class="col-md-3">Fecha solicitud</dt><dd class="col-md-9"><?php echo esc($cancelRow->requested_at?:'-'); ?></dd><dt class="col-md-3">Fecha confirmación</dt><dd class="col-md-9"><?php echo esc($cancelRow->fiscal_cancelled_at?:$cancelRow->confirmed_at?:'-'); ?></dd><dt class="col-md-3">Respuesta PAC/SAT</dt><dd class="col-md-9"><?php echo esc(trim(($cancelRow->provider_code?:'').' '.($cancelRow->provider_message?:''))?:'-'); ?></dd><?php endif; ?></dl><?php if(!empty($cancellation['warning'])): ?><div class="alert alert-warning mt10 mb0"><?php echo esc($cancellation['warning']); ?></div><?php endif; ?></div></div><?php endif; ?>

<?php if(!$isStamped): ?>
<?php echo form_open('payment_complements/'.$complement->id.'/details',['id'=>'complement-fiscal-details','class'=>'general-form']); ?><?php echo csrf_field(); ?>
<div class="card mb15"><div class="card-header fw-bold">Información fiscal del complemento</div><div class="card-body"><div class="row">
<div class="col-md-4"><label>Fecha del complemento</label><input type="datetime-local" name="issue_date" class="form-control" value="<?php echo esc($issue_date_input); ?>" min="<?php echo esc($issue_date_constraints['min_issue_datetime']); ?>" <?php echo $issue_date_constraints['max_issue_datetime']!==''?'max="'.esc($issue_date_constraints['max_issue_datetime']).'"':''; ?> required><small><?php echo esc($issue_date_constraints['validation_message']); ?></small></div>
<div class="col-md-4"><label>Fecha del pago</label><input class="form-control" value="<?php echo esc(format_to_date($payment->payment_date,false)); ?>" readonly><small>Proviene del pago administrativo y no se modifica aquí.</small></div>
<div class="col-md-4"><label>Forma de pago SAT</label><select id="payment-form-code" name="payment_form_code" class="form-control select2" required><option value="">Seleccione...</option><?php foreach($sat_payment_forms as$form): ?><option value="<?php echo esc($form->code); ?>" <?php echo $payment->effective_payment_form===$form->code?'selected':''; ?>><?php echo esc($form->code.' - '.$form->name); ?></option><?php endforeach; ?></select><small>El mapeo administrativo sólo propone el valor inicial; la selección guardada prevalece.</small></div>
</div><div id="bank-not-applicable" class="alert alert-info mt15 mb0 <?php echo $banking?'hide':''; ?>">La información bancaria no aplica para esta Forma de pago SAT.</div>
<div id="complement-bank-section" class="mt20 <?php echo $banking?'':'hide'; ?>"><hr><h5>Información bancaria</h5><div class="row">
<?php foreach(['ordering_bank_rfc'=>'RFC banco ordenante (RfcEmisorCtaOrd)','ordering_bank_name'=>'Banco ordenante extranjero','ordering_account'=>'Cuenta ordenante','beneficiary_bank_rfc'=>'RFC banco beneficiario','beneficiary_account'=>'Cuenta beneficiaria'] as$name=>$label): ?><div class="col-md-4"><label><?php echo $label; ?></label><input name="<?php echo $name; ?>" value="<?php echo esc($payment->$name??''); ?>" class="form-control"></div><?php endforeach; ?>
<div class="col-md-4"><label>TipoCadPago</label><input name="payment_chain_type" maxlength="2" value="<?php echo esc($payment->payment_chain_type??''); ?>" class="form-control"></div><div class="col-md-4"><label>CertPago</label><textarea name="payment_certificate" class="form-control" rows="2"><?php echo esc($payment->payment_certificate??''); ?></textarea></div><div class="col-md-4"><label>CadPago</label><textarea name="payment_chain" class="form-control" rows="2"><?php echo esc($payment->payment_chain??''); ?></textarea></div><div class="col-md-4"><label>SelloPago</label><textarea name="payment_signature" class="form-control" rows="2"><?php echo esc($payment->payment_signature??''); ?></textarea></div>
</div></div><span class="hide">no aplica para la FormaDePagoP actual</span><div class="text-end mt15"><button class="btn btn-primary" type="submit">Guardar información fiscal</button></div></div></div><?php echo form_close(); ?>
<?php else: ?><div class="alert alert-info">El Complemento timbrado es inmutable y se muestra en modo de sólo lectura.</div><?php endif; ?>

<div class="card mb15"><div class="card-header fw-bold">Resumen</div><div class="card-body"><div class="row text-center"><?php foreach(['Pago administrativo'=>'received','Aplicado administrativamente'=>'administrative_applied','Disponible administrativo'=>'administrative_available','Aplicado en este complemento'=>'included','Disponible fiscal para aplicar'=>'remaining'] as$label=>$key): ?><div class="col"><small><?php echo $label; ?></small><h5><?php echo to_currency($summary[$key]); ?></h5></div><?php endforeach; ?></div></div></div>

<?php if(!$isStamped): ?><div class="card mb15"><div class="card-header fw-bold">Facturas elegibles</div><div class="card-body"><?php if($candidates): ?><?php echo form_open('payment_complements/'.$complement->id.'/documents',['id'=>'add-complement-document-form','class'=>'general-form']); ?><?php echo csrf_field(); ?><div class="row"><div class="col-md-8"><select id="complement-fiscal-document" name="fiscal_document_id" class="form-control select2" required><option value="">Buscar factura PPD del cliente...</option><?php foreach($candidates as$c): ?><option value="<?php echo (int)$c->fiscal_document_id; ?>" data-maximum="<?php echo esc($c->fiscal_available); ?>"><?php echo esc(trim($c->series.' '.$c->folio).' · '.substr($c->uuid,0,8).'… · Total CFDI '.to_currency($c->fiscal_total).' · Pagado fiscal '.to_currency($c->prior_fiscal_paid).' · Saldo fiscal '.to_currency($c->fiscal_outstanding).' · Disponible '.to_currency($c->fiscal_available)); ?></option><?php endforeach; ?></select></div><div class="col-md-2"><input id="complement-amount-paid" name="amount_paid" class="form-control" inputmode="decimal" placeholder="Importe a aplicar" required></div><div class="col-md-2"><button class="btn btn-primary w-100" type="submit">Agregar</button></div></div><?php echo form_close(); ?><?php else: ?><div class="text-muted">No hay más facturas PPD elegibles.</div><?php endif; ?></div></div><?php endif; ?>

<div class="card"><div class="card-header fw-bold">CFDI relacionados</div><div class="card-body p0"><?php if(!$documents): ?><div class="p20 text-muted">No hay facturas agregadas al complemento.</div><?php else: ?><div class="table-responsive"><table class="table table-hover mb0"><thead><tr><th>Factura / UUID</th><th>Parcialidad</th><th class="text-end">Saldo anterior</th><th class="text-end">Pagado</th><th class="text-end">Insoluto</th><th>Impuestos</th><th></th></tr></thead><tbody><?php foreach($documents as$d): ?><tr><td><b><?php echo esc(trim($d->series.' '.$d->folio)); ?></b><br><code><?php echo esc($d->document_uuid); ?></code></td><td><?php echo (int)$d->installment_number; ?></td><td class="text-end"><?php echo to_currency($d->previous_balance); ?></td><td class="text-end"><?php echo to_currency($d->amount_paid); ?></td><td class="text-end"><?php echo to_currency($d->remaining_balance); ?></td><td>ObjetoImpDR <?php echo esc($d->tax_object_code_derived?:'?'); ?><br><a href="#" data-bs-toggle="collapse" data-bs-target="#tax-<?php echo (int)$d->id; ?>">Ver impuestos</a></td><td><?php if(!$isStamped): ?><?php echo form_open('payment_complements/'.$complement->id.'/documents/'.$d->id.'/remove',['class'=>'remove-complement-document-form']); ?><?php echo csrf_field(); ?><button class="btn btn-danger btn-sm">Quitar</button><?php echo form_close(); ?><?php endif; ?></td></tr><tr class="collapse" id="tax-<?php echo (int)$d->id; ?>"><td colspan="7"><div class="p10"><?php if(!empty($d->tax_error)): ?><span class="text-danger"><?php echo esc($d->tax_error); ?></span><?php elseif(!$d->tax_details): ?>Sin impuestos trasladados o retenidos.<?php else: ?><?php foreach($d->tax_details as$t): ?><div><?php echo esc($t['tax_type']==='withholding'?'Retención':'Traslado'); ?> · <?php echo esc($t['tax_code'].' '.$t['factor_type']); ?> · BaseDR <?php echo to_currency($t['base']); ?> · ImporteDR <?php echo to_currency($t['amount']); ?></div><?php endforeach; ?><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>
</div>

<div class="flex-shrink-0 details-view-right-section"><div class="card"><div class="card-header fw-bold">Acciones</div><div class="card-body">
<?php echo modal_anchor(get_uri('payment_complements/review/'.$complement->id),'Revisión fiscal',['class'=>'btn btn-default w-100 mb10','title'=>'Revisión fiscal','data-action-method'=>'GET','data-modal-lg'=>'1']); ?>
<?php echo modal_anchor(get_uri('payment_complements/preview/'.$complement->id),'Vista previa',['class'=>'btn btn-primary w-100 mb10','title'=>'Vista previa del Complemento','data-action-method'=>'GET','data-modal-lg'=>'1']); ?>
<?php if($isStamped&&$complement->fiscal_document_id): ?><a class="btn btn-default w-100 mb10" target="_blank" href="<?php echo get_uri('fiscal/stamping/xml/view/'.$complement->fiscal_document_id); ?>">Ver XML</a><a class="btn btn-default w-100 mb10" href="<?php echo get_uri('fiscal/stamping/xml/download/'.$complement->fiscal_document_id); ?>">Descargar XML</a><?php if(($stamp->pdf_status??'')==='valid'): ?><a class="btn btn-default w-100 mb10" target="_blank" href="<?php echo get_uri('fiscal/documents/'.$complement->fiscal_document_id.'/pdf/preview'); ?>">Ver PDF</a><a class="btn btn-default w-100 mb10" href="<?php echo get_uri('fiscal/documents/'.$complement->fiscal_document_id.'/pdf/download'); ?>">Descargar PDF</a><?php else: ?><div class="alert alert-warning p10">El XML está timbrado; el PDF permanece pendiente.</div><?php endif; ?><?php if(!empty($can_regenerate_pdf)&&!empty($stamp->uuid)&&!empty($stamp->stamped_xml_artifact_id)){try{$pdfTemplate=(new \App\Services\Fiscal\Pdf\FiscalPdfTemplateResolver())->resolve((int)$complement->issuer_profile_id,(string)config('FiscalPdfProvider')->provider,'P')->templateCode;}catch(\Throwable){$pdfTemplate='-';}echo js_anchor('Regenerar PDF',['class'=>'btn btn-warning w-100 mb10 fiscal-regenerate-pdf','data-document-id'=>$complement->fiscal_document_id,'data-document-label'=>'Complemento #'.$complement->id,'data-uuid'=>$stamp->uuid,'data-template'=>$pdfTemplate]);} ?><?php if((!$cancelRow->cancellation_request_id||in_array($cancelRow->cancellation_status??'',['rejected','transport_not_sent'],true))&&$can_cancel&&!$isFiscalCancelled): ?><?php echo modal_anchor(get_uri('payment_complements/cancel/form'),'Cancelar',['class'=>'btn btn-danger w-100 mb10','title'=>'Cancelar Complemento de Pago','data-post-complement_id'=>$complement->id]); ?><?php elseif(in_array($cancelRow->cancellation_status??'',['sending','pending','unknown'],true)&&$can_check_cancellation): ?><?php echo modal_anchor(get_uri('payment_complements/cancel/status/form'),'Verificar cancelación',['class'=>'btn btn-warning w-100 mb10','title'=>'Verificar cancelación','data-post-complement_id'=>$complement->id]); ?><?php elseif(($cancelRow->cancellation_status??'')==='accepted'&&$can_view_cancellation_receipt): ?><a class="btn btn-default w-100 mb10" href="<?php echo get_uri('payment_complements/'.$complement->id.'/cancel/receipt/'.$cancelRow->cancellation_request_id); ?>">Descargar acuse</a><?php endif; ?>
<?php elseif($can_stamp): ?><div class="alert alert-<?php echo $pac_environment==='sandbox'?'warning':'danger'; ?> p10"><b>PAC:</b> <?php echo $pac_environment==='sandbox'?'Ambiente de pruebas':'Ambiente configurado: '.esc($pac_environment); ?></div><button id="open-stamp-confirmation" class="btn btn-success w-100 mb10" type="button" <?php echo empty($readiness['ready'])?'disabled':''; ?>>Timbrar complemento</button><?php if(empty($readiness['ready'])): ?><small class="text-danger">La revisión fiscal contiene bloqueantes.</small><?php endif; ?><?php endif; ?>
<?php if(!$isStamped): ?><hr><?php echo form_open('payment_complements/'.$complement->id.'/discard',['id'=>'discard-form']); ?><?php echo csrf_field(); ?><label>Motivo para descartar</label><textarea name="reason" class="form-control mb10" required></textarea><button class="btn btn-danger w-100">Descartar borrador</button><?php echo form_close(); ?><?php endif; ?>
</div></div></div></div></div></div>

<div class="modal fade" id="stamp-confirmation" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Timbrar Complemento de Pago</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">¿Desea timbrar este Complemento de Pago?<br><br>Una vez timbrado no podrá modificar fecha, Forma de pago SAT, datos bancarios, facturas, importes, parcialidades, saldos ni impuestos.</div><div class="modal-footer"><button class="btn btn-default" data-bs-dismiss="modal">Cancelar</button><button id="confirm-stamp" class="btn btn-success">Sí, timbrar</button></div></div></div></div>
<script>$(function(){var bankForms=<?php echo json_encode($bankForms); ?>;$('.select2').select2();$('#payment-form-code').on('change',function(){var applies=bankForms.indexOf($(this).val())!==-1;$('#complement-bank-section').toggleClass('hide',!applies);$('#bank-not-applicable').toggleClass('hide',applies);});$('#complement-fiscal-document').on('change',function(){var max=$(this).find(':selected').data('maximum')||'';$('#complement-amount-paid').val(max).attr('max',max);});$('#complement-fiscal-details,#add-complement-document-form,.remove-complement-document-form').each(function(){$(this).appForm({isModal:false,onSuccess:function(){location.reload();}});});$('#discard-form').appForm({isModal:false,onSuccess:function(r){window.location.href=r.redirect_to;}});$('#open-stamp-confirmation').on('click',function(){new bootstrap.Modal(document.getElementById('stamp-confirmation')).show();});$('#confirm-stamp').on('click',function(){var b=$(this);if(b.prop('disabled'))return;b.prop('disabled',true).text('Timbrando…');$.ajax({url:'<?php echo get_uri('payment_complements/'.$complement->id.'/stamp'); ?>',type:'POST',data:{'<?php echo csrf_token(); ?>':'<?php echo csrf_hash(); ?>'},success:function(r){appAlert.success(r.message,{duration:5000});location.reload();},error:function(x){var r=x.responseJSON||{};appAlert.error(r.message||'El PAC rechazó el Complemento.');b.prop('disabled',false).text('Sí, timbrar');}});});});</script>

<?php if(!empty($can_regenerate_pdf)){ echo view('fiscal/pdf_regeneration_modal',['configure_pdf_allowed'=>(bool)($configure_pdf_allowed??false)]); } ?>
