<div class="modal-body">
    <p class="text-muted">Validación de sólo lectura. Cerrar esta ventana conserva el generador.</p>
    <div class="alert alert-<?php echo $ready ? 'success' : 'danger'; ?>"><strong><?php echo $ready ? 'Documento listo para timbrar.' : 'Documento NO listo para timbrar.'; ?></strong><?php if (!$ready): ?> Corrija los bloqueantes indicados antes de generar el CFDI.<?php endif; ?></div>
    <?php if ($preview): ?><div class="row mb15"><div class="col-md-6"><b>Emisor</b><br><?php echo esc($preview['issuer']['legal_name']); ?><br>RFC <?php echo esc($preview['issuer']['rfc']); ?></div><div class="col-md-6"><b>Receptor</b><br><?php echo esc($preview['receiver']['legal_name']); ?><br>RFC <?php echo esc($preview['receiver']['rfc']); ?></div></div><?php endif; ?>
    <?php foreach (['general'=>'Datos generales','documents'=>'Documentos relacionados','taxes'=>'Impuestos','banking'=>'Información bancaria','totals'=>'Totales Pago 2.0'] as $key=>$title): ?>
        <h5 class="mt20"><?php echo esc($title); ?></h5><div class="list-group">
        <?php foreach ($readiness['checks'] as $check): if (($check['section'] ?? 'general') !== $key) continue; ?><div class="list-group-item"><div class="d-flex justify-content-between"><b><?php echo esc($check['label']); ?></b><span class="badge bg-<?php echo $check['severity']==='correct'?'success':($check['severity']==='warning'?'warning':'danger'); ?>"><?php echo $check['severity']==='correct'?'Correcto':($check['severity']==='warning'?'Advertencia':'Bloqueante'); ?></span></div><div><?php echo esc($check['detail']); ?></div><?php if (!empty($check['resolution']) && $check['severity'] !== 'correct'): ?><small class="text-muted"><b>Cómo resolver:</b> <?php echo esc($check['resolution']); ?></small><?php endif; ?></div><?php endforeach; ?>
        </div>
    <?php endforeach; ?>
    <?php if ($preview): ?><h5 class="mt20">Totales Pago 2.0</h5><table class="table table-sm"><?php foreach ($preview['sat_totals'] as $name=>$value): ?><tr><td><?php echo esc($name); ?></td><td class="text-end"><?php echo to_currency($value); ?></td></tr><?php endforeach; ?></table><?php elseif (!empty($preview_error)): ?><div class="alert alert-danger mt15"><?php echo esc($preview_error); ?></div><?php endif; ?>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cerrar</button></div>
