<?php
$editing = !empty($draft);
$selected = array_map(static fn($row)=>(int)$row['sale']->id,$sales);
$saved = []; $savedSnapshots=[]; foreach($saved_items as$item){$saved[(int)$item->sale_item_id]=(string)$item->quantity;$savedSnapshots[(int)$item->sale_item_id]=json_decode((string)$item->fiscal_snapshot,true)?:[];}
$zone=new DateTimeZone($issue_date_constraints['timezone']);
$issue = $editing ? (new \App\Services\Fiscal\FiscalIssueDateNormalizer())->formatForInput((string)$draft->issue_date) : (new DateTimeImmutable('now',$zone))->format('Y-m-d\TH:i');
$receiverProfile = $receiver;
$action = $editing ? get_uri('fiscal/drafts/'.$draft->id) : get_uri('fiscal/drafts');
$selectedUse=$editing?(string)$draft->cfdi_use_code:(string)(($receiverProfile?->default_cfdi_use_id??0)?((array_values(array_filter($cfdi_uses,fn($r)=>(int)$r->id===(int)$receiverProfile->default_cfdi_use_id))[0]->code??'')):'');
$selectedMethod=$editing?(string)$draft->payment_method_code:(string)($payment_suggestion['payment_method_code']??'');
$selectedForm=$editing?(string)$draft->payment_form_code:(string)($payment_suggestion['payment_form_code']??'');
$selectedIssuerId=(int)($issuer->id??0);
?>
<div class="page-title clearfix"><h1><?php echo $editing?'Revisión fiscal · borrador #'.$draft->id:'Revisión fiscal'; ?></h1></div>
<div class="card"><div class="card-body">
<div class="alert alert-info">La venta comercial permanece cerrada e inmutable. Aquí sólo se editan los datos del CFDI y su snapshot fiscal. Guardar no llama al PAC.</div>
<?php echo form_open($action,['id'=>'fiscal-draft-form','class'=>'general-form']); echo csrf_field(); ?>
<input type="hidden" name="save_as_draft" value="1">
<h4>Estado de la revisión</h4>
<?php $blockers=[];if(!$issuer)$blockers[]='Falta emisor fiscal.';if(!$receiverProfile)$blockers[]='Falta configuración fiscal del receptor.';if(!$selectedUse)$blockers[]='Falta Uso CFDI.';if(!$selectedMethod)$blockers[]='Falta Método de pago.';if(!$selectedForm)$blockers[]='Falta Forma de pago.';if($blockers){?><div class="alert alert-warning"><strong>No lista</strong><ul><?php foreach($blockers as$b){?><li><?php echo esc($b);?></li><?php }?></ul></div><?php }else{?><div class="alert alert-success"><strong>Lista para prefactura</strong> · Revisión fiscal completa.</div><?php }?>
<h4>Ventas y asignaciones</h4>
<div class="alert alert-light"><strong>Comparación:</strong> Venta comercial vs CFDI propuesto. En precios con impuestos incluidos, separar base e IVA conservando el total es <strong>INFO</strong>; una diferencia que no conserve el total es <strong>ERROR</strong> y bloquea ready.</div>
<?php foreach($compatible_sales as$entry){$sale=$entry['sale'];$checked=in_array((int)$sale->id,$selected,true); ?>
<div class="border rounded p-3 mb10 sale-block" data-sale="<?php echo(int)$sale->id; ?>">
    <label class="fw-bold"><input type="checkbox" name="sale_ids[]" value="<?php echo(int)$sale->id; ?>" <?php echo$checked?'checked':''; ?>> Venta <?php echo esc($sale->display_id?:'#'.$sale->id); ?></label>
    <span class="ms-3">Total: <?php echo to_currency($sale->invoice_total); ?></span>
    <span class="ms-3">Disponible: <?php echo to_currency($entry['available']); ?></span>
    <table class="table table-sm mt10"><thead><tr><th>Descripción fiscal</th><th>Clave SAT</th><th>Cantidad</th><th>Clave unidad</th><th>Valor unitario</th><th>Objeto impuesto</th><th></th></tr></thead><tbody>
    <?php foreach($entry['items']as$item){$snap=$savedSnapshots[$item->id]??[];$desc=$snap['fiscal_description']??$item->fiscal_description??$item->description??$item->title;$prod=$snap['product_service_code']??$item->product_service_code??'';$unit=$snap['unit_code']??$item->unit_code??'';$object=$snap['tax_object_code']??$item->tax_object_code??''; ?><tr><td><?php echo esc($desc?:'Pendiente'); ?></td><td><?php echo esc($prod?:'Pendiente'); ?></td><td><?php echo esc($saved[$item->id]??($checked?$item->quantity:'0')); ?><input type="hidden" name="quantities[<?php echo$item->id; ?>]" value="<?php echo esc($saved[$item->id]??($checked?$item->quantity:'0')); ?>"></td><td><?php echo esc($unit?:'Pendiente'); ?></td><td><?php echo to_currency($item->rate); ?></td><td><?php echo esc($object?:'Pendiente'); ?></td><td><button type="button" class="btn btn-default btn-sm fiscal-item-edit" data-target="fiscal-item-<?php echo$item->id; ?>">Editar datos fiscales</button></td></tr><tr id="fiscal-item-<?php echo$item->id; ?>" class="fiscal-item-editor d-none"><td colspan="7"><div class="alert alert-info">Sólo actualiza el snapshot fiscal; no modifica invoice_items, cantidad, precio, descuento ni total comercial.</div><div class="row g-2"><div class="col-md-4"><label>Descripción fiscal</label><input class="form-control" name="fiscal_items[<?php echo$item->id; ?>][fiscal_description]" value="<?php echo esc($desc); ?>"></div><div class="col-md-2"><label>Clave producto SAT</label><input class="form-control" name="fiscal_items[<?php echo$item->id; ?>][product_service_code]" value="<?php echo esc($prod); ?>"></div><div class="col-md-2"><label>Clave unidad SAT</label><input class="form-control" name="fiscal_items[<?php echo$item->id; ?>][unit_code]" value="<?php echo esc($unit); ?>"></div><div class="col-md-2"><label>Unidad</label><input class="form-control" name="fiscal_items[<?php echo$item->id; ?>][commercial_unit]" value="<?php echo esc($snap['commercial_unit']??$item->unit_type); ?>"></div><div class="col-md-2"><label>Objeto impuesto</label><select class="form-control" name="fiscal_items[<?php echo$item->id; ?>][tax_object_code]"><option value="">Seleccionar</option><?php foreach($tax_object_codes as$row){?><option value="<?php echo esc($row->code);?>" <?php echo$object===$row->code?'selected':'';?>><?php echo esc($row->code.' · '.$row->description);?></option><?php }?></select></div></div><small>Base, tasa/cuota, importe e impuestos se regeneran con FiscalDecimal y fiscal_draft_item_taxes al guardar.</small></td></tr><?php } ?>
    </tbody></table>
    <table class="table table-sm table-bordered fiscal-tax-detail"><thead><tr><th>Concepto</th><th>Unidad</th><th>Base</th><th>Impuesto</th><th>Tasa/cuota</th><th>Importe impuesto</th><th>Importe concepto</th></tr></thead><tbody><?php foreach($entry['items'] as $item){$snap=$savedSnapshots[$item->id]??[];$tax=$snap['taxes'][0]??[];?><tr><td><?php echo esc($snap['fiscal_description']??$item->fiscal_description??$item->description??$item->title);?></td><td><?php echo esc($snap['commercial_unit']??$item->unit_type??'Pendiente');?></td><td><?php echo esc($snap['taxable_base']??'Se calcula al guardar');?></td><td><?php echo esc($tax['tax_code']??'Pendiente');?></td><td><?php echo esc($tax['rate_or_quota']??'Pendiente');?></td><td><?php echo esc($tax['amount']??'Se calcula al guardar');?></td><td><?php echo esc($snap['line_total']??'Se calcula al guardar');?></td></tr><tr><td colspan="7"><div class="row g-2"><div class="col-md-2"><label>Tipo</label><select class="form-control" name="fiscal_items[<?php echo$item->id;?>][taxes][0][tax_type]"><option value="transfer" <?php echo($tax['tax_type']??'transfer')==='transfer'?'selected':'';?>>Traslado</option><option value="withholding" <?php echo($tax['tax_type']??'')==='withholding'?'selected':'';?>>Retención</option></select></div><div class="col-md-3"><label>Impuesto SAT</label><select class="form-control" name="fiscal_items[<?php echo$item->id;?>][taxes][0][tax_code]"><option value="">Seleccionar</option><?php foreach($tax_codes as$code){?><option value="<?php echo esc($code->code);?>" <?php echo($tax['tax_code']??'')===$code->code?'selected':'';?>><?php echo esc($code->code.' · '.$code->description);?></option><?php }?></select></div><div class="col-md-3"><label>Factor</label><select class="form-control" name="fiscal_items[<?php echo$item->id;?>][taxes][0][factor_type]"><?php foreach(['Tasa','Cuota','Exento']as$factor){?><option value="<?php echo$factor;?>" <?php echo($tax['factor_type']??'Tasa')===$factor?'selected':'';?>><?php echo$factor;?></option><?php }?></select></div><div class="col-md-4"><label>Tasa/cuota</label><input class="form-control" name="fiscal_items[<?php echo$item->id;?>][taxes][0][rate_or_quota]" value="<?php echo esc($tax['rate_or_quota']??'0.160000');?>" inputmode="decimal"></div></div><small>Esta configuración sólo se persiste en el snapshot fiscal v2.</small></td></tr><?php }?></tbody></table>
</div><?php } ?>
<h4 class="mt20">Datos del CFDI</h4>
<div class="row g-2">
 <div class="col-md-4"><label>Emisor</label><select name="issuer_id" id="fiscal-issuer" class="form-control"><?php foreach($issuers as$candidate){ ?><option value="<?php echo (int)$candidate->id; ?>" data-rfc="<?php echo esc($candidate->rfc); ?>" data-legal="<?php echo esc($candidate->legal_name); ?>" data-regime="<?php echo esc(($candidate->tax_regime_code??'').' · '.($candidate->tax_regime_description??'')); ?>" data-cp="<?php echo esc($candidate->expedition_postal_code??$candidate->fiscal_postal_code??''); ?>" data-csd="<?php echo esc($candidate->certificate_number??''); ?>" <?php echo $selectedIssuerId===(int)$candidate->id?'selected':''; ?>><?php echo esc($candidate->legal_name.' · '.$candidate->rfc); ?></option><?php } ?></select></div>
 <div class="col-md-2"><label>Serie</label><select name="fiscal_series_id" id="fiscal-series" class="form-control"><?php foreach($series as$s){ ?><option value="<?php echo$s->id; ?>" data-issuer="<?php echo (int)$s->issuer_profile_id; ?>" <?php echo($editing&&(int)$draft->fiscal_series_id===(int)$s->id)?'selected':''; ?>><?php echo esc($s->series); ?></option><?php } ?></select><input type="hidden" name="provisional_series" id="provisional-series" value="<?php echo esc($editing?$draft->provisional_series:($series[0]->series??'')); ?>"></div>
 <div class="col-md-3"><label>Fecha de expedición CFDI</label><input type="datetime-local" name="issue_date" class="form-control" value="<?php echo$issue; ?>" min="<?php echo esc($issue_date_constraints['min_issue_datetime']);?>" <?php echo$issue_date_constraints['max_issue_datetime']!==''?'max="'.esc($issue_date_constraints['max_issue_datetime']).'"':'';?> required><small><?php echo esc($issue_date_constraints['validation_message'].' Zona: '.$issue_date_constraints['timezone']);?></small></div>
 <div class="col-md-1"><label>Moneda</label><input name="currency_code" class="form-control" value="<?php echo esc($editing?$draft->currency_code:'MXN'); ?>"></div>
 <div class="col-md-2"><label>Tipo de cambio</label><input name="exchange_rate" class="form-control" value="<?php echo esc($editing?$draft->exchange_rate:'1.000000'); ?>" inputmode="decimal"></div>
</div>
<h4 class="mt20">Datos del emisor</h4>
<div class="row g-2"><div class="col-md-4"><label>Razón social</label><input id="issuer-legal" class="form-control" readonly></div><div class="col-md-2"><label>RFC</label><input id="issuer-rfc" class="form-control" readonly></div><div class="col-md-2"><label>Régimen</label><input id="issuer-regime" class="form-control" readonly></div><div class="col-md-2"><label>CP expedición</label><input id="issuer-cp" class="form-control" readonly></div><div class="col-md-2"><label>CSD</label><input id="issuer-csd" class="form-control" readonly></div></div>
<div class="row g-2 mt10">
 <div class="col-md-3"><label>Forma de pago</label><select name="payment_form_code" class="form-control"><option value="">Seleccionar</option><?php foreach($payment_forms as$row){ ?><option value="<?php echo$row->code; ?>" <?php echo$selectedForm===$row->code?'selected':''; ?>><?php echo esc($row->code.' · '.$row->name); ?></option><?php } ?></select></div>
 <div class="col-md-3"><label>Método de pago</label><select name="payment_method_code" class="form-control"><option value="">Seleccionar</option><?php foreach($payment_methods as$row){ ?><option value="<?php echo$row->code; ?>" <?php echo$selectedMethod===$row->code?'selected':''; ?>><?php echo esc($row->code.' · '.$row->name); ?></option><?php } ?></select></div>
 <div class="col-md-3"><label>Condiciones</label><input name="conditions" class="form-control" value="<?php echo esc($editing?$draft->conditions:''); ?>"></div>
 <div class="col-md-3"><label>Observaciones</label><input name="observations" class="form-control" value="<?php echo esc($editing?$draft->observations:''); ?>"></div>
</div>
<h4 class="mt20">Receptor</h4>
<input type="hidden" name="receiver_profile_id" value="<?php echo(int)($receiverProfile->id??0); ?>">
<div class="row g-2">
 <div class="col-md-3"><label>Razón social fiscal</label><input class="form-control" value="<?php echo esc($receiverProfile->legal_name??''); ?>" readonly></div>
 <div class="col-md-2"><label>RFC</label><input class="form-control" value="<?php echo esc($receiverProfile->rfc??''); ?>" readonly></div>
 <div class="col-md-2"><label>Código postal fiscal</label><input class="form-control" value="<?php echo esc($receiverProfile->fiscal_postal_code??''); ?>" readonly></div>
 <div class="col-md-2"><label>Régimen fiscal</label><input class="form-control" value="<?php $match=array_values(array_filter($tax_regimes,fn($r)=>(int)$r->id===(int)($receiverProfile->tax_regime_id??0)));echo esc(($match[0]->code??'').' · '.($match[0]->description??'')); ?>" readonly></div>
 <div class="col-md-3"><label>Uso CFDI</label><select name="cfdi_use_code" class="form-control" required><option value="">Seleccionar</option><?php foreach($cfdi_uses as$row){ ?><option value="<?php echo esc($row->code); ?>" <?php echo$selectedUse===$row->code?'selected':''; ?>><?php echo esc($row->code.' · '.$row->description); ?></option><?php } ?></select><small>El cambio aplica sólo a este CFDI.</small></div>
</div>
<div class="alert alert-light mt10">Las preferencias maestras del cliente sólo precargan esta revisión y no se modifican al guardar.</div>
<input type="hidden" name="expedition_postal_code" id="expedition-postal-code" value="<?php echo esc($issuer->expedition_postal_code??''); ?>">
<div id="draft-validation-message" class="mt15"></div>
<div class="mt20"><button class="btn btn-primary" type="submit">Actualizar revisión y guardar borrador</button> <a class="btn btn-default" href="<?php echo get_uri('fiscal/drafts'); ?>">Cancelar</a></div>
<?php echo form_close(); ?>
</div></div>
<script>
$(document).ready(function(){
 $("#fiscal-draft-form").appForm({closeModalOnSuccess:false,onSuccess:function(result){window.location=result.redirect;},onAjaxSuccess:function(result){if(!result.success)$("#draft-validation-message").html('<div class="alert alert-danger">'+result.message+'</div>');}});
 $(".sale-block input[type=checkbox]").on("change",function(){$(this).closest(".sale-block").find(".concept-qty").prop("disabled",!this.checked);}).trigger("change");
 $(".fiscal-item-edit").on("click",function(){ $("#"+$(this).data("target")).toggleClass("d-none"); });
 function syncIssuer(){var issuer=$("#fiscal-issuer option:selected"),id=issuer.val();$("#issuer-legal").val(issuer.data("legal")||"");$("#issuer-rfc").val(issuer.data("rfc")||"");$("#issuer-regime").val(issuer.data("regime")||"");$("#issuer-cp,#expedition-postal-code").val(issuer.data("cp")||"");$("#issuer-csd").val(issuer.data("csd")||"");var options=$("#fiscal-series option");options.each(function(){var match=String($(this).data("issuer"))===String(id);$(this).prop("disabled",!match).prop("hidden",!match);});if(!$("#fiscal-series option:selected").length||$("#fiscal-series option:selected").prop("disabled")){$("#fiscal-series option:not(:disabled):first").prop("selected",true);}$("#provisional-series").val($("#fiscal-series option:selected").text());}
 $("#fiscal-issuer").on("change",syncIssuer);$("#fiscal-series").on("change",function(){$("#provisional-series").val($(this).find("option:selected").text());});syncIssuer();
});
</script>
