<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Prefactura</title><style>body{font-family:Arial,sans-serif;color:#222;max-width:1000px;margin:30px auto}.head{text-align:center;border-bottom:2px solid #333}.warning{color:#a00;font-weight:bold}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.box{border:1px solid #ddd;padding:15px;margin-top:15px}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{border:1px solid #ddd;padding:8px;text-align:left}.right{text-align:right}.actions{margin:20px 0}@media print{.actions{display:none}}</style></head><body>
<div class="head"><?php echo $issuer_logo; ?><h1>PREFACTURA</h1><p class="warning">DOCUMENTO SIN VALIDEZ FISCAL</p></div>
<div class="actions"><?php if($can_edit){ ?><a href="<?php echo get_uri('fiscal/drafts/'.$preinvoice['draft']['id'].'/edit'); ?>">Volver a editar / Guardar borrador</a> · <?php } ?><a href="<?php echo get_uri('fiscal/drafts/'.$preinvoice['draft']['id']); ?>">Ver borrador y marcar listo</a> · <button onclick="window.print()">Imprimir vista</button></div>
<div class="grid"><div class="box"><h3>Emisor</h3><strong><?php echo esc($preinvoice['issuer']['legal_name']??'Pendiente'); ?></strong><br>RFC: <?php echo esc($preinvoice['issuer']['rfc']??'Pendiente'); ?><br>Régimen: <?php echo esc($preinvoice['issuer']['tax_regime_id']??'Pendiente'); ?></div><div class="box"><h3>Receptor</h3><strong><?php echo esc($preinvoice['receiver']['legal_name']??'Pendiente'); ?></strong><br>RFC: <?php echo esc($preinvoice['receiver']['rfc']??'Pendiente'); ?><br>Código postal: <?php echo esc($preinvoice['receiver']['fiscal_postal_code']??'Pendiente'); ?></div></div>
<div class="box">Serie: <?php echo esc($preinvoice['draft']['provisional_series']?:'Pendiente'); ?><br>Fecha de expedición: <?php echo esc($preinvoice['issue_date']); ?><br>Ventas relacionadas: <?php echo esc(implode(', ',array_map(fn($sale)=>$sale['display_id']?:'#'.$sale['sale_id'],$preinvoice['sales']))); ?></div>
<table><thead><tr><th>Concepto</th><th>Cantidad</th><th>Valor unitario</th><th>Descuento</th><th>Impuestos</th><th>Total</th></tr></thead><tbody><?php foreach($preinvoice['concepts']as$item){$snapshot=$item['snapshot']??[]; ?><tr><td><?php echo esc($snapshot['fiscal_description']??$snapshot['title']??'Concepto'); ?><br><small>Objeto de impuesto: <?php echo esc($snapshot['object_tax']??$snapshot['tax_object_code']??'-'); ?></small></td><td><?php echo esc($item['quantity']); ?></td><td><?php echo to_currency($item['unit_price']); ?></td><td><?php echo to_currency($item['discount']); ?></td><td><?php foreach(($item['taxes']??[])as$tax){ ?><div><small><?php echo esc($tax['tax_type']==='withholding'?'Retención':'Traslado'); ?> <?php echo esc($tax['tax_code'].' '.$tax['factor_type']); ?> · Base <?php echo to_currency($tax['tax_base']); ?><?php if($tax['rate_or_quota']!==null){ ?> · <?php echo esc($tax['rate_or_quota']); ?><?php } ?> · <?php echo to_currency($tax['tax_amount']); ?></small></div><?php } ?></td><td><?php echo to_currency($item['total']); ?></td></tr><?php } ?></tbody></table>
<div class="box right">Subtotal: <?php echo to_currency($preinvoice['subtotal']); ?><br>Descuentos: <?php echo to_currency($preinvoice['discount']); ?><br>Impuestos trasladados: <?php echo to_currency($preinvoice['transferred']); ?><br>Retenciones: <?php echo to_currency($preinvoice['withheld']); ?><br><strong>Total: <?php echo to_currency($preinvoice['total']); ?></strong></div>
<div class="box">Forma de pago: <?php echo esc($preinvoice['payment_form']); ?> · Método de pago: <?php echo esc($preinvoice['payment_method']); ?> · Uso CFDI: <?php echo esc($preinvoice['cfdi_use']); ?><br>Observaciones: <?php echo esc($preinvoice['observations']); ?></div>
<p class="warning">Esta prefactura no contiene UUID, sello, timbre fiscal ni código QR.</p>
</body></html>
