<?php
$editing=!empty($draft);$summary=$review['summary'];$checks=$review['checks'];$isReady=$review['status']==='ready';
$action=$editing?get_uri('fiscal/drafts/'.$draft->id):get_uri('fiscal/drafts');
$zone=new DateTimeZone($issue_date_constraints['timezone']);$issue=$editing?(new \App\Services\Fiscal\FiscalIssueDateNormalizer())->formatForInput((string)$draft->issue_date):(new DateTimeImmutable('now',$zone))->format('Y-m-d\TH:i');
$selectedUse=$editing?(string)$draft->cfdi_use_code:(string)(($receiver?->default_cfdi_use_id??0)?((array_values(array_filter($cfdi_uses,fn($r)=>(int)$r->id===(int)$receiver->default_cfdi_use_id))[0]->code??'')):'');
$selectedMethod=$editing?(string)$draft->payment_method_code:(string)($payment_suggestion['payment_method_code']??'');$selectedForm=$editing?(string)$draft->payment_form_code:(string)($payment_suggestion['payment_form_code']??'');
$selectedIssuerId=(int)($draft->issuer_id??$issuer->id??0);$selectedSeriesId=(int)($draft->fiscal_series_id??0);$issuerSeries=array_values(array_filter($series,fn($s)=>(int)$s->issuer_profile_id===$selectedIssuerId));
$savedSnapshots=[];foreach($saved_items as$item)$savedSnapshots[(int)$item->sale_item_id]=json_decode((string)$item->fiscal_snapshot,true)?:[];
$checkRow=static fn(bool$ok,string$text):string=>'<div class="mb5 '.($ok?'text-success':'text-warning').'">'.($ok?'✓':'⚠').' '.esc($text).'</div>';
?>
<div class="page-title clearfix"><h1>Revisión fiscal</h1></div><div class="card"><div class="card-body fiscal-review-normal">
<style>.fiscal-review-normal .fiscal-product-correction{display:none!important}</style>
<?php echo form_open($action,['id'=>'fiscal-review-form','class'=>'general-form']);echo csrf_field(); ?>
<input type="hidden" name="ux_mode" value="normal"><input type="hidden" name="save_as_draft" value="1"><input type="hidden" name="sale_context_id" value="<?php echo(int)$normal_sale_id;?>"><input type="hidden" name="sale_ids[]" value="<?php echo(int)$normal_sale_id;?>">
<div class="fiscal-readiness-checks mb20"><?php echo$checkRow($checks['client_complete'],'Cliente fiscal completo'),$checkRow($checks['products_complete'],'Productos configurados'),$checkRow($checks['issuer_ready'],'Emisor y certificado disponibles'),$checkRow($checks['totals_valid'],'Totales verificados');?></div>
<?php if(!$isReady){?><div class="alert alert-warning"><strong>No es posible facturar todavía.</strong><ul class="mb0 mt10"><?php foreach($review['blockers']as$blocker){?><li><?php echo esc($blocker['message']);?></li><?php }?></ul></div><?php foreach($review['products']as$product){if($product['complete'])continue;?><div class="border rounded p-3 mb10"><strong>⚠ <?php echo esc($product['name']);?></strong><div>Falta configuración fiscal.</div><?php echo modal_anchor(get_uri('invoices/item_modal_form'),'Editar partida',['class'=>'btn btn-default btn-sm mt10','title'=>'Datos fiscales de la partida','data-post-id'=>$product['sale_item_id'],'data-post-invoice_id'=>$product['sale_id'],'data-post-fiscal_only'=>1]);?></div><?php }}?>
<div class="row g-3 mb20"><div class="col-md-6"><small class="text-muted">Emisor</small><?php if(count($issuers)===1){?><div class="fw-bold"><?php echo esc($summary['issuer_name']);?></div><input type="hidden" name="issuer_id" value="<?php echo$selectedIssuerId;?>"><?php }else{?><select name="issuer_id" id="fiscal-issuer" class="form-control"><?php foreach($issuers as$candidate){?><option value="<?php echo(int)$candidate->id;?>" <?php echo$selectedIssuerId===(int)$candidate->id?'selected':'';?>><?php echo esc($candidate->legal_name);?></option><?php }?></select><?php }?></div>
<div class="col-md-6"><small class="text-muted">Serie</small><?php if(count($issuerSeries)===1){?><div class="fw-bold"><?php echo esc($issuerSeries[0]->series);?></div><input type="hidden" name="fiscal_series_id" value="<?php echo(int)$issuerSeries[0]->id;?>"><?php }else{?><select name="fiscal_series_id" id="fiscal-series" class="form-control"><?php foreach($series as$s){?><option value="<?php echo(int)$s->id;?>" data-issuer="<?php echo(int)$s->issuer_profile_id;?>" <?php echo$selectedSeriesId===(int)$s->id?'selected':'';?>><?php echo esc($s->series);?></option><?php }?></select><?php }?></div>
<div class="col-md-8"><small class="text-muted">Cliente</small><div class="fw-bold"><?php echo esc($summary['receiver_name']);?></div><div>RFC: <?php echo esc($summary['receiver_rfc']);?></div><input type="hidden" name="receiver_profile_id" value="<?php echo(int)($receiver->id??0);?>"></div></div>
<div class="row g-3"><div class="col-md-3"><label>Fecha CFDI</label><input type="datetime-local" name="issue_date" class="form-control" value="<?php echo esc($issue);?>" min="<?php echo esc($issue_date_constraints['min_issue_datetime']);?>" <?php echo$issue_date_constraints['max_issue_datetime']!==''?'max="'.esc($issue_date_constraints['max_issue_datetime']).'"':'';?> required></div>
<div class="col-md-3"><label>Uso CFDI</label><select name="cfdi_use_code" class="form-control" required><option value="">Seleccionar</option><?php foreach($cfdi_uses as$row){?><option value="<?php echo esc($row->code);?>" <?php echo$selectedUse===$row->code?'selected':'';?>><?php echo esc($row->code.' · '.$row->description);?></option><?php }?></select></div>
<div class="col-md-3"><label>Método de pago</label><select name="payment_method_code" class="form-control" required><option value="">Seleccionar</option><?php foreach($payment_methods as$row){?><option value="<?php echo esc($row->code);?>" <?php echo$selectedMethod===$row->code?'selected':'';?>><?php echo esc($row->code.' · '.$row->name);?></option><?php }?></select></div>
<div class="col-md-3"><label>Forma de pago</label><select name="payment_form_code" class="form-control" required><option value="">Seleccionar</option><?php foreach($payment_forms as$row){?><option value="<?php echo esc($row->code);?>" <?php echo$selectedForm===$row->code?'selected':'';?>><?php echo esc($row->code.' · '.$row->name);?></option><?php }?></select></div></div>
<?php $currency=(string)($draft->currency_code??'MXN');?><div class="mt10"><strong>Moneda:</strong> <?php echo esc($currency);?><input type="hidden" name="currency_code" value="<?php echo esc($currency);?>"><?php if($currency!=='MXN'){?><label class="ms-3">Tipo de cambio <input name="exchange_rate" class="form-control d-inline-block w-auto" value="<?php echo esc($draft->exchange_rate??'');?>"></label><?php }else{?><input type="hidden" name="exchange_rate" value="1.000000"><?php }?></div>
<h4 class="mt20">Productos</h4><?php foreach($review['products']as$product){$snap=$savedSnapshots[$product['sale_item_id']]??[];?><div class="border rounded p-3 mb10"><div class="fw-bold"><?php echo esc($product['name']);?></div><div><?php echo esc($product['quantity'].' '.$product['unit']);?> × <?php echo to_currency($product['unit_price']);?><?php if($checks['products_complete']){?> · <?php echo esc($product['tax_label']);?><?php }?></div><input type="hidden" name="quantities[<?php echo$product['sale_item_id'];?>]" value="<?php echo esc($product['quantity']);?>"><?php if(!$checks['products_complete']){?><div class="mt10 fiscal-product-correction"><div class="alert alert-light">Completa únicamente los datos faltantes. Los cambios aplican sólo a esta factura.</div><div class="row g-2"><div class="col-md-4"><label>Descripción fiscal</label><input class="form-control" name="fiscal_items[<?php echo$product['sale_item_id'];?>][fiscal_description]" value="<?php echo esc($snap['fiscal_description']??$product['name']);?>"></div><div class="col-md-3"><label>ClaveProdServ</label><input class="form-control" name="fiscal_items[<?php echo$product['sale_item_id'];?>][product_service_code]" value="<?php echo esc($snap['product_service_code']??'');?>"></div><div class="col-md-3"><label>ClaveUnidad</label><input class="form-control" name="fiscal_items[<?php echo$product['sale_item_id'];?>][unit_code]" value="<?php echo esc($snap['unit_code']??'');?>"></div><div class="col-md-2"><label>Objeto de impuesto</label><select class="form-control" name="fiscal_items[<?php echo$product['sale_item_id'];?>][tax_object_code]"><option value="">Seleccionar</option><?php foreach($tax_object_codes as$row){?><option value="<?php echo esc($row->code);?>" <?php echo($snap['tax_object_code']??'')===$row->code?'selected':'';?>><?php echo esc($row->code.' · '.$row->description);?></option><?php }?></select></div></div><input type="hidden" name="fiscal_items[<?php echo$product['sale_item_id'];?>][commercial_unit]" value="<?php echo esc($snap['commercial_unit']??$product['unit']);?>"></div><?php }?></div><?php }?>
<div class="row justify-content-end mt20"><div class="col-md-5"><table class="table table-sm"><tr><th>Subtotal</th><td class="text-end"><?php echo to_currency($summary['subtotal']);?></td></tr><?php if(\App\Services\Fiscal\FiscalDecimal::micros($summary['discount'])>0){?><tr><th>Descuento</th><td class="text-end"><?php echo to_currency($summary['discount']);?></td></tr><?php }?><tr><th>Impuestos trasladados</th><td class="text-end"><?php echo to_currency($summary['transferred_taxes']);?></td></tr><?php if(\App\Services\Fiscal\FiscalDecimal::micros($summary['withheld_taxes'])>0){?><tr><th>Retenciones</th><td class="text-end"><?php echo to_currency($summary['withheld_taxes']);?></td></tr><?php }?><tr class="fw-bold"><th>Total</th><td class="text-end"><?php echo to_currency($summary['total']);?></td></tr></table></div></div>
<?php if($isReady){?><div class="alert alert-success">✓ Lista para facturar</div><?php }?>
<details class="mt15"><summary>Más opciones</summary><div class="row g-2 mt10"><div class="col-md-6"><label>Condiciones</label><input name="conditions" class="form-control" value="<?php echo esc($draft->conditions??'');?>"></div><div class="col-md-6"><label>Observaciones</label><input name="observations" class="form-control" value="<?php echo esc($draft->observations??'');?>"></div></div></details><div id="fiscal-review-message" class="mt15"></div>
<?php if($isReady){?><div id="fiscal-invoice-confirmation" class="alert alert-light border mt20 d-none"><h4>Confirmar factura</h4><div><strong>Cliente:</strong> <?php echo esc($summary['receiver_name']);?></div><div><strong>RFC:</strong> <?php echo esc($summary['receiver_rfc']);?></div><div><strong>Serie:</strong> <?php echo esc($issuerSeries[0]->series??'');?></div><div><strong>Uso CFDI:</strong> <?php echo esc($selectedUse);?></div><div><strong>Método/Forma:</strong> <?php echo esc($selectedMethod.' / '.$selectedForm);?></div><div><strong>Total:</strong> <?php echo to_currency($summary['total']);?></div><p class="mt10 mb0">Esta operación utilizará 1 timbre asignado.</p><div class="mt15"><button type="button" class="btn btn-default" id="cancel-fiscal-confirmation">Volver</button> <button type="button" class="btn btn-success" id="execute-fiscal-invoice">Confirmar y facturar</button></div></div><?php }?>
<div class="modal-footer px0 mt20"><button type="button" class="btn btn-default" data-bs-dismiss="modal">Cerrar</button><?php if($editing){?><a class="btn btn-default" target="_blank" href="<?php echo get_uri('fiscal/drafts/'.$draft->id.'/preinvoice');?>">Vista previa</a><?php }?><?php if($editing&&!empty($review['advanced'])){?><a class="btn btn-default" href="<?php echo get_uri('fiscal/drafts/'.$draft->id);?>">Herramientas avanzadas</a><?php }?><button class="btn btn-primary" type="submit">Guardar borrador</button><button class="btn btn-success" id="show-fiscal-confirmation" type="button" <?php echo!$isReady?'disabled':'';?>>Confirmar y facturar</button></div>
<script>$(document).ready(function(){var reloadSale=false,escapeUx=function(v){return $('<div>').text(v||'').html();};$('#ajaxModal').one('hidden.bs.modal',function(){if(reloadSale)window.location.reload();});$('#execute-fiscal-invoice').on('click.ux21',function(e){e.stopImmediatePropagation();var b=$(this);if(b.prop('disabled'))return;b.prop('disabled',true).text('Generando factura...');$('#cancel-fiscal-confirmation,#show-fiscal-confirmation').prop('disabled',true);$.ajax({url:'<?php echo get_uri('fiscal/sales/'.(int)$normal_sale_id.'/invoice-flow');?>',type:'POST',dataType:'json',data:$('#fiscal-review-form').serialize()}).done(function(r){reloadSale=!!r.sale_closed;if(r.success){appAlert.success(r.message);$('#ajaxModal').modal('hide');window.location=r.redirect_url;return;}var html='<div class="alert '+(r.status==='verification_pending'?'alert-warning':'alert-danger')+'">'+escapeUx(r.message);if(r.blockers){html+='<ul class="mb0 mt10">';$.each(r.blockers,function(_,x){html+='<li>'+escapeUx(x.message)+'</li>';});html+='</ul>';}if(r.xml_inspection){html+='<div class="mt10"><a class="btn btn-default btn-sm" target="_blank" rel="noopener" href="'+escapeUx(r.xml_inspection.url)+'">'+escapeUx(r.xml_inspection.label)+'</a></div>';}html+='</div>';$('#fiscal-review-message').html(html);if(r.retry_allowed){b.prop('disabled',false).text('Confirmar y facturar');$('#cancel-fiscal-confirmation').prop('disabled',false);}else b.text('Resultado en verificación');}).fail(function(){b.prop('disabled',false).text('Confirmar y facturar');$('#cancel-fiscal-confirmation').prop('disabled',false);$('#fiscal-review-message').html('<div class="alert alert-danger">No fue posible completar la solicitud.</div>');});});});</script>
<?php echo form_close();?></div></div><script>$(document).ready(function(){var escapeHtml=function(v){return $('<div>').text(v||'').html();};$('#fiscal-review-form').appForm({closeModalOnSuccess:false,onSuccess:function(result){if(result.html){$('#ajaxModalContent').html(result.html);appAlert.success(result.message);}},onAjaxSuccess:function(result){if(!result.success)$('#fiscal-review-message').html('<div class="alert alert-danger">'+escapeHtml(result.message)+'</div>');}});$('#fiscal-issuer').on('change',function(){var id=$(this).val(),options=$('#fiscal-series option');options.each(function(){var visible=String($(this).data('issuer'))===String(id);$(this).prop('disabled',!visible).prop('hidden',!visible);});$('#fiscal-series option:not(:disabled):first').prop('selected',true);}).trigger('change');$('#show-fiscal-confirmation').on('click',function(){$('#fiscal-invoice-confirmation').removeClass('d-none');$(this).prop('disabled',true);});$('#cancel-fiscal-confirmation').on('click',function(){$('#fiscal-invoice-confirmation').addClass('d-none');$('#show-fiscal-confirmation').prop('disabled',false);});$('#execute-fiscal-invoice').on('click',function(){var b=$(this);if(b.prop('disabled'))return;b.prop('disabled',true).text('Generando factura...');$('#cancel-fiscal-confirmation,#show-fiscal-confirmation').prop('disabled',true);$.ajax({url:'<?php echo$editing?get_uri('fiscal/drafts/'.$draft->id.'/invoice-flow'):'';?>',type:'POST',dataType:'json',data:{'<?php echo csrf_token();?>':'<?php echo csrf_hash();?>'}}).done(function(r){if(r.success){appAlert.success(r.message);$('#ajaxModal').modal('hide');window.location=r.redirect_url;return;}var html='<div class="alert '+(r.status==='verification_pending'?'alert-warning':'alert-danger')+'">'+escapeHtml(r.message);if(r.blockers){html+='<ul class="mb0 mt10">';$.each(r.blockers,function(_,x){html+='<li>'+escapeHtml(x.message)+'</li>';});html+='</ul>';}if(r.xml_inspection){html+='<div class="mt10"><a class="btn btn-default btn-sm" target="_blank" rel="noopener" href="'+escapeHtml(r.xml_inspection.url)+'">'+escapeHtml(r.xml_inspection.label)+'</a></div>';}html+='</div>';$('#fiscal-review-message').html(html);if(r.retry_allowed){b.prop('disabled',false).text('Confirmar y facturar');$('#cancel-fiscal-confirmation').prop('disabled',false);}else{b.text('Resultado en verificación');}}).fail(function(){b.prop('disabled',false).text('Confirmar y facturar');$('#cancel-fiscal-confirmation').prop('disabled',false);$('#fiscal-review-message').html('<div class="alert alert-danger">No fue posible completar la solicitud.</div>');});});});</script>
