<div class="page-title clearfix"><h1>Borrador fiscal #<?php echo(int)$draft->id; ?></h1><div class="title-button-group"><span class="badge bg-<?php echo esc($color); ?>"><?php echo esc($label); ?></span></div></div>
<div class="card"><div class="card-body">
<div class="alert alert-warning"><strong>PREFACTURA:</strong> este borrador todavía no tiene validez fiscal.</div>
<div class="row"><div class="col-md-3"><strong>Serie provisional</strong><br><?php echo esc($draft->provisional_series?:'Pendiente'); ?></div><div class="col-md-3"><strong>Expedición</strong><br><?php echo esc($draft->issue_date); ?></div><div class="col-md-3"><strong>Total</strong><br><?php echo to_currency($draft->total); ?></div><div class="col-md-3"><strong>Ventas relacionadas</strong><br><?php echo count($sales); ?></div></div>
<h4 class="mt20">Ventas y asignaciones</h4><table class="table"><thead><tr><th>Venta</th><th>Subtotal</th><th>Impuestos</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($sales as$sale){ ?><tr><td><?php echo esc($sale->display_id?:'#'.$sale->sale_id); ?></td><td><?php echo to_currency($sale->allocated_subtotal); ?></td><td><?php echo to_currency($sale->allocated_tax); ?></td><td><?php echo to_currency($sale->allocated_total); ?></td><td><a href="<?php echo get_uri('invoices/view/'.$sale->sale_id); ?>">Ver venta</a></td></tr><?php } ?></tbody></table>
<h4>Conceptos</h4><table class="table"><thead><tr><th>Concepto</th><th>Cantidad</th><th>Subtotal</th><th>Impuestos</th><th>Total</th></tr></thead><tbody><?php foreach($items as$item){$snapshot=json_decode($item->fiscal_snapshot,true)?:[]; ?><tr><td><?php echo esc($snapshot['fiscal_description']??$snapshot['title']??'Concepto'); ?></td><td><?php echo esc($item->quantity); ?></td><td><?php echo to_currency($item->subtotal); ?></td><td><?php echo to_currency($item->tax); ?></td><td><?php echo to_currency($item->total); ?></td></tr><?php } ?></tbody></table>
<?php if(!empty($payload['validation']['errors'])){ ?><h4>Datos pendientes</h4><?php foreach($payload['validation']['errors']as$error){ ?><div class="alert alert-warning"><?php echo esc($error['message']); ?></div><?php }} ?>
<h4>Historial</h4><ul><?php foreach($audit as$event){ ?><li><?php echo esc($event->created_at.' · '.$event->event.' · '.trim($event->first_name.' '.$event->last_name)); ?></li><?php } ?></ul>
<details class="mt20"><summary>Snapshot e impuestos detallados</summary><div class="mt10"><strong>Snapshot:</strong> v<?php echo(int)$draft->snapshot_version;?> · <strong>Estado técnico:</strong> <?php echo esc($draft->status);?> · <strong>CSD:</strong> <?php echo esc($certificate->certificate_number??'No disponible');?></div><?php if($snapshot){?><table class="table table-sm mt10"><thead><tr><th>Concepto</th><th>Base</th><th>Tipo</th><th>Impuesto</th><th>Factor</th><th>Tasa/cuota</th><th>Importe</th></tr></thead><tbody><?php foreach($snapshot['items']as$item)foreach($item['taxes']as$tax){?><tr><td><?php echo esc($item['snapshot']['fiscal_description']??$item['snapshot']['title']??'-');?></td><td><?php echo esc($tax['tax_base']);?></td><td><?php echo esc($tax['tax_type']);?></td><td><?php echo esc($tax['tax_code']);?></td><td><?php echo esc($tax['factor_type']);?></td><td><?php echo esc($tax['rate_or_quota']??'-');?></td><td><?php echo esc($tax['tax_amount']);?></td></tr><?php }?></tbody></table><?php }?></details>
<?php if($attempts){?><details class="mt20"><summary>Intentos</summary><ul><?php foreach($attempts as$attempt){?><li>#<?php echo(int)$attempt->id;?> · <?php echo esc($attempt->status);?> · <?php echo esc($attempt->provider);?></li><?php }?></ul></details><?php }?><?php if($artifacts){?><details class="mt20"><summary>Artefactos</summary><ul><?php foreach($artifacts as$artifact){?><li>#<?php echo(int)$artifact->id;?> · <?php echo esc($artifact->artifact_type);?> · <?php echo esc($artifact->validation_status);?></li><?php }?></ul></details><?php }?>
<div class="mt20"><?php if($can_edit&&in_array($draft->status,['draft','ready','error'],true)){ ?><a class="btn btn-primary" href="<?php echo get_uri('fiscal/drafts/'.$draft->id.'/edit'); ?>">Editar</a><?php } ?> <a class="btn btn-default" target="_blank" href="<?php echo get_uri('fiscal/drafts/'.$draft->id.'/preinvoice'); ?>">Ver prefactura</a><?php if($can_edit&&$draft->status!=='ready'&&in_array($draft->status,['draft','error'],true)){ ?> <button id="ready-draft-detail" class="btn btn-success">Marcar listo</button><?php }else{ ?> <button class="btn btn-success" disabled title="El timbrado se integrará en el siguiente incremento.">Listo para facturar</button><?php } ?><?php if($can_discard&&in_array($draft->status,['draft','ready','error'],true)){ ?> <button id="discard-draft-detail" class="btn btn-danger">Descartar</button><?php } ?></div>
<?php if($can_stamp&&$draft->status==='ready'){ ?>
<div class="mt20">
<?php if(!$preflight['allowed']){ ?><div class="alert alert-warning"><?php echo esc($preflight['errors'][0]); ?></div><?php } ?>
<button id="stamp-draft-detail" class="btn btn-success" <?php echo $preflight['allowed']?'':'disabled'; ?>>Facturar</button>
</div>
<?php } ?>
</div></div>
<script>$("#discard-draft-detail").on("click",function(){if(!confirm("¿Descartar el borrador y liberar sus reservas?"))return;$.post("<?php echo get_uri('fiscal/drafts/'.$draft->id.'/discard'); ?>",{"<?php echo csrf_token(); ?>":"<?php echo csrf_hash(); ?>"},function(r){if(r.success)location.reload();else appAlert.error(r.message);},"json");});</script>
<script>$("#ready-draft-detail").on("click",function(){$.post("<?php echo get_uri('fiscal/drafts/'.$draft->id.'/ready'); ?>",{"<?php echo csrf_token(); ?>":"<?php echo csrf_hash(); ?>"},function(r){if(r.success)location.reload();else appAlert.error(r.message);},"json");});</script>
<script>$("#stamp-draft-detail").on("click",function(){var b=$(this);if(b.prop("disabled"))return;if(!confirm("Vas a generar un CFDI.\n\nSerie: <?php echo esc($draft->provisional_series?:'Pendiente'); ?>\nFecha: <?php echo esc($draft->issue_date); ?>\nTotal: <?php echo esc($draft->total); ?>\nVentas relacionadas: <?php echo count($sales); ?>"))return;b.prop("disabled",true).text("Facturando…");$.post("<?php echo get_uri('fiscal/drafts/'.$draft->id.'/stamp'); ?>",{"<?php echo csrf_token(); ?>":"<?php echo csrf_hash(); ?>"},function(r){if(r.success)window.location=r.redirect;else{b.prop("disabled",false).text("Facturar");appAlert.error(r.message);}},"json").fail(function(){b.prop("disabled",false).text("Facturar");appAlert.error("No fue posible completar la solicitud.");});});</script>
