<?php
declare(strict_types=1);
define('ROOTPATH',dirname(__DIR__,2).DIRECTORY_SEPARATOR);define('FCPATH',ROOTPATH);require ROOTPATH.'app/Config/Paths.php';$paths=new Config\Paths();define('APPPATH',realpath($paths->appDirectory).DIRECTORY_SEPARATOR);define('SYSTEMPATH',realpath($paths->systemDirectory).DIRECTORY_SEPARATOR);define('WRITEPATH',realpath($paths->writableDirectory).DIRECTORY_SEPARATOR);define('ENVIRONMENT','development');require $paths->systemDirectory.'/Boot.php';CodeIgniter\Boot::bootTest($paths);helper(['general','date_time','plugin','currency']);require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
$pass=$fail=0;$a=function(bool$ok,string$message)use(&$pass,&$fail){echo($ok?'[PASS] ':'[FAIL] ').$message.PHP_EOL;$ok?$pass++:$fail++;};$read=static fn(string$p)=>(string)file_get_contents(APPPATH.$p);$service=$read('Services/Fiscal/Cancellation/FiscalCancellationService.php');$adapter=$read('Services/Fiscal/Cancellation/TimbradorXpressCancellationAdapter.php');$modal=$read('Views/fiscal/invoices/cancel_form.php');$list=$read('Views/fiscal/invoices/module_index.php');$module=$read('Controllers/Fiscal/InvoiceModule.php');$controller=$read('Controllers/Fiscal/Invoices.php');$presenter=$read('Services/Fiscal/Pac/FiscalDocumentStatusPresenter.php');$query=$read('Services/Fiscal/FiscalInvoiceCenterQueryService.php');$routes=$read('Config/FiscalRoutes.php');
$a(str_contains($service,"in_array(\$status,['accepted','pending'],true)"),'Request success/pending is a successful modal response.');
$a(str_contains($modal,'closeModalOnSuccess:true'),'Pending and cancelled close modal.');
$a(str_contains($modal,'onError:function')&&str_contains($modal,"r.status==='unknown'"),'Unknown blocks modal retry.');
$a(str_contains($modal,'Solicitud bloqueada'),'Unknown disables submit.');
$a(str_contains($service,"'rejected','transport_not_sent'=>'rejected'"),'Rejected remains correctable.');
$a(str_contains($module,"'unknown'=>['Verificando'"),'Cancellation unknown label is Verificando.');
$a(str_contains($presenter,"return ['stamped'")&&str_contains($presenter,'continúa timbrado'),'Fiscal status remains stamped while cancellation is verifying.');
$a(str_contains($controller,'cancellationStatus')&&str_contains($service,'fiscal_status')&&str_contains($service,'cancellation_status'),'Status AJAX returns canonical fields.');
$a(!str_contains($list,'table.appTable({reload:true})')&&str_contains($list,"$('#fiscal-invoices-table').appTable({reload:true})"),'List reload uses the real appTable selector.');
$a(!preg_match('/fiscal-cancellation-status[^\n]+ack\//',$list),'Status AJAX never navigates to acknowledgement.');
$a(str_contains($routes,"cancellation/ack/(:num)")&&str_contains($controller,'function ack'),'Acknowledgement route and controller agree on request id.');
$a(str_contains($module,'cancellation_ack_available'),'Acknowledgement action requires an artifact.');
$a(str_contains($query,"artifact_type=\\'cancellation_ack\\'")||str_contains($query,"artifact_type=\'cancellation_ack\'"),'Query projects acknowledgement availability.');
$a(str_contains($module,'canCancel($row)')&&str_contains($module,"['none','rejected']"),'Cancel is hidden for pending/cancelled/verifying.');
$a(str_contains($service,'provider_payload_base64')&&str_contains($service,'decoded_sha256'),'Provider evidence is durable and hashed.');
$a(str_contains($adapter,'FiscalCancellationStatusMapper')&&str_contains(file_get_contents(APPPATH.'Services/Fiscal/Cancellation/FiscalCancellationStatusMapper.php'),'N-998'),'SAT intermitency remains unknown, not rejected.');
$a(str_contains($service,'consumeCancellationRequest')&&str_contains($service,'consumeCancellationStatusQuery'),'Cancellation operations use the commercial wallet policy.');
$a(str_contains($service,"'accepted'=>'cancelled'")&&str_contains($service,"'unknown'=>'cancellation_pending'"),'Allocation can release only after confirmed cancellation.');
$a(!str_contains($controller,'FakeFiscalCancellationAdapter'),'Browser flow never uses the fake adapter.');
$a(str_contains($adapter,"'cancelarPEM'")&&str_contains($adapter,"'consultarEstadoSAT'"),'Only documented development operations are used.');
$db=db_connect();$rows=(new App\Services\Fiscal\FiscalInvoiceCenterQueryService($db))->search(['uuid'=>'A64C0FFB-974E-402D-8E20-CBC7F74E2F58'],10,0,true);$row=$rows[0]??null;
$a($row&&$row->visible_status==='stamped'&&$row->cancellation_status==='unknown','A-6 projects stamped plus verifying cancellation.');
$a($row&&(int)$row->cancellation_ack_available===0,'A-6 does not project an acknowledgement action.');
$account=$db->table('fiscal_stamp_accounts')->where(['issuer_profile_id'=>2,'environment'=>'development'])->get(1)->getRow();$a($account&&(int)$account->available_balance>=0&&(int)$account->reserved_balance===0,'Wallet remains valid with no cancellation reservation.');
$sale=$db->table('invoices')->where('id',14)->get(1)->getRow();$allocation=$db->table('fiscal_document_sales')->where(['fiscal_document_id'=>6,'sale_id'=>14])->get(1)->getRow();$a($sale&&$sale->status!=='cancelled'&&$allocation&&$allocation->allocation_status==='active','Sale and allocation remain intact while cancellation is unconfirmed.');
echo"\n{$pass} passed, {$fail} failed. Zero PAC calls.\n";exit($fail?1:0);
