<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
helper(['general','date_time','plugin']);require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
$db=require dirname(__DIR__).'/Increment02/isolated_database.php';$settings=[];foreach($db->table('settings')->get()->getResult()as$setting)$settings[$setting->setting_name]=$setting->setting_value;config('Rise')->app_settings_array=$settings+['timezone'=>'UTC'];
$admin=$db->table('users')->where(['deleted'=>0,'user_type'=>'staff','is_admin'=>1])->get(1)->getRow();$item=$db->table('items')->where('deleted',0)->orderBy('id')->get(1)->getRow();if(!$admin||!$item)throw new RuntimeException('The isolated clone needs an administrator and an item fixture.');session()->set('user_id',(int)$admin->id);
$passed=0;$failed=0;$assert=static function(bool$condition,string$message)use(&$passed,&$failed):void{echo($condition?'[PASS] ':'[FAIL] ').$message.PHP_EOL;$condition?$passed++:$failed++;};
$makeController=static function(array$post):array{$request=Config\Services::incomingrequest(null,false);$request->setMethod('POST');$request->setGlobal('post',$post);$request->setGlobal('request',$post);$response=Config\Services::response(null,false);$response->setStatusCode(200);service('validation')->reset();$controller=new App\Controllers\Fiscal\ItemSettings();$controller->initController($request,$response,service('logger'));return[$controller,$response];};
$runForm=static function(array$post)use($makeController):array{[$controller,$response]=$makeController($post);$result=$controller->form();if($result instanceof CodeIgniter\HTTP\ResponseInterface){$response=$result;$html=$result->getBody();}else$html=(string)$result;return['status'=>$response->getStatusCode(),'html'=>$html,'controller'=>$controller];};
$runJson=static function(string$method,array$post)use($makeController):array{[$controller]=$makeController($post);ob_start();$controller->$method();return json_decode((string)ob_get_clean(),true,512,JSON_THROW_ON_ERROR);};
try{
 $configurationIds=array_column($db->table('item_fiscal_settings')->select('id')->where('item_id',$item->id)->get()->getResultArray(),'id')?:[0];$db->table('item_fiscal_taxes')->whereIn('item_fiscal_setting_id',$configurationIds)->delete();$db->table('item_fiscal_settings')->where('item_id',$item->id)->delete();
 $legacy=$runForm(['item_id'=>$item->id]);$assert($legacy['status']===200&&str_contains($legacy['html'],'id="item-fiscal-form"'),'POST fiscal/items/form opens a legacy item without configuration.');$assert(str_contains($legacy['html'],'name="id" value="0"'),'Legacy modal initializes an empty configuration.');
 foreach(['name="commercial_unit"','name="fiscal_description"','name="identification_number"','name="tax_object_code_id"','name="status"']as$removed)$assert(!str_contains($legacy['html'],$removed),"Simplified form omits $removed.");
 $assert(str_contains($legacy['html'],htmlspecialchars((string)($item->unit_type?:'-')))&&str_contains($legacy['html'],htmlspecialchars((string)($item->description?:'-'))),'Summary shows administrative unit and description read-only.');
 $assert(substr_count($legacy['html'],'type="hidden"')>=4&&str_contains($legacy['html'],'quietMillis:350')&&!str_contains($legacy['html'],'processResults'),'Remote catalogs use Select2 3.x-compatible hidden inputs and AJAX options.');
 $assert(str_contains($legacy['html'],'option:selected'),'Tax selection change is wired to the live ObjetoImp summary.');
 $missing=$runForm(['item_id'=>99999999]);$assert($missing['status']===404&&str_contains($missing['html'],app_lang('fiscal_item_not_found')),'Missing item returns controlled 404 HTML.');

 $incomplete=$runJson('save',['item_id'=>$item->id,'item_type'=>'product','status'=>'ready','tax_object_code_id'=>999,'commercial_unit'=>'MANIPULATED','fiscal_description'=>'MANIPULATED','identification_number'=>'MANIPULATED']);$assert(($incomplete['success']??false)&&$incomplete['status']==='incomplete','Missing SAT keys calculate incomplete status.');
 $stored=$db->table('item_fiscal_settings')->where('id',$incomplete['id'])->get()->getRow();$assert($stored->status==='incomplete'&&$stored->commercial_unit===null&&$stored->fiscal_description===null&&$stored->identification_number===null,'Server ignores manipulated status and legacy fields.');$assert($db->table('sat_tax_object_codes')->where(['id'=>$stored->tax_object_code_id,'code'=>'01'])->countAllResults()===1,'No taxes derives ObjetoImp 01.');
 $existing=$runForm(['item_id'=>$item->id]);$assert($existing['status']===200&&str_contains($existing['html'],'name="id" value="'.$incomplete['id'].'"'),'Existing configuration reopens.');

 if(trim((string)$item->description)===''){$db->table('items')->where('id',$item->id)->update(['description'=>'Administrative description fixture']);$item->description='Administrative description fixture';}
 $product=$db->table('sat_product_service_keys')->where('is_active',1)->get(1)->getRow();$unit=$db->table('sat_unit_keys')->where('is_active',1)->get(1)->getRow();$object03=$db->table('sat_tax_object_codes')->where('code','03')->get()->getRow();$object04=$db->table('sat_tax_object_codes')->where('code','04')->get()->getRow();$taxCode=$db->table('sat_tax_codes')->where('code','002')->get()->getRow();$factor=$db->table('sat_tax_factor_types')->where('code','Tasa')->get()->getRow();
 $db->table('taxes')->insert(['title'=>'Increment03 HTTP IVA fixture','percentage'=>'16','sat_tax_code_id'=>$taxCode->id,'fiscal_tax_type'=>'transfer','factor_type_id'=>$factor->id,'xml_rate'=>'0.160000','is_fiscal_ready'=>1,'use_for_administrative'=>1,'use_for_fiscal'=>1,'deleted'=>0]);$taxId=(int)$db->insertID();
 $withoutTax=$runJson('save',['id'=>$incomplete['id'],'item_id'=>$item->id,'item_type'=>'product','sat_product_service_key_id'=>$product->id,'sat_unit_key_id'=>$unit->id,'status'=>'ready','tax_object_code_id'=>$object04->id]);$assert(($withoutTax['success']??false)&&$withoutTax['status']==='ready'&&$withoutTax['tax_object_code']==='01','Complete keys without taxes calculate ready and ObjetoImp 01.');
 $complete=$runJson('save',['id'=>$incomplete['id'],'item_id'=>$item->id,'item_type'=>'product','sat_product_service_key_id'=>$product->id,'sat_unit_key_id'=>$unit->id,'tax_object_code_id'=>$object04->id,'tax_ids'=>[$taxId],'status'=>'inactive','commercial_unit'=>'MANIPULATED','fiscal_description'=>'MANIPULATED']);$assert(($complete['success']??false)&&$complete['status']==='ready'&&$complete['tax_object_code']==='02','Fiscal-ready tax derives ObjetoImp 02 and ignores manipulated derived values.');
 $duplicate=$runJson('save',['id'=>$incomplete['id'],'item_id'=>$item->id,'item_type'=>'product','sat_product_service_key_id'=>$product->id,'sat_unit_key_id'=>$unit->id,'tax_ids'=>[$taxId,$taxId]]);$assert(($duplicate['success']??true)===false&&$db->table('item_fiscal_taxes')->where('item_fiscal_setting_id',$incomplete['id'])->countAllResults()===1,'Duplicate tax submission is rejected without changing relations.');
 $row=(new App\Models\Items_model())->get_details(['id'=>$item->id])->getRow();$assert($row&&$row->fiscal_status==='ready','Administrative listing exposes calculated ready badge.');$reopened=$runForm(['item_id'=>$item->id]);$assert(str_contains($reopened['html'],$product->code)&&str_contains($reopened['html'],$unit->code)&&str_contains($reopened['html'],'Increment03 HTTP IVA fixture'),'Editing recovers SAT selections and enriched tax option.');

 $db->table('item_fiscal_settings')->where('id',$incomplete['id'])->update(['tax_object_code_id'=>$object03->id]);$advanced03=$runJson('save',['id'=>$incomplete['id'],'item_id'=>$item->id,'item_type'=>'product','sat_product_service_key_id'=>$product->id,'sat_unit_key_id'=>$unit->id]);$assert($advanced03['tax_object_code']==='03','Existing advanced ObjetoImp 03 is preserved.');
 $db->table('item_fiscal_settings')->where('id',$incomplete['id'])->update(['tax_object_code_id'=>$object04->id]);$advanced04=$runJson('save',['id'=>$incomplete['id'],'item_id'=>$item->id,'item_type'=>'product','sat_product_service_key_id'=>$product->id,'sat_unit_key_id'=>$unit->id,'tax_ids'=>[$taxId]]);$assert($advanced04['tax_object_code']==='04','Existing advanced ObjetoImp 04 is preserved.');

 $db->table('sat_product_service_keys')->insert(['code'=>'99999991','description'=>'FixtureSearch Alpha','is_active'=>1]);$db->table('sat_product_service_keys')->insert(['code'=>'99999992','description'=>'FixtureSearch Beta','is_active'=>1]);$short=$runJson('search_products',['term'=>'Fi','page'=>1,'limit'=>1]);$page1=$runJson('search_products',['term'=>'Fixture','page'=>1,'limit'=>1]);$page2=$runJson('search_products',['term'=>'Fixture','page'=>2,'limit'=>1]);$assert($short['results']===[],'AJAX search does not run with two characters.');$assert(count($page1['results'])===1&&$page1['more']===true&&count($page2['results'])===1,'AJAX product search paginates from three characters using Select2 3.x JSON.');$unitSearch=$runJson('search_units',['term'=>'H87','page'=>1,'limit'=>20]);$assert(count($unitSearch['results'])===1&&str_contains($unitSearch['results'][0]['text'],'H87'),'AJAX unit search finds key with three characters.');
 $db->table('sat_product_service_keys')->where('id',$product->id)->update(['is_active'=>0]);$historical=$runForm(['item_id'=>$item->id]);$assert(str_contains($historical['html'],$product->code),'Editing recovers an inactive historical selected key.');
 $deactivated=$runJson('deactivate',['item_id'=>$item->id]);$assert(($deactivated['success']??false)&&(new App\Services\Fiscal\ItemFiscalReadinessService())->evaluate((int)$item->id)['status']==='inactive','Only explicit action deactivates configuration.');$activated=$runJson('activate',['item_id'=>$item->id]);$assert(($activated['success']??false),'Explicit action activates calculated-state processing.');
 $db->table('sat_product_service_keys')->set('is_active',0)->update();$db->table('sat_unit_keys')->set('is_active',0)->update();$db->table('sat_tax_object_codes')->set('is_active',0)->update();$emptyCatalogs=$runForm(['item_id'=>$item->id]);$assert($emptyCatalogs['status']===200&&str_contains($emptyCatalogs['html'],'id="item-fiscal-form"'),'Form remains available with empty active catalogs.');
 $reflection=new ReflectionClass($legacy['controller']);$allowed=$reflection->getMethod('allowed');$allowed->setAccessible(true);$login=$reflection->getProperty('login_user');$login->setAccessible(true);$user=$login->getValue($legacy['controller']);$user->is_admin=0;$user->permissions=[];$assert($allowed->invoke($legacy['controller'],false)===false&&$allowed->invoke($legacy['controller'],true)===false,'User without fiscal permissions is denied.');
}catch(Throwable$exception){echo'[FAIL] '.get_class($exception).': '.$exception->getMessage().PHP_EOL;$failed++;}
echo"\n$passed passed, $failed failed.\n";exit($failed===0?0:1);
