<div class="card"><div class="page-title clearfix"><h4><?php echo app_lang('fiscal_pdf_templates'); ?></h4></div><div class="card-body">
<?php if($can_manage){echo form_open(get_uri('fiscal/pdf-templates/save'),['id'=>'pdf-template-form','class'=>'general-form']);echo csrf_field();?>
<div class="row"><div class="col-md-3"><label><?php echo app_lang('fiscal_issuer'); ?></label><select name="issuer_id" class="form-control select2" required><option value=""></option><?php foreach($issuers as$i){?><option value="<?php echo$i->id; ?>"><?php echo esc($i->legal_name.' · '.$i->rfc); ?></option><?php } ?></select></div>
<div class="col-md-2"><label><?php echo app_lang('provider'); ?></label><?php echo form_dropdown('provider',['fake'=>'Fake PAC','timbradorxpress-tools'=>'TimbradorXpress Tools'],'fake',"class='form-control select2'"); ?></div>
<div class="col-md-2"><label><?php echo app_lang('document_type'); ?></label><?php echo form_dropdown('document_type',['I'=>'Ingreso','E'=>'Egreso','P'=>'Pago','T'=>'Traslado','N'=>'Nómina'],'I',"class='form-control select2'"); ?></div>
<div class="col-md-3"><label><?php echo app_lang('pdf_template_code'); ?></label><input name="template_code" maxlength="40" class="form-control" required></div>
<div class="col-md-1"><label><?php echo app_lang('active'); ?></label><?php echo form_checkbox('is_active','1',true,"class='form-check-input'"); ?></div><div class="col-md-1"><button class="btn btn-primary mt25"><?php echo app_lang('save'); ?></button></div></div><?php echo form_close(); ?><hr><?php } ?>
<table class="table table-bordered"><thead><tr><th><?php echo app_lang('fiscal_issuer'); ?></th><th><?php echo app_lang('provider'); ?></th><th><?php echo app_lang('document_type'); ?></th><th><?php echo app_lang('pdf_template_code'); ?></th><th><?php echo app_lang('status'); ?></th></tr></thead><tbody><?php foreach($templates as$t){$issuer=array_values(array_filter($issuers,fn($i)=>(int)$i->id===(int)$t->issuer_id))[0]??null;?><tr><td><?php echo esc($issuer?->legal_name??('#'.$t->issuer_id)); ?></td><td><?php echo esc($t->provider); ?></td><td><?php echo esc($t->document_type); ?></td><td><?php echo esc($t->template_code); ?></td><td><?php echo$t->is_active?app_lang('active'):app_lang('inactive'); ?></td></tr><?php } ?></tbody></table></div></div>
<script>$(document).ready(function(){$('.select2').select2();$('#pdf-template-form').appForm({closeModalOnSuccess:false,onAjaxSuccess:function(r){if(r.csrf)$('#pdf-template-form input[name="'+r.csrf.name+'"]').val(r.csrf.hash);},onSuccess:function(){location.reload();}});});</script>
