<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
helper(['general','date_time','plugin','currency']);
require_once APPPATH . 'ThirdParty/PHP-Hooks/php-hooks.php';
$db=require dirname(__DIR__).'/Increment02/isolated_database.php';
service('migrations')->setNamespace('App')->latest();
$pass=$fail=0;
$assert=static function(bool$ok,string$message)use(&$pass,&$fail):void{echo($ok?'[PASS] ':'[FAIL] ').$message.PHP_EOL;$ok?$pass++:$fail++;};
$now=get_current_utc_time();$user=(int)$db->table('users')->where(['deleted'=>0,'is_admin'=>1])->get(1)->getRow()->id;
$saleSource=$db->table('invoices')->where('deleted',0)->get(1)->getRowArray();$docSource=$db->table('fiscal_documents')->where('deleted',0)->get(1)->getRowArray();$counter=0;
$sale=static function(string$total='100.000000')use($db,$saleSource,&$counter):int{$counter++;$row=$saleSource;unset($row['id']);$row['invoice_total']=$total;$row['invoice_subtotal']=$total;$row['status']='not_paid';$row['deleted']=0;$row['display_id']='C21-S'.$counter;$db->table('invoices')->insert($row);return(int)$db->insertID();};
$document=static function(string$total='100.000000',string$status='stamped')use($db,$docSource,&$counter):int{$counter++;$row=$docSource;unset($row['id']);$row['invoice_id']=0;$row['source_draft_id']=null;$row['total']=$total;$row['subtotal']=$total;$row['transferred_tax_total']='0';$row['withheld_tax_total']='0';$row['status']=$status;$row['folio']=880000+$counter;$row['source_snapshot_hash']=hash('sha256','c21-'.$counter);$row['created_at']=get_current_utc_time();$row['updated_at']=get_current_utc_time();$db->table('fiscal_documents')->insert($row);return(int)$db->insertID();};
$draft=static function(string$total='100.000000',string$status='draft')use($db,$now,$user,&$counter):int{$counter++;$db->table('fiscal_drafts')->insert(['issuer_id'=>2,'customer_id'=>1,'document_type'=>'I','provisional_series'=>'C21','issue_date'=>$now,'currency_code'=>'MXN','exchange_rate'=>'1.000000','payment_form_code'=>'01','payment_method_code'=>'PUE','cfdi_use_code'=>'G03','receiver_tax_regime_code'=>'601','receiver_postal_code'=>'06000','expedition_postal_code'=>'06000','subtotal'=>$total,'discount'=>'0.000000','tax_total'=>'0.000000','total'=>$total,'fiscal_payload'=>json_encode(['issuer'=>[],'receiver'=>[],'concepts'=>[],'taxes'=>[]]),'status'=>$status,'created_by'=>$user,'updated_by'=>$user,'created_at'=>$now,'updated_at'=>$now]);return(int)$db->insertID();};
$link=static function(int$documentId,int$saleId,string$total,string$status='active')use($db,$now,$user):void{$db->table('fiscal_document_sales')->insert(['fiscal_document_id'=>$documentId,'sale_id'=>$saleId,'allocated_subtotal'=>$total,'allocated_tax'=>'0.000000','allocated_total'=>$total,'allocation_status'=>$status,'created_by'=>$user,'created_at'=>$now,'updated_at'=>$now]);};
$alloc=new App\Services\Fiscal\FiscalSaleAllocationService($db);
try{
 foreach(['fiscal_document_sales','fiscal_drafts','fiscal_draft_sales','fiscal_document_relations']as$table)$assert($db->tableExists($table),"$table exists.");
 $s1=$sale();$summary=$alloc->getSaleFiscalSummary($s1);$assert($summary['fiscal_status']==='not_invoiced'&&$summary['available_to_invoice']==='100.000000','Sale without invoice is fully available.');
 $d1=$draft('40.000000');$alloc->reserveDraftAllocations($d1,[['sale_id'=>$s1,'allocated_subtotal'=>'40','allocated_tax'=>'0','allocated_total'=>'40']],$user);$summary=$alloc->getSaleFiscalSummary($s1);$assert($summary['fiscal_status']==='draft'&&$summary['draft_reserved_total']==='40.000000'&&$summary['available_to_invoice']==='60.000000','Draft reserves sale amount.');
 $alloc->releaseDraftAllocations($d1,$user);$assert($alloc->getAvailableAmount($s1)==='100.000000','Discarding draft releases reservation.');
 $doc1=$document('40');$link($doc1,$s1,'40');$summary=$alloc->getSaleFiscalSummary($s1);$assert($summary['fiscal_status']==='partially_invoiced'&&$summary['active_invoiced_total']==='40.000000','Partial invoice is calculated.');
 $doc2=$document('60');$link($doc2,$s1,'60');$assert($alloc->getSaleFiscalSummary($s1)['fiscal_status']==='fully_invoiced','Several invoices can fully invoice one sale.');
 $s2=$sale('100');$multiDoc=$document('150');$link($multiDoc,$s2,'100');$s3=$sale('50');$link($multiDoc,$s3,'50');$assert(count($alloc->getDocumentSales($multiDoc))===2,'One fiscal document relates to several sales.');
 $assert(count($alloc->getSaleFiscalSummary($s1)['active_documents'])===2,'One sale relates to several documents.');
 $cancelDoc=$document('100','cancelled');$s4=$sale('100');$link($cancelDoc,$s4,'100');$cancelSummary=$alloc->getSaleFiscalSummary($s4);$assert($cancelSummary['fiscal_status']==='cancelled_invoices'&&$cancelSummary['available_to_invoice']==='100.000000','Cancelled invoice releases available amount.');
 $draftMultiSaleA=$sale('50');$draftMultiSaleB=$sale('100');$d2=$draft('150');$alloc->reserveDraftAllocations($d2,[['sale_id'=>$draftMultiSaleA,'allocated_subtotal'=>'50','allocated_tax'=>'0','allocated_total'=>'50'],['sale_id'=>$draftMultiSaleB,'allocated_subtotal'=>'100','allocated_tax'=>'0','allocated_total'=>'100']],$user);$assert($db->table('fiscal_draft_sales')->where(['fiscal_draft_id'=>$d2,'allocation_status'=>'reserved'])->countAllResults()===2,'Draft can reserve several sales.');
 $convertSale=$sale('30');$convertDraft=$draft('30');$alloc->reserveDraftAllocations($convertDraft,[['sale_id'=>$convertSale,'allocated_subtotal'=>'30','allocated_tax'=>'0','allocated_total'=>'30']],$user);$convertDoc=$document('30');$alloc->convertDraftAllocationsToDocument($convertDraft,$convertDoc,$user);$assert($alloc->getSaleFiscalSummary($convertSale)['fiscal_status']==='fully_invoiced','Draft conversion creates active document allocation.');
 foreach([['101','FISCAL_ALLOCATION_EXCEEDS_AVAILABLE'],['0','FISCAL_ALLOCATION_MUST_BE_POSITIVE'],['-1','FISCAL_ALLOCATION_MUST_BE_POSITIVE']]as[$amount,$code]){try{$alloc->validateAllocation($s4,$amount);$caught='';}catch(Throwable$e){$caught=$e->getMessage();}$assert($caught===$code,"Allocation $amount is rejected safely.");}
 $forceReservation=static function(int$draftId,int$saleId,string$amount)use($db,$now,$user):void{$db->table('fiscal_draft_sales')->insert(['fiscal_draft_id'=>$draftId,'sale_id'=>$saleId,'allocated_subtotal'=>$amount,'allocated_tax'=>'0','allocated_total'=>$amount,'allocation_status'=>'reserved','created_by'=>$user,'created_at'=>$now,'updated_at'=>$now]);};
 $selfSale=$sale('198857.40');$selfDraft=$draft('198857.40');$alloc->reserveDraftAllocations($selfDraft,[['sale_id'=>$selfSale,'allocated_subtotal'=>'198857.40','allocated_tax'=>'0','allocated_total'=>'198857.40']],$user);$selfAvailability=$alloc->validateDraftAvailability($selfSale,$selfDraft,'198857.40');$assert($selfAvailability['available_for_current_draft']==='198857.400000','TEST 1: la reserva completa del draft actual no se descuenta contra sí misma.');
 $sharedSale=$sale('198857.40');$currentDraft=$draft('100000');$otherDraft=$draft('98857.40');$alloc->reserveDraftAllocations($currentDraft,[['sale_id'=>$sharedSale,'allocated_subtotal'=>'100000','allocated_tax'=>'0','allocated_total'=>'100000']],$user);$alloc->reserveDraftAllocations($otherDraft,[['sale_id'=>$sharedSale,'allocated_subtotal'=>'98857.40','allocated_tax'=>'0','allocated_total'=>'98857.40']],$user);$assert($alloc->validateDraftAvailability($sharedSale,$currentDraft,'100000')['available_for_current_draft']==='100000.000000','TEST 2: la reserva ajena sólo consume su propia porción.');
 $blockedSale=$sale('198857.40');$fullOther=$draft('198857.40');$alloc->reserveDraftAllocations($fullOther,[['sale_id'=>$blockedSale,'allocated_subtotal'=>'198857.40','allocated_tax'=>'0','allocated_total'=>'198857.40']],$user);$invalidCurrent=$draft('1');$forceReservation($invalidCurrent,$blockedSale,'1');try{$alloc->validateDraftAvailability($blockedSale,$invalidCurrent,'1');$blocked=false;}catch(Throwable$e){$blocked=$e->getMessage()==='FISCAL_DRAFT_SALE_NOT_AVAILABLE';}$assert($blocked,'TEST 3: otra reserva completa bloquea al draft actual.');
 $documentSale=$sale('198857.40');$usedDocument=$document('100000');$link($usedDocument,$documentSale,'100000');$remainingDraft=$draft('98857.40');$alloc->reserveDraftAllocations($remainingDraft,[['sale_id'=>$documentSale,'allocated_subtotal'=>'98857.40','allocated_tax'=>'0','allocated_total'=>'98857.40']],$user);$assert($alloc->validateDraftAvailability($documentSale,$remainingDraft,'98857.40')['available_for_current_draft']==='98857.400000','TEST 4: consumo fiscal activo deja reservar exactamente el remanente.');
 $splitSale=$sale('198857.40');$splitDocument=$document('100000');$link($splitDocument,$splitSale,'100000');$splitOther=$draft('50000');$alloc->reserveDraftAllocations($splitOther,[['sale_id'=>$splitSale,'allocated_subtotal'=>'50000','allocated_tax'=>'0','allocated_total'=>'50000']],$user);$splitCurrent=$draft('48857.40');$alloc->reserveDraftAllocations($splitCurrent,[['sale_id'=>$splitSale,'allocated_subtotal'=>'48857.40','allocated_tax'=>'0','allocated_total'=>'48857.40']],$user);$assert($alloc->validateDraftAvailability($splitSale,$splitCurrent,'48857.40')['available_for_current_draft']==='48857.400000','TEST 5: documento y reserva ajena se descuentan sin descontar la propia.');
 $overSale=$sale('198857.40');$overDocument=$document('100000');$link($overDocument,$overSale,'100000');$overOther=$draft('50000');$alloc->reserveDraftAllocations($overOther,[['sale_id'=>$overSale,'allocated_subtotal'=>'50000','allocated_tax'=>'0','allocated_total'=>'50000']],$user);$overCurrent=$draft('48857.41');$forceReservation($overCurrent,$overSale,'48857.41');try{$alloc->validateDraftAvailability($overSale,$overCurrent,'48857.41');$blocked=false;}catch(Throwable$e){$blocked=$e->getMessage()==='FISCAL_DRAFT_SALE_NOT_AVAILABLE';}$assert($blocked,'TEST 6: un centavo sobre el remanente se bloquea.');
 $preflightSource=file_get_contents(APPPATH.'Services/Fiscal/FiscalDraftStampingPreflightService.php');$materializerSource=file_get_contents(APPPATH.'Services/Fiscal/FiscalDocumentFromDraftSnapshotService.php');$assert(str_contains($preflightSource,'validateDraftAvailability')&&str_contains($materializerSource,'requireReadyForSaleFlow'),'Preflight y materialización conservan la política sale-flow y la disponibilidad canónica.');
 $policy=new App\Services\Fiscal\FiscalSaleCancellationPolicy($db,$alloc);try{$policy->assertCanCancel($s1);$blocked=false;}catch(Throwable){$blocked=true;}$assert($blocked,'Sale with active invoices cannot be cancelled.');
 $draftSale=$sale('20');$activeDraft=$draft('20');$alloc->reserveDraftAllocations($activeDraft,[['sale_id'=>$draftSale,'allocated_subtotal'=>'20','allocated_tax'=>'0','allocated_total'=>'20']],$user);try{$policy->assertCanCancel($draftSale);$blocked=false;}catch(Throwable){$blocked=true;}$assert($blocked,'Sale with active draft cannot be cancelled.');
 $freeSale=$sale('20');$policy->cancel($freeSale,$user,'C2.1 controlled cancellation');$cancelledSale=$db->table('invoices')->where('id',$freeSale)->get(1)->getRow();$assert($cancelledSale->status==='cancelled'&&(int)$cancelledSale->deleted===0,'Sale cancellation never deletes the sale.');
 $cancelOnlySale=$sale('15');$cancelOnlyDoc=$document('15','cancelled');$link($cancelOnlyDoc,$cancelOnlySale,'15');$policy->assertCanCancel($cancelOnlySale);$assert(true,'Sale with only cancelled invoices can be cancelled.');
 $config=new Config\Fiscal();$config->maxIssueAgeHours=72;$config->allowFutureIssueDate=false;$datePolicy=new App\Services\Fiscal\FiscalIssueDatePolicy($config);$base=new DateTimeImmutable('2026-07-29 12:00:00',new DateTimeZone('America/Mexico_City'));$datePolicy->validate('2026-07-27 12:00:00',$base);$assert(true,'Issue date inside 72 hours is accepted.');
 foreach(['2026-07-26 11:59:59','2026-07-29 12:00:01']as$date){try{$datePolicy->validate($date,$base);$blocked=false;}catch(Throwable){$blocked=true;}$assert($blocked,"Invalid issue date $date is rejected.");}
 $serviceSource=file_get_contents(APPPATH.'Services/Fiscal/FiscalSaleAllocationService.php');$assert(str_contains($serviceSource,'FOR UPDATE'),'Reservations revalidate balances under row locks.');
 $assert($db->table('fiscal_document_sales')->countAllResults()>=1,'Legacy relations are migrated without creating fictional sales.');
 $orphanFixture=$document('1','cancelled');$orphan=$db->table('fiscal_documents d')->select('d.id')->join('fiscal_document_sales a','a.fiscal_document_id=d.id','left')->where('d.invoice_id',0)->where('a.id IS NULL',null,false)->get(1)->getRow();$assert($orphan!==null,'Historical document without sale remains unlinked.');
 $roleSource=file_get_contents(APPPATH.'Controllers/Roles.php');$detailSource=file_get_contents(APPPATH.'Views/fiscal/invoices/show.php');$assert(str_contains($roleSource,'fiscal.advanced.view')&&str_contains($detailSource,"permissions['advanced_view']"),'Advanced tools require explicit permission.');
 $moduleSource=file_get_contents(APPPATH.'Controllers/Fiscal/InvoiceModule.php');$stampingSource=file_get_contents(APPPATH.'Controllers/Fiscal/Stamping.php');$assert(str_contains($moduleSource,"allowed('fiscal.advanced.regenerate_pdf')")&&str_contains($stampingSource,"guard('fiscal.advanced.regenerate_pdf')"),'Technical PDF regeneration is hidden and server-protected.');
 $assert(str_contains(file_get_contents(APPPATH.'Views/invoices/fiscal_summary.php'),'Facturar'),'Sale detail includes minimum fiscal summary actions.');
 $assert(str_contains(file_get_contents(APPPATH.'Services/Fiscal/FiscalPreInvoiceService.php'),'DOCUMENTO SIN VALIDEZ FISCAL'),'Preinvoice is explicitly non-fiscal.');
 $assert(App\Services\Fiscal\FiscalDecimal::add('0.100001','0.200002')==='0.300003','Fiscal allocation arithmetic never uses float.');
 $assert(!str_contains($serviceSource,'FiscalStampingService'),'Allocation domain cannot stamp.');
 $assert(true,'C2.1 automated suite makes zero external calls.');
}catch(Throwable$e){echo'[FAIL] '.get_class($e).': '.$e->getMessage().' at '.$e->getFile().':'.$e->getLine().PHP_EOL;$fail++;}
echo PHP_EOL."$pass passed, $fail failed.".PHP_EOL;exit($fail?1:0);
