<?php
declare(strict_types=1);

foreach(['fiscal.enabled'=>'false','fiscal.stampingEnabled'=>'false','fiscal.allowRealPac'=>'false','fiscal.runtimeMode'=>'automated_test','fiscal.pacAdapter'=>'fake']as$key=>$value){putenv($key.'='.$value);$_ENV[$key]=$_SERVER[$key]=$value;}
require dirname(__DIR__).'/bootstrap.php';
require_once APPPATH.'Database/Migrations/2026-09-29-120000_CreateCanonicalPaymentComplementExternalDocuments.php';
require_once APPPATH.'Database/Migrations/2026-09-30-100000_AddCanonicalFiscalStampTransportEvidence.php';

use App\Database\Migrations\AddCanonicalFiscalStampTransportEvidence;
use App\Database\Migrations\CreateCanonicalPaymentComplementExternalDocuments;
use App\Services\PaymentComplementCfdiMaterializer;
use App\Services\PaymentComplementExternalDocumentService;
use App\Services\PaymentComplementFiscalSnapshotService;
use App\Services\PaymentComplementRelatedDocumentNormalizer;
use Config\Database;

$server=null;$db=null;$owned=null;$passed=0;$failed=0;
$assert=static function(bool$ok,string$label)use(&$passed,&$failed):void{echo($ok?'[PASS] ':'[FAIL] ').$label.PHP_EOL;$ok?$passed++:$failed++;};
$reject=static function(callable$action,string$label)use($assert):void{try{$action();$assert(false,$label);}catch(Throwable){$assert(true,$label);}};
try{
    $local=config(Database::class)->default;if(!in_array($local['hostname'],['localhost','127.0.0.1','::1'],true))throw new RuntimeException('P11 requires a local MySQL fixture server.');
    mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$server=new mysqli($local['hostname'],$local['username'],$local['password'],'',(int)$local['port']);$owned='ikontrol_test_p11_'.bin2hex(random_bytes(6));$server->query('CREATE DATABASE `'.$owned.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci');
    $db=Database::connect(array_replace($local,['DSN'=>'','database'=>$owned,'DBDriver'=>'MySQLi','DBPrefix'=>'p11_','pConnect'=>false,'DBDebug'=>true,'failover'=>[]]),false);$forge=Database::forge($db);
    $assert($db->query('SELECT DATABASE() n')->getRow()->n===$owned,'1. Owned isolated MySQL schema verified.');
    $make=static function(string$table,array$fields,array$keys=[])use($forge):void{$forge->addField($fields);$forge->addKey('id',true);foreach($keys as$columns=>$name)$forge->addUniqueKey(explode(',',$columns),$name);$forge->createTable($table);};
    $id=['type'=>'INT','unsigned'=>true,'auto_increment'=>true];$int=['type'=>'INT','unsigned'=>true];$nullableInt=['type'=>'INT','unsigned'=>true,'null'=>true];$decimal=['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0.000000'];$date=['type'=>'DATETIME','null'=>true];
    $make('invoices',['id'=>$id,'sentinel'=>['type'=>'VARCHAR','constraint'=>20]]);$make('payment_allocations',['id'=>$id,'sentinel'=>['type'=>'VARCHAR','constraint'=>20]]);$make('financial_account_movements',['id'=>$id,'sentinel'=>['type'=>'VARCHAR','constraint'=>20]]);
    $make('invoice_payments',['id'=>$id,'amount'=>$decimal,'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'active'],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'sentinel'=>['type'=>'VARCHAR','constraint'=>20]]);
    $make('sat_currencies',['id'=>$id,'code'=>['type'=>'CHAR','constraint'=>3],'is_active'=>['type'=>'TINYINT','constraint'=>1,'default'=>1]],['code'=>'uq_currency']);
    $make('payment_complements',['id'=>$id,'status'=>['type'=>'VARCHAR','constraint'=>30],'fiscal_document_id'=>$nullableInt,'updated_at'=>$date,'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);
    $make('payment_complement_payments',['id'=>$id,'payment_complement_id'=>$int,'source_invoice_payment_id'=>$int,'currency_code'=>['type'=>'CHAR','constraint'=>3],'amount'=>$decimal,'updated_at'=>$date,'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);
    $make('fiscal_documents',['id'=>$id,'invoice_id'=>$int,'series'=>['type'=>'VARCHAR','constraint'=>25,'default'=>''],'folio'=>['type'=>'VARCHAR','constraint'=>40,'default'=>''],'payment_method_code'=>['type'=>'VARCHAR','constraint'=>3,'default'=>'PPD'],'currency_code'=>['type'=>'CHAR','constraint'=>3,'default'=>'MXN'],'total'=>$decimal,'status'=>['type'=>'VARCHAR','constraint'=>30],'cancelled_at'=>$date,'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);
    $make('fiscal_document_stamps',['id'=>$id,'fiscal_document_id'=>$int,'uuid'=>['type'=>'CHAR','constraint'=>36]]);
    $make('fiscal_document_items',['id'=>$id,'fiscal_document_id'=>$int,'line_number'=>$int,'tax_object_code'=>['type'=>'CHAR','constraint'=>2]]);
    $make('fiscal_document_item_taxes',['id'=>$id,'fiscal_document_item_id'=>$int,'tax_code'=>['type'=>'CHAR','constraint'=>3],'tax_type'=>['type'=>'VARCHAR','constraint'=>20],'factor_type'=>['type'=>'VARCHAR','constraint'=>10],'rate_or_quota'=>['type'=>'DECIMAL','constraint'=>'18,6','null'=>true],'taxable_base'=>$decimal,'amount'=>['type'=>'DECIMAL','constraint'=>'18,6','null'=>true],'sort_order'=>$int]);
    $make('payment_complement_documents',['id'=>$id,'payment_complement_payment_id'=>$int,'payment_allocation_id'=>$nullableInt,'invoice_id'=>$int,'fiscal_document_id'=>$int,'document_uuid'=>['type'=>'CHAR','constraint'=>36],'currency_dr'=>['type'=>'CHAR','constraint'=>3],'equivalence_dr'=>['type'=>'DECIMAL','constraint'=>'28,10'],'installment_number'=>$int,'previous_balance'=>$decimal,'amount_paid'=>$decimal,'remaining_balance'=>$decimal,'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);
    $make('payment_complement_fiscal_snapshots',['id'=>$id,'payment_complement_id'=>$int,'version'=>$int,'status'=>['type'=>'VARCHAR','constraint'=>20],'payload_json'=>['type'=>'LONGTEXT'],'xml_content'=>['type'=>'LONGTEXT'],'sha256'=>['type'=>'CHAR','constraint'=>64],'created_by'=>$nullableInt,'created_at'=>$date]);
    $make('fiscal_stamp_attempts',['id'=>$id,'operation'=>['type'=>'VARCHAR','constraint'=>80],'sent_at'=>$date,'status'=>['type'=>'VARCHAR','constraint'=>40],'requires_reconciliation'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);

    foreach(['invoices','payment_allocations','financial_account_movements']as$table)$db->table($table)->insert(['id'=>1,'sentinel'=>'preserve']);$db->table('invoice_payments')->insert(['id'=>1,'amount'=>'1000','status'=>'active','deleted'=>0,'sentinel'=>'preserve']);foreach(['MXN','USD','EUR']as$currency)$db->table('sat_currencies')->insert(['code'=>$currency,'is_active'=>1]);
    $before=[];foreach(['invoices','invoice_payments','payment_allocations','financial_account_movements']as$table)$before[$table]=$db->table($table)->get()->getResultArray();
    (new CreateCanonicalPaymentComplementExternalDocuments($forge))->up();(new AddCanonicalFiscalStampTransportEvidence($forge))->up();
    $assert($db->tableExists('payment_complement_external_documents')&&$db->tableExists('payment_complement_external_taxes'),'2. Directed P04 migration applied.');
    $attemptFields=array_column($db->getFieldData('fiscal_stamp_attempts'),'name');$assert(in_array('request_sent',$attemptFields,true)&&in_array('pac_endpoint',$attemptFields,true),'3. Directed P10 migration applied ['.implode(',',$attemptFields).'].');
    $assert(array_column($db->getFieldData('fiscal_documents'),null,'name')['invoice_id']->nullable,'4. Payment fiscal document permits nullable invoice_id.');

    for($i=1;$i<=3;$i++){$db->table('payment_complements')->insert(['id'=>$i,'status'=>'draft','fiscal_document_id'=>null,'deleted'=>0]);$db->table('payment_complement_payments')->insert(['id'=>$i,'payment_complement_id'=>$i,'source_invoice_payment_id'=>1,'currency_code'=>'MXN','amount'=>'0','deleted'=>0]);}
    $internalUuid='11111111-1111-1111-1111-111111111111';$db->table('fiscal_documents')->insert(['id'=>10,'invoice_id'=>1,'series'=>'A','folio'=>'10','payment_method_code'=>'PPD','currency_code'=>'MXN','total'=>'1160','status'=>'stamped','deleted'=>0]);$db->table('fiscal_document_stamps')->insert(['fiscal_document_id'=>10,'uuid'=>$internalUuid]);$db->table('fiscal_document_items')->insert(['id'=>10,'fiscal_document_id'=>10,'line_number'=>1,'tax_object_code'=>'02']);$db->table('fiscal_document_item_taxes')->insert(['fiscal_document_item_id'=>10,'tax_code'=>'002','tax_type'=>'transferred','factor_type'=>'Tasa','rate_or_quota'=>'0.160000','taxable_base'=>'1000','amount'=>'160','sort_order'=>1]);$db->table('payment_complement_documents')->insert(['payment_complement_payment_id'=>1,'invoice_id'=>1,'fiscal_document_id'=>10,'document_uuid'=>$internalUuid,'currency_dr'=>'MXN','equivalence_dr'=>'1','installment_number'=>1,'previous_balance'=>'1160','amount_paid'=>'580','remaining_balance'=>'580','deleted'=>0]);$db->table('payment_complement_payments')->where('id',1)->update(['amount'=>'580']);
    $normalizer=new PaymentComplementRelatedDocumentNormalizer($db);$internal=$normalizer->forPayment(1,1);$assert(count($internal)===1&&$internal[0]['source_type']==='internal'&&$internal[0]['invoice_id']===1,'5. Internal invoice normalizes with administrative identity preserved.');$assert($internal[0]['Serie']==='A'&&$internal[0]['Folio']==='10'&&$internal[0]['MetodoDePagoDR']==='PPD','6. Internal normalized CFDI freezes series folio and payment method.');

    $externalService=new PaymentComplementExternalDocumentService($db);$externalInput=['uuid'=>'22222222-2222-2222-2222-222222222222','series'=>'EXT','folio'=>'20','currency_code'=>'MXN','equivalence_dr'=>'1','payment_method_code'=>'PPD','tax_object_code'=>'02','installment_number'=>2,'previous_balance'=>'232','paid_amount'=>'116','remaining_balance'=>'116','taxes'=>[['tax_type'=>'transfer','base'=>'100','tax_code'=>'002','factor_type'=>'Tasa','rate_or_quota'=>'0.160000','amount'=>'16'],['tax_type'=>'withholding','base'=>'100','tax_code'=>'001','factor_type'=>'Tasa','rate_or_quota'=>'0.100000','amount'=>'10']]];$externalId=$externalService->save(2,0,$externalInput,9);$external=$normalizer->forPayment(2,2);$assert(count($external)===1&&$external[0]['source_type']==='external'&&$external[0]['invoice_id']===null,'7. External-only CFDI normalizes without invoice.');$assert(count($external[0]['ImpuestosDR']['TrasladosDR'])===1&&count($external[0]['ImpuestosDR']['RetencionesDR'])===1,'8. External preserves multiple transfer and withholding taxes.');
    $assert((string)$db->table('payment_complement_payments')->where('id',2)->get()->getRow()->amount==='116.000000','9. External amount synchronizes fiscal payment only.');
    $db->table('payment_complement_documents')->insert(['payment_complement_payment_id'=>2,'invoice_id'=>1,'fiscal_document_id'=>10,'document_uuid'=>$internalUuid,'currency_dr'=>'MXN','equivalence_dr'=>'1','installment_number'=>1,'previous_balance'=>'1160','amount_paid'=>'580','remaining_balance'=>'580','deleted'=>0]);$db->table('payment_complement_payments')->where('id',2)->update(['amount'=>'696']);$mixed=$normalizer->forPayment(2,2);$assert(count($mixed)===2&&array_column($mixed,'source_type')===['internal','external'],'10. Mixed complement returns deterministic internal/external documents.');

    $duplicate=$externalInput;$duplicate['uuid']=$internalUuid;$reject(fn()=>$externalService->save(2,0,$duplicate,9),'11. UUID duplicate across internal/external is rejected.');
    $usd=$externalInput;$usd['uuid']='33333333-3333-3333-3333-333333333333';$usd['currency_code']='USD';$usd['equivalence_dr']='0.1234567890';$usd['tax_object_code']='01';$usd['previous_balance']='10';$usd['paid_amount']='5';$usd['remaining_balance']='5';$usd['taxes']=[];$usdId=$externalService->save(3,0,$usd,9);$assert((string)$db->table('payment_complement_payments')->where('id',3)->get()->getRow()->amount==='40.500000','12. Foreign MonedaDR keeps ten-decimal EquivalenciaDR precision.');
    $exempt=$externalInput;$exempt['uuid']='44444444-4444-4444-4444-444444444444';$exempt['taxes']=[['tax_type'=>'transfer','base'=>'10','tax_code'=>'002','factor_type'=>'Exento','rate_or_quota'=>null,'amount'=>null]];$exempt['paid_amount']='10';$exempt['previous_balance']='10';$exempt['remaining_balance']='0';$exemptId=$externalService->save(3,0,$exempt,9);$docs3=$normalizer->forPayment(3,3);$assert(count($docs3)===2&&count(array_unique(array_column($docs3,'IdDocumento')))===2,'13. Multiple external documents coexist.');$exemptDoc=array_values(array_filter($docs3,fn($d)=>$d['IdDocumento']===$exempt['uuid']))[0];$assert(!isset($exemptDoc['ImpuestosDR']['TrasladosDR'][0]['ImporteDR']),'14. Exempt tax omits rate and amount.');

    $snapshot=['issue_date'=>'2026-09-30T12:00:00','issuer'=>['rfc'=>'AAA010101AAA','legal_name'=>'EMISOR','tax_regime_code'=>'601','expedition_postal_code'=>'06000'],'receiver'=>['rfc'=>'XAXX010101000','legal_name'=>'RECEPTOR','tax_regime_code'=>'616','fiscal_postal_code'=>'06000'],'sat_totals'=>['MontoTotalPagos'=>'696.00'],'totals'=>['TrasladosP'=>[],'RetencionesP'=>[]],'payments'=>[['FechaPago'=>'2026-09-30T12:00:00','FormaDePagoP'=>'03','MonedaP'=>'MXN','TipoCambioP'=>'1','Monto'=>'696','DoctoRelacionado'=>$mixed]]];$xml=(new PaymentComplementCfdiMaterializer())->materialize($snapshot);$assert(substr_count($xml,'<pago20:DoctoRelacionado ')===2&&str_contains($xml,'IdDocumento="'.$internalUuid.'"')&&str_contains($xml,'IdDocumento="'.$externalInput['uuid'].'"'),'15. Materializer consumes normalized mixed documents.');$assert(str_contains($xml,'pago20:TrasladoDR')&&str_contains($xml,'pago20:RetencionDR'),'16. XML materializes persisted DR transfers and withholdings.');$assert(str_contains($xml,'Serie="A"')&&str_contains($xml,'Folio="10"')&&str_contains($xml,'EquivalenciaDR="1"'),'17. XML contains frozen identity balances and MXN equivalence.');

    $frozenPayload=$snapshot;$frozenPayload['version']=8;$frozenPayload['complement_id']=2;$frozenPayload['xml']=$xml;$integrity=$frozenPayload;unset($integrity['xml']);$frozenPayload['sha256']=hash('sha256',json_encode($integrity,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$db->table('payment_complement_fiscal_snapshots')->insert(['payment_complement_id'=>2,'version'=>1,'status'=>'frozen','payload_json'=>json_encode($frozenPayload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'xml_content'=>$xml,'sha256'=>$frozenPayload['sha256'],'created_by'=>9,'created_at'=>gmdate('Y-m-d H:i:s')]);$firstFrozen=(new PaymentComplementFiscalSnapshotService($db))->compose(2);$db->table('payment_complement_external_documents')->where('id',$externalId)->update(['folio'=>'CHANGED']);$secondFrozen=(new PaymentComplementFiscalSnapshotService($db))->compose(2);$assert($firstFrozen===$secondFrozen&&str_contains($secondFrozen['xml'],'Folio="20"'),'18. Frozen snapshot ignores later source changes.');$reject(fn()=>$externalService->save(2,$externalId,$externalInput,9),'19. External edit is blocked after snapshot.');$reject(fn()=>$externalService->remove(2,$externalId),'20. External removal is blocked after snapshot.');
    $externalService->remove(3,$usdId);$assert(count($normalizer->forPayment(3,3))===1,'21. External document can be removed before snapshot.');

    $after=[];foreach(['invoices','invoice_payments','payment_allocations','financial_account_movements']as$table)$after[$table]=$db->table($table)->get()->getResultArray();$assert($before===$after,'22/23/24. External and mixed flow creates no invoice allocation or financial movement.');
    $assert($db->table('payment_complement_documents')->where('payment_complement_payment_id',2)->countAllResults()===1,'25. Mixed flow does not duplicate internal payment allocation/document relation.');
    $beforeExternal=$db->table('payment_complement_external_documents')->countAllResults();$reject(fn()=>$externalService->save(3,0,array_replace($externalInput,['uuid'=>'bad']),9),'26. Invalid external write rolls back.');$assert($db->table('payment_complement_external_documents')->countAllResults()===$beforeExternal,'27. Failed external transaction leaves no partial document.');
    $source=file_get_contents(APPPATH.'FiscalServices/PaymentComplementFiscalDocumentService.php');$stamping=file_get_contents(APPPATH.'FiscalServices/PaymentComplementStampingService.php');$routes=file_get_contents(APPPATH.'Config/Routes.php');$assert(str_contains($source,"'invoice_id'=>\$invoiceId")&&str_contains($source,'FiscalRuntimeContext::fiscalEnvironment'),'28. Fiscal document supports external-only origin and canonical environment.');$assert(str_contains($stamping,'PaymentComplementFiscalSnapshotService')&&str_contains($stamping,'FiscalStampingService'),'29. Complement stamping freezes snapshot then delegates to P10 pipeline.');$assert(substr_count($routes,'external-documents')===3&&substr_count($routes,"['filter' => 'csrf']")>=3,'30. External mutations are explicit POST routes with CSRF.');
    echo "{$passed} passed, {$failed} failed. No source database or PAC accessed.\n";
}catch(Throwable$e){fwrite(STDERR,'[FAIL] '.get_class($e).': '.$e->getMessage().PHP_EOL.$e->getTraceAsString().PHP_EOL);$failed++;}
finally{if($db)$db->close();if($server&&$owned){if(!preg_match('/^ikontrol_test_p11_[a-f0-9]{12}$/D',$owned))throw new RuntimeException('Unsafe cleanup target.');$server->query('DROP DATABASE `'.$owned.'`');$server->close();echo "Owned synthetic MySQL schema removed.\n";}}
exit($failed?1:0);
