<?php
declare(strict_types=1); namespace App\Database\Migrations; use CodeIgniter\Database\Migration;
final class CreateSupplierCostHistory extends Migration{
 public function up(){
  if(!$this->db->tableExists('suppliers')){$this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'name'=>['type'=>'VARCHAR','constraint'=>180],'contact_name'=>['type'=>'VARCHAR','constraint'=>150,'null'=>true],'phone'=>['type'=>'VARCHAR','constraint'=>40,'null'=>true],'email'=>['type'=>'VARCHAR','constraint'=>180,'null'=>true],'notes'=>['type'=>'TEXT','null'=>true],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'active'],'created_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME'],'updated_at'=>['type'=>'DATETIME'],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);$this->forge->addKey('id',true);$this->forge->addKey(['status','deleted']);$this->forge->addUniqueKey(['name','deleted'],'uq_supplier_name_active');$this->forge->createTable('suppliers');}
  if(!$this->db->fieldExists('supplier_id','proposal_items')){$this->forge->addColumn('proposal_items',['supplier_id'=>['type'=>'INT','unsigned'=>true,'null'=>true,'after'=>'item_id']]);$this->db->query('ALTER TABLE '.$this->db->prefixTable('proposal_items').' ADD KEY idx_proposal_item_supplier (supplier_id), ADD CONSTRAINT fk_proposal_item_supplier FOREIGN KEY (supplier_id) REFERENCES '.$this->db->prefixTable('suppliers').'(id) ON DELETE RESTRICT ON UPDATE RESTRICT');}
  if(!$this->db->tableExists('product_supplier_cost_history')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'product_id'=>['type'=>'INT'],'supplier_id'=>['type'=>'INT','unsigned'=>true],'proposal_id'=>['type'=>'INT'],'proposal_item_id'=>['type'=>'INT'],'client_id'=>['type'=>'INT'],'unit_cost'=>['type'=>'DECIMAL','constraint'=>'18,6'],'sale_unit_price'=>['type'=>'DECIMAL','constraint'=>'18,6'],'quantity'=>['type'=>'DECIMAL','constraint'=>'18,6'],'currency'=>['type'=>'CHAR','constraint'=>3,'default'=>'MXN'],'quoted_at'=>['type'=>'DATETIME'],'recorded_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME'],'source_status'=>['type'=>'VARCHAR','constraint'=>20],'snapshot_version'=>['type'=>'INT','unsigned'=>true,'default'=>1],'economic_hash'=>['type'=>'CHAR','constraint'=>64]]);$this->forge->addKey('id',true);$this->forge->addUniqueKey(['proposal_item_id','economic_hash'],'uq_supplier_cost_item_economic');$this->forge->addKey(['product_id','quoted_at']);$this->forge->addKey(['supplier_id','quoted_at']);$this->forge->addKey(['proposal_id','source_status']);$this->forge->addForeignKey('product_id','items','id','RESTRICT','RESTRICT','fk_cost_history_product');$this->forge->addForeignKey('supplier_id','suppliers','id','RESTRICT','RESTRICT','fk_cost_history_supplier');$this->forge->addForeignKey('proposal_id','proposals','id','RESTRICT','RESTRICT','fk_cost_history_proposal');$this->forge->addForeignKey('proposal_item_id','proposal_items','id','RESTRICT','RESTRICT','fk_cost_history_proposal_item');$this->forge->addForeignKey('client_id','clients','id','RESTRICT','RESTRICT','fk_cost_history_client');$this->forge->createTable('product_supplier_cost_history');}
 }
 public function down(){if($this->db->tableExists('product_supplier_cost_history'))$this->forge->dropTable('product_supplier_cost_history');if($this->db->fieldExists('supplier_id','proposal_items')){$this->db->query('ALTER TABLE '.$this->db->prefixTable('proposal_items').' DROP FOREIGN KEY fk_proposal_item_supplier');$this->forge->dropColumn('proposal_items','supplier_id');}if($this->db->tableExists('suppliers'))$this->forge->dropTable('suppliers');}
}
