<?php
declare(strict_types=1);
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
final class CreateFiscalCreditNotes extends Migration{
 public function up(){
  if(!$this->db->tableExists('fiscal_credit_notes')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'source_fiscal_document_id'=>['type'=>'BIGINT','unsigned'=>true],'source_invoice_id'=>['type'=>'INT','unsigned'=>true],'fiscal_document_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'client_id'=>['type'=>'INT','unsigned'=>true],'issuer_profile_id'=>['type'=>'INT','unsigned'=>true],'receiver_profile_id'=>['type'=>'INT','unsigned'=>true],'issue_date'=>['type'=>'DATETIME'],'relation_type_code'=>['type'=>'VARCHAR','constraint'=>3,'default'=>'01'],'currency_code'=>['type'=>'CHAR','constraint'=>3,'default'=>'MXN'],'payment_form_code'=>['type'=>'VARCHAR','constraint'=>3],'payment_method_code'=>['type'=>'VARCHAR','constraint'=>3],'cfdi_use_code'=>['type'=>'VARCHAR','constraint'=>5,'default'=>'G02'],'status'=>['type'=>'VARCHAR','constraint'=>30,'default'=>'draft'],'subtotal'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0'],'discount'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0'],'transferred_tax_total'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0'],'withheld_tax_total'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0'],'total'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0'],'created_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME'],'updated_at'=>['type'=>'DATETIME'],'stamped_at'=>['type'=>'DATETIME','null'=>true],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);$this->forge->addKey('id',true);$this->forge->addUniqueKey('fiscal_document_id','uq_credit_note_fiscal_document');foreach(['source_fiscal_document_id','source_invoice_id','client_id','status']as$k)$this->forge->addKey($k);$this->forge->addForeignKey('source_fiscal_document_id','fiscal_documents','id','RESTRICT','RESTRICT','fk_cn_source_doc');$this->forge->addForeignKey('fiscal_document_id','fiscal_documents','id','RESTRICT','RESTRICT','fk_cn_fiscal_doc');$this->forge->createTable('fiscal_credit_notes');}
  if(!$this->db->tableExists('fiscal_credit_note_items')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'fiscal_credit_note_id'=>['type'=>'BIGINT','unsigned'=>true],'source_fiscal_document_item_id'=>['type'=>'BIGINT','unsigned'=>true],'quantity'=>['type'=>'DECIMAL','constraint'=>'18,6'],'unit_value'=>['type'=>'DECIMAL','constraint'=>'18,6'],'discount'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0'],'subtotal'=>['type'=>'DECIMAL','constraint'=>'18,6'],'transferred_tax_total'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0'],'withheld_tax_total'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0'],'total'=>['type'=>'DECIMAL','constraint'=>'18,6'],'created_at'=>['type'=>'DATETIME'],'updated_at'=>['type'=>'DATETIME'],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);$this->forge->addKey('id',true);$this->forge->addUniqueKey(['fiscal_credit_note_id','source_fiscal_document_item_id'],'uq_credit_note_source_line');$this->forge->addKey('source_fiscal_document_item_id');$this->forge->addForeignKey('fiscal_credit_note_id','fiscal_credit_notes','id','CASCADE','RESTRICT','fk_cn_item_note');$this->forge->addForeignKey('source_fiscal_document_item_id','fiscal_document_items','id','RESTRICT','RESTRICT','fk_cn_item_source');$this->forge->createTable('fiscal_credit_note_items');}
 }
 public function down(){$this->forge->dropTable('fiscal_credit_note_items',true);$this->forge->dropTable('fiscal_credit_notes',true);}
}