<?php
declare(strict_types=1);
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;use RuntimeException;
final class CreateFiscalPdfProviderWorkflow extends Migration{
 public function up():void{
  foreach(['fiscal_profiles','fiscal_documents','fiscal_document_stamps','fiscal_stamp_attempts','fiscal_document_binary_artifacts']as$t)if(!$this->db->tableExists($t))throw new RuntimeException("PDF workflow precondition missing: $t");
  if(!$this->db->tableExists('fiscal_issuer_pdf_templates')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'issuer_id'=>['type'=>'BIGINT','unsigned'=>true],'provider'=>['type'=>'VARCHAR','constraint'=>40],'document_type'=>['type'=>'CHAR','constraint'=>1],'template_code'=>['type'=>'VARCHAR','constraint'=>40],'is_active'=>['type'=>'TINYINT','constraint'=>1,'default'=>1],'created_by'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'updated_by'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME'],'updated_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addUniqueKey(['issuer_id','provider','document_type'],'uq_fiscal_pdf_template');foreach(['issuer_id','provider','document_type','is_active']as$k)$this->forge->addKey($k);$this->forge->createTable('fiscal_issuer_pdf_templates');}
  if(!$this->db->tableExists('fiscal_pdf_generation_attempts')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'document_id'=>['type'=>'BIGINT','unsigned'=>true],'stamp_id'=>['type'=>'BIGINT','unsigned'=>true],'stamp_attempt_id'=>['type'=>'BIGINT','unsigned'=>true],'uuid'=>['type'=>'CHAR','constraint'=>36],'provider'=>['type'=>'VARCHAR','constraint'=>40],'environment'=>['type'=>'VARCHAR','constraint'=>20],'template_code'=>['type'=>'VARCHAR','constraint'=>40],'status'=>['type'=>'VARCHAR','constraint'=>30],'provider_code'=>['type'=>'VARCHAR','constraint'=>50,'null'=>true],'provider_message'=>['type'=>'TEXT','null'=>true],'request_sent'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'retryable'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'requires_reconciliation'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'idempotency_key'=>['type'=>'CHAR','constraint'=>64],'started_at'=>['type'=>'DATETIME','null'=>true],'completed_at'=>['type'=>'DATETIME','null'=>true],'created_by'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME'],'updated_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addUniqueKey('idempotency_key','uq_fiscal_pdf_attempt_idempotency');foreach(['document_id','stamp_id','stamp_attempt_id','uuid','status']as$k)$this->forge->addKey($k);$this->forge->createTable('fiscal_pdf_generation_attempts');}
  if(!$this->db->tableExists('fiscal_pdf_template_audit')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'template_id'=>['type'=>'BIGINT','unsigned'=>true],'issuer_id'=>['type'=>'BIGINT','unsigned'=>true],'action'=>['type'=>'VARCHAR','constraint'=>40],'old_template_code'=>['type'=>'VARCHAR','constraint'=>40,'null'=>true],'new_template_code'=>['type'=>'VARCHAR','constraint'=>40,'null'=>true],'user_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addKey('template_id');$this->forge->addKey('issuer_id');$this->forge->createTable('fiscal_pdf_template_audit');}
  $f=[];foreach(['pdf_generation_attempt_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true,'after'=>'stamp_attempt_id'],'template_code'=>['type'=>'VARCHAR','constraint'=>40,'null'=>true,'after'=>'template'],'artifact_status'=>['type'=>'VARCHAR','constraint'=>20,'null'=>true,'after'=>'validation_status'],'superseded_at'=>['type'=>'DATETIME','null'=>true,'after'=>'created_at']]as$n=>$d)if(!$this->db->fieldExists($n,'fiscal_document_binary_artifacts'))$f[$n]=$d;if($f)$this->forge->addColumn('fiscal_document_binary_artifacts',$f);
  $i=$this->db->getIndexData('fiscal_document_binary_artifacts');if(isset($i['uq_fiscal_binary_document_type']))$this->db->query('ALTER TABLE '.$this->db->protectIdentifiers($this->db->prefixTable('fiscal_document_binary_artifacts')).' DROP INDEX `uq_fiscal_binary_document_type`');$i=$this->db->getIndexData('fiscal_document_binary_artifacts');if(!isset($i['idx_fiscal_binary_active']))$this->db->query('CREATE INDEX `idx_fiscal_binary_active` ON '.$this->db->protectIdentifiers($this->db->prefixTable('fiscal_document_binary_artifacts')).' (`fiscal_document_id`,`artifact_type`,`artifact_status`)');
 }
 public function down():void{if($this->db->tableExists('fiscal_document_binary_artifacts')){$i=$this->db->getIndexData('fiscal_document_binary_artifacts');if(isset($i['idx_fiscal_binary_active']))$this->db->query('ALTER TABLE '.$this->db->protectIdentifiers($this->db->prefixTable('fiscal_document_binary_artifacts')).' DROP INDEX `idx_fiscal_binary_active`');foreach(['superseded_at','artifact_status','template_code','pdf_generation_attempt_id']as$f)if($this->db->fieldExists($f,'fiscal_document_binary_artifacts'))$this->forge->dropColumn('fiscal_document_binary_artifacts',$f);}foreach(['fiscal_pdf_template_audit','fiscal_pdf_generation_attempts','fiscal_issuer_pdf_templates']as$t)if($this->db->tableExists($t))$this->forge->dropTable($t);}
}
