<?php
declare(strict_types=1);
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
final class CreateWarehouseTransfers extends Migration {
 public function up(){
  if(!$this->db->tableExists('warehouse_transfers')){$this->forge->addField([
   'id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'folio'=>['type'=>'VARCHAR','constraint'=>30,'null'=>true],
   'origin_warehouse_id'=>['type'=>'INT','unsigned'=>true],'destination_warehouse_id'=>['type'=>'INT','unsigned'=>true],
   'transfer_date'=>['type'=>'DATETIME'],'status'=>['type'=>'VARCHAR','constraint'=>30,'default'=>'draft'],
   'carrier'=>['type'=>'VARCHAR','constraint'=>120,'null'=>true],'tracking_number'=>['type'=>'VARCHAR','constraint'=>120,'null'=>true],
   'tracking_created_at'=>['type'=>'DATETIME','null'=>true],'picked_up_at'=>['type'=>'DATETIME','null'=>true],'dispatched_at'=>['type'=>'DATETIME','null'=>true],
   'estimated_arrival_at'=>['type'=>'DATETIME','null'=>true],'received_at'=>['type'=>'DATETIME','null'=>true],
   'reference_type'=>['type'=>'VARCHAR','constraint'=>40,'null'=>true],'reference_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],
   'reference_text'=>['type'=>'VARCHAR','constraint'=>220,'null'=>true],'notes'=>['type'=>'TEXT','null'=>true],
   'dispatch_movement_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'created_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],
   'cancelled_at'=>['type'=>'DATETIME','null'=>true],'cancelled_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],
   'created_at'=>['type'=>'DATETIME'],'updated_at'=>['type'=>'DATETIME'],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]
  ]);$this->forge->addKey('id',true);$this->forge->addUniqueKey('folio');$this->forge->addKey(['origin_warehouse_id','status','transfer_date']);$this->forge->addKey(['destination_warehouse_id','status','transfer_date']);$this->forge->addKey('tracking_number');$this->forge->addForeignKey('origin_warehouse_id','warehouses','id','RESTRICT','RESTRICT','fk_wt_origin');$this->forge->addForeignKey('destination_warehouse_id','warehouses','id','RESTRICT','RESTRICT','fk_wt_destination');$this->forge->addForeignKey('dispatch_movement_id','warehouse_movements','id','RESTRICT','RESTRICT','fk_wt_dispatch_movement');$this->forge->createTable('warehouse_transfers');}
  if(!$this->db->tableExists('warehouse_transfer_lines')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'warehouse_transfer_id'=>['type'=>'BIGINT','unsigned'=>true],'warehouse_product_id'=>['type'=>'INT','unsigned'=>true],'quantity_sent'=>['type'=>'DECIMAL','constraint'=>'18,6'],'notes'=>['type'=>'TEXT','null'=>true]]);$this->forge->addKey('id',true);$this->forge->addUniqueKey(['warehouse_transfer_id','warehouse_product_id']);$this->forge->addKey('warehouse_product_id');$this->forge->addForeignKey('warehouse_transfer_id','warehouse_transfers','id','RESTRICT','RESTRICT','fk_wtl_transfer');$this->forge->addForeignKey('warehouse_product_id','warehouse_products','id','RESTRICT','RESTRICT','fk_wtl_product');$this->forge->createTable('warehouse_transfer_lines');}
  if(!$this->db->tableExists('warehouse_transfer_receipts')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'warehouse_transfer_id'=>['type'=>'BIGINT','unsigned'=>true],'receipt_date'=>['type'=>'DATETIME'],'warehouse_movement_id'=>['type'=>'BIGINT','unsigned'=>true],'notes'=>['type'=>'TEXT','null'=>true],'created_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addKey(['warehouse_transfer_id','receipt_date']);$this->forge->addForeignKey('warehouse_transfer_id','warehouse_transfers','id','RESTRICT','RESTRICT','fk_wtr_transfer');$this->forge->addForeignKey('warehouse_movement_id','warehouse_movements','id','RESTRICT','RESTRICT','fk_wtr_movement');$this->forge->createTable('warehouse_transfer_receipts');}
  if(!$this->db->tableExists('warehouse_transfer_receipt_lines')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'warehouse_transfer_receipt_id'=>['type'=>'BIGINT','unsigned'=>true],'warehouse_transfer_line_id'=>['type'=>'BIGINT','unsigned'=>true],'warehouse_product_id'=>['type'=>'INT','unsigned'=>true],'quantity_received'=>['type'=>'DECIMAL','constraint'=>'18,6']]);$this->forge->addKey('id',true);$this->forge->addUniqueKey(['warehouse_transfer_receipt_id','warehouse_transfer_line_id']);$this->forge->addKey(['warehouse_transfer_line_id','warehouse_product_id']);$this->forge->addForeignKey('warehouse_transfer_receipt_id','warehouse_transfer_receipts','id','RESTRICT','RESTRICT','fk_wtrl_receipt');$this->forge->addForeignKey('warehouse_transfer_line_id','warehouse_transfer_lines','id','RESTRICT','RESTRICT','fk_wtrl_line');$this->forge->addForeignKey('warehouse_product_id','warehouse_products','id','RESTRICT','RESTRICT','fk_wtrl_product');$this->forge->createTable('warehouse_transfer_receipt_lines');}
  if(!$this->db->tableExists('warehouse_transfer_discrepancies')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'warehouse_transfer_id'=>['type'=>'BIGINT','unsigned'=>true],'warehouse_transfer_line_id'=>['type'=>'BIGINT','unsigned'=>true],'warehouse_product_id'=>['type'=>'INT','unsigned'=>true],'quantity_difference'=>['type'=>'DECIMAL','constraint'=>'18,6'],'reason'=>['type'=>'TEXT'],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'reported'],'created_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addUniqueKey('warehouse_transfer_line_id');$this->forge->addKey(['warehouse_transfer_id','status']);$this->forge->addForeignKey('warehouse_transfer_id','warehouse_transfers','id','RESTRICT','RESTRICT','fk_wtd_transfer');$this->forge->addForeignKey('warehouse_transfer_line_id','warehouse_transfer_lines','id','RESTRICT','RESTRICT','fk_wtd_line');$this->forge->addForeignKey('warehouse_product_id','warehouse_products','id','RESTRICT','RESTRICT','fk_wtd_product');$this->forge->createTable('warehouse_transfer_discrepancies');}
  if(!$this->db->tableExists('warehouse_transfer_events')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'warehouse_transfer_id'=>['type'=>'BIGINT','unsigned'=>true],'event_type'=>['type'=>'VARCHAR','constraint'=>40],'event_at'=>['type'=>'DATETIME'],'user_id'=>['type'=>'INT','unsigned'=>true,'null'=>true],'notes'=>['type'=>'TEXT','null'=>true],'metadata_json'=>['type'=>'TEXT','null'=>true]]);$this->forge->addKey('id',true);$this->forge->addKey(['warehouse_transfer_id','event_at']);$this->forge->addKey('event_type');$this->forge->addForeignKey('warehouse_transfer_id','warehouse_transfers','id','RESTRICT','RESTRICT','fk_wte_transfer');$this->forge->createTable('warehouse_transfer_events');}
 }
 public function down(){foreach(['warehouse_transfer_events','warehouse_transfer_discrepancies','warehouse_transfer_receipt_lines','warehouse_transfer_receipts','warehouse_transfer_lines','warehouse_transfers'] as $t)if($this->db->tableExists($t))$this->forge->dropTable($t);}
}
