<?php
declare(strict_types=1);
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
use RuntimeException;
class CreateSaleFiscalPricingPreparations extends Migration{
 public function up():void{if($this->db->tableExists('sale_fiscal_pricing_preparations'))return;if(!$this->db->tableExists('invoices')||!$this->db->tableExists('fiscal_profiles'))throw new RuntimeException('Cannot create fiscal pricing preparations: required tables are missing.');$money=['type'=>'DECIMAL','constraint'=>'18,2','default'=>'0.00'];$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'invoice_id'=>['type'=>'INT','unsigned'=>true],'issuer_profile_id'=>['type'=>'INT','unsigned'=>true],'receiver_profile_id'=>['type'=>'INT','unsigned'=>true,'null'=>true],'fiscal_series_id'=>['type'=>'INT','unsigned'=>true,'null'=>true],'pricing_mode'=>['type'=>'VARCHAR','constraint'=>20], 'administrative_subtotal'=>$money,'administrative_discount'=>$money,'administrative_tax_total'=>$money,'administrative_total'=>$money,'estimated_fiscal_base'=>$money,'estimated_fiscal_discount'=>$money,'estimated_fiscal_tax_total'=>$money,'estimated_fiscal_total'=>$money,'difference_amount'=>$money,'previous_balance'=>$money,'estimated_balance'=>$money,'payment_total_snapshot'=>$money,'status'=>['type'=>'VARCHAR','constraint'=>30,'default'=>'simulated'],'requires_confirmation'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'confirmed_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],'confirmed_at'=>['type'=>'DATETIME','null'=>true],'applied_to_sale'=>['type'=>'TINYINT','constraint'=>1,'default'=>0],'applied_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],'applied_at'=>['type'=>'DATETIME','null'=>true],'calculation_payload'=>['type'=>'LONGTEXT','null'=>true],'created_by'=>['type'=>'INT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->addKey(['invoice_id','status']);$this->forge->addKey(['issuer_profile_id','created_at']);$this->forge->createTable('sale_fiscal_pricing_preparations');}
 public function down():void{if($this->db->tableExists('sale_fiscal_pricing_preparations'))$this->forge->dropTable('sale_fiscal_pricing_preparations');}
}
