<?php
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
class CreatePaymentComplementDrafts extends Migration
{
 public function up(){
  if(!$this->db->tableExists('payment_complements')){$this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'client_id'=>['type'=>'INT'],'issuer_profile_id'=>['type'=>'INT','null'=>true],'issue_date'=>['type'=>'DATETIME'],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'draft'],'notes'=>['type'=>'TEXT','null'=>true],'created_by'=>['type'=>'INT','null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);$this->forge->addKey('id',true);$this->forge->createTable('payment_complements');}
  if(!$this->db->tableExists('payment_complement_payments')){$this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'payment_complement_id'=>['type'=>'INT','unsigned'=>true],'source_invoice_payment_id'=>['type'=>'INT','null'=>true],'payment_date'=>['type'=>'DATE'],'payment_form_code'=>['type'=>'VARCHAR','constraint'=>3,'null'=>true],'currency_code'=>['type'=>'VARCHAR','constraint'=>3,'default'=>'MXN'],'exchange_rate'=>['type'=>'DECIMAL','constraint'=>'18,6','default'=>1],'amount'=>['type'=>'DECIMAL','constraint'=>'18,6'],'operation_number'=>['type'=>'VARCHAR','constraint'=>100,'null'=>true],'ordering_bank_rfc'=>['type'=>'VARCHAR','constraint'=>13,'null'=>true],'ordering_bank_name'=>['type'=>'VARCHAR','constraint'=>150,'null'=>true],'ordering_account'=>['type'=>'VARCHAR','constraint'=>100,'null'=>true],'beneficiary_bank_rfc'=>['type'=>'VARCHAR','constraint'=>13,'null'=>true],'beneficiary_account'=>['type'=>'VARCHAR','constraint'=>100,'null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);$this->forge->addKey('id',true);$this->forge->createTable('payment_complement_payments');}
  if(!$this->db->tableExists('payment_complement_documents')){$this->forge->addField(['id'=>['type'=>'INT','unsigned'=>true,'auto_increment'=>true],'payment_complement_payment_id'=>['type'=>'INT','unsigned'=>true],'fiscal_document_id'=>['type'=>'INT','unsigned'=>true],'document_uuid'=>['type'=>'VARCHAR','constraint'=>36],'currency_dr'=>['type'=>'VARCHAR','constraint'=>3,'null'=>true],'equivalence_dr'=>['type'=>'DECIMAL','constraint'=>'18,6','null'=>true],'installment_number'=>['type'=>'INT'],'previous_balance'=>['type'=>'DECIMAL','constraint'=>'18,6'],'amount_paid'=>['type'=>'DECIMAL','constraint'=>'18,6'],'remaining_balance'=>['type'=>'DECIMAL','constraint'=>'18,6'],'tax_object_code'=>['type'=>'VARCHAR','constraint'=>3,'null'=>true],'snapshot_json'=>['type'=>'LONGTEXT','null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true],'deleted'=>['type'=>'TINYINT','constraint'=>1,'default'=>0]]);$this->forge->addKey('id',true);$this->forge->createTable('payment_complement_documents');}
 }
 public function down(){}
}
