<?php
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
use RuntimeException;
final class HardenFinancialLedger extends Migration
{
 public function up():void
 {
  foreach(['financial_accounts','financial_account_movements','financial_account_transfers','invoice_payments','expenses','payment_methods']as$t)if(!$this->db->tableExists($t))throw new RuntimeException("Falta la tabla {$t} para endurecer el ledger.");
  $this->add('payment_methods','default_financial_account_id',['type'=>'INT','unsigned'=>true,'null'=>true,'after'=>'type']);
  foreach(['invoice_payments','expenses']as$t){$this->add($t,'status',['type'=>'VARCHAR','constraint'=>20,'default'=>'active']);$this->add($t,'cancelled_at',['type'=>'DATETIME','null'=>true]);$this->add($t,'cancelled_by',['type'=>'INT','null'=>true]);$this->add($t,'cancellation_reason',['type'=>'VARCHAR','constraint'=>500,'null'=>true]);}
  $this->add('expenses','financial_total',['type'=>'DECIMAL','constraint'=>'18,6','default'=>'0.000000','after'=>'amount']);
  foreach(['movement_role'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'original'],'reversal_of_movement_id'=>['type'=>'INT','unsigned'=>true,'null'=>true],'reversed_movement_id'=>['type'=>'INT','unsigned'=>true,'null'=>true],'reversal_reason'=>['type'=>'VARCHAR','constraint'=>500,'null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]as$n=>$d)$this->add('financial_account_movements',$n,$d);
  foreach(['status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'active'],'cancelled_at'=>['type'=>'DATETIME','null'=>true],'cancelled_by'=>['type'=>'INT','null'=>true],'cancellation_reason'=>['type'=>'VARCHAR','constraint'=>500,'null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]as$n=>$d)$this->add('financial_account_transfers',$n,$d);
  $p=$this->db->DBPrefix;
  $this->db->query("UPDATE {$p}financial_accounts SET type='other' WHERE type NOT IN ('cash','bank','card','wallet','other')");
  $this->db->query("UPDATE {$p}financial_accounts SET currency='MXN'");
  $this->db->query("UPDATE {$p}invoice_payments SET status=IF(deleted=1,'cancelled','active')");$this->db->query("UPDATE {$p}expenses SET status=IF(deleted=1,'cancelled','active')");
  $this->db->query("UPDATE {$p}expenses e LEFT JOIN {$p}taxes t1 ON t1.id=e.tax_id LEFT JOIN {$p}taxes t2 ON t2.id=e.tax_id2 SET e.financial_total=ROUND(e.amount+(e.amount*COALESCE(t1.percentage,0)/100)+(e.amount*COALESCE(t2.percentage,0)/100),6)");
  $missingPayments=(int)$this->db->query("SELECT COUNT(*) c FROM {$p}invoice_payments WHERE destination_financial_account_id IS NULL OR destination_financial_account_id=0")->getRow()->c;
  $missingExpenses=(int)$this->db->query("SELECT COUNT(*) c FROM {$p}expenses WHERE source_financial_account_id IS NULL OR source_financial_account_id=0")->getRow()->c;
  $transitionId=0;if($missingPayments||$missingExpenses){$row=$this->db->table('financial_accounts')->where(['name'=>'Cuenta transitoria histórica por clasificar','deleted'=>0])->get(1)->getRow();if($row)$transitionId=(int)$row->id;else{$this->db->table('financial_accounts')->insert(['name'=>'Cuenta transitoria histórica por clasificar','type'=>'other','description'=>'Cuenta creada por migración para operaciones legacy sin cuenta. Debe reclasificarse mediante movimientos documentados.','currency'=>'MXN','opening_balance'=>'0.000000','is_active'=>1,'deleted'=>0,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);$transitionId=(int)$this->db->insertID();}$this->db->query("UPDATE {$p}invoice_payments SET destination_financial_account_id=? WHERE destination_financial_account_id IS NULL OR destination_financial_account_id=0",[$transitionId]);$this->db->query("UPDATE {$p}expenses SET source_financial_account_id=? WHERE source_financial_account_id IS NULL OR source_financial_account_id=0",[$transitionId]);}
  $this->db->query("UPDATE {$p}financial_account_movements SET movement_role='original',updated_at=COALESCE(updated_at,created_at,NOW())");
  $this->db->query("DELETE m1 FROM {$p}financial_account_movements m1 JOIN {$p}financial_account_movements m2 ON m1.reference_type=m2.reference_type AND m1.reference_id=m2.reference_id AND m1.movement_role=m2.movement_role AND m1.id>m2.id");
  $this->db->query("INSERT INTO {$p}financial_account_movements(financial_account_id,direction,amount,movement_date,reference_type,reference_id,movement_role,description,is_active,created_by,created_at,updated_at) SELECT ip.destination_financial_account_id,'in',ROUND(ip.amount,6),ip.payment_date,'invoice_payment',ip.id,'original',ip.note,1,ip.created_by,COALESCE(ip.created_at,NOW()),COALESCE(ip.created_at,NOW()) FROM {$p}invoice_payments ip LEFT JOIN {$p}financial_account_movements m ON m.reference_type='invoice_payment' AND m.reference_id=ip.id AND m.movement_role='original' WHERE ip.status='active' AND ip.deleted=0 AND m.id IS NULL");
  $this->db->query("INSERT INTO {$p}financial_account_movements(financial_account_id,direction,amount,movement_date,reference_type,reference_id,movement_role,description,is_active,created_by,created_at,updated_at) SELECT e.source_financial_account_id,'out',e.financial_total,e.expense_date,'expense',e.id,'original',e.title,1,e.created_by,NOW(),NOW() FROM {$p}expenses e LEFT JOIN {$p}financial_account_movements m ON m.reference_type='expense' AND m.reference_id=e.id AND m.movement_role='original' WHERE e.status='active' AND e.deleted=0 AND m.id IS NULL");
  $this->forge->modifyColumn('financial_accounts',['type'=>['name'=>'type','type'=>'VARCHAR','constraint'=>20],'currency'=>['name'=>'currency','type'=>'CHAR','constraint'=>3,'default'=>'MXN'],'opening_balance'=>['name'=>'opening_balance','type'=>'DECIMAL','constraint'=>'18,6','default'=>'0.000000']]);
  $this->forge->modifyColumn('invoice_payments',['amount'=>['name'=>'amount','type'=>'DECIMAL','constraint'=>'18,6'],'destination_financial_account_id'=>['name'=>'destination_financial_account_id','type'=>'INT','unsigned'=>true,'null'=>false]]);
  $this->forge->modifyColumn('expenses',['amount'=>['name'=>'amount','type'=>'DECIMAL','constraint'=>'18,6'],'source_financial_account_id'=>['name'=>'source_financial_account_id','type'=>'INT','unsigned'=>true,'null'=>false]]);
  foreach(['ALTER TABLE '.$p.'financial_accounts ADD CONSTRAINT chk_financial_account_type CHECK (type IN (\'cash\',\'bank\',\'card\',\'wallet\',\'other\'))','ALTER TABLE '.$p.'financial_accounts ADD CONSTRAINT chk_financial_account_currency CHECK (currency=\'MXN\')','ALTER TABLE '.$p.'financial_account_movements ADD CONSTRAINT chk_financial_movement_direction CHECK (direction IN (\'in\',\'out\'))','ALTER TABLE '.$p.'financial_account_movements ADD CONSTRAINT chk_financial_movement_amount CHECK (amount>0)','ALTER TABLE '.$p.'financial_account_movements ADD CONSTRAINT chk_financial_movement_role CHECK (movement_role IN (\'original\',\'reversal\'))']as$sql)$this->safe($sql);
  $this->safe("ALTER TABLE {$p}financial_account_movements ADD UNIQUE KEY uq_financial_source (reference_type,reference_id,movement_role)");
  $this->safe("ALTER TABLE {$p}financial_account_movements ADD UNIQUE KEY uq_financial_reversal (reversal_of_movement_id)");
  $this->safe("ALTER TABLE {$p}financial_account_movements ADD KEY idx_financial_account_date (financial_account_id,movement_date,id)");
  foreach(["ALTER TABLE {$p}financial_account_movements ADD CONSTRAINT fk_fam_account FOREIGN KEY(financial_account_id) REFERENCES {$p}financial_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT","ALTER TABLE {$p}financial_account_movements ADD CONSTRAINT fk_fam_reversal_of FOREIGN KEY(reversal_of_movement_id) REFERENCES {$p}financial_account_movements(id) ON DELETE RESTRICT","ALTER TABLE {$p}financial_account_movements ADD CONSTRAINT fk_fam_reversed_by FOREIGN KEY(reversed_movement_id) REFERENCES {$p}financial_account_movements(id) ON DELETE RESTRICT","ALTER TABLE {$p}financial_account_transfers ADD CONSTRAINT fk_fat_source FOREIGN KEY(source_account_id) REFERENCES {$p}financial_accounts(id) ON DELETE RESTRICT","ALTER TABLE {$p}financial_account_transfers ADD CONSTRAINT fk_fat_destination FOREIGN KEY(destination_account_id) REFERENCES {$p}financial_accounts(id) ON DELETE RESTRICT","ALTER TABLE {$p}invoice_payments ADD CONSTRAINT fk_invoice_payment_account FOREIGN KEY(destination_financial_account_id) REFERENCES {$p}financial_accounts(id) ON DELETE RESTRICT","ALTER TABLE {$p}expenses ADD CONSTRAINT fk_expense_account FOREIGN KEY(source_financial_account_id) REFERENCES {$p}financial_accounts(id) ON DELETE RESTRICT","ALTER TABLE {$p}payment_methods ADD CONSTRAINT fk_payment_method_default_account FOREIGN KEY(default_financial_account_id) REFERENCES {$p}financial_accounts(id) ON DELETE RESTRICT"]as$sql)$this->safe($sql);
 }
 public function down():void{}
 private function add(string$t,string$f,array$d):void{if(!$this->db->fieldExists($f,$t))$this->forge->addColumn($t,[$f=>$d]);}
 private function safe(string$sql):void{try{$this->db->query($sql);}catch(\Throwable$e){if(!str_contains(strtolower($e->getMessage()),'duplicate')&&!str_contains(strtolower($e->getMessage()),'already exists'))throw$e;}}
}
