<?php
declare(strict_types=1);
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;use RuntimeException;
final class CreateFiscalStampCommercialControl extends Migration{
 public function up():void{foreach(['fiscal_profiles','fiscal_documents','fiscal_stamp_attempts','fiscal_document_stamps','fiscal_cancellation_requests','users']as$t)if(!$this->db->tableExists($t))throw new RuntimeException("Stamp commercial control prerequisite missing: {$t}");
  if(!$this->db->fieldExists('is_platform_superadmin','users'))$this->forge->addColumn('users',['is_platform_superadmin'=>['type'=>'TINYINT','constraint'=>1,'default'=>0,'after'=>'is_admin']]);
  if(!$this->db->tableExists('platform_identity_audit')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'user_id'=>['type'=>'BIGINT','unsigned'=>true],'action'=>['type'=>'VARCHAR','constraint'=>50],'previous_value'=>['type'=>'TINYINT','constraint'=>1],'new_value'=>['type'=>'TINYINT','constraint'=>1],'reason'=>['type'=>'VARCHAR','constraint'=>500],'changed_by'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addKey(['user_id','created_at']);$this->forge->createTable('platform_identity_audit');}
  if(!$this->db->tableExists('fiscal_stamp_accounts')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'issuer_profile_id'=>['type'=>'BIGINT','unsigned'=>true],'available_balance'=>['type'=>'INT','unsigned'=>true,'default'=>0],'reserved_balance'=>['type'=>'INT','unsigned'=>true,'default'=>0],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'active'],'created_at'=>['type'=>'DATETIME'],'updated_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addUniqueKey('issuer_profile_id','uq_stamp_account_issuer');$this->forge->addKey('status');$this->forge->createTable('fiscal_stamp_accounts');$t=$this->db->protectIdentifiers($this->db->prefixTable('fiscal_stamp_accounts'));$this->db->query("ALTER TABLE {$t} ADD CONSTRAINT chk_stamp_account_status CHECK (status IN ('active','suspended')), ADD CONSTRAINT chk_stamp_available_nonnegative CHECK (available_balance >= 0), ADD CONSTRAINT chk_stamp_reserved_nonnegative CHECK (reserved_balance >= 0)");}
  if(!$this->db->tableExists('fiscal_stamp_movements')){$this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'stamp_account_id'=>['type'=>'BIGINT','unsigned'=>true],'movement_type'=>['type'=>'VARCHAR','constraint'=>50],'quantity'=>['type'=>'INT'],'available_before'=>['type'=>'INT','unsigned'=>true],'available_after'=>['type'=>'INT','unsigned'=>true],'reserved_before'=>['type'=>'INT','unsigned'=>true],'reserved_after'=>['type'=>'INT','unsigned'=>true],'fiscal_document_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'pac_attempt_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'fiscal_document_stamp_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'fiscal_cancellation_request_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'idempotency_key'=>['type'=>'VARCHAR','constraint'=>191],'consumption_key'=>['type'=>'VARCHAR','constraint'=>191,'null'=>true],'reason'=>['type'=>'TEXT'],'reference'=>['type'=>'VARCHAR','constraint'=>191,'null'=>true],'created_by'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'created_at'=>['type'=>'DATETIME']]);$this->forge->addKey('id',true);$this->forge->addUniqueKey('idempotency_key','uq_stamp_movement_idempotency');$this->forge->addUniqueKey('consumption_key','uq_stamp_consumption');foreach(['stamp_account_id','fiscal_document_id','pac_attempt_id','fiscal_document_stamp_id','fiscal_cancellation_request_id','created_at']as$k)$this->forge->addKey($k);$this->forge->createTable('fiscal_stamp_movements');$t=$this->db->protectIdentifiers($this->db->prefixTable('fiscal_stamp_movements'));$types="'allocation','adjustment_credit','adjustment_debit','document_reservation','document_consumption','document_release','reconciliation_consumption','reconciliation_release','cancellation_reservation','cancellation_consumption','cancellation_release'";$this->db->query("ALTER TABLE {$t} ADD CONSTRAINT chk_stamp_movement_quantity CHECK (quantity <> 0), ADD CONSTRAINT chk_stamp_movement_type CHECK (movement_type IN ({$types}))");}}
 public function down():void{foreach(['fiscal_stamp_movements','fiscal_stamp_accounts','platform_identity_audit']as$t)if($this->db->tableExists($t))$this->forge->dropTable($t);if($this->db->fieldExists('is_platform_superadmin','users'))$this->forge->dropColumn('users','is_platform_superadmin');}
}
