<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);require$root.'/tests/bootstrap.php';helper(['general','date_time','currency','form']);$db=require$root.'/tests/Increment02/isolated_database.php';
use App\Services\FiscalDocumentHistoricalTaxResolver;use App\Services\PaymentComplementCfdiMaterializer;use App\Services\Fiscal\FiscalIssueDateNormalizer;use App\Services\Fiscal\FiscalIssueDatePolicy;
$p=$f=0;$ok=function($v,$m)use(&$p,&$f){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$p++:$f++;};$resolver=new FiscalDocumentHistoricalTaxResolver($db);$item=$db->table('fiscal_document_items')->where('fiscal_document_id',1)->get(1)->getRow();if(!$item)throw new RuntimeException('Fixture fiscal sin concepto.');$db->table('fiscal_document_items')->where('id',$item->id)->update(['tax_object_code'=>'02']);$db->table('fiscal_document_item_taxes')->where('fiscal_document_item_id',$item->id)->delete();$insert=function(array$r)use($db,$item){$db->table('fiscal_document_item_taxes')->insert($r+['fiscal_document_item_id'=>$item->id,'sort_order'=>1,'created_at'=>get_current_utc_time()]);};
$insert(['tax_code'=>'002','tax_type'=>'transferred','factor_type'=>'Tasa','rate_or_quota'=>'0.160000','taxable_base'=>'1000.00','amount'=>'160.00']);$h=$resolver->resolve(1);$full=$resolver->prorate($h,'1160.000000','1160.000000')[0];$half=$resolver->prorate($h,'580.000000','1160.000000')[0];$ok($full['base']==='1000.000000'&&$full['amount']==='160.000000','IVA 16 completo conserva base e impuesto históricos');$ok($half['base']==='500.000000'&&$half['amount']==='80.000000','IVA 16 parcial se prorratea sin float');
$db->table('fiscal_document_item_taxes')->where('fiscal_document_item_id',$item->id)->delete();$insert(['tax_code'=>'002','tax_type'=>'transferred','factor_type'=>'Tasa','rate_or_quota'=>'0.000000','taxable_base'=>'1000.00','amount'=>'0.00']);$zero=$resolver->resolve(1)['taxes'][0];$ok($zero['rate_or_quota']==='0.000000'&&$zero['amount']==='0.000000','IVA 0 se conserva como tasa cero');
$db->table('fiscal_document_item_taxes')->where('fiscal_document_item_id',$item->id)->delete();$insert(['tax_code'=>'002','tax_type'=>'transferred','factor_type'=>'Exento','rate_or_quota'=>null,'taxable_base'=>'1000.00','amount'=>'0.00']);$exempt=$resolver->resolve(1)['taxes'][0];$ok($exempt['exempt']&&$exempt['rate_or_quota']===null,'Exento conserva factor sin inventar tasa');
$db->table('fiscal_document_item_taxes')->where('fiscal_document_item_id',$item->id)->delete();$insert(['tax_code'=>'001','tax_type'=>'withheld','factor_type'=>'Tasa','rate_or_quota'=>'0.100000','taxable_base'=>'1000.00','amount'=>'100.00']);$withheld=$resolver->resolve(1)['taxes'][0];$ok($withheld['tax_type']==='withholding'&&$withheld['tax_code']==='001','retención histórica se clasifica como RetencionesDR');
$db->table('fiscal_document_item_taxes')->where('fiscal_document_item_id',$item->id)->delete();$insert(['tax_code'=>'002','tax_type'=>'transferred','factor_type'=>'Tasa','rate_or_quota'=>'0.160000','taxable_base'=>'500.00','amount'=>'80.00']);$insert(['tax_code'=>'002','tax_type'=>'transferred','factor_type'=>'Tasa','rate_or_quota'=>'0.080000','taxable_base'=>'500.00','amount'=>'40.00']);$multi=$resolver->resolve(1);$ok(count($multi['taxes'])===2,'CFDI con múltiples tasas conserva grupos separados');$db->table('fiscal_document_items')->where('id',$item->id)->update(['tax_object_code'=>'01']);$db->table('fiscal_document_item_taxes')->where('fiscal_document_item_id',$item->id)->delete();$ok($resolver->resolve(1)['tax_object_code']==='01','ObjetoImpDR se deriva como 01 desde conceptos no objeto');
$normalizer=new FiscalIssueDateNormalizer();$date=$normalizer->normalizeTransport(date('Y-m-d\TH:i'));(new FiscalIssueDatePolicy())->validate($date);$ok(str_contains($date,' ')&&strlen($date)===19,'Fecha complemento usa normalizador y política fiscal existentes');$edit=(string)file_get_contents($root.'/app/Views/payment_complements/edit.php');$ok(str_contains($edit,'Fecha del pago')&&str_contains($edit,'readonly'),'Fecha pago es informativa y no editable');
$xml=(new PaymentComplementCfdiMaterializer())->materialize(['issue_date'=>date('Y-m-d\TH:i:s'),'sat_totals'=>['MontoTotalPagos'=>'580.000000','TotalTrasladosBaseIVA16'=>'500.000000','TotalTrasladosImpuestoIVA16'=>'80.000000'],'totals'=>['TrasladosP'=>['x'=>['BaseP'=>'500.000000','ImpuestoP'=>'002','TipoFactorP'=>'Tasa','TasaOCuotaP'=>'0.160000','ImporteP'=>'80.000000']],'RetencionesP'=>[]],'payments'=>[['FechaPago'=>date('Y-m-d').'T12:00:00','FormaDePagoP'=>'03','MonedaP'=>'MXN','TipoCambioP'=>'1.000000','Monto'=>'580.000000','RfcEmisorCtaBen'=>'BBA830831LJ2','CtaBeneficiario'=>'1234','DoctoRelacionado'=>[['IdDocumento'=>'00000000-0000-0000-0000-000000000001','MonedaDR'=>'MXN','EquivalenciaDR'=>'1.000000','NumParcialidad'=>1,'ImpSaldoAnt'=>'1160.000000','ImpPagado'=>'580.000000','ImpSaldoInsoluto'=>'580.000000','ObjetoImpDR'=>'02','ImpuestosDR'=>['TrasladosDR'=>[['BaseDR'=>'500.000000','ImpuestoDR'=>'002','TipoFactorDR'=>'Tasa','TasaOCuotaDR'=>'0.160000','ImporteDR'=>'80.000000']],'RetencionesDR'=>[]]]]]]]);$ok(str_contains($xml,'ObjetoImpDR="02"')&&str_contains($xml,'pago20:TrasladoDR')&&str_contains($xml,'TotalTrasladosBaseIVA16="500.000000"'),'materializador incluye ObjetoImpDR, ImpuestosDR/P y totales SAT');
$review=(string)file_get_contents($root.'/app/Views/payment_complements/review.php');$preview=(string)file_get_contents($root.'/app/Views/payment_complements/preview.php');$routes=(string)file_get_contents($root.'/app/Config/Routes.php');$ok(str_contains($edit,"data-action-method'=>'GET'")&&str_contains($edit,'payment_complements/review/')&&str_contains($review,'modal-body')&&!str_contains($review,'page-title'),'Revisión fiscal abre como modal sin abandonar generador');$ok(str_contains($edit,'payment_complements/preview/')&&str_contains($preview,'modal-body')&&str_contains($preview,'Cerrar y volver al generador'),'Preview modal conserva contexto');$ok(str_contains($routes,"payment_complements/(:num)/details")&&str_contains($edit,'csrf_field()'),'edición fiscal usa POST explícito con CSRF');$ok(str_contains($edit,'Información bancaria')&&str_contains($edit,'no aplica para la FormaDePagoP actual'),'bancos se muestran condicionalmente');
echo"TOTAL PASS=$p FAIL=$f".PHP_EOL;exit($f?1:0);
