<?php
declare(strict_types=1);
namespace App\Services\Fiscal;
use App\Services\Fiscal\Cfdi40\CfdiCurrencyTotalsCalculator;
final class CommercialTaxBreakdownService
{
 public function __construct(private mixed$db=null){$this->db??=db_connect();}
 public function forSale(int$saleId,?int$issuerId=null):array{
  $sale=$this->db->table('invoices')->where(['id'=>$saleId,'deleted'=>0])->get(1)->getRow();if(!$sale)return$this->empty(['Venta inexistente']);$items=$this->db->table('invoice_items')->where(['invoice_id'=>$saleId,'deleted'=>0])->orderBy('sort')->get()->getResult();$currencyLines=[];$missing=[];$resolver=new CommercialItemTaxResolver($this->db);$included=true;$grossDocument='0.000000';foreach($items as$item)$grossDocument=FiscalDecimal::add($grossDocument,FiscalDecimal::multiply((string)$item->quantity,(string)$item->rate));$documentDiscount=$this->documentDiscount($sale,$grossDocument);
  foreach($items as$item){$gross=FiscalDecimal::multiply((string)$item->quantity,(string)$item->rate);$lineDiscount=FiscalDecimal::micros($grossDocument)>0?FiscalDecimal::prorate($documentDiscount,$gross,$grossDocument):'0.000000';$c=$resolver->invoiceItem((int)$item->id,(string)$item->quantity,(string)$item->rate,$lineDiscount,$issuerId);$included=$c['prices_include_tax'];if(!$c['ready']){$missing=array_merge($missing,array_map(fn($m)=>(string)$item->title.': '.$m,$c['blockers']));continue;}$currencyLines[]=['subtotal'=>FiscalDecimal::add($c['base'],$lineDiscount),'discount'=>$lineDiscount,'transferred'=>$c['transfers'],'withheld'=>$c['withholdings']];}
  $totals=$currencyLines?(new CfdiCurrencyTotalsCalculator())->fromLines($currencyLines):['subtotal'=>'0.00','discount'=>'0.00','transferred'=>'0.00','withheld'=>'0.00','total'=>'0.00'];return['ready'=>!$missing&&!!$currencyLines,'prices_include_tax'=>$included]+$totals+['missing'=>array_values(array_unique($missing))];
 }
 public function forProposal(int$id,?int$issuerId=null):array{return$this->forProductDocument('proposals','proposal_items','proposal_id',$id,$issuerId);}
 public function forEstimate(int$id,?int$issuerId=null):array{return$this->forProductDocument('estimates','estimate_items','estimate_id',$id,$issuerId);}
 public function lineForSale(int$itemId,?int$issuerId=null):array{
  $item=$this->db->table('invoice_items')->where(['id'=>$itemId,'deleted'=>0])->get(1)->getRow();if(!$item)return[];$sale=$this->db->table('invoices')->where(['id'=>$item->invoice_id,'deleted'=>0])->get(1)->getRow();if(!$sale)return[];$items=$this->db->table('invoice_items')->where(['invoice_id'=>$item->invoice_id,'deleted'=>0])->get()->getResult();$grossDocument='0.000000';foreach($items as$row)$grossDocument=FiscalDecimal::add($grossDocument,FiscalDecimal::multiply((string)$row->quantity,(string)$row->rate));$gross=FiscalDecimal::multiply((string)$item->quantity,(string)$item->rate);$discount=FiscalDecimal::micros($grossDocument)>0?FiscalDecimal::prorate($this->documentDiscount($sale,$grossDocument),$gross,$grossDocument):'0.000000';return(new CommercialItemTaxResolver($this->db))->invoiceItem($itemId,(string)$item->quantity,(string)$item->rate,$discount,$issuerId);
 }
 public function lineForDocument(string$parentTable,string$itemTable,string$foreignKey,int$itemId,?int$issuerId=null):array{
  $item=$this->db->table($itemTable)->where(['id'=>$itemId,'deleted'=>0])->get(1)->getRow();if(!$item)return[];$parent=$this->db->table($parentTable)->where(['id'=>$item->$foreignKey,'deleted'=>0])->get(1)->getRow();if(!$parent)return[];$items=$this->db->table($itemTable)->where([$foreignKey=>$parent->id,'deleted'=>0])->get()->getResult();$grossDocument='0.000000';foreach($items as$row)$grossDocument=FiscalDecimal::add($grossDocument,FiscalDecimal::multiply((string)$row->quantity,(string)$row->rate));$gross=FiscalDecimal::multiply((string)$item->quantity,(string)$item->rate);$parentDiscount=$this->documentDiscount($parent,$grossDocument);$discount=FiscalDecimal::micros($grossDocument)>0?FiscalDecimal::prorate($parentDiscount,$gross,$grossDocument):'0.000000';$stored=json_decode((string)($item->fiscal_override_json??''),true);return(new CommercialItemTaxResolver($this->db))->product((int)$item->item_id,(int)$parent->company_id,(string)$item->quantity,(string)$item->rate,$discount,$issuerId,is_array($stored)?$stored:null,(string)($item->price_origin??'manual'));
 }
 private function forProductDocument(string$parentTable,string$itemTable,string$foreignKey,int$id,?int$issuerId):array{
  $parent=$this->db->table($parentTable)->where(['id'=>$id,'deleted'=>0])->get(1)->getRow();if(!$parent)return$this->empty(['Documento inexistente']);$items=$this->db->table($itemTable)->where([$foreignKey=>$id,'deleted'=>0])->orderBy('sort')->get()->getResult();$currencyLines=[];$missing=[];$resolver=new CommercialItemTaxResolver($this->db);$included=true;$grossDocument='0.000000';foreach($items as$item)$grossDocument=FiscalDecimal::add($grossDocument,FiscalDecimal::multiply((string)$item->quantity,(string)$item->rate));$parentDiscount=$this->documentDiscount($parent,$grossDocument);
  foreach($items as$item){$gross=FiscalDecimal::multiply((string)$item->quantity,(string)$item->rate);$lineDiscount=FiscalDecimal::micros($grossDocument)>0?FiscalDecimal::prorate($parentDiscount,$gross,$grossDocument):'0.000000';$override=json_decode((string)($item->fiscal_override_json??''),true);$c=$resolver->product((int)$item->item_id,(int)$parent->company_id,(string)$item->quantity,(string)$item->rate,$lineDiscount,$issuerId,is_array($override)?$override:null,(string)($item->price_origin??'manual'));$included=$c['prices_include_tax'];if(!$c['ready']){$missing=array_merge($missing,array_map(fn($m)=>(string)$item->title.': '.$m,$c['blockers']));continue;}$currencyLines[]=['subtotal'=>FiscalDecimal::add($c['base'],$lineDiscount),'discount'=>$lineDiscount,'transferred'=>$c['transfers'],'withheld'=>$c['withholdings']];}
  $totals=$currencyLines?(new CfdiCurrencyTotalsCalculator())->fromLines($currencyLines):['subtotal'=>'0.00','discount'=>'0.00','transferred'=>'0.00','withheld'=>'0.00','total'=>'0.00'];return['ready'=>!$missing&&!!$currencyLines,'prices_include_tax'=>$included]+$totals+['missing'=>array_values(array_unique($missing))];
 }
 private function documentDiscount(object$parent,string$gross):string{$amount=(string)($parent->discount_amount??'0');if(($parent->discount_amount_type??'')==='percentage')return FiscalDecimal::multiply($gross,FiscalDecimal::divide($amount,'100.000000'));return FiscalDecimal::micros($amount)>0?$amount:'0.000000';}
 private function empty(array$m):array{return['ready'=>false,'prices_include_tax'=>true,'subtotal'=>'0.000000','discount'=>'0.000000','transferred'=>'0.000000','withheld'=>'0.000000','total'=>'0.000000','missing'=>$m];}
}
