<?php
declare(strict_types=1);
namespace App\Services\Fiscal;
use RuntimeException;
class FiscalDecimalCalculator{
 private int$scale;private bool$bc;
 public function __construct(int$scale=8,?bool$useBc=null){$this->scale=$scale;$this->bc=$useBc??extension_loaded('bcmath');if($this->bc&&!extension_loaded('bcmath'))$this->bc=false;}
 public function normalize(string|int$v,int$scale=null):string{$scale??=$this->scale;$this->validate((string)$v);if($this->bc)return bcadd((string)$v,'0',$scale);return$this->fromScaled($this->toScaled((string)$v,$scale),$scale);}
 public function add(string$a,string$b,int$scale=null):string{$scale??=$this->scale;if($this->bc)return bcadd($a,$b,$scale);return$this->fromScaled($this->signedAdd($this->toScaled($a,$scale),$this->toScaled($b,$scale)),$scale);}
 public function sub(string$a,string$b,int$scale=null):string{return$this->add($a,$this->negate($b),$scale);}
 public function mul(string$a,string$b,int$scale=null):string{$scale??=$this->scale;if($this->bc)return bcmul($a,$b,$scale);$ia=$this->toScaled($a,$scale);$ib=$this->toScaled($b,$scale);$negative=(str_starts_with($ia,'-') xor str_starts_with($ib,'-'));$product=$this->unsignedMul(ltrim($ia,'-'),ltrim($ib,'-'));$product=$this->truncateRight($product,$scale);return$this->fromScaled(($negative&&$product!=='0'?'-':'').$product,$scale);}
 public function div(string$a,string$b,int$scale=null):string{$scale??=$this->scale;$this->validate($a);$this->validate($b);if($this->compare($b,'0','0')===0)throw new RuntimeException('Division by zero.');if($this->bc)return bcdiv($a,$b,$scale);$ia=$this->toScaled($a,$scale);$ib=$this->toScaled($b,$scale);$negative=(str_starts_with($ia,'-') xor str_starts_with($ib,'-'));$numerator=ltrim($ia,'-').str_repeat('0',$scale);$quotient=$this->unsignedDiv($numerator,ltrim($ib,'-'));return$this->fromScaled(($negative&&$quotient!=='0'?'-':'').$quotient,$scale);}
 public function compare(string$a,string$b,string$tolerance='0.005'):int{$scale=$this->scale;$difference=$this->abs($this->sub($a,$b,$scale));if($this->rawCompare($difference,$tolerance,$scale)<=0)return 0;return$this->rawCompare($a,$b,$scale);}
 public function money(string$v):string{$normalized=$this->normalize($v,$this->scale);$scaled=$this->toScaled($normalized,$this->scale);$negative=str_starts_with($scaled,'-');$digits=ltrim($scaled,'-');$discard=$this->scale-2;$roundDigit=$discard>0?($digits[strlen($digits)-$discard]??'0'):'0';$cents=$discard>0?$this->truncateRight($digits,$discard):$digits;if($roundDigit>='5')$cents=$this->unsignedAdd($cents,'1');return$this->fromScaled(($negative&&$cents!=='0'?'-':'').$cents,2);}
 public function abs(string$v):string{return str_starts_with($v,'-')?substr($v,1):$v;}
 public function rate(string$v):string{return$this->normalize($v,6);}
 private function validate(string$v):void{if(!preg_match('/^-?\d+(?:\.\d+)?$/',trim($v)))throw new RuntimeException('Invalid decimal value.');}
 private function negate(string$v):string{$this->validate($v);return str_starts_with($v,'-')?substr($v,1):($this->rawCompare($v,'0',$this->scale)===0?'0':'-'.$v);}
 private function toScaled(string$v,int$scale):string{$this->validate($v);$v=trim($v);$negative=str_starts_with($v,'-');$v=ltrim($v,'-');[$whole,$fraction]=array_pad(explode('.',$v,2),2,'');$digits=ltrim($whole.str_pad(substr($fraction,0,$scale),$scale,'0'),'0');if($digits==='')$digits='0';return$negative&&$digits!=='0'?'-'.$digits:$digits;}
 private function fromScaled(string$integer,int$scale):string{$negative=str_starts_with($integer,'-');$digits=ltrim(ltrim($integer,'-'),'0');if($digits==='')$digits='0';if($scale===0)return($negative&&$digits!=='0'?'-':'').$digits;$digits=str_pad($digits,$scale+1,'0',STR_PAD_LEFT);$out=substr($digits,0,-$scale).'.'.substr($digits,-$scale);return($negative&&$digits!=='0'?'-':'').$out;}
 private function signedAdd(string$a,string$b):string{$an=str_starts_with($a,'-');$bn=str_starts_with($b,'-');$aa=ltrim($a,'-');$bb=ltrim($b,'-');if($an===$bn){$r=$this->unsignedAdd($aa,$bb);return$an&&$r!=='0'?'-'.$r:$r;}$cmp=$this->unsignedCompare($aa,$bb);if($cmp===0)return'0';if($cmp>0){$r=$this->unsignedSub($aa,$bb);return$an?'-'.$r:$r;}$r=$this->unsignedSub($bb,$aa);return$bn?'-'.$r:$r;}
 private function unsignedCompare(string$a,string$b):int{$a=ltrim($a,'0')?:'0';$b=ltrim($b,'0')?:'0';return strlen($a)<=>strlen($b)?:strcmp($a,$b);}
 private function unsignedAdd(string$a,string$b):string{$carry=0;$out='';for($i=strlen($a)-1,$j=strlen($b)-1;$i>=0||$j>=0||$carry;$i--,$j--){$sum=($i>=0?(int)$a[$i]:0)+($j>=0?(int)$b[$j]:0)+$carry;$out=($sum%10).$out;$carry=intdiv($sum,10);}return ltrim($out,'0')?:'0';}
 private function unsignedSub(string$a,string$b):string{$borrow=0;$out='';for($i=strlen($a)-1,$j=strlen($b)-1;$i>=0;$i--,$j--){$n=(int)$a[$i]-$borrow-($j>=0?(int)$b[$j]:0);if($n<0){$n+=10;$borrow=1;}else$borrow=0;$out=$n.$out;}return ltrim($out,'0')?:'0';}
 private function unsignedMul(string$a,string$b):string{$result='0';for($j=strlen($b)-1,$zeros=0;$j>=0;$j--,$zeros++){$carry=0;$row='';$digit=(int)$b[$j];for($i=strlen($a)-1;$i>=0;$i--){$n=(int)$a[$i]*$digit+$carry;$row=($n%10).$row;$carry=intdiv($n,10);}if($carry)$row=$carry.$row;$result=$this->unsignedAdd($result,$row.str_repeat('0',$zeros));}return ltrim($result,'0')?:'0';}
 private function unsignedDiv(string$a,string$b):string{if(($b=ltrim($b,'0'))==='')throw new RuntimeException('Division by zero.');$remainder='0';$out='';foreach(str_split(ltrim($a,'0')?:'0')as$digit){$remainder=ltrim($remainder.$digit,'0')?:'0';$q=0;while($this->unsignedCompare($remainder,$b)>=0){$remainder=$this->unsignedSub($remainder,$b);$q++;}$out.=(string)$q;}return ltrim($out,'0')?:'0';}
 private function truncateRight(string$v,int$count):string{if($count<=0)return ltrim($v,'0')?:'0';return ltrim(strlen($v)>$count?substr($v,0,-$count):'0','0')?:'0';}
 private function rawCompare(string$a,string$b,int$scale):int{$ia=$this->toScaled($a,$scale);$ib=$this->toScaled($b,$scale);$an=str_starts_with($ia,'-');$bn=str_starts_with($ib,'-');if($an!==$bn)return$an?-1:1;$cmp=$this->unsignedCompare(ltrim($ia,'-'),ltrim($ib,'-'));return$an?-$cmp:$cmp;}
}
