<?php
declare(strict_types=1);
namespace App\Services\Fiscal;
use App\Models\Fiscal\Fiscal_profiles_model;
use App\Models\Fiscal\Sale_fiscal_pricing_preparations_model;
use App\Models\Invoices_model;
use App\Models\Invoice_items_model;
use RuntimeException;
class SaleTaxPricingSimulationService{
 private FiscalDecimalCalculator$d;private $db;
 public function __construct($db=null){$this->db=$db?:db_connect();$this->d=new FiscalDecimalCalculator();}
 public function simulate(int$invoiceId,int$issuerId,?int$receiverId=null,?int$seriesId=null,?string$override=null,int|string|null$userId=null,bool$persist=true):array{
  $invoice=(new Invoices_model())->get_details(['id'=>$invoiceId])->getRow();if(!$invoice||!$invoice->id||$invoice->deleted||$invoice->status==='cancelled')throw new RuntimeException('La venta no está disponible para simulación fiscal.');$issuer=(new Fiscal_profiles_model())->get_one($issuerId);if(!$issuer->id||$issuer->profile_type!=='issuer'||$issuer->status!=='ready')throw new RuntimeException('El emisor no está listo.');$mode=$override?:($issuer->tax_pricing_mode?:'tax_inclusive');if(!in_array($mode,['tax_inclusive','tax_exclusive','preserve_total'],true))throw new RuntimeException('La política de precios no es válida.');
  $items=(new Invoice_items_model())->get_details(['invoice_id'=>$invoiceId])->getResult();if(!$items)throw new RuntimeException('La venta no contiene partidas.');$adminSubtotal=$this->d->money((string)$invoice->invoice_subtotal);$adminDiscount=$this->d->money((string)$invoice->discount_total);$adminTax=$this->d->money($this->d->sub($this->d->add((string)$invoice->tax,(string)$invoice->tax2),(string)$invoice->tax3));$adminTotal=$this->d->money((string)$invoice->invoice_total);$payment=(string)($invoice->payment_received??'0');$previousBalance=$this->d->money($this->d->sub($adminTotal,$payment));
  $grossTotal='0';foreach($items as$i)$grossTotal=$this->d->add($grossTotal,(string)$i->total);$remainingDiscount=$adminDiscount;$remainingPreservedTotal=$adminTotal;$baseTotal='0';$taxTotal='0';$details=[];$errors=[];$mappingSignature=null;$mappingSupported=true;
  foreach($items as$index=>$item){if(!(int)$item->item_id){$errors[]='La partida '.$item->title.' es manual y no tiene configuración fiscal.';continue;}$setting=$this->db->table('item_fiscal_settings')->where(['item_id'=>$item->item_id,'is_default'=>1,'deleted'=>0])->get(1)->getRow();if(!$setting){$errors[]='El producto '.$item->title.' no tiene configuración fiscal.';continue;}$taxes=$this->db->table('item_fiscal_taxes ft')->select('t.id,t.title,t.fiscal_tax_type,t.xml_rate,t.xml_quota,t.percentage,f.code factor_code,t.is_fiscal_ready,t.use_for_fiscal')->join('taxes t','t.id=ft.tax_id')->join('sat_tax_factor_types f','f.id=t.factor_type_id','left')->where(['ft.item_fiscal_setting_id'=>$setting->id,'ft.is_active'=>1,'t.deleted'=>0])->orderBy('ft.sort_order')->get()->getResult();$gross=$this->d->normalize((string)$item->total);$discount=$index===count($items)-1?$remainingDiscount:($this->d->compare($grossTotal,'0')===0?'0':$this->d->money($this->d->mul($adminDiscount,$this->d->div($gross,$grossTotal))));$remainingDiscount=$this->d->sub($remainingDiscount,$discount);$net=$this->d->sub($gross,$discount);$rateSum='0';$lineTax='0';$signature=[];
   if($mode!=='tax_exclusive'){$net=$index===count($items)-1?$remainingPreservedTotal:($this->d->compare($grossTotal,'0')===0?'0':$this->d->money($this->d->mul($adminTotal,$this->d->div($gross,$grossTotal))));$remainingPreservedTotal=$this->d->sub($remainingPreservedTotal,$net);}foreach($taxes as$tax){if(!(int)$tax->is_fiscal_ready||!(int)$tax->use_for_fiscal){$errors[]='El impuesto '.$tax->title.' no está fiscalmente listo.';continue;}$sign=$tax->fiscal_tax_type==='withholding'?'-':'1';if($tax->factor_code==='Exento'){$amount='0';}elseif($tax->factor_code==='Tasa'){$rate=$this->d->rate((string)$tax->xml_rate);$signedRate=$sign==='-'?'-'.$rate:$rate;$rateSum=$this->d->add($rateSum,$signedRate,8);$amount=null;}elseif($tax->factor_code==='Cuota'&&$mode==='tax_exclusive'){$amount=$this->d->mul((string)$item->quantity,(string)$tax->xml_quota);if($sign==='-')$amount='-'.$amount;$mappingSupported=false;}else{$errors[]='La combinación de cuota e impuestos incluidos no puede desglosarse de forma segura.';$amount='0';}$signature[]=[(int)$tax->id,$tax->fiscal_tax_type,$tax->factor_code,(string)$tax->xml_rate,(string)$tax->xml_quota];if($amount!==null)$lineTax=$this->d->add($lineTax,$amount);}
   if($mode==='tax_exclusive'){$base=$net;foreach($taxes as$tax)if($tax->factor_code==='Tasa'&&(int)$tax->is_fiscal_ready&&(int)$tax->use_for_fiscal){$amount=$this->d->mul($base,(string)$tax->xml_rate);if($tax->fiscal_tax_type==='withholding')$amount='-'.$amount;$lineTax=$this->d->add($lineTax,$amount);}}else{$denominator=$this->d->add('1',$rateSum);if($this->d->compare($denominator,'0')<=0){$errors[]='La combinación de tasas no permite extraer una base válida.';$base='0';}else{$base=$this->d->div($net,$denominator);$lineTax=$this->d->sub($net,$base);}}
   $base=$this->d->money($base);$lineTax=$this->d->money($lineTax);$baseTotal=$this->d->add($baseTotal,$base);$taxTotal=$this->d->add($taxTotal,$lineTax);$signatureJson=json_encode($signature);if($mappingSignature===null)$mappingSignature=$signatureJson;elseif($mappingSignature!==$signatureJson)$mappingSupported=false;$details[]=['invoice_item_id'=>(int)$item->id,'item_id'=>(int)$item->item_id,'description'=>$item->title,'quantity'=>(string)$item->quantity,'gross'=>$this->d->money($gross),'discount'=>$this->d->money($discount),'base'=>$base,'tax'=>$lineTax,'taxes'=>$signature];
  }
  $baseTotal=$this->d->money($baseTotal);$taxTotal=$this->d->money($taxTotal);$estimatedTotal=$mode==='tax_exclusive'?$this->d->money($this->d->add($baseTotal,$taxTotal)):$adminTotal;$difference=$this->d->money($this->d->sub($estimatedTotal,$adminTotal));$estimatedBalance=$this->d->money($this->d->sub($estimatedTotal,$payment));$requires=$this->d->compare($difference,'0')!==0;$status=$requires?'confirmation_required':'simulated';$warnings=[];if($mode==='tax_exclusive'&&$this->d->compare($payment,$adminTotal)>=0&&$requires)$warnings[]='La venta está pagada, pero la política agregará impuestos y generará un nuevo saldo pendiente.';
  $mappingRows=$mappingSignature?json_decode($mappingSignature,true):[];$transfers=array_values(array_filter($mappingRows,fn($r)=>$r[1]==='transfer'&&$r[2]==='Tasa'));$withholdings=array_values(array_filter($mappingRows,fn($r)=>$r[1]==='withholding'&&$r[2]==='Tasa'));$unsupportedRows=array_filter($mappingRows,fn($r)=>!in_array($r[2],['Tasa','Exento'],true));$mappingSupported=$mappingSupported&&!$errors&&!$unsupportedRows&&count($transfers)<=2&&count($withholdings)<=1;$riseTaxIds=array_merge(array_column($transfers,0),array_fill(0,max(0,2-count($transfers)),0),array_column($withholdings,0));
  $payload=['version'=>1,'mode'=>$mode,'invoice_snapshot'=>['invoice_total'=>$adminTotal,'invoice_subtotal'=>$adminSubtotal,'discount_total'=>$adminDiscount,'payment_total'=>$this->d->money($payment),'status'=>$invoice->status],'items'=>$details,'rise_mapping_supported'=>$mappingSupported,'rise_tax_ids'=>array_slice($riseTaxIds,0,3),'errors'=>$errors,'warnings'=>$warnings];$data=['invoice_id'=>$invoiceId,'issuer_profile_id'=>$issuerId,'receiver_profile_id'=>$receiverId,'fiscal_series_id'=>$seriesId,'pricing_mode'=>$mode,'administrative_subtotal'=>$adminSubtotal,'administrative_discount'=>$adminDiscount,'administrative_tax_total'=>$adminTax,'administrative_total'=>$adminTotal,'estimated_fiscal_base'=>$baseTotal,'estimated_fiscal_discount'=>$adminDiscount,'estimated_fiscal_tax_total'=>$taxTotal,'estimated_fiscal_total'=>$estimatedTotal,'difference_amount'=>$difference,'previous_balance'=>$previousBalance,'estimated_balance'=>$estimatedBalance,'payment_total_snapshot'=>$this->d->money($payment),'status'=>$status,'requires_confirmation'=>$requires?1:0,'calculation_payload'=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'created_by'=>$userId,'created_at'=>get_current_utc_time(),'updated_at'=>get_current_utc_time()];$id=null;if($persist){$model=new Sale_fiscal_pricing_preparations_model();$this->db->transStart();$model->supersedeActive($invoiceId);$id=$model->ci_save($data);$this->db->transComplete();if(!$this->db->transStatus())throw new RuntimeException('No fue posible guardar la preparación fiscal.');}$data['id']=$id;$data['payload']=$payload;$data['errors']=$errors;$data['warnings']=$warnings;return$data;
 }
}
