<?php
declare(strict_types=1);
foreach(['fiscal.enabled'=>'false','fiscal.stampingEnabled'=>'false','fiscal.allowRealPac'=>'false']as$k=>$v){putenv("$k=$v");$_ENV[$k]=$_SERVER[$k]=$v;}
require dirname(__DIR__).'/bootstrap.php';require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
helper(['plugin','general','date_time']);
require_once APPPATH.'Database/Migrations/2026-08-29-130000_CreateWarehouseLogisticsFoundation.php';require_once APPPATH.'Database/Migrations/2026-08-31-090000_CreateWarehouseTransfers.php';require_once APPPATH.'Database/Migrations/2026-08-31-091000_AddWarehouseProductLabelLogo.php';
use App\Database\Migrations\CreateWarehouseLogisticsFoundation;use App\Database\Migrations\CreateWarehouseTransfers;use App\Database\Migrations\AddWarehouseProductLabelLogo;use App\Services\WarehouseLabelService;use App\Services\WarehouseMovementService;use App\Services\WarehouseStockService;use App\Services\WarehouseTransferService;use Config\Database;
$server=$db=null;$owned=null;$passed=0;$assert=static function(bool$ok,string$label)use(&$passed):void{if(!$ok)throw new RuntimeException($label);$passed++;echo"[PASS] $label\n";};
try{$local=config(Database::class)->default;if(!in_array($local['hostname'],['localhost','127.0.0.1','::1'],true))throw new RuntimeException('Local fixture server required.');mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$server=new mysqli($local['hostname'],$local['username'],$local['password'],'',(int)$local['port']);$owned='ikontrol_test_p08_'.bin2hex(random_bytes(6));$server->query("CREATE DATABASE `$owned` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci");$db=Database::connect(array_replace($local,['DSN'=>'','database'=>$owned,'DBDriver'=>'MySQLi','DBPrefix'=>'p08_','pConnect'=>false,'DBDebug'=>true,'failover'=>[]]),false);$assert($db->query('SELECT DATABASE() n')->getRow()->n===$owned,'owned MySQL fixture target verified');$forge=Database::forge($db);(new CreateWarehouseLogisticsFoundation($forge))->up();(new CreateWarehouseTransfers($forge))->up();(new AddWarehouseProductLabelLogo($forge))->up();$db->resetDataCache();$assert($db->tableExists('warehouse_transfer_discrepancies')&&$db->fieldExists('label_logo','warehouse_products'),'three canonical migration effects are present');
$now=gmdate('Y-m-d H:i:s');foreach([['Origen','ORI'],['Destino','DES']]as$x)$db->table('warehouses')->insert(['name'=>$x[0],'code'=>$x[1],'status'=>'active','created_at'=>$now,'updated_at'=>$now,'deleted'=>0]);$origin=1;$destination=2;$db->table('warehouse_products')->insert(['name'=>'Producto áéí','internal_code'=>'P08-1','barcode'=>'4006381333931','control_unit'=>'PZA','status'=>'active','created_at'=>$now,'updated_at'=>$now,'deleted'=>0]);$product=1;$move=new WarehouseMovementService($db);$stock=new WarehouseStockService($db);$entry=$move->createDraft(['movement_type'=>'ENTRY','warehouse_id'=>$origin,'lines'=>[['warehouse_product_id'=>$product,'quantity'=>'100']]],1);$move->confirm($entry,1);$exit=$move->createDraft(['movement_type'=>'EXIT','warehouse_id'=>$origin,'lines'=>[['warehouse_product_id'=>$product,'quantity'=>'20']]],1);$move->confirm($exit,1);$adjust=$move->createDraft(['movement_type'=>'ADJUSTMENT','warehouse_id'=>$origin,'lines'=>[['warehouse_product_id'=>$product,'physical_quantity'=>'75']]],1);$move->confirm($adjust,1);$assert($stock->getStock($product,$origin)==='75.000000','entry, exit and adjustment change stock only through confirmed movements');
$blocked=$move->createDraft(['movement_type'=>'EXIT','warehouse_id'=>$origin,'lines'=>[['warehouse_product_id'=>$product,'quantity'=>'76']]],1);try{$move->confirm($blocked,1);throw new RuntimeException('negative stock accepted');}catch(InvalidArgumentException){$assert($stock->getStock($product,$origin)==='75.000000','insufficient exit rolls back without negative stock');}
$transfer=new WarehouseTransferService($db);$id=$transfer->createDraft(['origin_warehouse_id'=>$origin,'destination_warehouse_id'=>$destination,'lines'=>[['warehouse_product_id'=>$product,'quantity_sent'=>'40']]],1);$transfer->dispatch($id,1);$line=(int)$db->table('warehouse_transfer_lines')->where('warehouse_transfer_id',$id)->get()->getRow()->id;$assert($stock->getStock($product,$origin)==='35.000000'&&$transfer->getInTransitStock($product)==='40.000000','dispatch decreases origin and records in transit');$transfer->receive($id,[$line=>'30'],'partial',1);$assert($stock->getStock($product,$destination)==='30.000000'&&$transfer->getInTransitStock($product)==='10.000000','partial receipt preserves pending transit');$transfer->receive($id,[$line=>'10'],'complete',1);$assert($stock->getStock($product,$destination)==='40.000000'&&$transfer->getInTransitStock($product)==='0.000000','complete receipt does not duplicate stock');try{$transfer->receive($id,[$line=>'1'],'retry',1);throw new RuntimeException('duplicate receipt accepted');}catch(InvalidArgumentException){$assert($stock->getStock($product,$destination)==='40.000000','duplicate receipt is rejected idempotently');}
$difference=$transfer->createDraft(['origin_warehouse_id'=>$origin,'destination_warehouse_id'=>$destination,'lines'=>[['warehouse_product_id'=>$product,'quantity_sent'=>'10']]],1);$transfer->dispatch($difference,1);$dline=(int)$db->table('warehouse_transfer_lines')->where('warehouse_transfer_id',$difference)->get()->getRow()->id;$transfer->receive($difference,[$dline=>'8'],'partial',1);$transfer->closeWithDifference($difference,'missing',1);$assert($db->table('warehouse_transfers')->where('id',$difference)->get()->getRow()->status==='received_with_difference'&&$transfer->getInTransitStock($product)==='0.000000','difference closes pending transit without destination inflation');
$labels=new WarehouseLabelService($db);$movementCount=$db->table('warehouse_movements')->countAllResults();$preview=$labels->renderPreview($product,['size_preset'=>'50x30','quantity'=>1]);$pdf=$labels->pdf($product,['size_preset'=>'50x30','quantity'=>1]);$assert(str_contains($preview,'Producto áéí')&&str_contains($preview,'<svg')&&str_starts_with($pdf,'%PDF-'),'labels preserve UTF-8 and generate matching preview/PDF');$assert($db->table('warehouse_movements')->countAllResults()===$movementCount,'label generation creates no movement');echo"$passed passed, 0 failed. No source data or PAC accessed.\n";
}catch(Throwable$e){fwrite(STDERR,'[FAIL] '.$e->getMessage().PHP_EOL.$e->getTraceAsString().PHP_EOL);exit(1);}finally{if($db)$db->close();if($server&&$owned){if(!preg_match('/^ikontrol_test_p08_[a-f0-9]{12}$/D',$owned))throw new RuntimeException('Unsafe cleanup target.');$server->query("DROP DATABASE `$owned`");$server->close();echo"Owned synthetic MySQL schema removed.\n";}}
