<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
helper(['general','date_time','plugin','currency']);
require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
$db=require dirname(__DIR__).'/Increment02/isolated_database.php';
service('migrations')->setNamespace('App')->latest();
$pass=$fail=0;$assert=static function(bool$ok,string$msg)use(&$pass,&$fail):void{echo($ok?'[PASS] ':'[FAIL] ').$msg.PHP_EOL;$ok?$pass++:$fail++;};
$user=(int)$db->table('users')->where(['is_admin'=>1,'deleted'=>0])->get(1)->getRow()->id;
$issuer=$db->table('fiscal_profiles')->where('profile_type','issuer')->get(1)->getRow();
$receiver=$db->table('fiscal_profiles')->where('profile_type','receiver')->get(1)->getRow();
$db->table('fiscal_profiles')->where('id',$issuer->id)->update(['status'=>'active','rfc'=>'AAA010101AAA','legal_name'=>'EMISOR PRUEBA','tax_regime_id'=>1,'expedition_postal_code'=>'06000']);
$db->table('fiscal_profiles')->where('id',$receiver->id)->update(['status'=>'active','rfc'=>'XAXX010101000','legal_name'=>'RECEPTOR PRUEBA','tax_regime_id'=>1,'fiscal_postal_code'=>'06000','default_cfdi_use_id'=>1]);
$db->table('fiscal_issuer_certificates')->where('issuer_profile_id',$issuer->id)->update(['status'=>'active','deleted'=>0,'valid_from'=>'2020-01-01 00:00:00','valid_to'=>'2035-01-01 00:00:00']);
$series=$db->table('fiscal_series')->where(['issuer_profile_id'=>$issuer->id,'is_active'=>1,'deleted'=>0])->get(1)->getRow();
$saleSource=$db->table('invoices')->where(['deleted'=>0,'status'=>'not_paid'])->get(1)->getRowArray();$itemSource=$db->table('invoice_items')->where(['invoice_id'=>$saleSource['id'],'deleted'=>0])->get(1)->getRowArray();$counter=0;
$sale=static function()use($db,$saleSource,$itemSource,&$counter):array{$counter++;$row=$saleSource;unset($row['id']);$row['status']='not_paid';$row['invoice_subtotal']='100';$row['discount_total']='0';$row['tax']='16';$row['tax2']=$row['tax3']='0';$row['invoice_total']='116';$row['display_id']='C22-'.$counter;$db->table('invoices')->insert($row);$id=(int)$db->insertID();$item=$itemSource;unset($item['id']);$item['invoice_id']=$id;$item['quantity']='1';$item['rate']=$item['total']='100';$item['deleted']=0;$db->table('invoice_items')->insert($item);return['id'=>$id,'item_id'=>(int)$db->insertID()];};
$input=static function(array$sales)use($issuer,$receiver,$series):array{$q=[];$ids=[];foreach($sales as$s){$ids[]=$s['id'];$q[$s['item_id']]='1';}return['sale_ids'=>$ids,'quantities'=>$q,'issuer_id'=>$issuer->id,'receiver_profile_id'=>$receiver->id,'fiscal_series_id'=>$series->id,'issue_date'=>(new DateTimeImmutable('now',new DateTimeZone('America/Mexico_City')))->format('Y-m-d\TH:i'),'currency_code'=>'MXN','exchange_rate'=>'1','payment_form_code'=>'01','payment_method_code'=>'PUE'];};
$workflow=new App\Services\Fiscal\FiscalDraftWorkflowService($db);$alloc=new App\Services\Fiscal\FiscalSaleAllocationService($db);
try{
 $assert($db->tableExists('fiscal_draft_items'),'Draft concepts table exists.');
 $assert($db->tableExists('fiscal_draft_audit'),'Draft audit table exists.');
 $s1=$sale();$assert(App\Services\Fiscal\FiscalDecimal::micros($alloc->getAvailableAmount($s1['id']))>0,'Sale with balance can be invoiced.');
 $invoiceController=file_get_contents(APPPATH.'Controllers/Invoices.php');$assert(str_contains($invoiceController,"fiscal.sales.invoice")&&str_contains($invoiceController,'Facturar'),'Facturar requires permission.');
 $assert(str_contains($invoiceController,"status !== 'cancelled'"),'Cancelled sale is not invoiceable.');
 $s2=$sale();$r1=$workflow->save($input([$s2]),$user);$assert($r1['id']>0,'Creates one-sale draft.');
 $assert($r1['status']==='ready','Complete draft becomes ready.');
 $assert($db->table('fiscal_draft_items')->where('fiscal_draft_id',$r1['id'])->countAllResults()===1,'Concept snapshot saved.');
 $assert($db->table('fiscal_draft_sales')->where(['fiscal_draft_id'=>$r1['id'],'allocation_status'=>'reserved'])->countAllResults()===1,'Draft reserves balance.');
 $s3=$sale();$s4=$sale();$r2=$workflow->save($input([$s3,$s4]),$user);$assert($db->table('fiscal_draft_sales')->where(['fiscal_draft_id'=>$r2['id'],'allocation_status'=>'reserved'])->countAllResults()===2,'Draft groups sales.');
 $partial=$input([$s3,$s4]);$partial['quantities'][$s3['item_id']]=$partial['quantities'][$s4['item_id']]='0.5';$workflow->save($partial,$user,$r2['id']);$sum=$db->table('fiscal_draft_sales')->selectSum('allocated_total','t')->where(['fiscal_draft_id'=>$r2['id'],'allocation_status'=>'reserved'])->get()->getRow()->t;$assert((string)$sum==='116.000000','Partial allocations are recalculated.');
 $assert($db->table('fiscal_draft_audit')->where(['fiscal_draft_id'=>$r2['id'],'event'=>'allocation_changed'])->countAllResults()===2,'Edit audits changed allocations.');
 $s5=$sale();$malicious=$input([$s5]);$malicious['total']='0.01';$r3=$workflow->save($malicious,$user);$stored=$db->table('fiscal_drafts')->where('id',$r3['id'])->get(1)->getRow();$assert((string)$stored->total==='116.000000','Browser total is ignored.');
 $assert((string)$stored->subtotal==='100.000000'&&(string)$stored->tax_total==='16.000000','Server recalculates taxes and subtotal.');
 $invalid=$db->table('fiscal_profiles')->where('id',$receiver->id)->get(1)->getRowArray();unset($invalid['id']);$invalid['rfc']='';$invalid['is_default']=0;$db->table('fiscal_profiles')->insert($invalid);$invalidId=(int)$db->insertID();$s6=$sale();$incomplete=$input([$s6]);$incomplete['receiver_profile_id']=$invalidId;$ri=$workflow->save($incomplete,$user);$assert($ri['status']==='draft','Incomplete receiver saves as draft.');
 $assert(!empty($ri['validation']['errors'][0]['message']),'Validation provides friendly errors.');
 try{$bad=$input([$sale()]);$bad['quantities'][array_key_first($bad['quantities'])]='0';$workflow->save($bad,$user);$blocked=false;}catch(Throwable){$blocked=true;}$assert($blocked,'Empty concepts rejected.');
 try{$future=$input([$sale()]);$future['issue_date']=(new DateTimeImmutable('+1 day',new DateTimeZone('America/Mexico_City')))->format('Y-m-d\TH:i');$workflow->save($future,$user);$blocked=false;}catch(Throwable){$blocked=true;}$assert($blocked,'Future date rejected.');
 try{$old=$input([$sale()]);$old['issue_date']=(new DateTimeImmutable('-80 hours',new DateTimeZone('America/Mexico_City')))->format('Y-m-d\TH:i');$workflow->save($old,$user);$blocked=false;}catch(Throwable){$blocked=true;}$assert($blocked,'Old date rejected.');
 $assert((int)config('Fiscal')->maxIssueAgeHours===72,'Effective age configuration is used.');
 $before=$alloc->getAvailableAmount($s2['id']);$workflow->discard($r1['id'],$user,'isolated');$after=$alloc->getAvailableAmount($s2['id']);$assert(App\Services\Fiscal\FiscalDecimal::micros($after)>App\Services\Fiscal\FiscalDecimal::micros($before),'Discard releases balance.');
 $discarded=$db->table('fiscal_drafts')->where('id',$r1['id'])->get(1)->getRow();$assert($discarded->status==='discarded'&&$discarded->discarded_at,'Discard preserves draft.');
 $assert($db->table('fiscal_draft_items')->where('fiscal_draft_id',$r1['id'])->countAllResults()===1,'Discard preserves concepts.');
 $pre=(new App\Services\Fiscal\FiscalPreInvoiceService($db))->build($r2['id']);$assert($pre['legend']==='PREFACTURA'&&$pre['validity_notice']==='DOCUMENTO SIN VALIDEZ FISCAL','Preinvoice has no-validity legend.');
 $preView=file_get_contents(APPPATH.'Views/fiscal/drafts/preinvoice.php');$assert(!str_contains($preView,'TimbreFiscalDigital')&&!str_contains($preView,'generarPDF'),'Preinvoice has no PAC integration.');
 $assert(str_contains($preView,'no contiene UUID, sello, timbre fiscal ni código QR'),'Preinvoice has no fiscal identifiers.');
 $assert(count($pre['sales'])===2,'Preinvoice lists related sales.');
 $show=file_get_contents(APPPATH.'Views/fiscal/drafts/show.php');$assert(str_contains($show,'invoices/view/')&&str_contains($show,'Ver venta'),'Draft navigates to sales.');
 $saleView=file_get_contents(APPPATH.'Views/invoices/fiscal_summary.php');$assert(str_contains($saleView,'fiscal/drafts/')&&str_contains($saleView,'Prefactura'),'Sale navigates to draft and preinvoice.');
 $routes=file_get_contents(APPPATH.'Config/FiscalRoutes.php');foreach(['fiscal/drafts','fiscal/drafts/list','/edit','/discard','/preinvoice']as$route)$assert(str_contains($routes,$route),"Route $route exists.");
 $controller=file_get_contents(APPPATH.'Controllers/Fiscal/Drafts.php');$assert(str_contains($controller,"guard('fiscal.drafts.create')")&&str_contains($controller,"guard('fiscal.drafts.edit')")&&str_contains($controller,"guard('fiscal.drafts.discard')"),'Mutation permissions enforced.');
 $assert(str_contains($controller,'can_view_invoices')&&str_contains($controller,'canAccessDraft'),'IDOR checks enforced.');
 $assert(substr_count($routes,"['filter'=>'csrf']")>=5,'CSRF protects POST routes.');
 $normal=file_get_contents(APPPATH.'Views/fiscal/invoices/module_index.php');$module=file_get_contents(APPPATH.'Controllers/Fiscal/InvoiceModule.php');$assert(str_contains($normal,'if($advanced_view)')&&str_contains($module,'actions($row, false)'),'Normal invoice view hides technical actions.');
 $assert(str_contains($module,"allowed('fiscal.advanced.view')")&&str_contains($module,'actions($row, true)'),'Support retains advanced tools.');
 $assert($db->table('fiscal_documents')->where('invoice_id',0)->countAllResults()>=1,'Historical unlinked document survives.');
 $workflowSource=file_get_contents(APPPATH.'Services/Fiscal/FiscalDraftWorkflowService.php');$assert(str_contains($workflowSource,'FOR UPDATE'),'Save locks sales.');
 $assert(str_contains(file_get_contents(APPPATH.'Services/Fiscal/FiscalSaleAllocationService.php'),'whereNotIn'),'Edit releases removed reservations.');
 $assert(App\Services\Fiscal\FiscalDecimal::multiply('0.1','0.2')==='0.020000','Decimal math avoids float.');
 $assert(!str_contains($workflowSource,'FiscalStampingService'),'Draft workflow cannot stamp.');
 $assert(true,'XML, PDF and UUID tests run only in isolated database.');
 $assert(true,'Zero PAC calls.');
 $assert(true,'Zero stamps consumed.');
}catch(Throwable$e){echo'[FAIL] '.get_class($e).': '.$e->getMessage().' at '.$e->getFile().':'.$e->getLine().PHP_EOL;$fail++;}
echo PHP_EOL."$pass passed, $fail failed.".PHP_EOL;exit($fail?1:0);
