<?php if (!empty($can_view_supplier_costs)): $prefix=$field_prefix; $selectId=$prefix.'-item-supplier'; ?>
<div class="card bg-light mb15 commercial-supplier-fields" data-prefix="<?php echo esc($prefix,'attr'); ?>"><div class="card-body">
<h6><i data-feather="briefcase" class="icon-16"></i> Información interna de proveedor</h6>
<div class="form-group"><label>Proveedor utilizado</label><div class="input-group"><?php echo form_dropdown('supplier_id',$suppliers_dropdown??[],(int)($model_info->supplier_id??0),"id='{$selectId}' class='form-control select2'".(empty($can_edit_supplier_costs)?" disabled='disabled'":"")); ?><?php if(!empty($can_manage_suppliers)&&!empty($can_edit_supplier_costs)): ?><button type="button" class="btn btn-default quick-supplier-open"><i data-feather="plus" class="icon-16"></i> Nuevo proveedor</button><?php endif; ?><button type="button" class="btn btn-outline-primary compare-suppliers <?php echo empty($model_info->item_id)?'hide':''; ?>"><i data-feather="bar-chart-2" class="icon-16"></i> Comparar</button></div></div>
<?php if(!empty($can_edit_supplier_costs))echo view('items/_commercial_margin_fields',['field_prefix'=>$prefix,'model_info'=>$model_info]); ?>
<div class="selected-supplier-history alert alert-light <?php echo empty($selected_supplier_history)?'hide':''; ?>" data-last-cost="<?php echo esc($selected_supplier_history['last_cost']??'','attr'); ?>"><strong>Último costo:</strong> <span data-history-cost><?php echo isset($selected_supplier_history['last_cost'])?to_currency($selected_supplier_history['last_cost']):'-'; ?></span> · <span data-history-date><?php echo isset($selected_supplier_history['last_date'])?esc(format_to_datetime($selected_supplier_history['last_date'])):'-'; ?></span><?php if(!empty($can_edit_supplier_costs)): ?> <button type="button" class="btn btn-default btn-sm use-last-cost">Usar último costo</button><?php endif; ?></div>
<div class="alert alert-info mb0 <?php echo empty($cost_indicators['supplier_count'])?'hide':''; ?>"><b>Referencia histórica</b>: <?php echo esc($cost_indicators['last_supplier']??'-'); ?> · <?php echo isset($cost_indicators['last_cost'])?to_currency($cost_indicators['last_cost']):'-'; ?> · mejor <?php echo isset($cost_indicators['best_cost'])?to_currency($cost_indicators['best_cost']):'-'; ?></div>
</div></div>
<script>
$(function(){var card=$('.commercial-supplier-fields[data-prefix="<?php echo esc($prefix,'js'); ?>"]'),form=card.closest('form'),select=card.find('#<?php echo $selectId; ?>'),comparisonEl=$('.supplier-comparison-modal[data-prefix="<?php echo esc($prefix,'js'); ?>"]')[0],comparison=new bootstrap.Modal(comparisonEl);
function choose(d){var id=String(d.supplier_id||d.id||''),name=d.supplier_name||d.name||d.text||'';if(!id||!name)return false;if(!select.find('option[value="'+id+'"]').length)select.append(new Option(name,id,true,true));select.val(id).trigger('change');return true;}
function reference(){var product=form.find('[name=item_id]').val(),supplier=select.val(),box=card.find('.selected-supplier-history');if(!product||!supplier){box.addClass('hide');return;}appAjaxRequest({url:'<?php echo get_uri('proposals/products'); ?>/'+product+'/suppliers/'+supplier+'/cost-reference',type:'POST',dataType:'json',success:function(r){if(!r.found){box.addClass('hide');return;}box.removeClass('hide').attr('data-last-cost',r.reference.last_cost);box.find('[data-history-cost]').text(r.reference.last_cost);box.find('[data-history-date]').text(r.reference.last_date);}});}
select.on('change',reference);card.find('.use-last-cost').on('click',function(){var v=card.find('.selected-supplier-history').attr('data-last-cost');if(v)form.find('[name=<?php echo $prefix; ?>_item_cost]').val(v).trigger('change');});
form.on('fiscal:item:load',function(){card.find('.compare-suppliers').toggleClass('hide',!form.find('[name=item_id]').val());});
card.find('.compare-suppliers').on('click',function(){var product=form.find('[name=item_id]').val();if(!product)return;var content=$(comparisonEl).find('.supplier-comparison-content').html('<div class="p20 text-center">Cargando…</div>');comparison.show();appAjaxRequest({url:'<?php echo get_uri('proposals/products'); ?>/'+product+'/supplier-comparison',type:'POST',data:{proposal_item_id:0},success:function(html){content.html(html);}});});$(comparisonEl).on('click','.select-compared-supplier',function(){choose({id:$(this).data('id'),name:$(this).data('name')});comparison.hide();});
var quickEl=$('.quick-supplier-modal[data-prefix="<?php echo esc($prefix,'js'); ?>"]')[0];if(quickEl){$(quickEl).appendTo(document.body);var quick=new bootstrap.Modal(quickEl),qf=$(quickEl).find('.quick-supplier-form'),existing=null;card.find('.quick-supplier-open').on('click',function(){existing=null;qf.find('[data-supplier-duplicate]').addClass('hide');quick.show();});qf.appForm({isModal:false,closeModalOnSuccess:false,onSuccess:function(r){if(choose(r)){quick.hide();qf[0].reset();}},onError:function(r){if(!r.duplicate_supplier)return;existing=r.existing;var box=qf.find('[data-supplier-duplicate]').removeClass('hide');box.find('[data-supplier-duplicate-message]').text(r.message);box.find('[data-supplier-existing-name]').text(existing.name);box.find('[data-supplier-existing-detail]').text([existing.rfc,existing.phone,existing.email].filter(Boolean).join(' · '));box.find('[data-supplier-create-anyway]').toggleClass('hide',!r.allow_create);}});qf.on('click','[data-supplier-use-existing]',function(){if(existing&&choose(existing))quick.hide();});qf.on('click','[data-supplier-create-anyway]',function(){qf.find('[data-supplier-allow-similar]').val('1');qf.submit();});quickEl.addEventListener('hidden.bs.modal',function(){if($('#ajaxModal').hasClass('show'))document.body.classList.add('modal-open');});}});
</script>
<?php endif; ?>
