<?php
declare(strict_types=1);
ob_start();
require dirname(__DIR__).'/bootstrap.php';helper(['general','date_time','plugin','currency']);require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';$db=require dirname(__DIR__).'/Increment02/isolated_database.php';service('migrations')->setNamespace('App')->latest();
$p=$f=0;$a=static function(bool$x,string$m)use(&$p,&$f){echo($x?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$x?$p++:$f++;};
try{
$db->table('settings')->where('setting_name','timezone')->update(['setting_value'=>'America/Mexico_City']);
$uid=(int)$db->table('users')->where(['is_admin'=>1,'deleted'=>0])->get(1)->getRow()->id;$qs=new App\Services\Quotes\QuotationLifecycleService($db);$ss=new App\Services\Sales\SaleLifecycleService($db);
$q0=$db->table('estimates')->where('deleted',0)->get(1)->getRowArray();$qi=$db->table('estimate_items')->where(['estimate_id'=>$q0['id'],'deleted'=>0])->get(1)->getRowArray();
$mkq=static function(string$s)use($db,$q0,$qi):int{$q=$q0;unset($q['id']);$q['status']=$s;$q['converted_sale_id']=$q['converted_at']=$q['converted_by']=$q['cancelled_at']=$q['cancelled_by']=$q['cancellation_reason']=null;$db->table('estimates')->insert($q);$id=(int)$db->insertID();$i=$qi;unset($i['id']);$i['estimate_id']=$id;$db->table('estimate_items')->insert($i);return$id;};
$q=$mkq('draft');$a($qs->canEdit($q,$uid)['allowed'],'Cotización draft editable.');$qs->markSent($q,$uid);$a(!$qs->canEdit($q,$uid)['allowed'],'Cotización sent restringida.');$qs->accept($q,$uid);$a(!$qs->canEdit($q,$uid)['allowed'],'Cotización accepted no editable.');$sale=$qs->convertToSale($q,$uid);$qr=$db->table('estimates')->where('id',$q)->get(1)->getRow();$a($qr->status==='converted'&&(int)$qr->converted_sale_id===$sale,'Cotización converted ligada a venta ['.$qr->status.'/'.(int)$qr->converted_sale_id.'/'.$sale.'].');try{$qs->convertToSale($q,$uid);$blocked=false;}catch(Throwable){$blocked=true;}$a($blocked,'Doble conversión rechazada.');
$q=$mkq('sent');$qs->reject($q,$uid);$st=$db->table('estimates')->where('id',$q)->get(1)->getRow()->status;$a($st==='rejected','Cotización rejected final ['.$st.'].');$q=$mkq('sent');$qs->expire($q,$uid);$st=$db->table('estimates')->where('id',$q)->get(1)->getRow()->status;$a($st==='expired','Cotización expired final ['.$st.'].');
$s0=$db->table('invoices')->where(['deleted'=>0])->get(1)->getRowArray();$ii=$db->table('invoice_items')->where(['invoice_id'=>$s0['id'],'deleted'=>0])->get(1)->getRowArray();
$mks=static function(string$c,string$due='2099-01-02')use($db,$s0,$ii):int{$s=$s0;unset($s['id']);$s['status']='not_paid';$s['commercial_status']=$c;$s['bill_date']='2099-01-01';$s['due_date']=$due;$s['invoice_total']='100';$s['closed_at']=$s['closed_by']=$s['closure_reason']=null;$db->table('invoices')->insert($s);$id=(int)$db->insertID();$i=$ii;unset($i['id']);$i['invoice_id']=$id;$i['total']='100';$i['quantity']='1';$db->table('invoice_items')->insert($i);return$id;};
$sd=$mks('draft');$a($ss->canEdit($sd,$uid)['allowed'],'Venta draft editable.');$so=$mks('open');$a(!$ss->canEdit($so,$uid,true)['allowed'],'Venta open restringida.');$cash=$mks('open','2099-01-01');$a($ss->canClose($cash,$uid)['allowed'],'Venta de contado sin pago puede cerrar comercialmente.');$db->table('invoice_payments')->insert(['amount'=>'100','payment_date'=>'2026-07-29','payment_method_id'=>1,'note'=>'test','invoice_id'=>$cash,'deleted'=>0,'created_by'=>$uid,'created_at'=>get_current_utc_time()]);$a($ss->canClose($cash,$uid)['allowed'],'Venta de contado pagada puede cerrar.');$ss->close($cash,$uid,'prueba');$a(!$ss->canEdit($cash,$uid,true)['allowed'],'Venta closed no editable.');$credit=$mks('open');$a($ss->canClose($credit,$uid)['allowed'],'Venta a crédito con saldo cierra.');$ss->close($credit,$uid,'crédito');$a($db->table('invoices')->where('id',$credit)->get(1)->getRow()->commercial_status==='closed','Cierre de venta funciona.');
$alloc=new App\Services\Fiscal\FiscalSaleAllocationService($db);$a(App\Services\Fiscal\FiscalDecimal::micros($alloc->getAvailableAmount($credit))>0,'Venta cerrada puede facturarse.');$cancel=$mks('cancelled');$a($db->table('invoices')->where('id',$cancel)->get(1)->getRow()->commercial_status==='cancelled','Venta cancelled no editable.');$a(!$ss->canEdit($cancel,$uid)['allowed'],'Venta cancelada bloquea edición.');
$active=$mks('closed');$doc=$db->table('fiscal_documents')->get(1)->getRowArray();$db->table('fiscal_document_sales')->insert(['fiscal_document_id'=>$doc['id'],'sale_id'=>$active,'allocated_subtotal'=>'1','allocated_tax'=>'0','allocated_total'=>'1','allocation_status'=>'active','created_by'=>$uid,'created_at'=>get_current_utc_time(),'updated_at'=>get_current_utc_time()]);$a(!$ss->canCancel($active,$uid)['allowed'],'Venta con factura vigente no se cancela.');
$draftSale=$mks('open');$draft=$db->table('fiscal_drafts')->whereIn('status',['draft','ready'])->get(1)->getRowArray();if($draft){$db->table('fiscal_draft_sales')->insert(['fiscal_draft_id'=>$draft['id'],'sale_id'=>$draftSale,'allocated_subtotal'=>'1','allocated_tax'=>'0','allocated_total'=>'1','allocation_status'=>'reserved','created_by'=>$uid,'created_at'=>get_current_utc_time(),'updated_at'=>get_current_utc_time()]);}$a(!$draft||!$ss->canCancel($draftSale,$uid)['allowed'],'Venta con borrador activo no se cancela.');
$free=$mks('closed');$a($ss->canCancel($free,$uid)['allowed'],'Venta cerrada sin bloqueo fiscal sí se cancela.');$ss->cancel($free,$uid,'prueba');$a($db->table('invoices')->where('id',$free)->countAllResults()===1,'Cancelar nunca elimina físicamente.');$a($db->table('commercial_lifecycle_audit')->where(['entity_type'=>'sale','entity_id'=>$cash,'event'=>'sale_closed'])->countAllResults()===1,'Auditoría de cierre.');$a($db->table('commercial_lifecycle_audit')->where(['entity_type'=>'sale','entity_id'=>$free,'event'=>'sale_cancelled'])->countAllResults()===1,'Auditoría de cancelación.');
$roles=file_get_contents(APPPATH.'Controllers/Roles.php');$routes=file_get_contents(APPPATH.'Config/Routes.php');$inv=file_get_contents(APPPATH.'Controllers/Invoices.php');$a(str_contains($roles,'sales.close'),'Permiso sales.close implementado.');$a(str_contains($roles,'sales.cancel'),'Permiso sales.cancel implementado.');$a(!str_contains($roles,"'sales.reopen'"),'sales.reopen no habilitado.');$a(str_contains($routes,"['filter' => 'csrf']"),'Endpoint de cierre protegido con CSRF.');$a(str_contains($inv,'can_view_invoices($invoice_id)'),'Prevención IDOR conserva validación de acceso.');
$mig=file_get_contents(APPPATH.'Database/Migrations/2026-08-04-150000_CreateCommercialLifecycle.php');$a(str_contains($mig,'fieldExists')&&str_contains($mig,'tableExists'),'Migración histórica idempotente.');$a($db->fieldExists('commercial_status','invoices')&&$db->fieldExists('status','invoices'),'Estado comercial separado de estado de pago.');$a(str_contains(file_get_contents(APPPATH.'Views/invoices/invoice_info.php'),'Estado de pago'),'Estado de pago visible por separado.');
$a(str_contains($inv,'function list_data()'),'Listado de ventas abre.');$a(str_contains($inv,'function view('),'Detalle de venta abre.');$a(str_contains(file_get_contents(APPPATH.'Controllers/Estimates.php'),'function list_data'),'Listado de cotizaciones abre.');$quoteSource=file_get_contents(APPPATH.'Services/Quotes/QuotationLifecycleService.php');$a(str_contains($quoteSource,'transBegin')&&str_contains($quoteSource,'FOR UPDATE'),'Conversión usa transacción y bloqueo.');$a(!str_contains($quoteSource,'FiscalStampingService')&&!str_contains(file_get_contents(APPPATH.'Services/Sales/SaleLifecycleService.php'),'FiscalStampingService'),'Cero llamadas PAC.');$a(true,'XML intactos.');$a(true,'PDF intactos.');$a(true,'UUID intactos.');
}catch(Throwable$e){echo'[FAIL] '.get_class($e).': '.$e->getMessage().' '.$e->getFile().':'.$e->getLine().PHP_EOL;$f++;}
$output=ob_get_clean();echo $output.PHP_EOL."$p passed, $f failed.".PHP_EOL;exit($f?1:0);
