<?php
declare(strict_types=1);ob_start();$root=dirname(__DIR__,2);require $root.'/tests/bootstrap.php';helper(['general','date_time','currency']);$db=require $root.'/tests/Increment02/isolated_database.php';
use App\Services\WarehouseMovementService;use App\Services\WarehouseStockService;use App\Services\WarehouseTransferService;
$p=$f=0;$ok=function($v,$m)use(&$p,&$f){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$p++:$f++;};$now=get_current_utc_time();$actor=(int)$db->table('users')->where('deleted',0)->get(1)->getRow()->id;
$mkWarehouse=function($name,$code)use($db,$actor,$now){$db->table('warehouses')->insert(['name'=>$name,'code'=>$code.'-'.substr(uniqid(),-5),'status'=>'active','created_by'=>$actor,'created_at'=>$now,'updated_at'=>$now,'deleted'=>0]);return(int)$db->insertID();};$origin=$mkWarehouse('León F2','LEONF2');$destination=$mkWarehouse('Guadalajara F2','GDLF2');$db->table('warehouse_products')->insert(['name'=>'T28 F2','internal_code'=>'T28-'.uniqid(),'control_unit'=>'PAR','status'=>'active','created_by'=>$actor,'created_at'=>$now,'updated_at'=>$now,'deleted'=>0]);$product=(int)$db->insertID();
$stock=new WarehouseStockService($db);$movement=new WarehouseMovementService($db);$entry=$movement->createDraft(['movement_type'=>'ENTRY','warehouse_id'=>$origin,'lines'=>[['warehouse_product_id'=>$product,'quantity'=>'200']]],$actor);$movement->confirm($entry,$actor);$ok($db->tableExists('warehouse_movement_lines')&&$stock->getTotalControlled($product)==='200.000000'&&is_array($stock->getProductStocks($product)),'detalle consulta la tabla canónica prefijada sin error 1146');
$svc=new WarehouseTransferService($db);$tr=$svc->createDraft(['origin_warehouse_id'=>$origin,'destination_warehouse_id'=>$destination,'lines'=>[['warehouse_product_id'=>$product,'quantity_sent'=>'40']]],$actor);$ok($stock->getStock($product,$origin)==='200.000000'&&$svc->getInTransitStock($product)==='0.000000','borrador no afecta stock ni tránsito');$svc->dispatch($tr,$actor);$ok($stock->getStock($product,$origin)==='160.000000'&&$stock->getStock($product,$destination)==='0.000000'&&$svc->getInTransitStock($product)==='40.000000','despacho resta origen, no suma destino y deriva tránsito');$line=(int)$db->table('warehouse_transfer_lines')->where('warehouse_transfer_id',$tr)->get()->getRow()->id;$svc->receive($tr,[$line=>'30'],'Parcial',$actor);$ok($stock->getStock($product,$destination)==='30.000000'&&$svc->getInTransitStock($product)==='10.000000'&&$db->table('warehouse_transfers')->where('id',$tr)->get()->getRow()->status==='partially_received','recepción parcial suma 30 y deja 10 en tránsito');$svc->receive($tr,[$line=>'10'],'Final',$actor);$ok($stock->getStock($product,$destination)==='40.000000'&&$svc->getInTransitStock($product)==='0.000000'&&$db->table('warehouse_transfers')->where('id',$tr)->get()->getRow()->status==='received','segunda recepción completa traspaso');$ok($db->table('warehouse_transfer_receipts')->where('warehouse_transfer_id',$tr)->countAllResults()===2,'recepciones parciales se conservan como eventos propios');
$tr2=$svc->createDraft(['origin_warehouse_id'=>$origin,'destination_warehouse_id'=>$destination,'lines'=>[['warehouse_product_id'=>$product,'quantity_sent'=>'20']]],$actor);$svc->dispatch($tr2,$actor);$line2=(int)$db->table('warehouse_transfer_lines')->where('warehouse_transfer_id',$tr2)->get()->getRow()->id;$svc->receive($tr2,[$line2=>'18'],'Llegaron 18',$actor);$svc->closeWithDifference($tr2,'Faltante en tránsito',$actor);$diff=$db->table('warehouse_transfer_discrepancies')->where('warehouse_transfer_id',$tr2)->get()->getRow();$ok($diff&&$diff->quantity_difference==='-2.000000'&&$svc->getInTransitStock($product)==='0.000000'&&$db->table('warehouse_transfers')->where('id',$tr2)->get()->getRow()->status==='received_with_difference','faltante 2 se cierra con incidencia explícita sin entrar a destino');
$tr3=$svc->createDraft(['origin_warehouse_id'=>$origin,'destination_warehouse_id'=>$destination,'lines'=>[['warehouse_product_id'=>$product,'quantity_sent'=>'10']]],$actor);$svc->dispatch($tr3,$actor);$line3=(int)$db->table('warehouse_transfer_lines')->where('warehouse_transfer_id',$tr3)->get()->getRow()->id;$blocked=false;try{$svc->receive($tr3,[$line3=>'11'],'',$actor);}catch(InvalidArgumentException $e){$blocked=str_contains($e->getMessage(),'más de lo enviado');}$ok($blocked&&$stock->getStock($product,$destination)==='58.000000','sobrante mayor a enviado se bloquea sin alterar destino');$cancelBlocked=false;try{$svc->cancelDraft($tr3,$actor);}catch(InvalidArgumentException $e){$cancelBlocked=str_contains($e->getMessage(),'ya fue despachado');}$ok($cancelBlocked,'cancelación directa posterior al despacho está bloqueada');
$tr4=$svc->createDraft(['origin_warehouse_id'=>$origin,'destination_warehouse_id'=>$destination,'lines'=>[['warehouse_product_id'=>$product,'quantity_sent'=>'1']]],$actor);$svc->cancelDraft($tr4,$actor);$ok($db->table('warehouse_transfers')->where('id',$tr4)->get()->getRow()->status==='cancelled','borrador puede cancelarse sin movimientos');$ok($db->table('warehouse_transfer_events')->where('warehouse_transfer_id',$tr)->countAllResults()>=3,'timeline conserva creación, despacho y recepciones');$types=$db->table('warehouse_movements')->select('movement_type,warehouse_id')->where(['reference_type'=>'WAREHOUSE_TRANSFER','reference_id'=>$tr])->orderBy('id')->get()->getResultArray();$ok(array_column($types,'movement_type')===['EXIT','ENTRY','ENTRY'],'kardex usa ledger canónico para despacho y cada recepción');
$items=$db->table('items')->countAllResults();$proposals=$db->table('proposals')->countAllResults();$fiscal=$db->table('fiscal_documents')->countAllResults();$svc->updateLogistics($tr,['carrier'=>'DHL','tracking_number'=>'DHL123456'],$actor);$ok($db->table('items')->countAllResults()===$items&&$db->table('proposals')->countAllResults()===$proposals&&$db->table('fiscal_documents')->countAllResults()===$fiscal,'traspasos no modifican comercial, propuestas ni fiscal');
$a=$svc->createDraft(['origin_warehouse_id'=>$origin,'destination_warehouse_id'=>$destination,'lines'=>[['warehouse_product_id'=>$product,'quantity_sent'=>'100']]],$actor);$b=$svc->createDraft(['origin_warehouse_id'=>$origin,'destination_warehouse_id'=>$destination,'lines'=>[['warehouse_product_id'=>$product,'quantity_sent'=>'100']]],$actor);$svc->dispatch($a,$actor);$concurrencyBlocked=false;try{$svc->dispatch($b,$actor);}catch(InvalidArgumentException $e){$concurrencyBlocked=str_contains($e->getMessage(),'cantidad suficiente');}$ok($concurrencyBlocked,'bloqueo transaccional impide que dos despachos consuman el mismo saldo');$source=file_get_contents($root.'/app/Services/WarehouseTransferService.php');$ok(str_contains($source,'FOR UPDATE')&&str_contains($source,'transBegin'),'despacho y recepción usan transacción y bloqueo de filas');
echo "TOTAL PASS=$p FAIL=$f".PHP_EOL;$out=ob_get_clean();echo$out;exit($f?1:0);
