<?php
declare(strict_types=1);
namespace App\Services\Legacy\Fc2;
final class Fc2MasterDataCompatibilityService {
 public function clients(array$records):array{$f=[];$this->duplicates($records,'rfc','client','RFC_DUPLICATE','warning',$f);$this->duplicates($records,'razon_social_comparison','client','LEGAL_NAME_DUPLICATE','warning',$f);$this->duplicates($records,'email_comparison','client','EMAIL_DUPLICATE','warning',$f);$exact=[];$n=new Fc2DataNormalizer();foreach($records as$r){$d=$r->data;$key=implode('|',[$d['rfc']??'',$d['razon_social_comparison']??'',$d['codigo_postal']??'',$n->duplicateText($d['pais']??'')]);if($key!=='|||')$exact[$key][]=$r;}foreach($exact as$rows)if(count($rows)>1)foreach($rows as$r)$this->add($f,'conflict','CLIENT_EXACT_DUPLICATE_CANDIDATE','client',$r->sourceId);foreach($records as$r){$d=$r->data;$id=$r->sourceId;if(!$d['regimen_fiscal'])$this->add($f,'warning','CLIENT_TAX_REGIME_MISSING','client',$id);$this->add($f,'warning','CLIENT_CFDI_USE_MISSING','client',$id);if(in_array($d['rfc'],['XAXX010101000','XEXX010101000'],true))$this->add($f,'info','CLIENT_GENERIC_RFC','client',$id);if(!$n->validPostalCode($d['codigo_postal']))$this->add($f,'error','CLIENT_POSTAL_CODE_INVALID','client',$id);if($d['pais']&&!preg_match('/^(MEX|MEXICO|MÉXICO)$/iu',$d['pais']))$this->add($f,'warning','CLIENT_COUNTRY_REVIEW','client',$id);$this->add($f,'info','CLIENT_OBSERVATIONS_NO_DIRECT_DESTINATION','client',$id);if(!$d['rfc_valid'])$this->add($f,'warning','CLIENT_RFC_FORMAT_REVIEW','client',$id);}return$f;}
 public function products(array$records):array{$f=[];$this->duplicates($records,'clave_interna','product','PRODUCT_INTERNAL_KEY_DUPLICATE','warning',$f);foreach($records as$r){$d=$r->data;$id=$r->sourceId;if(!$d['descripcion'])$this->add($f,'error','PRODUCT_DESCRIPTION_MISSING','product',$id);if($d['precio_error']||$d['precio']===null)$this->add($f,'error','PRODUCT_PRICE_INVALID','product',$id);elseif(preg_match('/^0+(?:\.0+)?$/',$d['precio']))$this->add($f,'warning','PRODUCT_PRICE_ZERO','product',$id);if($d['clave_prod_serv_id']!==null&&!$d['clave_prod_serv'])$this->add($f,'error','PRODUCT_SAT_KEY_MISSING','product',$id);if($d['clave_unidad_id']!==null&&!$d['clave_unidad'])$this->add($f,'error','PRODUCT_SAT_UNIT_MISSING','product',$id);$this->add($f,'warning','PRODUCT_TAX_OBJECT_MISSING','product',$id);$this->add($f,'warning','PRODUCT_TAXES_MISSING','product',$id);$this->add($f,'warning','PRODUCT_TYPE_UNDECIDED','product',$id);if($d['observaciones'])$this->add($f,'info','PRODUCT_OBSERVATIONS_NO_DIRECT_DESTINATION','product',$id);if($d['precio']!==null&&str_contains($d['precio'],'.')&&strlen(rtrim(substr(strrchr($d['precio'],'.'),1),'0'))>2)$this->add($f,'info','PRODUCT_PRICE_REQUIRES_SIX_DECIMAL_DESTINATION','product',$id);}return$f;}
 public function series(array$records):array{$f=[];$groups=[];foreach($records as$r){$d=$r->data;$key=mb_strtoupper((string)$d['tipo']).'|'.mb_strtoupper((string)$d['serie']);$groups[$key][]=$r;}foreach($groups as$rows)if(count($rows)>1)foreach($rows as$r){$this->add($f,'conflict','SERIES_TYPE_SERIES_DUPLICATE','series',$r->sourceId);$this->add($f,'conflict','SERIES_FOLIO_AMBIGUOUS','series',$r->sourceId);$this->add($f,'conflict','SERIES_IKONTROL_CONSTRAINT_CONFLICT','series',$r->sourceId);}foreach($records as$r){$d=$r->data;if(!$d['serie'])$this->add($f,'warning','SERIES_EMPTY','series',$r->sourceId);$type=mb_strtoupper((string)$d['tipo']);if($type==='INGRESO')$this->add($f,'info','SERIES_INGRESO_MAPS_TO_I','series',$r->sourceId);elseif(!in_array($type,['EGRESO','PAGO'],true))$this->add($f,'conflict','SERIES_TYPE_NOT_TRANSLATABLE','series',$r->sourceId);}return$f;}
 public function summary(array$records,array$findings):array{$counts=['info'=>0,'warning'=>0,'conflict'=>0,'error'=>0];$affected=[];foreach($findings as$x){$counts[$x['severity']]++;$affected[$x['entity'].':'.$x['source_id']][$x['severity']]=true;}$compatible=0;$incomplete=0;foreach($records as$r){$a=$affected[(str_contains($r->sourceTable,'cliente')?'client':(str_contains($r->sourceTable,'producto')?'product':'series')).':'.$r->sourceId]??[];if(isset($a['error'])||isset($a['conflict']))$incomplete++;else$compatible++;}return['total'=>count($records),'compatible'=>$compatible,'requires_review'=>$incomplete]+$counts;}
 private function duplicates(array$rs,string$field,string$entity,string$code,string$severity,array&$f):void{$g=[];foreach($rs as$r){$v=$r->data[$field]??null;if($v!==null&&$v!=='')$g[(string)$v][]=$r;}foreach($g as$rows)if(count($rows)>1)foreach($rows as$r)$this->add($f,$severity,$code,$entity,$r->sourceId);}
 private function add(array&$f,string$severity,string$code,string$entity,string$id):void{$f[]=['severity'=>$severity,'code'=>$code,'entity'=>$entity,'source_id'=>$id];}
}
