<?php
declare(strict_types=1);
define('ROOTPATH',dirname(__DIR__,2).DIRECTORY_SEPARATOR);define('FCPATH',ROOTPATH);require ROOTPATH.'app/Config/Paths.php';$paths=new Config\Paths();define('APPPATH',realpath($paths->appDirectory).DIRECTORY_SEPARATOR);define('SYSTEMPATH',realpath($paths->systemDirectory).DIRECTORY_SEPARATOR);define('WRITEPATH',realpath($paths->writableDirectory).DIRECTORY_SEPARATOR);define('ENVIRONMENT','development');require $paths->systemDirectory.'/Boot.php';CodeIgniter\Boot::bootTest($paths);helper(['general','date_time','plugin','currency']);require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
use App\Services\Fiscal\FiscalIssueDatePolicy;use App\Services\Fiscal\SaleTaxPricingSimulationService;
$p=$f=0;$a=static function(bool$ok,string$m)use(&$p,&$f){echo($ok?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$ok?$p++:$f++;};$read=static fn($x)=>(string)file_get_contents(APPPATH.$x);
try{$view=$read('Views/fiscal/drafts/form.php');$workflow=$read('Services/Fiscal/FiscalDraftWorkflowService.php');$validation=$read('Services/Fiscal/FiscalDraftValidationService.php');$routes=$read('Config/FiscalRoutes.php');
 session()->set('user_id',1);$request=service('request');$request->setHeader('X-Requested-With','XMLHttpRequest');$controller=new App\Controllers\Fiscal\Drafts();$controller->initController($request,service('response'),service('logger'));$saleId=(int)(db_connect()->table('invoices')->where('deleted',0)->orderBy('id','DESC')->get(1)->getRow()->id??0);$html=$controller->create($saleId);
 $a(is_string($html)&&str_contains($html,'Revisión fiscal'),'Facturar abre revisión HTTP 200.');$a(!str_contains($html,'Page not found'),'La revisión no devuelve 404.');$a(str_contains($view,'venta comercial permanece cerrada e inmutable'),'Venta closed permanece inmutable.');$a(!str_contains($view,'edit_invoice')&&!str_contains($view,'invoice_modal_form'),'Editar concepto no llama editar venta.');$a(str_contains($view,'Editar datos fiscales'),'Concepto fiscal editable.');
 foreach(['fiscal_description'=>'Descripción fiscal','product_service_code'=>'Clave SAT','unit_code'=>'Clave unidad','tax_object_code'=>'Objeto impuesto']as$n=>$l)$a(str_contains($view,$n),$l.' editable.');
 $a(str_contains($view,'Uso CFDI'),'Uso CFDI visible.');$a(str_contains($view,'name="cfdi_use_code"'),'Uso CFDI editable.');$a(str_contains($view,'Método de pago'),'Método visible.');$a(str_contains($view,'name="payment_method_code"'),'Método editable.');$a(str_contains($view,'Forma de pago'),'Forma visible.');$a(str_contains($view,'name="payment_form_code"'),'Forma editable.');$a(str_contains($workflow,'default_cfdi_use_id'),'Defaults cliente usados.');$a(!str_contains($view,'confirm_receiver_update'),'Cambio no modifica defaults cliente.');
 $a(str_contains($view,'Fecha de expedición CFDI'),'Fecha CFDI visible.');$policy=new FiscalIssueDatePolicy();$now=new DateTimeImmutable('2026-08-13 12:00:00',new DateTimeZone('America/Mexico_City'));$policy->validate('2026-08-13 11:00:00',$now);$a(true,'Fecha válida.');try{$policy->validate('2026-08-14 11:00:00',$now);$blocked=false;}catch(Throwable){$blocked=true;}$a($blocked,'Fecha inválida bloqueada.');$a($policy->constraints($now)['timezone']==='America/Mexico_City','Timezone correcto.');
 $a(str_contains($workflow,'CfdiPaymentRuleService')&&str_contains($view,'payment_suggestion'),'Not paid preselecciona PPD/99.');$a(str_contains($workflow,"'snapshot_version'=>2"),'Snapshot v2 actualizado.');$a(str_contains($workflow,'fiscal_draft_item_taxes'),'Impuestos actualizados.');$decimal=new App\Services\Fiscal\FiscalDecimalCalculator();$base=$decimal->money($decimal->div('116.00','1.16'));$tax=$decimal->money($decimal->sub('116.00',$base));$a($base==='100.00'&&$tax==='16.00','Precio IVA incluido separa base/impuesto.');$a(str_contains($view,'Venta comercial')&&str_contains($view,'CFDI propuesto'),'Comparación comercial/fiscal.');$a(str_contains($validation,'CONCEPT_FISCAL_DESCRIPTION_REQUIRED'),'Blocker impide ready.');$a(str_contains($view,'Lista para prefactura'),'Lista permite borrador.');$a(str_contains($workflow,'candidateSales===$requested'),'No duplica borrador vigente.');
 $pre=$read('Services/Fiscal/FiscalPreInvoiceService.php');$a(str_contains($pre,"payment_method_code")&&str_contains($pre,"payment_form_code")&&str_contains($pre,"cfdi_use_code"),'Prefactura refleja selección.');$a(str_contains($read('Services/Sales/SaleLifecycleService.php'),'closed'),'Venta sigue closed.');$a(str_contains($routes,"fiscal/drafts/(:num)/stamp")&&str_contains($read('Services/Fiscal/FiscalDraftStampingPreflightService.php'),'development'),'Flujo PAC preparado.');
}catch(Throwable$e){echo'[FAIL] '.get_class($e).': '.$e->getMessage().PHP_EOL;$f++;}echo"\n{$p} passed, {$f} failed.\n";exit($f?1:0);
