<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';helper(['general','date_time','plugin','currency']);require_once APPPATH.'ThirdParty/PHP-Hooks/php-hooks.php';
$db=require dirname(__DIR__).'/Increment02/isolated_database.php';service('migrations')->setNamespace('App')->latest();
$settings=[];foreach($db->table('settings')->get()->getResult()as$s)$settings[$s->setting_name]=$s->setting_value;config('Rise')->app_settings_array=$settings+['timezone'=>'UTC','default_currency'=>'MXN'];session();
$p=0;$f=0;$a=static function(bool$ok,string$m)use(&$p,&$f){echo($ok?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$ok?$p++:$f++;};
foreach(['fiscal_documents','fiscal_document_issuers','fiscal_document_receivers','fiscal_document_items','fiscal_document_item_taxes','fiscal_document_tax_totals','fiscal_document_metadata','fiscal_document_audit','sat_payment_forms','sat_payment_methods','sat_currencies']as$t)$a($db->tableExists($t),"$t exists in isolated database.");
$now=date('Y-m-d H:i:s');$company=$db->table('company')->where('deleted',0)->get(1)->getRow();$client=$db->table('clients')->where('deleted',0)->get(1)->getRow();$user=$db->table('users')->where('deleted',0)->get(1)->getRow();$regime=$db->table('sat_tax_regimes')->where('is_active',1)->get(1)->getRow();$use=$db->table('sat_cfdi_uses')->where('is_active',1)->get(1)->getRow();
$profileBase=['tax_regime_id'=>$regime->id,'fiscal_postal_code'=>'06000','fiscal_country_code'=>'MEX','fiscal_street'=>'Snapshot street','fiscal_neighborhood'=>'Centro','fiscal_municipality'=>'Cuauhtemoc','fiscal_state'=>'CDMX','status'=>'ready','is_default'=>1,'created_by'=>$user->id,'created_at'=>$now,'updated_at'=>$now];
$db->table('fiscal_profiles')->insert($profileBase+['profile_type'=>'issuer','company_id'=>$company->id,'client_id'=>null,'rfc'=>'AAA010101AAA','legal_name'=>'EMISOR SNAPSHOT','expedition_postal_code'=>'06000','tax_pricing_mode'=>'tax_exclusive','allow_sale_tax_pricing_override'=>0]);$issuerId=(int)$db->insertID();
$db->table('fiscal_profiles')->insert($profileBase+['profile_type'=>'receiver','company_id'=>null,'client_id'=>$client->id,'rfc'=>'XAXX010101000','legal_name'=>'RECEPTOR SNAPSHOT','default_cfdi_use_id'=>$use->id]);$receiverId=(int)$db->insertID();
$db->table('fiscal_series')->insert(['issuer_profile_id'=>$issuerId,'document_type'=>'ingreso','series'=>'T','initial_folio'=>1,'current_folio'=>0,'is_default'=>1,'is_active'=>1,'deleted'=>0,'created_by'=>$user->id,'created_at'=>$now,'updated_at'=>$now]);$seriesId=(int)$db->insertID();
$sourceItem=$db->table('items')->where('deleted',0)->get(1)->getRowArray();unset($sourceItem['id']);$sourceItem['title']='Increment 06 isolated product';$db->table('items')->insert($sourceItem);$itemId=(int)$db->insertID();
$productKey=$db->table('sat_product_service_keys')->where('is_active',1)->get(1)->getRow();$unitKey=$db->table('sat_unit_keys')->where('is_active',1)->get(1)->getRow();$object=$db->table('sat_tax_object_codes')->where('code','02')->get(1)->getRow();
$db->table('item_fiscal_settings')->insert(['item_id'=>$itemId,'item_type'=>'product','sat_product_service_key_id'=>$productKey->id,'sat_unit_key_id'=>$unitKey->id,'commercial_unit'=>'Pieza','tax_object_code_id'=>$object->id,'fiscal_description'=>'Snapshot product','is_default'=>1,'status'=>'ready','created_by'=>$user->id,'created_at'=>$now,'updated_at'=>$now,'deleted'=>0]);$settingId=(int)$db->insertID();
$satTax=$db->table('sat_tax_codes')->where('code','002')->get(1)->getRow();$factor=$db->table('sat_tax_factor_types')->where('code','Tasa')->get(1)->getRow();
$db->table('taxes')->insert(['title'=>'IVA 16 snapshot','percentage'=>'16','sat_tax_code_id'=>$satTax->id,'fiscal_tax_type'=>'transfer','factor_type_id'=>$factor->id,'xml_rate'=>'0.160000','xml_quota'=>null,'is_fiscal_ready'=>1,'use_for_administrative'=>1,'use_for_fiscal'=>1,'deleted'=>0]);$taxId=(int)$db->insertID();
$db->table('item_fiscal_taxes')->insert(['item_fiscal_setting_id'=>$settingId,'tax_id'=>$taxId,'sort_order'=>1,'is_active'=>1,'created_at'=>$now,'updated_at'=>$now]);
$sourceInvoice=$db->table('invoices')->where('deleted',0)->get(1)->getRowArray();unset($sourceInvoice['id']);$sourceInvoice=array_merge($sourceInvoice,['client_id'=>$client->id,'company_id'=>$company->id,'project_id'=>0,'status'=>'not_paid','tax_id'=>$taxId,'tax_id2'=>0,'tax_id3'=>0,'discount_amount'=>'0','discount_total'=>'0','invoice_subtotal'=>'100','invoice_total'=>'116','tax'=>'16','tax2'=>'0','tax3'=>'0','deleted'=>0,'created_by'=>$user->id]);$db->table('invoices')->insert($sourceInvoice);$invoiceId=(int)$db->insertID();
$sourceLine=$db->table('invoice_items')->where('deleted',0)->get(1)->getRowArray();unset($sourceLine['id']);foreach([[1,'Snapshot line A'],[2,'Snapshot line B']]as[$sort,$title]){$line=array_merge($sourceLine,['invoice_id'=>$invoiceId,'item_id'=>$itemId,'title'=>$title,'description'=>$title.' description','quantity'=>'1','unit_type'=>'Pieza','rate'=>'50','total'=>'50','sort'=>$sort,'taxable'=>1,'deleted'=>0]);$db->table('invoice_items')->insert($line);}
$simulation=(new App\Services\Fiscal\SaleTaxPricingSimulationService($db))->simulate($invoiceId,$issuerId,$receiverId,$seriesId,'tax_exclusive',(int)$user->id,true);
$fixedFiscalInstant=new DateTimeImmutable('2026-07-24T04:25:52+00:00');$fiscalDates=new App\Services\Fiscal\FiscalIssueDateService(static fn()=>$fixedFiscalInstant);
$service=new App\Services\Fiscal\FiscalDraftCreationService($db,$fiscalDates);$options=['payment_form_code'=>'99','payment_method_code'=>'PPD','currency_code'=>'MXN','exchange_rate'=>'','export_code'=>'01'];
$before=(int)$db->table('fiscal_series')->where('id',$seriesId)->get()->getRow()->current_folio;$created=$service->create($invoiceId,$issuerId,$receiverId,$seriesId,(int)$simulation['id'],$options,(int)$user->id,true);
$doc=$db->table('fiscal_documents')->where('id',$created['id'])->get()->getRow();$a($created['action']==='created'&&$doc->status==='ready','Ready sale creates a persistent fiscal draft.');$a((int)$doc->folio===$before+1,'Folio is consumed only with the complete draft.');$a($db->table('fiscal_document_issuers')->where('fiscal_document_id',$doc->id)->countAllResults()===1&&$db->table('fiscal_document_receivers')->where('fiscal_document_id',$doc->id)->countAllResults()===1,'Issuer and receiver snapshots are complete.');$a($db->table('fiscal_document_items')->where('fiscal_document_id',$doc->id)->countAllResults()===2,'Both sale items are frozen.');$a($db->table('fiscal_document_item_taxes it')->join('fiscal_document_items i','i.id=it.fiscal_document_item_id')->where('i.fiscal_document_id',$doc->id)->countAllResults()===2,'Item taxes are frozen.');$a((string)$doc->subtotal==='100.00'&&(string)$doc->transferred_tax_total==='16.00'&&(string)$doc->total==='116.00','Header totals reconcile exactly.');$a(strlen($doc->source_snapshot_hash)===64,'Deterministic SHA-256 snapshot hash is stored.');
$same=$service->create($invoiceId,$issuerId,$receiverId,$seriesId,(int)$simulation['id'],$options,(int)$user->id,true);$a($same['action']==='existing'&&(int)$same['id']===(int)$doc->id&&$db->table('fiscal_documents')->where('invoice_id',$invoiceId)->countAllResults()===1,'Identical creation is idempotent and consumes no second folio.');
$foreignOptions=['payment_form_code'=>'03','payment_method_code'=>'PUE','currency_code'=>'USD','exchange_rate'=>'17.250000','export_code'=>'01'];$foreign=$service->create($invoiceId,$issuerId,$receiverId,$seriesId,(int)$simulation['id'],$foreignOptions,(int)$user->id,true,true);$foreignDoc=$db->table('fiscal_documents')->where('id',$foreign['id'])->get()->getRow();$a($foreignDoc->currency_code==='USD'&&(string)$foreignDoc->exchange_rate==='17.250000'&&$foreignDoc->payment_method_code==='PUE','Foreign currency with explicit decimal exchange rate and PUE is accepted.');$a($db->table('fiscal_documents')->where('id',$doc->id)->get()->getRow()->status==='superseded','Confirmed changed preparation supersedes rather than edits the prior snapshot.');
$db->table('fiscal_profiles')->where('id',$receiverId)->update(['legal_name'=>'RECEPTOR MODIFICADO']);$db->table('items')->where('id',$itemId)->update(['title'=>'PRODUCTO MODIFICADO']);$snapshot=(new App\Models\Fiscal\Fiscal_documents_model())->complete((int)$doc->id);$a($snapshot['receiver']->legal_name==='RECEPTOR SNAPSHOT'&&$snapshot['items'][0]->description==='Snapshot line A description','Live receiver and product edits do not change snapshots.');
$locked=$service->changeStatus((int)$foreignDoc->id,'lock',(int)$user->id,true);$lockedRow=$db->table('fiscal_documents')->where('id',$foreignDoc->id)->get()->getRow();$a($locked['status']==='locked'&&$lockedRow->locked_at!==null,'Ready draft can be locked and becomes immutable by state.');
$a($lockedRow->issue_date==='2026-07-23 22:25:52'&&$locked['issue_date']==='2026-07-23 22:25:52','Closing freezes Comprobante.Fecha in America/Mexico_City instead of UTC.');
$lockedAgain=$service->changeStatus((int)$foreignDoc->id,'lock',(int)$user->id,true);$a($lockedAgain['action']==='existing'&&$lockedAgain['issue_date']==='2026-07-23 22:25:52','Repeated close preserves the frozen fiscal issue date.');
$beforeFailure=(int)$db->table('fiscal_series')->where('id',$seriesId)->get()->getRow()->current_folio;$countBefore=$db->table('fiscal_documents')->countAllResults();try{$service->create($invoiceId,$issuerId,$receiverId,$seriesId,(int)$simulation['id'],array_merge($options,['currency_code'=>'USD','exchange_rate'=>'0']),(int)$user->id,true,true);$blocked=false;}catch(Throwable$e){$blocked=true;}$a($blocked&&$db->table('fiscal_documents')->countAllResults()===$countBefore&&(int)$db->table('fiscal_series')->where('id',$seriesId)->get()->getRow()->current_folio===$beforeFailure,'Validation failure leaves no document and consumes no folio.');
try{$service->create($invoiceId,$issuerId,$receiverId,$seriesId,(int)$simulation['id'],$options,(int)$user->id,false);$denied=false;}catch(Throwable$e){$denied=true;}$a($denied,'Legacy role without explicit create permission is denied.');
$a($db->table('fiscal_document_audit')->where(['fiscal_document_id'=>$doc->id,'action'=>'created'])->countAllResults()===1&&$db->table('fiscal_document_audit')->where(['fiscal_document_id'=>$foreignDoc->id,'action'=>'locked'])->countAllResults()===1,'Creation and lock events are audited.');
$a(!$db->tableExists('cfdi_xml')&&!$db->fieldExists('uuid','fiscal_documents'),'No XML, UUID, seal, PAC, or stamped payload is stored.');
$admin=$db->table('users')->where(['deleted'=>0,'user_type'=>'staff','is_admin'=>1])->get(1)->getRow();
if($admin){
 session()->set('user_id',(int)$admin->id);
 $makeViewer=static function(){$request=Config\Services::incomingrequest(null,false);$request->setMethod('GET');$request->setGlobal('get',['ajaxModal'=>1]);$request->setGlobal('request',['ajaxModal'=>1]);$response=Config\Services::response(null,false);$response->setStatusCode(200);$controller=new App\Controllers\Fiscal\InvoiceReview();$controller->initController($request,$response,service('logger'));return[$controller,$response];};
 [$viewer,$viewerResponse]=$makeViewer();$viewerResult=$viewer->draft((int)$foreignDoc->id);$viewerHtml=$viewerResult instanceof CodeIgniter\HTTP\ResponseInterface?$viewerResult->getBody():(string)$viewerResult;
 $a($viewerResponse->getStatusCode()===200&&str_contains($viewerHtml,'Snapshot line A description'),'Authenticated GET viewer renders a locked snapshot with HTTP 200.');
 $a(str_contains($viewerHtml,'EMISOR SNAPSHOT')&&str_contains($viewerHtml,'RECEPTOR SNAPSHOT')&&str_contains($viewerHtml,'16.00'),'Viewer renders issuer, receiver, concepts, taxes, and totals from snapshots.');
 $a(!str_contains($viewerHtml,'default_lang.')&&!str_contains($viewerHtml,'Timbrar'),'Viewer contains resolved language and no stamping action.');
 [$missingViewer]=$makeViewer();$missingResult=$missingViewer->draft(999999999);$a($missingResult instanceof CodeIgniter\HTTP\ResponseInterface&&$missingResult->getStatusCode()===404&&str_contains($missingResult->getBody(),app_lang('fiscal_draft_not_found')),'Missing fiscal document returns controlled modal HTML with HTTP 404.');
 foreach(['draft','ready','locked','ready_to_stamp','stamped']as$state){$db->table('fiscal_documents')->where('id',$foreignDoc->id)->update(['status'=>$state]);[$stateViewer,$stateResponse]=$makeViewer();$stateResult=$stateViewer->draft((int)$foreignDoc->id);$stateHtml=$stateResult instanceof CodeIgniter\HTTP\ResponseInterface?$stateResult->getBody():(string)$stateResult;$a($stateResponse->getStatusCode()===200&&str_contains($stateHtml,'Snapshot line A description'),"GET viewer opens fiscal document state {$state}.");}
 [$wrongIdViewer]=$makeViewer();$wrongIdResult=$wrongIdViewer->draft((int)$invoiceId);$wrongIdIsSame=$wrongIdResult instanceof CodeIgniter\HTTP\ResponseInterface&&str_contains($wrongIdResult->getBody(),'Snapshot line A description');$a((int)$invoiceId!==(int)$foreignDoc->id&&!$wrongIdIsSame,'invoice_id is not interpreted as fiscal_document.id.');
 $nonAdmin=$db->table('users')->where(['deleted'=>0,'user_type'=>'staff','is_admin'=>0])->get(1)->getRow();if(!$nonAdmin){$row=(array)$admin;unset($row['id']);$row['first_name']='No fiscal permission';$row['email']='no-fiscal-'.bin2hex(random_bytes(4)).'@example.test';$row['is_admin']=0;$row['role_id']=0;$db->table('users')->insert($row);$nonAdmin=$db->table('users')->where('id',(int)$db->insertID())->get(1)->getRow();}session()->set('user_id',(int)$nonAdmin->id);[$deniedViewer]=$makeViewer();$deniedResult=$deniedViewer->draft((int)$foreignDoc->id);$a($deniedResult instanceof CodeIgniter\HTTP\ResponseInterface&&$deniedResult->getStatusCode()===403&&str_contains($deniedResult->getBody(),app_lang('fiscal_access_denied')),'User without fiscal draft permission receives controlled HTTP 403.');session()->set('user_id',(int)$admin->id);
}else{$a(false,'Isolated database provides an administrator for viewer HTTP characterization.');}
echo"\n$p passed, $f failed.\n";exit($f?1:0);
