<?php
declare(strict_types=1);
namespace App\Controllers;
use App\FiscalServices\PaymentComplementCancellationService;use App\Services\Fiscal\Cancellation\CancellationBusinessDayPolicy;use App\Services\Fiscal\Cancellation\FiscalCancellationReasonCatalog;use App\Services\Fiscal\Stamps\FiscalStampAccountService;use CodeIgniter\Exceptions\PageNotFoundException;use Throwable;
final class Payment_complement_cancellations extends Security_Controller
{
 public function form(){$this->guard('fiscal_invoices_cancel');$id=(int)$this->request->getPost('complement_id');$d=(new PaymentComplementCancellationService())->context($id);$c=$d['complement'];if($c->status!=='stamped'||!$c->uuid||$c->fiscal_document_status==='cancelled'||($c->cancellation_request_id&&!in_array($c->cancellation_status,['rejected','transport_not_sent'],true)))throw PageNotFoundException::forPageNotFound();$d['reasons']=(new FiscalCancellationReasonCatalog())->options();$d['balance']=(new FiscalStampAccountService())->getBalance((int)$c->issuer_profile_id,'development');return$this->template->view('payment_complements/cancel_form',$d);}
 public function request(int$id){$this->guard('fiscal_invoices_cancel');try{$r=(new PaymentComplementCancellationService())->request($id,(string)$this->request->getPost('cancellation_reason'),$this->request->getPost('replacement_uuid')?:null,(int)$this->login_user->id);return$this->response->setJSON($r+['csrf'=>['name'=>csrf_token(),'hash'=>csrf_hash()]]);}catch(Throwable$e){return$this->response->setStatusCode(422)->setJSON(['success'=>false,'message'=>$e->getMessage(),'csrf'=>['name'=>csrf_token(),'hash'=>csrf_hash()]]);}}
 public function statusForm(){$this->guard('fiscal_status_query');$id=(int)$this->request->getPost('complement_id');$d=(new PaymentComplementCancellationService())->context($id);$r=$d['complement'];if(!$r->cancellation_request_id)throw PageNotFoundException::forPageNotFound();$zone=new \DateTimeZone((string)(get_setting('timezone')?:'UTC'));$d['requested']=(new \DateTimeImmutable((string)$r->requested_at,new \DateTimeZone('UTC')))->setTimezone($zone);$d['recommended']=(new CancellationBusinessDayPolicy())->recommendedAt($d['requested']);$d['balance']=(new FiscalStampAccountService())->getBalance((int)$r->issuer_profile_id,'development');$d['query_key']=bin2hex(random_bytes(16));return$this->template->view('payment_complements/cancellation_status_form',$d);}
 public function check(int$id){$this->guard('fiscal_status_query');try{return$this->response->setJSON((new PaymentComplementCancellationService())->check($id,(int)$this->login_user->id,(string)$this->request->getPost('query_key')));}catch(Throwable$e){return$this->response->setStatusCode(422)->setJSON(['success'=>false,'message'=>$e->getMessage()]);}}
 public function receipt(int$id,int$requestId){$this->guard('fiscal_invoices_view_cancellation');$db=db_connect();$request=$db->table('fiscal_cancellation_requests r')->join('payment_complements c','c.fiscal_document_id=r.fiscal_document_id')->where(['r.id'=>$requestId,'c.id'=>$id,'c.deleted'=>0])->get(1)->getRow();$a=$request?$db->table('fiscal_cancellation_artifacts')->where(['fiscal_cancellation_request_id'=>$requestId,'artifact_type'=>'cancellation_ack'])->get(1)->getRow():null;if(!$a)throw PageNotFoundException::forPageNotFound();$bytes=base64_decode((string)$a->content_base64,true);if($bytes===false||!hash_equals((string)$a->decoded_sha256,hash('sha256',$bytes)))throw PageNotFoundException::forPageNotFound();return$this->response->setHeader('Content-Type','application/xml; charset=UTF-8')->setHeader('Content-Disposition','attachment; filename="acuse-cancelacion-complemento.xml"')->setHeader('Cache-Control','private, no-store')->setBody($bytes);}
 private function allowed(string$p):bool{if($this->login_user->is_admin)return true;$all=is_array($this->login_user->permissions)?$this->login_user->permissions:(@unserialize((string)$this->login_user->permissions)?:[]);return(bool)get_array_value($all,$p);}
 private function guard(string$p):void{if(!$this->allowed($p))app_redirect('forbidden');}
}
