<?php
namespace App\Controllers; use App\Models\Suppliers_model; use App\Services\SupplierCostHistoryService; use App\Services\SupplierService;
final class Suppliers extends Security_Controller{private Suppliers_model$model;function __construct(){parent::__construct();$this->access_only_team_members();$this->model=new Suppliers_model();}
 private function allowed(string$p):bool{$permissions=is_array($this->login_user->permissions)?$this->login_user->permissions:(@unserialize((string)$this->login_user->permissions)?:[]);if($p==='suppliers_view'&&get_array_value($permissions,'suppliers_manage'))return true;if($p==='supplier_costs_view'&&get_array_value($permissions,'supplier_costs_edit'))return true;return(bool)($this->login_user->is_admin||get_array_value($permissions,$p));}private function guard(string$p):void{if(!$this->allowed($p))app_redirect('forbidden');}
 function index(){$this->guard('suppliers_view');return$this->template->rander('suppliers/index',['can_manage'=>$this->allowed('suppliers_manage')]);}
 function list_data(){$this->guard('suppliers_view');$out=[];foreach($this->model->get_all_where(['deleted'=>0],1000000,0,'name')->getResult()as$s){$actions='<a class="btn btn-default btn-sm" href="'.get_uri('suppliers/view/'.$s->id).'" title="Ver"><i data-feather="eye" class="icon-16"></i></a>';if($this->allowed('suppliers_manage')){$actions.=' '.modal_anchor(get_uri('suppliers/modal_form'),'<i data-feather="edit" class="icon-16"></i>',['class'=>'btn btn-default btn-sm','title'=>'Editar proveedor','data-post-id'=>$s->id]);$actions.=' '.js_anchor('<i data-feather="'.($s->status==='active'?'pause-circle':'play-circle').'" class="icon-16"></i>',['class'=>'btn btn-default btn-sm supplier-toggle','title'=>$s->status==='active'?'Inactivar':'Activar','data-id'=>$s->id]);}$out[]=[esc($s->name),esc($s->rfc?:'-'),esc($s->contact_name?:'-'),esc($s->phone?:'-'),esc($s->email?:'-'),$s->status==='active'?'<span class="badge bg-success">Activo</span>':'<span class="badge bg-secondary">Inactivo</span>',$actions];}return$this->response->setJSON(['data'=>$out]);}
 function modal_form(){$this->guard('suppliers_manage');$id=(int)$this->request->getPost('id');return$this->template->view('suppliers/modal_form',['model_info'=>$this->model->get_one($id),'quick'=>(bool)$this->request->getPost('quick')]);}
 function save(){$this->guard('suppliers_manage');try{$result=(new SupplierService())->save($this->request->getPost(),(int)$this->login_user->id);return$this->response->setJSON($result);}catch(\InvalidArgumentException$e){return$this->response->setJSON(['success'=>false,'message'=>$e->getMessage()]);}catch(\Throwable$e){log_message('error','Supplier save failed: '.$e->getMessage());return$this->response->setJSON(['success'=>false,'message'=>'No fue posible guardar el proveedor. Intente nuevamente.']);}}
 function view(int$id){$this->guard('suppliers_view');$supplier=$this->model->get_one($id);if(!$supplier->id)show_404();$history=new SupplierCostHistoryService();$draftCount=db_connect()->table('proposal_items pi')->join('proposals p','p.id=pi.proposal_id')->where(['pi.supplier_id'=>$id,'pi.deleted'=>0,'p.deleted'=>0,'p.status'=>'draft'])->countAllResults();return$this->template->rander('suppliers/view',['supplier'=>$supplier,'products'=>$history->supplierProducts($id),'history'=>$history->supplierHistory($id),'draft_assignments_count'=>$draftCount,'can_view_costs'=>$this->allowed('supplier_costs_view'),'can_manage'=>$this->allowed('suppliers_manage')]);}
 function toggle_status(){$this->guard('suppliers_manage');$id=(int)$this->request->getPost('id');$row=$this->model->get_one($id);if(!$row->id)return$this->response->setStatusCode(404)->setJSON(['success'=>false]);$status=$row->status==='active'?'inactive':'active';$this->model->ci_save(['status'=>$status,'updated_at'=>get_current_utc_time()],$id);return$this->response->setJSON(['success'=>true,'message'=>'Estado actualizado.']);}
}
