<?php
namespace App\Controllers;
use App\Services\WarehouseTransferService;
final class Warehouse_transfers extends Security_Controller {
 private $db;
 function __construct(){parent::__construct();$this->access_only_team_members();$this->db=db_connect();}
 private function allowed(string $p):bool{$permissions=is_array($this->login_user->permissions)?$this->login_user->permissions:(@unserialize((string)$this->login_user->permissions)?:[]);return(bool)($this->login_user->is_admin||get_array_value($permissions,$p));}
 private function guard(string $p){if(!$this->allowed($p))app_redirect('forbidden');}
 private function error(\Throwable $e,int $code=422){return $this->response->setStatusCode($code)->setJSON(['success'=>false,'message'=>$e->getMessage()]);}
 private function t(string $n,string $a=''):string{return $this->db->prefixTable($n).($a?' '.$a:'');}
 function index(){$this->guard('warehouse_transfers_view');return $this->template->rander('warehouses/transfers',['mode'=>'all','can_create'=>$this->allowed('warehouse_transfers_create')]);}
 function in_transit(){$this->guard('warehouse_transfers_view');return $this->template->rander('warehouses/transfers',['mode'=>'transit','can_create'=>false]);}
 function receipts(){$this->guard('warehouse_transfers_view');return $this->template->rander('warehouses/transfers',['mode'=>'receipts','can_create'=>false]);}
 function list_data($mode='all'){$this->guard('warehouse_transfers_view');$b=$this->db->table($this->t('warehouse_transfers','t'))->select('t.*,o.name origin_name,d.name destination_name,COUNT(tl.id) product_count,COALESCE(SUM(tl.quantity_sent),0) sent_total')->join($this->t('warehouses','o'),'o.id=t.origin_warehouse_id')->join($this->t('warehouses','d'),'d.id=t.destination_warehouse_id')->join($this->t('warehouse_transfer_lines','tl'),'tl.warehouse_transfer_id=t.id','left')->where('t.deleted',0)->groupBy('t.id');if($mode==='transit')$b->whereIn('t.status',['in_transit','partially_received']);if($mode==='receipts')$b->whereIn('t.status',['in_transit','partially_received']);foreach(['origin_warehouse_id'=>'t.origin_warehouse_id','destination_warehouse_id'=>'t.destination_warehouse_id','status'=>'t.status'] as $q=>$f)if($v=$this->request->getPost($q))$b->where($f,$v);if($v=$this->request->getPost('tracking_number'))$b->like('t.tracking_number',$v);$out=[];foreach($b->orderBy('t.transfer_date','DESC')->get()->getResult() as $r){$actions='<a class="btn btn-default btn-sm" href="'.get_uri('warehouses/transfers/view/'.$r->id).'"><i data-feather="eye" class="icon-16"></i></a>';if(in_array($r->status,['in_transit','partially_received'],true)&&$this->allowed('warehouse_transfers_receive'))$actions.=' '.modal_anchor(get_uri('warehouses/transfers/'.$r->id.'/receive-form'),'<i data-feather="download" class="icon-16"></i>',['class'=>'btn btn-default btn-sm']);$out[]=[esc($r->folio),esc($r->origin_name),esc($r->destination_name),esc($r->transfer_date),(int)$r->product_count,esc($r->tracking_number?:'-'),$this->badge($r->status),$actions];}return $this->response->setJSON(['data'=>$out]);}
 function form(){$this->guard('warehouse_transfers_create');$warehouses=[''=>'-'];foreach($this->db->table('warehouses')->where(['status'=>'active','deleted'=>0])->orderBy('name')->get()->getResult() as $r)$warehouses[$r->id]=$r->code.' - '.$r->name;$products=[''=>'-'];foreach($this->db->table('warehouse_products')->where(['status'=>'active','deleted'=>0])->orderBy('name')->get()->getResult() as $r)$products[$r->id]=$r->internal_code.' - '.$r->name;return $this->template->view('warehouses/transfer_form',['warehouses'=>$warehouses,'products'=>$products]);}
 function save(){$this->guard('warehouse_transfers_create');try{$id=(new WarehouseTransferService($this->db))->createDraft((array)$this->request->getPost(),(int)$this->login_user->id);return $this->response->setJSON(['success'=>true,'message'=>'Traspaso guardado como borrador.','redirect'=>get_uri('warehouses/transfers/view/'.$id)]);}catch(\Throwable $e){return $this->error($e);}}
 function view($id){$this->guard('warehouse_transfers_view');$tr=$this->db->table($this->t('warehouse_transfers','t'))->select('t.*,o.name origin_name,o.code origin_code,d.name destination_name,d.code destination_code,CONCAT(u.first_name," ",u.last_name) creator_name')->join($this->t('warehouses','o'),'o.id=t.origin_warehouse_id')->join($this->t('warehouses','d'),'d.id=t.destination_warehouse_id')->join($this->t('users','u'),'u.id=t.created_by','left')->where('t.id',(int)$id)->get()->getRow();if(!$tr)show_404();$received=(new WarehouseTransferService($this->db))->receivedByLine((int)$id);$lines=$this->db->table($this->t('warehouse_transfer_lines','tl'))->select('tl.*,p.name product_name,p.internal_code,p.control_unit')->join($this->t('warehouse_products','p'),'p.id=tl.warehouse_product_id')->where('tl.warehouse_transfer_id',(int)$id)->get()->getResult();foreach($lines as $l){$l->quantity_received=$received[$l->id]??'0.000000';$l->quantity_pending=bcsub((string)$l->quantity_sent,$l->quantity_received,6);}$receipts=$this->db->table($this->t('warehouse_transfer_receipts','r'))->select('r.*,m.folio movement_folio,CONCAT(u.first_name," ",u.last_name) user_name')->join($this->t('warehouse_movements','m'),'m.id=r.warehouse_movement_id')->join($this->t('users','u'),'u.id=r.created_by','left')->where('r.warehouse_transfer_id',(int)$id)->orderBy('r.receipt_date','DESC')->get()->getResult();$events=$this->db->table($this->t('warehouse_transfer_events','e'))->select('e.*,CONCAT(u.first_name," ",u.last_name) user_name')->join($this->t('users','u'),'u.id=e.user_id','left')->where('e.warehouse_transfer_id',(int)$id)->orderBy('e.event_at','DESC')->get()->getResult();$differences=$this->db->table($this->t('warehouse_transfer_discrepancies','x'))->select('x.*,p.name product_name')->join($this->t('warehouse_products','p'),'p.id=x.warehouse_product_id')->where('x.warehouse_transfer_id',(int)$id)->get()->getResult();return $this->template->rander('warehouses/transfer_view',['transfer'=>$tr,'lines'=>$lines,'receipts'=>$receipts,'events'=>$events,'differences'=>$differences,'can_dispatch'=>$this->allowed('warehouse_transfers_dispatch'),'can_receive'=>$this->allowed('warehouse_transfers_receive'),'can_logistics'=>$this->allowed('warehouse_transfers_manage_logistics')]);}
 function dispatch($id){$this->guard('warehouse_transfers_dispatch');try{(new WarehouseTransferService($this->db))->dispatch((int)$id,(int)$this->login_user->id);return $this->response->setJSON(['success'=>true,'message'=>'Traspaso despachado. La mercancía está en tránsito.']);}catch(\Throwable $e){return $this->error($e);}}
 function receive_form($id){$this->guard('warehouse_transfers_receive');$tr=$this->db->table('warehouse_transfers')->where('id',(int)$id)->get()->getRow();if(!$tr||!in_array($tr->status,['in_transit','partially_received'],true))show_404();$received=(new WarehouseTransferService($this->db))->receivedByLine((int)$id);$lines=$this->db->table($this->t('warehouse_transfer_lines','tl'))->select('tl.*,p.name product_name,p.internal_code')->join($this->t('warehouse_products','p'),'p.id=tl.warehouse_product_id')->where('tl.warehouse_transfer_id',(int)$id)->get()->getResult();foreach($lines as $l){$l->received=$received[$l->id]??'0.000000';$l->pending=bcsub((string)$l->quantity_sent,$l->received,6);}return $this->template->view('warehouses/transfer_receive_form',['transfer'=>$tr,'lines'=>$lines]);}
 function receive($id){$this->guard('warehouse_transfers_receive');try{$receipt=(new WarehouseTransferService($this->db))->receive((int)$id,(array)$this->request->getPost('quantities'),(string)$this->request->getPost('notes'),(int)$this->login_user->id);return $this->response->setJSON(['success'=>true,'receipt_id'=>$receipt,'message'=>'Recepción registrada correctamente.']);}catch(\Throwable $e){return $this->error($e);}}
 function close_difference($id){$this->guard('warehouse_transfers_receive');try{(new WarehouseTransferService($this->db))->closeWithDifference((int)$id,(string)$this->request->getPost('reason'),(int)$this->login_user->id);return $this->response->setJSON(['success'=>true,'message'=>'Traspaso cerrado con diferencia e incidencia trazable.']);}catch(\Throwable $e){return $this->error($e);}}
 function cancel($id){$this->guard('warehouse_transfers_create');try{(new WarehouseTransferService($this->db))->cancelDraft((int)$id,(int)$this->login_user->id);return $this->response->setJSON(['success'=>true,'message'=>'Borrador de traspaso cancelado.']);}catch(\Throwable $e){return $this->error($e);}}
 function logistics($id){$this->guard('warehouse_transfers_manage_logistics');try{(new WarehouseTransferService($this->db))->updateLogistics((int)$id,(array)$this->request->getPost(),(int)$this->login_user->id);return $this->response->setJSON(['success'=>true,'message'=>'Datos logísticos actualizados.']);}catch(\Throwable $e){return $this->error($e);}}
 private function badge($s){$map=['draft'=>'Borrador','prepared'=>'Preparado','in_transit'=>'En tránsito','partially_received'=>'Recepción parcial','received'=>'Recibido','received_with_difference'=>'Recibido con diferencia','cancelled'=>'Cancelado'];return '<span class="badge bg-'.(in_array($s,['received'],true)?'success':(in_array($s,['cancelled','received_with_difference'],true)?'secondary':'warning')).'">'.esc($map[$s]??$s).'</span>';}
}
