<?php
namespace App\Controllers;
use App\Services\WarehouseLabelService;
final class Warehouse_labels extends Security_Controller{
 private $db;function __construct(){parent::__construct();$this->access_only_team_members();$this->db=db_connect();}private function allowed($p){$x=is_array($this->login_user->permissions)?$this->login_user->permissions:(@unserialize((string)$this->login_user->permissions)?:[]);return$this->login_user->is_admin||get_array_value($x,$p);}private function guard($p){if(!$this->allowed($p))app_redirect('forbidden');}private function error(\Throwable$e,$code=422){return$this->response->setStatusCode($code)->setJSON(['success'=>false,'message'=>$e->getMessage()]);}
 function form($id){$this->guard('warehouse_products_view');try{$p=(new WarehouseLabelService($this->db))->product((int)$id);return$this->template->view('warehouses/label_form',['product'=>$p]);}catch(\Throwable$e){return$this->error($e,404);}}
 function preview($id){$this->guard('warehouse_products_view');try{$html=(new WarehouseLabelService($this->db))->renderPreview((int)$id,(array)$this->request->getPost());return$this->response->setJSON(['success'=>true,'html'=>$html]);}catch(\Throwable$e){return$this->error($e);}}
 function pdf($id){$this->guard('warehouse_products_view');try{$svc=new WarehouseLabelService($this->db);$p=$svc->product((int)$id);$bytes=$svc->pdf((int)$id,(array)$this->request->getPost());if(!str_starts_with($bytes,'%PDF-'))throw new \RuntimeException('El generador no produjo un PDF válido.');$name='Etiquetas_'.preg_replace('/[^A-Za-z0-9_-]+/','_',trim((string)$p->internal_code)).'.pdf';while(ob_get_level()>0){ob_end_clean();}return$this->response->setStatusCode(200)->setHeader('Content-Type','application/pdf')->setHeader('Content-Disposition','inline; filename="'.$name.'"')->setHeader('Content-Length',(string)strlen($bytes))->setHeader('Cache-Control','private, no-store')->setHeader('X-Content-Type-Options','nosniff')->setBody($bytes);}catch(\Throwable$e){log_message('error','No fue posible generar PDF de etiquetas: '.$e->getMessage());return$this->error(new \RuntimeException('No fue posible generar el PDF de etiquetas.'));}}
 function upload_logo($id){$this->guard('warehouse_products_manage');try{$svc=new WarehouseLabelService($this->db);$p=$svc->product((int)$id);$file=$this->request->getFile('label_logo');if(!$file||!$file->isValid()||$file->hasMoved())throw new \InvalidArgumentException('Seleccione un archivo de imagen válido.');if($file->getSize()<=0||$file->getSize()>WarehouseLabelService::MAX_LOGO_BYTES)throw new \InvalidArgumentException('El logo debe pesar como máximo 2 MB.');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($file->getTempName());$extensions=['image/png'=>'png','image/jpeg'=>'jpg'];if(!isset($extensions[$mime])||@getimagesize($file->getTempName())===false)throw new \InvalidArgumentException('El logo debe ser PNG o JPG/JPEG válido.');$dir=$svc->logoDirectory();if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new \RuntimeException('No fue posible preparar el directorio de logos.');$name='product_'.$p->id.'_'.bin2hex(random_bytes(8)).'.'.$extensions[$mime];$file->move($dir,$name);$old=$p->label_logo??null;$this->db->table('warehouse_products')->where('id',(int)$id)->update(['label_logo'=>$name,'updated_at'=>get_current_utc_time()]);$this->deleteOwned($svc,$old,(int)$id);return$this->response->setJSON(['success'=>true,'message'=>'Logo para etiquetas actualizado.']);}catch(\Throwable$e){return$this->error($e);}}
 function remove_logo($id){$this->guard('warehouse_products_manage');try{$svc=new WarehouseLabelService($this->db);$p=$svc->product((int)$id);$this->db->table('warehouse_products')->where('id',(int)$id)->update(['label_logo'=>null,'updated_at'=>get_current_utc_time()]);$this->deleteOwned($svc,$p->label_logo??null,(int)$id);return$this->response->setJSON(['success'=>true,'message'=>'Logo para etiquetas eliminado.']);}catch(\Throwable$e){return$this->error($e);}}
 function logo($id){$this->guard('warehouse_products_view');try{$svc=new WarehouseLabelService($this->db);$p=$svc->product((int)$id);$path=$svc->logoPath($p);if(!$path)show_404();$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($path);return$this->response->setHeader('Content-Type',$mime)->setHeader('Cache-Control','private, max-age=3600')->setBody((string)file_get_contents($path));}catch(\Throwable$e){show_404();}}
 private function deleteOwned(WarehouseLabelService$svc,mixed$name,int$id):void{if(!$name)return;$base=basename((string)$name);if(!str_starts_with($base,'product_'.$id.'_'))return;$path=$svc->logoDirectory().$base;if(is_file($path))@unlink($path);}
}
