<?php
namespace App\Controllers;
use App\Services\WarehouseMovementService;use App\Services\WarehouseStockService;
final class Warehouse_logistics extends Security_Controller{
 private $db;function __construct(){parent::__construct();$this->access_only_team_members();$this->db=db_connect();}private function t($n,$a=''){return$this->db->prefixTable($n).($a?' '.$a:'');}private function allowed($p){$x=is_array($this->login_user->permissions)?$this->login_user->permissions:(@unserialize((string)$this->login_user->permissions)?:[]);return$this->login_user->is_admin||get_array_value($x,$p);}private function guard($p){if(!$this->allowed($p))app_redirect('forbidden');}private function error($e){return$this->response->setStatusCode(422)->setJSON(['success'=>false,'message'=>$e->getMessage()]);}
 function index(){$this->guard('warehouse_view');$stock=new WarehouseStockService($this->db);$recent=function($type){return$this->db->table($this->t('warehouse_movements','m'))->select('m.*,w.name warehouse_name')->join($this->t('warehouses','w'),'w.id=m.warehouse_id')->where(['m.movement_type'=>$type,'m.status'=>'confirmed'])->orderBy('m.confirmed_at','DESC')->get(5)->getResult();};return$this->template->rander('warehouses/dashboard',['active_products'=>$this->db->table('warehouse_products')->where(['status'=>'active','deleted'=>0])->countAllResults(),'active_warehouses'=>$this->db->table('warehouses')->where(['status'=>'active','deleted'=>0])->countAllResults(),'total_stock'=>$stock->totalAll(),'recent_entries'=>$recent('ENTRY'),'recent_exits'=>$recent('EXIT'),'recent_adjustments'=>$recent('ADJUSTMENT')]);}
 function entries(){return$this->page('ENTRY');}function exits(){return$this->page('EXIT');}function adjustments(){return$this->page('ADJUSTMENT');}private function page($type){$this->guard('warehouse_movements_view');return$this->template->rander('warehouses/movements',['type'=>$type,'can_create'=>$this->allowed($type==='ADJUSTMENT'?'warehouse_adjustments':'warehouse_movements_create')]);}
 function list_data($type){$this->guard('warehouse_movements_view');$out=[];foreach($this->db->table($this->t('warehouse_movements','m'))->select('m.*,w.name warehouse_name,CONCAT(u.first_name," ",u.last_name) user_name')->join($this->t('warehouses','w'),'w.id=m.warehouse_id')->join($this->t('users','u'),'u.id=m.confirmed_by','left')->where('m.movement_type',strtoupper($type))->orderBy('m.movement_date','DESC')->get()->getResult()as$r){$a='<a class="btn btn-default btn-sm" href="'.get_uri('warehouses/movements/view/'.$r->id).'"><i data-feather="eye" class="icon-16"></i></a>';$out[]=[esc($r->folio),esc($r->movement_date),esc($r->warehouse_name),esc($r->reference_text?:'-'),esc($r->status),esc(trim($r->user_name)?:'-'),$a];}return$this->response->setJSON(['data'=>$out]);}
 function form($type){$type=strtoupper($type);$this->guard($type==='ADJUSTMENT'?'warehouse_adjustments':'warehouse_movements_create');if(!in_array($type,['ENTRY','EXIT','ADJUSTMENT'],true))show_404();$warehouses=[''=>'-'];foreach($this->db->table('warehouses')->where(['status'=>'active','deleted'=>0])->orderBy('name')->get()->getResult()as$r)$warehouses[$r->id]=$r->code.' - '.$r->name;$products=[''=>'-'];foreach($this->db->table('warehouse_products')->where(['status'=>'active','deleted'=>0])->orderBy('name')->get()->getResult()as$r)$products[$r->id]=$r->internal_code.' - '.$r->name;return$this->template->view('warehouses/movement_form',['type'=>$type,'warehouses'=>$warehouses,'products'=>$products]);}
 function save(){$type=strtoupper((string)$this->request->getPost('movement_type'));$this->guard($type==='ADJUSTMENT'?'warehouse_adjustments':'warehouse_movements_create');try{$id=(new WarehouseMovementService($this->db))->createDraft((array)$this->request->getPost(),(int)$this->login_user->id);return$this->response->setJSON(['success'=>true,'id'=>$id,'message'=>'Movimiento guardado como borrador.','redirect'=>get_uri('warehouses/movements/view/'.$id)]);}catch(\Throwable$e){return$this->error($e);}}
 function confirm($id){$this->guard('warehouse_movements_create');try{(new WarehouseMovementService($this->db))->confirm((int)$id,(int)$this->login_user->id);return$this->response->setJSON(['success'=>true,'message'=>'Movimiento confirmado.']);}catch(\Throwable$e){return$this->error($e);}}
 function cancel($id){$this->guard('warehouse_movements_create');try{(new WarehouseMovementService($this->db))->cancel((int)$id,(string)$this->request->getPost('reason'),(int)$this->login_user->id);return$this->response->setJSON(['success'=>true,'message'=>'Movimiento cancelado.']);}catch(\Throwable$e){return$this->error($e);}}
 function view($id){$this->guard('warehouse_movements_view');$m=$this->db->table($this->t('warehouse_movements','m'))->select('m.*,w.name warehouse_name,CONCAT(c.first_name," ",c.last_name) creator_name,CONCAT(f.first_name," ",f.last_name) confirmer_name')->join($this->t('warehouses','w'),'w.id=m.warehouse_id')->join($this->t('users','c'),'c.id=m.created_by','left')->join($this->t('users','f'),'f.id=m.confirmed_by','left')->where('m.id',(int)$id)->get()->getRow();if(!$m)show_404();$lines=$this->db->table($this->t('warehouse_movement_lines','l'))->select('l.*,p.name product_name,p.internal_code,p.control_unit')->join($this->t('warehouse_products','p'),'p.id=l.warehouse_product_id')->where('l.warehouse_movement_id',(int)$id)->get()->getResult();return$this->template->rander('warehouses/movement_view',['movement'=>$m,'lines'=>$lines,'can_confirm'=>$this->allowed($m->movement_type==='ADJUSTMENT'?'warehouse_adjustments':'warehouse_movements_create')]);}
 function history(){$this->guard('warehouse_movements_view');$b=$this->db->table($this->t('warehouse_movement_lines','l'))->select('m.*,l.quantity_delta,p.name product_name,p.internal_code,w.name warehouse_name,CONCAT(u.first_name," ",u.last_name) user_name')->join($this->t('warehouse_movements','m'),'m.id=l.warehouse_movement_id')->join($this->t('warehouse_products','p'),'p.id=l.warehouse_product_id')->join($this->t('warehouses','w'),'w.id=m.warehouse_id')->join($this->t('users','u'),'u.id=m.confirmed_by','left')->where('m.status','confirmed');foreach(['warehouse_id'=>'m.warehouse_id','product_id'=>'l.warehouse_product_id','movement_type'=>'m.movement_type']as$q=>$field)if($v=$this->request->getGet($q))$b->where($field,$v);if($v=$this->request->getGet('folio'))$b->like('m.folio',$v);if($v=$this->request->getGet('reference'))$b->like('m.reference_text',$v);return$this->template->rander('warehouses/history',['rows'=>$b->orderBy('m.movement_date','DESC')->get(1000)->getResult(),'warehouses'=>$this->db->table('warehouses')->where('deleted',0)->get()->getResult(),'products'=>$this->db->table('warehouse_products')->where('deleted',0)->get()->getResult()]);}
}
