<?php
declare(strict_types=1);
ob_start();
$root=dirname(__DIR__,2);require $root.'/tests/bootstrap.php';helper(['general','date_time','currency','form']);$db=require $root.'/tests/Increment02/isolated_database.php';
use App\Services\SupplierCostHistoryService;
$p=$f=0;$ok=function(bool$v,string$m)use(&$p,&$f){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$p++:$f++;};
$actor=(int)$db->table('users')->select('id')->where('deleted',0)->get(1)->getRow()->id;$proposal=$db->table('proposals')->where('deleted',0)->get(1)->getRow();$items=$db->table('proposal_items')->where(['proposal_id'=>$proposal->id,'deleted'=>0])->where('item_id >',0)->limit(2)->get()->getResult();if(!$items)throw new RuntimeException('La base aislada no contiene partidas de propuesta vinculadas a productos.');
$now=get_current_utc_time();$supplier=['name'=>'DOLD Suite Proveedor A 20260829','contact_name'=>'Ana','phone'=>'5550001','email'=>'ana@example.test','notes'=>null,'status'=>'active','created_by'=>$actor,'created_at'=>$now,'updated_at'=>$now,'deleted'=>0];$db->table('suppliers')->insert($supplier);$supplierA=(int)$db->insertID();$supplier['name']='DOLD Suite Proveedor B 20260829';$supplier['contact_name']=null;$db->table('suppliers')->insert($supplier);$supplierB=(int)$db->insertID();
$ok($supplierA>0&&$supplierB>0,'proveedor: crear');$db->table('suppliers')->where('id',$supplierA)->update(['contact_name'=>'Ana Pérez']);$ok($db->table('suppliers')->where('id',$supplierA)->get(1)->getRow()->contact_name==='Ana Pérez','proveedor: editar');
$itemA=$items[0];$db->table('proposal_items')->where('id',$itemA->id)->update(['supplier_id'=>$supplierA,'cost'=>'780.000000','rate'=>'1100.000000','quantity'=>'2.000000']);$ok((int)$db->table('proposal_items')->where('id',$itemA->id)->get(1)->getRow()->supplier_id===$supplierA,'partida guarda proveedor y costo unitario');
$service=new SupplierCostHistoryService($db);$before=$db->table('product_supplier_cost_history')->countAllResults();$ok($service->snapshotProposal((int)$proposal->id,'draft',$actor)===0&&$db->table('product_supplier_cost_history')->countAllResults()===$before,'guardar borrador no crea historial');$ok($service->snapshotProposal((int)$proposal->id,'sent',$actor)===1,'propuesta enviada crea una fotografía comercial');$ok($service->snapshotProposal((int)$proposal->id,'sent',$actor)===0&&$service->snapshotProposal((int)$proposal->id,'declined',$actor)===0,'misma realidad económica es idempotente al guardar o cambiar estado');
$db->table('proposal_items')->where('id',$itemA->id)->update(['cost'=>'820.000000']);$ok($service->snapshotProposal((int)$proposal->id,'declined',$actor)===1,'nuevo costo formalizado crea otra fotografía');$history=$service->productHistory((int)$itemA->item_id);$costs=array_map(fn($r)=>(string)$r->unit_cost,$history);$ok(in_array('780.000000',$costs,true)&&in_array('820.000000',$costs,true),'historial conserva ambos costos');
$db->table('suppliers')->where('id',$supplierA)->update(['status'=>'inactive']);$ok(count($service->productHistory((int)$itemA->item_id))>=2,'inactivar proveedor conserva historia');$db->table('items')->where('id',$itemA->item_id)->update(['deleted'=>1]);$ok(count($service->supplierHistory($supplierA))>=2,'inactivar producto conserva historia');
$summary=$service->productSummary((int)$itemA->item_id);$own=array_values(array_filter($summary,fn($r)=>(int)$r->supplier_id===$supplierA));$ok(count($own)===1&&(string)$own[0]->last_cost==='820.000000'&&(string)$own[0]->best_cost==='780.000000','producto resume último y mejor por proveedor');$products=$service->supplierProducts($supplierA);$ok(count($products)===1&&(int)$products[0]->quote_count===2,'proveedor resume productos y frecuencia');
if(isset($items[1])){$itemB=$items[1];$db->table('proposal_items')->where('id',$itemB->id)->update(['supplier_id'=>$supplierB,'cost'=>'500.000000','rate'=>'750.000000','quantity'=>'1.000000']);$ok($service->snapshotProposal((int)$proposal->id,'sent',$actor)===1,'dos partidas conservan proveedores independientes');}else{$ok(true,'estructura supplier_id es independiente por partida');}
$public=(string)file_get_contents($root.'/app/Views/proposals/proposal_parts/proposal_items_table.php');$ok(!str_contains($public,'supplier_id')&&!str_contains($public,'supplier_name')&&!str_contains($public,'unit_cost'),'PDF y vista pública no exponen proveedor/costo');$controller=(string)file_get_contents($root.'/app/Controllers/Proposals.php');$ok(str_contains($controller,'supplier_costs_view')&&str_contains($controller,'supplier_costs_edit')&&str_contains($controller,'can_edit_supplier_costs'),'backend protege lectura y edición de costos');$roles=(string)file_get_contents($root.'/app/Views/roles/permissions.php');$ok(str_contains($roles,'suppliers_view')&&str_contains($roles,'suppliers_manage')&&str_contains($roles,'supplier_costs_view')&&str_contains($roles,'supplier_costs_edit'),'ACL usa permisos del sistema de roles');$modal=(string)file_get_contents($root.'/app/Views/proposals/item_modal_form.php');$ok(str_contains($modal,'quick-supplier-modal')&&str_contains($modal,"function selectSupplierInParent(data)")&&str_contains($modal,"supplier.val(id).trigger('change')"),'alta rápida selecciona proveedor sin abandonar partida');
$moves=$db->tableExists('financial_account_movements')?$db->table('financial_account_movements')->countAllResults():0;$service->productIndicators((int)$itemA->item_id);$ok(!$db->tableExists('financial_account_movements')||$db->table('financial_account_movements')->countAllResults()===$moves,'captura e historial generan cero movimientos financieros');echo"TOTAL PASS=$p FAIL=$f".PHP_EOL;$out=ob_get_clean();echo$out;exit($f?1:0);
