<?php
declare(strict_types=1);namespace App\Services\Fiscal\Pdf;
use App\Contracts\Fiscal\Pdf\PacPdfGenerationAdapterInterface;use App\Domain\Fiscal\Pdf\FiscalPacPdfGenerationResult;use App\Domain\Fiscal\Pdf\PacPdfGenerationRequest;use App\Services\Fiscal\FiscalArtifactStorageService;use App\Services\Fiscal\Pac\PacPdfArtifactService;use Config\FiscalPdfProvider;use DOMDocument;use DOMElement;use DOMXPath;use RuntimeException;use Throwable;
final class FiscalPacPdfGenerationService{
 private $db;public function __construct($db=null,private readonly ?PacPdfGenerationAdapterInterface$adapter=null,private readonly ?FiscalPdfProvider$config=null,private readonly ?string$artifactRoot=null,private readonly ?FiscalIssuerBrandingService$branding=null){$this->db=$db?:db_connect();}
 public function generate(int$documentId,int$userId,?string$templateOverride=null,bool$regenerate=false):FiscalPacPdfGenerationResult{
  $lock='ikontrol:fiscal:pdf:'.$documentId;if((int)$this->db->query('SELECT GET_LOCK(?,0) acquired',[$lock])->getRow()->acquired!==1)throw new RuntimeException('FISCAL_PDF_CONCURRENT_REQUEST');
  try{return$this->generateLocked($documentId,$userId,$templateOverride,$regenerate);}finally{$this->db->query('SELECT RELEASE_LOCK(?)',[$lock]);}
 }
 private function generateLocked(int$id,int$userId,?string$templateOverride,bool$regenerate):FiscalPacPdfGenerationResult{
  $c=$this->config??config('FiscalPdfProvider');
  $doc=$this->db->table('fiscal_documents')->where(['id'=>$id,'deleted'=>0])->get(1)->getRow();$stamp=$this->db->table('fiscal_document_stamps')->where('fiscal_document_id',$id)->get(1)->getRow();$issuer=$this->db->table('fiscal_document_issuers')->where('fiscal_document_id',$id)->get(1)->getRow();$receiver=$this->db->table('fiscal_document_receivers')->where('fiscal_document_id',$id)->get(1)->getRow();
  if(!$doc)throw new RuntimeException('FISCAL_PDF_DOCUMENT_NOT_FOUND');
  if(!$stamp||!$stamp->stamped_xml_artifact_id)throw new RuntimeException('FISCAL_PDF_STAMPED_XML_MISSING');
  if(!$issuer||!$receiver)throw new RuntimeException('FISCAL_PDF_DOCUMENT_DATA_MISSING');
  $type=match(strtolower((string)$doc->document_type)){'income','i'=>'I','expense','e'=>'E','payment','p'=>'P','transfer','t'=>'T','payroll','n'=>'N',default=>strtoupper(substr((string)$doc->document_type,0,1))};
  $provider=$c->provider;$selection=(new FiscalPdfTemplateResolver($this->db,$c))->resolve((int)$doc->issuer_profile_id,$provider,$type);$template=$templateOverride??$selection->templateCode;if(!(new FiscalPdfTemplateResolver($this->db,$c))->valid($template))throw new RuntimeException('FISCAL_PDF_TEMPLATE_INVALID');
  if($stamp->pac_pdf_artifact_id&&!$regenerate){try{$existing=(new PacPdfArtifactService($this->db))->read($id);$existingTemplate=(string)($existing['artifact']->template_code??$existing['artifact']->template??'');if($existingTemplate===$template)return FiscalPacPdfGenerationResult::fromArray(['success'=>true,'status'=>'existing','pdf_artifact_id'=>(int)$existing['artifact']->id,'pdf_available'=>true,'attempt_id'=>(int)($existing['artifact']->pdf_generation_attempt_id??0),'template_code'=>$template]);}catch(Throwable){}}
  if($provider!=='fake'&&strtolower((string)$stamp->provider)==='fake')throw new RuntimeException('FISCAL_PDF_FAKE_DOCUMENT_EXTERNAL_BLOCKED');
  $xmlArtifact=$this->db->table('fiscal_document_artifacts')->where(['id'=>(int)$stamp->stamped_xml_artifact_id,'fiscal_document_id'=>$id,'artifact_type'=>'stamped_xml','superseded_at'=>null])->get(1)->getRow();if(!$xmlArtifact)throw new RuntimeException('FISCAL_PDF_STAMPED_XML_MISSING');$xml=(new FiscalArtifactStorageService($this->db,$this->artifactRoot))->read($xmlArtifact);$xmlUuid=$this->uuidFromStampedXml($xml);
  $metadata=(new FiscalPdfPrintMetadataBuilder())->build($xml,$doc,$issuer,$receiver);$logo=($this->branding??new FiscalIssuerBrandingService())->logoBase64((int)$doc->issuer_profile_id);$adapter=$this->adapter??(new FiscalPdfGenerationAdapterFactory(config('Fiscal'),$c))->create();$key=hash('sha256',implode('|',[$id,$xmlUuid,$provider,$template,$regenerate?(int)($stamp->pac_pdf_artifact_id??0):'generate']));
  $existingAttempt=$this->db->table('fiscal_pdf_generation_attempts')->where('idempotency_key',$key)->get(1)->getRow();
  $retrySourceAttempt=$existingAttempt&&in_array((string)$existingAttempt->status,['transport_not_sent','provider_rejected'],true)?$existingAttempt:null;
  if($existingAttempt&&!$retrySourceAttempt)return FiscalPacPdfGenerationResult::fromArray(['success'=>$existingAttempt->status==='success','status'=>(string)$existingAttempt->status,'attempt_id'=>(int)$existingAttempt->id,'pdf_available'=>$existingAttempt->status==='success','template_code'=>$template,'requires_reconciliation'=>(bool)$existingAttempt->requires_reconciliation]);
  $hadActivePdf=(int)($stamp->pac_pdf_artifact_id??0)>0;$previousPdfStatus=(string)($stamp->pdf_status??'pending');$previousPdfTemplate=$stamp->pdf_template??null;$previousDocumentStatus=(string)$doc->status;
  $now=get_current_utc_time();$this->db->transBegin();try{$this->db->query('SELECT id FROM '.$this->db->prefixTable('fiscal_documents').' WHERE id=? FOR UPDATE',[$id]);if($retrySourceAttempt){$archivedKey=hash('sha256',$key.'|closed|'.$retrySourceAttempt->id.'|'.$retrySourceAttempt->completed_at);$this->db->table('fiscal_pdf_generation_attempts')->where('id',(int)$retrySourceAttempt->id)->update(['idempotency_key'=>$archivedKey,'updated_at'=>$now]);$existingAttempt=null;}$this->db->table('fiscal_pdf_generation_attempts')->insert(['document_id'=>$id,'stamp_id'=>$stamp->id,'stamp_attempt_id'=>$stamp->stamp_attempt_id,'uuid'=>$xmlUuid,'provider'=>$provider,'environment'=>config('Fiscal')->environment,'template_code'=>$template,'status'=>'pending','request_sent'=>0,'retryable'=>0,'requires_reconciliation'=>0,'idempotency_key'=>$key,'started_at'=>$now,'created_by'=>$userId,'created_at'=>$now,'updated_at'=>$now]);$attemptId=(int)$this->db->insertID();if(!$hadActivePdf&&$previousDocumentStatus!=='cancelled'){$this->db->table('fiscal_document_stamps')->where('id',$stamp->id)->update(['pdf_status'=>'processing','pdf_template'=>$template]);$this->db->table('fiscal_documents')->where('id',$id)->update(['status'=>'stamped_pdf_processing','updated_at'=>$now]);}$this->db->transCommit();}catch(Throwable$e){$this->db->transRollback();throw$e;}
  $correlationId=hash('sha256',$attemptId.'|'.$id.'|'.microtime(true));
  $this->stage('PDF_STAGE_1_ATTEMPT_CREATED',$attemptId,$id,$provider,$template,$correlationId);
  $this->db->table('fiscal_pdf_generation_attempts')->where('id',$attemptId)->update(['status'=>'sending','updated_at'=>get_current_utc_time()]);
  $this->stage('PDF_STAGE_2_BEFORE_ADAPTER',$attemptId,$id,$provider,$template,$correlationId);
  try{
   $result=$adapter->generate(new PacPdfGenerationRequest($id,(int)$stamp->id,(int)$stamp->stamp_attempt_id,$xmlUuid,$xml,$template,$metadata,$logo,$attemptId,$correlationId));
  }catch(Throwable$e){
   $message=$this->sanitizeException($e);
   $done=get_current_utc_time();
   $this->db->transBegin();
   try{
    $this->db->table('fiscal_pdf_generation_attempts')->where('id',$attemptId)->update(['status'=>'transport_not_sent','provider_code'=>null,'provider_message'=>$message,'request_sent'=>0,'retryable'=>1,'requires_reconciliation'=>0,'completed_at'=>$done,'updated_at'=>$done]);
    if(!$hadActivePdf&&$previousDocumentStatus!=='cancelled'){$this->db->table('fiscal_document_stamps')->where('id',$stamp->id)->update(['pdf_status'=>'pending','pdf_template'=>$template]);$this->db->table('fiscal_documents')->where('id',$id)->update(['status'=>'stamped_pdf_pending','updated_at'=>$done]);}
    $this->db->transCommit();
   }catch(Throwable$finalizeError){$this->db->transRollback();throw$finalizeError;}
   return FiscalPacPdfGenerationResult::fromArray(['success'=>false,'status'=>'transport_not_sent','attempt_id'=>$attemptId,'pdf_available'=>$hadActivePdf,'template_code'=>$template,'requires_reconciliation'=>false,'provider_message'=>$message]);
  }
  $status=$result->success?'success':$result->status;$documentStatus=match($status){'success'=>'stamped','unknown'=>'stamped_pdf_unknown','sending','pending'=>'stamped_pdf_processing',default=>'stamped_pdf_error'};if($previousDocumentStatus==='cancelled')$documentStatus='cancelled';$pdfStatus=match($status){'success'=>'valid','unknown'=>'unknown','sending','pending'=>'processing',default=>'error'};$artifact=null;
  if($status==='rejected')$status='provider_rejected';
  if($result->success){if($result->providerCode!=='210'||!$result->pdfBase64){$status='provider_rejected';$documentStatus='stamped_pdf_error';$pdfStatus='error';}else{try{$artifact=(new PacPdfArtifactService($this->db))->store($id,(int)$stamp->stamp_attempt_id,$xmlUuid,$result->pdfBase64,$template,$userId,$result->provider,$attemptId,true,true);$this->stage('PDF_STAGE_8_ARTIFACT_PERSISTED',$attemptId,$id,$provider,$template,$correlationId);}catch(Throwable){$status='provider_rejected';$documentStatus='stamped_pdf_error';$pdfStatus='error';}}}
  if($hadActivePdf&&!$artifact){$documentStatus=$previousDocumentStatus;$pdfStatus=$previousPdfStatus;$template=$previousPdfTemplate;}
  $done=get_current_utc_time();$this->db->transBegin();try{$this->db->table('fiscal_pdf_generation_attempts')->where('id',$attemptId)->update(['status'=>$status,'provider_code'=>$result->providerCode,'provider_message'=>$result->providerMessage,'request_sent'=>$result->requestSent?1:0,'retryable'=>$result->retryable?1:0,'requires_reconciliation'=>$result->requiresReconciliation?1:0,'completed_at'=>$done,'updated_at'=>$done]);$stampUpdate=['pdf_status'=>$pdfStatus,'pdf_template'=>$template];if($artifact){if($hadActivePdf){$oldUpdate=['artifact_type'=>'pac_pdf_superseded','validation_status'=>'superseded'];if($this->db->fieldExists('artifact_status','fiscal_document_binary_artifacts'))$oldUpdate['artifact_status']='superseded';if($this->db->fieldExists('superseded_at','fiscal_document_binary_artifacts'))$oldUpdate['superseded_at']=$done;$this->db->table('fiscal_document_binary_artifacts')->where('id',(int)$stamp->pac_pdf_artifact_id)->update($oldUpdate);}if($this->db->fieldExists('artifact_status','fiscal_document_binary_artifacts'))$this->db->table('fiscal_document_binary_artifacts')->where('id',(int)$artifact->id)->update(['artifact_status'=>'active']);$stampUpdate['pac_pdf_artifact_id']=$artifact->id;}$this->db->table('fiscal_document_stamps')->where('id',$stamp->id)->update($stampUpdate);$this->db->table('fiscal_documents')->where('id',$id)->update(['status'=>$documentStatus,'updated_at'=>$done]);$this->db->table('fiscal_document_audit')->insert(['fiscal_document_id'=>$id,'invoice_id'=>$doc->invoice_id,'user_id'=>$userId,'action'=>$artifact?'pac_pdf_generated':'pac_pdf_generation_failed','reason'=>json_encode(['pdf_attempt_id'=>$attemptId,'template_code'=>$template,'provider'=>$result->provider,'status'=>$status],JSON_UNESCAPED_SLASHES),'created_at'=>$done]);$this->db->transCommit();}catch(Throwable$e){$this->db->transRollback();throw$e;}
 return FiscalPacPdfGenerationResult::fromArray(['success'=>$artifact!==null,'status'=>$documentStatus,'attempt_id'=>$attemptId,'pdf_artifact_id'=>$artifact?->id,'pdf_available'=>$artifact!==null,'template_code'=>$template,'requires_reconciliation'=>$result->requiresReconciliation,'provider_code'=>$result->providerCode,'provider_message'=>$result->providerMessage]);
 }
 private function stage(string$stage,int$attemptId,int$documentId,string$provider,string$template,string$correlationId):void{log_message('info',$stage.' {context}',['context'=>json_encode(['attempt_id'=>$attemptId,'document_id'=>$documentId,'provider'=>$provider,'template_code'=>$template,'correlation_id'=>$correlationId,'timestamp'=>gmdate('c')],JSON_UNESCAPED_SLASHES)]);}
 private function sanitizeException(Throwable$e):string{$message=trim((string)preg_replace('/[\x00-\x1F\x7F]+/u',' ',$e->getMessage()));if($message==='')$message=get_class($e);return mb_substr($message,0,240);}
 private function uuidFromStampedXml(string$xml):string{
  if(trim($xml)==='')throw new RuntimeException('FISCAL_PDF_STAMPED_XML_MISSING');
  if(stripos($xml,'<!DOCTYPE')!==false||stripos($xml,'<!ENTITY')!==false)throw new RuntimeException('FISCAL_PDF_XML_INVALID: DTD_ENTITY_NOT_ALLOWED');
  $dom=new DOMDocument();$previous=libxml_use_internal_errors(true);try{if(!$dom->loadXML($xml,LIBXML_NONET|LIBXML_NOBLANKS|LIBXML_NOCDATA))throw new RuntimeException('FISCAL_PDF_XML_INVALID: XML_NOT_WELL_FORMED');}finally{libxml_clear_errors();libxml_use_internal_errors($previous);}
  $xpath=new DOMXPath($dom);$xpath->registerNamespace('tfd','http://www.sat.gob.mx/TimbreFiscalDigital');$nodes=$xpath->query('//tfd:TimbreFiscalDigital');if(!$nodes||$nodes->length!==1)throw new RuntimeException('FISCAL_PDF_XML_INVALID: TIMBREFISCALDIGITAL_MISSING');
  $node=$nodes->item(0);$uuid=$node instanceof DOMElement?strtoupper(trim($node->getAttribute('UUID'))):'';if($uuid==='')throw new RuntimeException('FISCAL_PDF_UUID_MISSING');if(!preg_match('/^[0-9A-F]{8}-[0-9A-F]{4}-[1-5][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/',$uuid))throw new RuntimeException('FISCAL_PDF_XML_INVALID: UUID_INVALID');return$uuid;
 }
}
