<?php
declare(strict_types=1);
namespace App\FiscalServices;
use App\Services\Fiscal\Cancellation\FiscalCancellationService;
use RuntimeException;
final class PaymentComplementCancellationService
{
 private $db;private FiscalCancellationService$cancellations;
 public function __construct($db=null,?FiscalCancellationService$cancellations=null){$this->db=$db?:db_connect();$this->cancellations=$cancellations?:new FiscalCancellationService($this->db);}
 public function context(int$id):array{$c=$this->db->table('payment_complements c')->select('c.*,cl.company_name,fd.status fiscal_document_status,fd.total fiscal_total,s.uuid,s.stamp_date',false)->join('clients cl','cl.id=c.client_id')->join('fiscal_documents fd','fd.id=c.fiscal_document_id','left')->join('fiscal_document_stamps s','s.fiscal_document_id=fd.id','left')->where(['c.id'=>$id,'c.deleted'=>0])->get(1)->getRow();if(!$c)throw new RuntimeException('El Complemento de Pago no existe.');$r=$c->fiscal_document_id?$this->db->table('fiscal_cancellation_requests')->where('fiscal_document_id',$c->fiscal_document_id)->orderBy('id','DESC')->get(1)->getRow():null;foreach(['id'=>'cancellation_request_id','status'=>'cancellation_status','cancellation_reason'=>'cancellation_reason','replacement_uuid'=>'replacement_uuid','requested_at'=>'requested_at','confirmed_at'=>'confirmed_at','cancelled_at'=>'fiscal_cancelled_at','provider_code'=>'provider_code','provider_message'=>'provider_message']as$source=>$target)$c->{$target}=$r->{$source}??null;$p=$this->db->table('payment_complement_payments p')->select('p.amount,ip.amount received_amount,p.source_invoice_payment_id')->join('invoice_payments ip','ip.id=p.source_invoice_payment_id')->where(['p.payment_complement_id'=>$id,'p.deleted'=>0])->get(1)->getRow();return['complement'=>$c,'payment'=>$p,'warning'=>$this->laterStampedWarning($id)];}
 public function request(int$id,string$reason,?string$replacement,int$user):array{$c=$this->context($id)['complement'];if($c->status!=='stamped'||!$c->fiscal_document_id||!trim((string)$c->uuid))throw new RuntimeException('Sólo un Complemento timbrado y vigente puede solicitar cancelación.');return$this->decorate($id,$this->cancellations->cancel((int)$c->fiscal_document_id,$reason,$replacement,$user,true));}
 public function check(int$id,int$user,string$key):array{$c=$this->context($id)['complement'];if(!$c->fiscal_document_id)throw new RuntimeException('El Complemento no tiene documento fiscal asociado.');return$this->decorate($id,$this->cancellations->queryStatus((int)$c->fiscal_document_id,$user,true,$key));}
 private function decorate(int$id,array$r):array{$r['complement_id']=$id;if(!empty($r['request_id'])&&!empty($r['ack_available']))$r['ack_url']=get_uri('payment_complements/'.$id.'/cancel/receipt/'.(int)$r['request_id']);if(($r['status']??'')==='accepted')$r['message']='Complemento de Pago cancelado fiscalmente.';elseif(($r['status']??'')==='pending')$r['message']='Solicitud enviada. La cancelación permanece en proceso hasta confirmación fiscal.';return$r;}
 private function laterStampedWarning(int$id):?string{$ids=array_map('intval',array_column($this->db->table('payment_complement_documents d')->select('d.fiscal_document_id')->join('payment_complement_payments p','p.id=d.payment_complement_payment_id')->where(['p.payment_complement_id'=>$id,'d.deleted'=>0,'p.deleted'=>0])->get()->getResultArray(),'fiscal_document_id'));if(!$ids)return null;$count=$this->db->table('payment_complement_documents d')->join('payment_complement_payments p','p.id=d.payment_complement_payment_id')->join('payment_complements c','c.id=p.payment_complement_id')->join('fiscal_documents fd','fd.id=c.fiscal_document_id')->whereIn('d.fiscal_document_id',$ids)->where('c.id >',$id)->where(['d.deleted'=>0,'p.deleted'=>0,'c.deleted'=>0,'c.status'=>'stamped'])->where('fd.status !=','cancelled')->countAllResults();return$count?'Existen Complementos posteriores timbrados. No se renumerarán; revise la secuencia fiscal antes de sustituir.':null;}
}
