<?php
declare(strict_types=1);
namespace App\FiscalServices;
use DOMDocument;use DOMElement;use DOMXPath;use RuntimeException;
final class PaymentComplementPrintDataBuilder
{
 public function build(string$xml):array{$dom=new DOMDocument();if(!$dom->loadXML($xml,LIBXML_NONET|LIBXML_NOBLANKS)||!$dom->documentElement)throw new RuntimeException('PAYMENT_COMPLEMENT_PRINT_XML_INVALID');$x=new DOMXPath($dom);$x->registerNamespace('cfdi','http://www.sat.gob.mx/cfd/4');$x->registerNamespace('pago20','http://www.sat.gob.mx/');$x->registerNamespace('tfd','http://www.sat.gob.mx/TimbreFiscalDigital');$root=$dom->documentElement;if($root->getAttribute('TipoDeComprobante')!=='P')throw new RuntimeException('PAYMENT_COMPLEMENT_PRINT_TYPE_INVALID');$issuer=$this->first($x,'/cfdi:Comprobante/cfdi:Emisor');$receiver=$this->first($x,'/cfdi:Comprobante/cfdi:Receptor');$stamp=$this->first($x,'//tfd:TimbreFiscalDigital',false);$totals=$this->first($x,'//pago20:Pagos/pago20:Totales');$payments=[];foreach($x->query('//pago20:Pagos/pago20:Pago')?:[]as$payment){if(!$payment instanceof DOMElement)continue;$entry=['attributes'=>$this->attributes($payment),'documents'=>[],'taxes'=>$this->taxes($x,$payment,['TrasladoP','RetencionP'])];foreach($x->query('./pago20:DoctoRelacionado',$payment)?:[]as$document)if($document instanceof DOMElement)$entry['documents'][]=['attributes'=>$this->attributes($document),'taxes'=>$this->taxes($x,$document,['TrasladoDR','RetencionDR'])];$payments[]=$entry;}return['document'=>['type'=>'P','type_name'=>'Recepción de Pagos','series'=>$root->getAttribute('Serie'),'folio'=>$root->getAttribute('Folio'),'date'=>$root->getAttribute('Fecha'),'currency'=>$root->getAttribute('Moneda'),'certificate'=>$root->getAttribute('NoCertificado')],'issuer'=>$this->attributes($issuer),'receiver'=>$this->attributes($receiver),'stamp'=>$stamp?$this->attributes($stamp):[],'totals'=>$this->attributes($totals),'payments'=>$payments];}
 private function taxes(DOMXPath$x,DOMElement$context,array$names):array{$out=[];foreach($names as$name)foreach($x->query('.//pago20:'.$name,$context)?:[]as$node)if($node instanceof DOMElement)$out[]=['kind'=>$name,'attributes'=>$this->attributes($node)];return$out;}
 private function first(DOMXPath$x,string$query,bool$required=true):?DOMElement{$node=$x->query($query)?->item(0);if($node instanceof DOMElement)return$node;if($required)throw new RuntimeException('PAYMENT_COMPLEMENT_PRINT_NODE_MISSING: '.$query);return null;}
 private function attributes(DOMElement$node):array{$out=[];foreach($node->attributes as$attribute)$out[$attribute->nodeName]=(string)$attribute->nodeValue;return$out;}
}
