<?php
declare(strict_types=1);
define('ROOTPATH',dirname(__DIR__,2).DIRECTORY_SEPARATOR);define('FCPATH',ROOTPATH);require ROOTPATH.'app/Config/Paths.php';$p=new Config\Paths();define('APPPATH',realpath($p->appDirectory).DIRECTORY_SEPARATOR);define('SYSTEMPATH',realpath($p->systemDirectory).DIRECTORY_SEPARATOR);define('WRITEPATH',realpath($p->writableDirectory).DIRECTORY_SEPARATOR);define('ENVIRONMENT','development');require$p->systemDirectory.'/Boot.php';CodeIgniter\Boot::bootTest($p);helper(['plugin','general','date_time']);
use App\Services\Fiscal\FiscalDecimal;use App\Services\Fiscal\FiscalDraftTaxSnapshotService;
$pass=$fail=0;$ok=function(bool$v,string$m)use(&$pass,&$fail){echo($v?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$v?$pass++:$fail++;};
try{$db=db_connect();$attempts=$db->table('fiscal_stamp_attempts')->countAllResults();$moves=$db->table('fiscal_stamp_movements')->countAllResults();$issuer=$db->table('fiscal_profiles')->where('id',2)->get(1)->getRow();$calc=new FiscalDraftTaxSnapshotService($db);$tax=[['tax_code'=>'002','tax_type'=>'transfer','factor_type'=>'Tasa','rate_or_quota'=>'0.160000']];$concept=fn($qty,$gross,$discount='0')=>['sale_item_id'=>0,'quantity'=>(string)$qty,'subtotal'=>(string)$gross,'discount'=>(string)$discount,'total'=>FiscalDecimal::subtract((string)$gross,(string)$discount),'snapshot'=>['tax_object_code'=>'02','taxes'=>$tax]];
$ok($issuer&&property_exists($issuer,'tax_pricing_mode'),'Setting empresa encontrada.');$ok($issuer->tax_pricing_mode==='tax_inclusive','included=true activo.');$ex=$calc->calculate($concept(1,'58'),'tax_exclusive');$ok((float)$ex['total']===67.28,'included=false soportado.');
$resolver=file_get_contents(APPPATH.'Services/Fiscal/CommercialItemTaxResolver.php');$breakdown=file_get_contents(APPPATH.'Services/Fiscal/CommercialTaxBreakdownService.php');$review=file_get_contents(APPPATH.'Services/Fiscal/FiscalReviewPreparation.php');$snapshot=file_get_contents(APPPATH.'Services/Fiscal/FiscalDraftTaxSnapshotService.php');
$ok(str_contains($resolver,'InvoiceItemTaxResolver'),'Producto es fuente canónica.');$ok(str_contains($resolver,'invoiceItem'),'Override de partida tiene prioridad.');$ok(!str_contains($resolver,'tax_id')&&!str_contains($resolver,'taxable'),'Encabezado/taxable no son fuente.');
foreach(['Invoices','Estimates','Proposals']as$c){$src=file_get_contents(APPPATH."Controllers/$c.php");$ok(str_contains($src,'? (int)')&&str_contains($src,': 0'),"$c conserva legacy al editar y guarda neutral al crear.");}
$inc=$calc->calculate($concept(2,'116'),'tax_inclusive');$ok((float)$inc['base']===100.0,'Precio 58 incluido produce base 50.');$ok((float)$inc['total']===116.0,'Cantidad 2 incluida total 116.');$ok($inc['taxes'][0]['tax_code']==='002','IVA usa código 002.');
$multi=$calc->calculate(['sale_item_id'=>0,'quantity'=>'2','subtotal'=>'116','discount'=>'0','total'=>'116','snapshot'=>['tax_object_code'=>'02','taxes'=>[['tax_code'=>'002','tax_type'=>'transfer','factor_type'=>'Tasa','rate_or_quota'=>'0.160000'],['tax_code'=>'001','tax_type'=>'withholding','factor_type'=>'Tasa','rate_or_quota'=>'0.100000']]]],'tax_inclusive');$ok(count($multi['taxes'])===2&&FiscalDecimal::micros($multi['withheld'])>0,'Múltiples impuestos/retenciones.');
$none=$calc->calculate(['sale_item_id'=>0,'quantity'=>'10','subtotal'=>'2000','discount'=>'0','total'=>'2000','snapshot'=>['tax_object_code'=>'01','taxes'=>[]]],'tax_inclusive');$ok((float)$none['total']===2000.0,'ObjetoImp 01 sin impuesto.');$blocked=false;try{$calc->calculate(['sale_item_id'=>0,'quantity'=>'1','subtotal'=>'100','discount'=>'0','total'=>'100','snapshot'=>['tax_object_code'=>'02','taxes'=>[]]],'tax_inclusive');}catch(Throwable){$blocked=true;}$ok($blocked,'ObjetoImp 02 sin impuesto bloquea.');
$ok(str_contains($breakdown,'forProposal')&&str_contains($breakdown,'CommercialItemTaxResolver'),'Proposal usa motor único.');$ok(str_contains($breakdown,'forEstimate')&&str_contains($breakdown,'CommercialItemTaxResolver'),'Estimate usa motor único.');$ok(str_contains($breakdown,'invoiceItem'),'Sale usa motor único.');$ok(str_contains($review,'CommercialItemTaxResolver'),'Review usa motor único.');$ok(str_contains($snapshot,'signedQuotas'),'Snapshot comparte cálculo de tasas/cuotas.');
$discount=$calc->calculate($concept(10,'2000','200'),'tax_inclusive');$ok((float)$discount['total']===1800.0&&abs((float)$discount['base']-1551.724138)<.00001,'Descuento incluido no duplica impuesto.');
$ok(str_contains(file_get_contents(APPPATH.'Services/ProposalToInvoiceService.php'),'item_id'),'Proposal→Sale conserva item_id.');$ok(str_contains(file_get_contents(APPPATH.'Services/EstimateAcceptanceService.php'),'item_id'),'Estimate→Sale conserva item_id.');
$invoiceController=file_get_contents(APPPATH.'Controllers/Invoices.php');$ok(str_contains($invoiceController,'commercial_status')&&str_contains($invoiceController,"Pago: "),'Listado usa estado comercial y pago separado.');
$lang=file_get_contents(APPPATH.'Language/Spanish/default_lang.php');$ok(str_contains($lang,'["converted"] = "Convertida"')&&str_contains($lang,'["expired"] = "Vencida"'),'Traducciones españolas completas.');
$views=file_get_contents(APPPATH.'Views/invoices/modal_form.php').file_get_contents(APPPATH.'Views/estimates/modal_form.php').file_get_contents(APPPATH.'Views/proposals/modal_form.php');$ok(!str_contains($views,'form_dropdown("tax_id"'),'Modales sin impuestos de encabezado.');$ok(str_contains($resolver,'partida libre'),'Línea libre queda explícita.');
$ok($db->table('fiscal_stamp_attempts')->countAllResults()===$attempts,'PAC calls=0.');$ok($db->table('fiscal_stamp_movements')->countAllResults()===$moves,'Stamps=0.');
}catch(Throwable$e){echo'[FAIL] '.$e->getMessage().PHP_EOL;$fail++;}echo"\n$pass passed, $fail failed.\n";exit($fail?1:0);
