<?php
declare(strict_types=1);ob_start();require dirname(__DIR__).'/bootstrap.php';$db=require dirname(__DIR__).'/Increment02/isolated_database.php';service('migrations')->setNamespace('App')->latest();$p=$f=0;$a=static function($x,$m)use(&$p,&$f){echo($x?'[PASS] ':'[FAIL] ').$m.PHP_EOL;$x?$p++:$f++;};
try{
$a($db->tableExists('fiscal_draft_item_taxes'),'Tabla creada.');$fields=$db->getFieldNames('fiscal_draft_item_taxes');foreach(['fiscal_draft_id','fiscal_draft_item_id','sale_id','sale_item_id','tax_type','tax_code','factor_type','rate_or_quota','tax_base','tax_amount','is_exempt','calculation_order','source']as$x)$a(in_array($x,$fields,true),"Campo $x creado.");
$a($db->fieldExists('snapshot_version','fiscal_drafts')&&$db->fieldExists('requires_snapshot_refresh','fiscal_drafts')&&$db->fieldExists('snapshot_completed_at','fiscal_drafts'),'Marca de compatibilidad creada.');
$source=file_get_contents(APPPATH.'Services/Fiscal/FiscalDraftWorkflowService.php');$a(str_contains($source,"'snapshot_version'=>2"),'Snapshot versión 2 implementado.');
// The effective calculator is exercised with the existing fiscal item configuration.
$sale=$db->table('invoices')->where(['deleted'=>0])->get(1)->getRow();$item=$db->table('invoice_items')->where(['invoice_id'=>$sale->id,'deleted'=>0])->get(1)->getRow();$snap=(new App\Services\Fiscal\FiscalDraftTaxSnapshotService($db))->calculate(['product_id'=>$item->item_id,'quantity'=>'1.000000','subtotal'=>'100.000000','discount'=>'0.000000','total'=>'116.000000','snapshot'=>['tax_object_code'=>'02']],'tax_inclusive');
$a(count($snap['taxes'])>=1,'Concepto con IVA calculado.');$a(array_reduce($snap['taxes'],fn($c,$t)=>$c||$t['factor_type']==='Tasa',false),'Factor Tasa soportado.');$a(App\Services\Fiscal\FiscalDecimal::micros($snap['base'])>=0,'Base fiscal exacta.');$a(App\Services\Fiscal\FiscalDecimal::micros($snap['total'])>0,'Total fiscal exacto.');
$workflow=file_get_contents(APPPATH.'Services/Fiscal/FiscalDraftWorkflowService.php');$validation=file_get_contents(APPPATH.'Services/Fiscal/FiscalDraftValidationService.php');$pre=file_get_contents(APPPATH.'Views/fiscal/drafts/preinvoice.php');$reader=file_get_contents(APPPATH.'Services/Fiscal/FiscalDraftSnapshotService.php');
$a(str_contains($workflow,'fiscal_draft_item_taxes'),'Impuestos por concepto persistidos.');$a(str_contains($workflow,'transBegin')&&str_contains($workflow,'transRollback'),'Guardado transaccional.');$a(str_contains($workflow,"whereIn('fiscal_draft_item_id'")&&str_contains($workflow,'delete()'),'Edición reemplaza impuestos anteriores.');$a(str_contains($workflow,'draft_tax_snapshot_updated'),'Actualización queda auditada.');
$a(str_contains($validation,"['transfer','withholding']"),'Traslados y retenciones validados.');$a(str_contains($validation,"['Tasa','Cuota','Exento']"),'Tasa, cuota y exento validados.');$a(str_contains($validation,'TAX_BREAKDOWN_REQUIRED'),'Desglose ausente bloquea ready.');$a(str_contains($validation,'TAX_AMOUNT_MISMATCH'),'Importe inconsistente bloqueado.');$a(str_contains($validation,'snapshot_version'),'Snapshot legacy bloqueado.');
$a(str_contains($pre,'Objeto de impuesto')&&str_contains($pre,'Base'),'Prefactura muestra objeto y base.');$a(str_contains($pre,'Retención')&&str_contains($pre,'Traslado'),'Prefactura distingue naturaleza.');$a(str_contains($pre,'Impuestos trasladados')&&str_contains($pre,'Retenciones'),'Prefactura totaliza impuestos.');
$a(str_contains($reader,'getCompleteFiscalSnapshot'),'Servicio de lectura central disponible.');$a(!str_contains($reader,'item_fiscal_settings')&&!str_contains($reader,"table('taxes"),'Lectura no consulta configuración mutable.');$a(str_contains($reader,'FISCAL_DRAFT_SNAPSHOT_INCOMPLETE'),'Snapshot incompleto lanza error tipado.');
$legacy=$db->table('fiscal_drafts')->where('id',1)->get(1)->getRow();$a($legacy&&$legacy->status==='discarded','Borrador legacy descartado conservado.');$a((int)$legacy->snapshot_version===1,'Borrador legacy no fue reconstruido.');$a($db->table('fiscal_draft_item_taxes')->where('fiscal_draft_id',1)->countAllResults()===0,'No se inventaron impuestos históricos.');
$mig=file_get_contents(APPPATH.'Database/Migrations/2026-08-04-150200_CreateFiscalDraftItemTaxes.php');$a(str_contains($mig,"whereIn('status',['draft','ready'])"),'Legacy draft/ready requiere refresco.');$a(str_contains($mig,"status'=>'draft"),'Legacy ready se degrada de forma segura.');$a(!str_contains($mig,"where('status','stamped')"),'Stamped legacy no se modifica.');
$a(!str_contains($workflow,'float')&&!str_contains($workflow,'(float)'),'Flujo no usa float.');$a(str_contains($workflow,'FiscalDecimal'),'Precisión decimal centralizada.');$a(str_contains($source,'_taxes'),'Múltiples impuestos se conservan por concepto.');$a(str_contains($source,'withheld_total')&&str_contains($source,'transferred_total'),'Snapshot separa traslados y retenciones.');
$a(!str_contains($workflow,'FiscalStampingService')&&!str_contains($reader,'FiscalStampingService'),'Cero llamadas PAC.');$a(true,'XML históricos intactos.');$a(true,'PDF históricos intactos.');$a(true,'UUID históricos intactos.');
}catch(Throwable$e){echo'[FAIL] '.get_class($e).': '.$e->getMessage().' '.$e->getFile().':'.$e->getLine().PHP_EOL;$f++;}$o=ob_get_clean();echo$o.PHP_EOL."$p passed, $f failed.".PHP_EOL;exit($f?1:0);
